import test from 'node:test';
import assert from 'node:assert/strict';
import { compile } from '../src/compiler.js';
import { buildNativeGuiIRV08 } from '../src/native-gui-ir-v08.js';
import { emitAppKitGuiObjCppV09, PATCH_APPKIT_GUI_BACKEND_V09_VERSION } from '../src/appkit-gui-v09.js';

const source = `create text status = "idle"

window "People" as main size 520, 320:
  table "Name", "Role" as people at 24, 64 size 440, 180:
    row "Ada", "Engineer"
    row "Grace", "Scientist"

when people changed:
  change status:
    set = "selected"
`;

test('AppKit backend v0.9 maps Table to multi-column NSTableView', () => {
  const ir = buildNativeGuiIRV08(compile(source, { kind: 'window', name: 'People' }));
  const mm = emitAppKitGuiObjCppV09(ir);
  assert.equal(PATCH_APPKIT_GUI_BACKEND_V09_VERSION, '0.9');
  assert.match(mm, /Generated by Patch AppKit GUI backend 0\.9/);
  assert.match(mm, /NSTableColumn \*column = \[\[NSTableColumn alloc\] initWithIdentifier:@"0"\]/);
  assert.match(mm, /column\.title = @"Name"/);
  assert.match(mm, /column\.title = @"Role"/);
  assert.match(mm, /PatchTableCellValue/);
  assert.match(mm, /PatchTableRow_0/);
  assert.match(mm, /NSArray<NSString \*> \*eventValue/);
  assert.match(mm, /gPatchTableSelectionCount/);
  assert.match(mm, /numberOfRowsInTableView/);
  assert.doesNotMatch(mm, /__patch_native_table_shadow_/);
  assert.doesNotMatch(mm, /Event_0\(row >= 0 \? PatchListOptionValue/);
});

test('AppKit backend v0.9 keeps scroll-wrapper resize and accessibility behavior', () => {
  const responsive = source.replace(
    'table "Name", "Role" as people at 24, 64 size 440, 180:',
    '# @layout anchor left right top\n  table "Name", "Role" as people at 24, 64 size 440, 180:'
  );
  const ir = buildNativeGuiIRV08(compile(responsive, { kind: 'window', name: 'People' }));
  const mm = emitAppKitGuiObjCppV09(ir);
  assert.match(mm, /ApplyPatchAccessibility/);
  assert.match(mm, /setAccessibilityLabel/);
  assert.match(mm, /enclosingScrollView/);
  assert.match(mm, /ApplyPatchResponsiveLayout/);
});
