import test from 'node:test';
import assert from 'node:assert/strict';
import { compile } from '../src/compiler.js';
import { buildNativeGuiIRV08 } from '../src/native-gui-ir-v08.js';
import { emitGtkGuiCppV09, PATCH_GTK_GUI_BACKEND_V09_VERSION } from '../src/gtk-gui-v09.js';

const source = `create text status = "idle"

window "People" as main size 520, 320:
  table "Name", "Role" as people at 24, 64 size 440, 180:
    row "Ada", "Engineer"
    row "Grace", "Scientist"

when people changed:
  change status:
    set = "selected"
`;

test('GTK backend v0.9 maps Table to GtkTreeView with GtkListStore', () => {
  const ir = buildNativeGuiIRV08(compile(source, { kind: 'window', name: 'People' }));
  const cpp = emitGtkGuiCppV09(ir);
  assert.equal(PATCH_GTK_GUI_BACKEND_V09_VERSION, '0.9');
  assert.match(cpp, /Generated by Patch GTK GUI backend 0\.9/);
  assert.match(cpp, /gtk_list_store_new\(2, G_TYPE_STRING, G_TYPE_STRING\)/);
  assert.match(cpp, /gtk_tree_view_new_with_model/);
  assert.match(cpp, /gtk_tree_view_column_new_with_attributes\("Name"/);
  assert.match(cpp, /gtk_tree_view_column_new_with_attributes\("Role"/);
  assert.match(cpp, /gtk_scrolled_window_new/);
  assert.match(cpp, /GtkTreeSelection \*selection/);
  assert.match(cpp, /OnTableChanged/);
  assert.match(cpp, /std::vector<std::string> PatchTableRow_0/);
  assert.match(cpp, /static void Event_0\(const std::vector<std::string>& eventValue\)/);
  assert.match(cpp, /gPatchTableSelectionCount/);
  assert.doesNotMatch(cpp, /__patch_native_table_shadow_/);
});

test('GTK backend v0.9 keeps accessibility and responsive wrapper behavior', () => {
  const responsive = source.replace(
    'table "Name", "Role" as people at 24, 64 size 440, 180:',
    '# @layout anchor left right top\n  table "Name", "Role" as people at 24, 64 size 440, 180:'
  );
  const ir = buildNativeGuiIRV08(compile(responsive, { kind: 'window', name: 'People' }));
  const cpp = emitGtkGuiCppV09(ir);
  assert.match(cpp, /atk_object_set_name/);
  assert.match(cpp, /gTableViews\[0\]/);
  assert.match(cpp, /ApplyPatchResponsiveLayout/);
  assert.match(cpp, /gtk_fixed_move\(GTK_FIXED\(gFixed\[0\]\), gControls\[0\]/);
  assert.match(cpp, /gtk_widget_set_size_request\(gControls\[0\]/);
});
