import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { compile } from '../src/compiler.js';
import {
  buildNativeGuiIRV12,
  validateNativeGuiIRV12,
  toV11CompatibleV12,
  flattenNativeGuiControlsV12
} from '../src/native-gui-ir-v12.js';
import { buildNativeGuiPlan } from '../src/native-gui-build-plan.js';
import { emitWin32GuiCppV13 } from '../src/win32-gui-v13.js';
import { emitAppKitGuiObjCppV13 } from '../src/appkit-gui-v13.js';
import { emitGtkGuiCppV13 } from '../src/gtk-gui-v13.js';

const source = fs.readFileSync('examples/treeview-window.patch', 'utf8');

function build() {
  return buildNativeGuiIRV12(compile(source, { name: 'NativeTreeView', kind: 'window' }));
}

test('Native GUI IR 1.2 carries recursive TreeView hierarchy and transient path events', () => {
  const ir = build();
  assert.equal(ir.version, '1.2');
  assert.deepEqual(ir.states, [
    { name: 'rootLabel', type: 'text', initial: 'src' },
    { name: 'selected', type: 'list', initial: [] }
  ]);
  const controls = flattenNativeGuiControlsV12(ir);
  const tree = controls.find(control => control.id === 'files');
  assert.ok(tree);
  assert.equal(tree.type, 'tree');
  assert.equal(tree.binding, null);
  assert.deepEqual(tree.nodes, [
    { text: '{rootLabel}', children: [{ text: 'compiler.js', children: [] }, { text: 'parser.js', children: [] }] },
    { text: 'docs', children: [{ text: 'ROADMAP.md', children: [] }, { text: 'TREEVIEW_STAGE1.md', children: [] }] }
  ]);
  assert.deepEqual(ir.events, [{
    control: 'files', event: 'changed', valueType: 'text-list', form: 'main',
    actions: [{ kind: 'change', target: 'selected', stateType: 'list', ops: [{ op: 'set', value: { kind: 'eventValue' } }] }]
  }]);
  assert.equal(validateNativeGuiIRV12(ir), ir);
  assert.equal(JSON.stringify(ir).includes('__patch_native_tree_shadow_'), false);
});

test('Native GUI IR 1.2 backend projection is private and preserves original IR', () => {
  const ir = build();
  const compatible = toV11CompatibleV12(ir);
  assert.equal(compatible.version, '1.1');
  const shadow = compatible.states.find(state => state.name.startsWith('__patch_native_tree_shadow_'));
  assert.ok(shadow);
  assert.equal(shadow.type, 'list');
  const treeShadow = compatible.forms[0].controls.find(control => control.id === 'files');
  assert.equal(treeShadow.type, 'listbox');
  assert.equal(treeShadow.selectionMode, 'multiple');
  assert.equal(treeShadow.binding, shadow.name);
  assert.equal(ir.forms[0].controls.find(control => control.id === 'files').type, 'tree');
  assert.equal(JSON.stringify(ir).includes(shadow.name), false);
});

test('Native GUI build plan selects additive TreeView v1.3 tier automatically', () => {
  const compiled = compile(source, { name: 'NativeTreeView', kind: 'window' });
  const plan = buildNativeGuiPlan(compiled);
  assert.equal(plan.tier, 'tree-v13');
  assert.equal(plan.gui.version, '1.2');
  assert.equal(plan.features.tree, true);
  assert.equal(plan.features.listState, true);
});

test('Win32 v1.3 emits a real TreeView and no private shadow state', () => {
  const cpp = emitWin32GuiCppV13(build());
  assert.match(cpp, /Generated by Patch Win32 GUI backend 1\.3/);
  assert.match(cpp, /WC_TREEVIEWW/);
  assert.match(cpp, /TVN_SELCHANGEDW/);
  assert.match(cpp, /ICC_TREEVIEW_CLASSES/);
  assert.match(cpp, /PatchTreePath_/);
  assert.match(cpp, /TreeNodeText_/);
  assert.doesNotMatch(cpp, /__patch_native_tree_shadow_/);
});

test('AppKit v1.3 emits NSOutlineView hierarchy and full-path selection', () => {
  const sourceText = emitAppKitGuiObjCppV13(build());
  assert.match(sourceText, /Generated by Patch AppKit GUI backend 1\.3/);
  assert.match(sourceText, /NSOutlineView/);
  assert.match(sourceText, /outlineViewSelectionDidChange/);
  assert.match(sourceText, /PatchTreePath/);
  assert.match(sourceText, /TreeNodeText_/);
  assert.doesNotMatch(sourceText, /__patch_native_tree_shadow_/);
});

test('GTK v1.3 emits GtkTreeStore hierarchy and full-path selection', () => {
  const sourceText = emitGtkGuiCppV13(build());
  assert.match(sourceText, /Generated by Patch GTK GUI backend 1\.3/);
  assert.match(sourceText, /gtk_tree_store_new/);
  assert.match(sourceText, /OnTreeChanged/);
  assert.match(sourceText, /PatchTreeSelectedPath/);
  assert.match(sourceText, /TreeNodeText_/);
  assert.doesNotMatch(sourceText, /__patch_native_tree_shadow_/);
});

test('Native GUI IR 1.2 rejects list-state interpolation in TreeView node labels', () => {
  const bad = `create list values = ["x"]\nwindow "X" as main:\n  tree as files:\n    node "{values}"\n      node "leaf"\n`;
  assert.throws(() => buildNativeGuiIRV12(compile(bad, { name: 'BadTree', kind: 'window' })), /cannot interpolate list state/i);
});
