import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { compile } from '../src/compiler.js';
import { buildNativeGuiIR } from '../src/native-gui-ir.js';
import {
  PATCH_NATIVE_ACCESSIBILITY_VERSION,
  humanizeNativeIdentifier,
  nativeAccessibleName,
  nativeRadioItemAccessibleName,
  needsExplicitNativeAccessibleName
} from '../src/native-accessibility.js';
import { emitWin32GuiCpp, PATCH_WIN32_GUI_BACKEND_VERSION } from '../src/win32-gui-v08.js';
import { emitAppKitGuiObjCpp, PATCH_APPKIT_GUI_BACKEND_VERSION } from '../src/appkit-gui-v08.js';
import { emitGtkGuiCpp, PATCH_GTK_GUI_BACKEND_VERSION } from '../src/gtk-gui-v08.js';

function nativeIr(file, name = 'AccessibilityDemo') {
  const source = fs.readFileSync(file, 'utf8');
  return buildNativeGuiIR(compile(source, { kind: 'window', name }));
}

test('native accessibility naming contract is deterministic and humanizes Patch ids', () => {
  assert.equal(PATCH_NATIVE_ACCESSIBILITY_VERSION, '0.1');
  assert.equal(humanizeNativeIdentifier('user_name'), 'User name');
  assert.equal(humanizeNativeIdentifier('user-name'), 'User name');
  assert.equal(humanizeNativeIdentifier('userName'), 'User Name');
  assert.equal(humanizeNativeIdentifier('APIKey'), 'API Key');
  assert.equal(nativeAccessibleName({ type: 'input', id: 'account_name', text: '' }), 'Account name');
  assert.equal(nativeAccessibleName({ type: 'button', id: 'save', text: 'Save' }), 'Save');
  assert.equal(nativeAccessibleName({ type: 'button', id: 'dynamic_save', text: 'Save {name}' }), 'Dynamic save');
  assert.equal(nativeRadioItemAccessibleName({ type: 'radio', id: 'mode' }, 'Advanced'), 'Mode: Advanced');
  assert.equal(needsExplicitNativeAccessibleName({ type: 'input' }), true);
  assert.equal(needsExplicitNativeAccessibleName({ type: 'checkbox' }), false);
});

test('backend v0.8 labels unnamed input and Tabs controls on all three native platforms', () => {
  const ir = nativeIr('examples/tabs-window.patch', 'TabsAccessibility');
  const win = emitWin32GuiCpp(ir);
  const mac = emitAppKitGuiObjCpp(ir);
  const gtk = emitGtkGuiCpp(ir);

  assert.equal(PATCH_WIN32_GUI_BACKEND_VERSION, '0.8');
  assert.equal(PATCH_APPKIT_GUI_BACKEND_VERSION, '0.8');
  assert.equal(PATCH_GTK_GUI_BACKEND_VERSION, '0.8');
  assert.match(win, /Generated by Patch Win32 GUI backend 0\.8/);
  assert.match(mac, /Generated by Patch AppKit GUI backend 0\.8/);
  assert.match(gtk, /Generated by Patch GTK GUI backend 0\.8/);

  assert.match(win, /SetPatchAccessibleName\(gControls\[0\], L"Settings"\)/);
  assert.match(win, /SetPatchAccessibleName\(gControls\[2\], L"Name"\)/);
  assert.match(mac, /setAccessibilityLabel:@"Settings"/);
  assert.match(mac, /setAccessibilityLabel:@"Name"/);
  assert.match(gtk, /SetPatchAccessibleName\(gControls\[0\], "Settings"\)/);
  assert.match(gtk, /SetPatchAccessibleName\(gControls\[2\], "Name"\)/);
});

test('Win32 uses Microsoft Active Accessibility annotation and reads it back in native smoke', () => {
  const win = emitWin32GuiCpp(nativeIr('examples/input-window.patch', 'WinA11y'));
  for (const marker of [
    '#include <oleacc.h>',
    'IAccPropServices *service',
    'CoCreateInstance(CLSID_AccPropServices',
    'SetHwndPropStr(hwnd, OBJID_CLIENT, CHILDID_SELF, PROPID_ACC_NAME, name)',
    'ClearHwndProps(hwnd, OBJID_CLIENT, CHILDID_SELF',
    'AccessibleObjectFromWindow(hwnd, OBJID_CLIENT, IID_IAccessible',
    'accessible->get_accName(child, &value)',
    'PatchAccessibleName(gControls[0]) != L"Name"',
    'PatchComScope patchCom',
    'ApplyPatchAccessibility();',
    'ClearPatchAccessibleNames(); DestroyWindow(hwnd)'
  ]) assert.ok(win.includes(marker), marker);
});

test('AppKit uses method-based accessibility labels and reads them back in native smoke', () => {
  const mac = emitAppKitGuiObjCpp(nativeIr('examples/input-window.patch', 'MacA11y'));
  assert.match(mac, /\[gControls\[0\] setAccessibilityLabel:@"Name"\]/);
  assert.match(mac, /\[gControls\[0\] accessibilityLabel\]/);
  assert.match(mac, /isEqualToString:@"Name"/);
  assert.match(mac, /ApplyPatchAccessibility\(\);/);
});

test('GTK3 uses the widget AtkObject name and reads it back in native smoke', () => {
  const gtk = emitGtkGuiCpp(nativeIr('examples/input-window.patch', 'GtkA11y'));
  assert.match(gtk, /#include <atk\/atk\.h>/);
  assert.match(gtk, /gtk_widget_get_accessible\(widget\)/);
  assert.match(gtk, /atk_object_set_name\(accessible, name\)/);
  assert.match(gtk, /atk_object_get_name\(accessible\)/);
  assert.match(gtk, /PatchAccessibleName\(gControls\[0\]\)/);
  assert.match(gtk, /std::string\(name\) != "Name"/);
});

test('Radio options preserve their visible option while adding group context and smoke checks it', () => {
  const ir = nativeIr('examples/radio-window.patch', 'RadioAccessibility');
  const win = emitWin32GuiCpp(ir);
  const mac = emitAppKitGuiObjCpp(ir);
  const gtk = emitGtkGuiCpp(ir);
  for (const expected of ['Mode: Basic', 'Mode: Advanced', 'Mode: Expert']) {
    assert.ok(win.includes(`L"${expected}"`), `Win32 ${expected}`);
    assert.ok(mac.includes(`@"${expected}"`), `AppKit ${expected}`);
    assert.ok(gtk.includes(`"${expected}"`), `GTK ${expected}`);
  }
  assert.match(win, /PatchAccessibleName\(gRadioItems/);
  assert.match(mac, /NSButton \*\).*accessibilityLabel.*Mode: Advanced/);
  assert.match(gtk, /PatchAccessibleName\(gRadioItems/);
});

test('combo and listbox receive explicit names while native buttons keep their built-in visible labels', () => {
  const combo = nativeIr('examples/combo-window.patch', 'ComboAccessibility');
  const list = nativeIr('examples/listbox-window.patch', 'ListAccessibility');
  for (const [ir, expected] of [[combo, 'Size'], [list, 'Fruit']]) {
    assert.ok(emitWin32GuiCpp(ir).includes(`L"${expected}"`));
    assert.ok(emitAppKitGuiObjCpp(ir).includes(`@"${expected}"`));
    assert.ok(emitGtkGuiCpp(ir).includes(`"${expected}"`));
  }

  const forms = nativeIr('examples/forms-navigation.patch', 'ButtonAccessibility');
  const win = emitWin32GuiCpp(forms);
  assert.doesNotMatch(win, /SetPatchAccessibleName\([^\n]+Open settings/);
  assert.doesNotMatch(win, /SetPatchAccessibleName\([^\n]+Notifications/);
});

test('native build entrypoints use current and frozen backends', () => {
  const win32 = fs.readFileSync('scripts/build-native-win32.js', 'utf8');
  const appkit = fs.readFileSync('scripts/build-native-appkit.js', 'utf8');
  const gtk = fs.readFileSync('scripts/build-native-gtk.js', 'utf8');
  assert.match(win32, /win32-gui-v13\.js/);
  assert.match(win32, /win32-gui-v14\.js/);
  assert.doesNotMatch(win32, /win32-gui-v08\.js/);
  assert.match(appkit, /appkit-gui-v13\.js/);
  assert.match(appkit, /appkit-gui-v14\.js/);
  assert.doesNotMatch(appkit, /appkit-gui-v08\.js/);
  assert.match(gtk, /gtk-gui-v13\.js/);
  assert.match(gtk, /gtk-gui-v14\.js/);
  assert.doesNotMatch(gtk, /gtk-gui-v08\.js/);
});
