import test from 'node:test';
import assert from 'node:assert/strict';
import { compile } from '../src/compiler.js';
import {
  buildNativeGuiIRV13,
  validateNativeGuiIRV13,
  toV12CompatibleV13,
  flattenNativeGuiControlsV13
} from '../src/native-gui-ir-v13.js';
import { buildNativeGuiIRV12 } from '../src/native-gui-ir-v12.js';
import { buildNativeGuiPlan } from '../src/native-gui-build-plan.js';
import { flattenCurrentNativeGuiControls } from '../src/native-current-contract.js';
import { emitWin32GuiCppV14 } from '../src/win32-gui-v14.js';
import { emitAppKitGuiObjCppV14 } from '../src/appkit-gui-v14.js';
import { emitGtkGuiCppV14 } from '../src/gtk-gui-v14.js';

const SOURCE = `create number volume = 50

window "Mixer" as main size 520, 260:
  slider 0..100 as volume step 5 at 24, 64 size 280, 44

when volume changed:
  change volume:
    set = value
`;

function build(source = SOURCE) {
  return buildNativeGuiIRV13(compile(source, { name: 'NativeSlider', kind: 'window' }));
}

test('Native GUI IR 1.3 carries Slider range step binding and numeric changed value', () => {
  const ir = build();
  assert.equal(ir.version, '1.3');
  assert.deepEqual(ir.states, [{ name: 'volume', type: 'number', initial: 50 }]);
  const slider = flattenNativeGuiControlsV13(ir).find(control => control.id === 'volume');
  assert.ok(slider);
  assert.equal(slider.type, 'slider');
  assert.equal(slider.binding, 'volume');
  assert.deepEqual({ min: slider.min, max: slider.max, step: slider.step }, { min: 0, max: 100, step: 5 });
  assert.deepEqual(ir.events, [{
    control: 'volume', event: 'changed', valueType: 'number', form: 'main',
    actions: [{ kind: 'change', target: 'volume', stateType: 'number', ops: [{ op: 'set', value: { kind: 'eventValue' } }] }]
  }]);
  assert.equal(validateNativeGuiIRV13(ir), ir);
  assert.equal(JSON.stringify(ir).includes('__patch_native_slider_shadow_'), false);
});

test('Native GUI IR 1.3 compatibility projection is private and preserves original Slider', () => {
  const ir = build();
  const compatible = toV12CompatibleV13(ir);
  assert.equal(compatible.version, '1.2');
  const shadow = compatible.states.find(state => state.name.startsWith('__patch_native_slider_shadow_'));
  assert.ok(shadow);
  assert.equal(shadow.type, 'text');
  const control = compatible.forms[0].controls.find(item => item.id === 'volume');
  assert.equal(control.type, 'input');
  assert.equal(control.binding, shadow.name);
  assert.equal(compatible.events[0].valueType, 'text');
  assert.equal(ir.forms[0].controls.find(item => item.id === 'volume').type, 'slider');
  assert.equal(JSON.stringify(ir).includes(shadow.name), false);
});

test('Native GUI build plan selects additive Slider backend 1.4 automatically', () => {
  const compiled = compile(SOURCE, { name: 'NativeSlider', kind: 'window' });
  const plan = buildNativeGuiPlan(compiled);
  assert.equal(plan.tier, 'slider-v14');
  assert.equal(plan.gui.version, '1.4');
  assert.equal(plan.features.slider, true);
});

test('Native GUI 1.4 composes Slider with TreeView and nested Tabs without downgrading either', () => {
  const mixed = `create number volume = 25
create list selected = []
window "Mixed" as main size 640, 420:
  tabs as settings:
    tab "Audio":
      slider 0..100 as volume step 5
    tab "Files":
      tree as files:
        node "src"
          node "parser.js"
when volume changed:
  change volume:
    set = value
when files changed:
  change selected:
    set = value
`;
  const plan = buildNativeGuiPlan(compile(mixed, { name: 'MixedNative', kind: 'window' }));
  assert.equal(plan.tier, 'slider-v14');
  assert.equal(plan.gui.version, '1.4');
  assert.equal(plan.features.slider, true);
  assert.equal(plan.features.tree, true);
  const controls = flattenCurrentNativeGuiControls(plan.gui);
  assert.equal(controls.find(control => control.id === 'volume').type, 'slider');
  assert.equal(controls.find(control => control.id === 'files').type, 'tree');
  assert.ok(controls.find(control => control.id === 'volume').parentTabIndex >= 0);
});

test('unbound native Slider uses declared minimum as initial widget value', () => {
  const ir = build(`window "Unbound" as main:\n  slider -2..2 as zoom step 0.25\n`);
  const slider = flattenNativeGuiControlsV13(ir).find(control => control.id === 'zoom');
  assert.equal(slider.binding, null);
  assert.equal(slider.min, -2);
  assert.equal(slider.max, 2);
  assert.equal(slider.step, 0.25);
});

test('frozen Native GUI IR 1.2 remains fail-closed for Slider source', () => {
  assert.throws(() => buildNativeGuiIRV12(compile(SOURCE, { name: 'FrozenNative', kind: 'window' })), /Slider is not enabled|does not support 'slider'/i);
});

test('Win32 backend 1.4 emits TRACKBAR Slider and bounded numeric dispatch', () => {
  const source = emitWin32GuiCppV14(build());
  assert.match(source, /Generated by Patch Win32 GUI backend 1\.4/);
  assert.match(source, /TRACKBAR_CLASSW/);
  assert.match(source, /ICC_BAR_CLASSES/);
  assert.match(source, /WM_HSCROLL/);
  assert.match(source, /PatchSliderValue_/);
  assert.match(source, /static void Event_0\(double eventValue\)/);
  assert.doesNotMatch(source, /__patch_native_slider_shadow_/);
});

test('AppKit backend 1.4 emits NSSlider and numeric action dispatch', () => {
  const source = emitAppKitGuiObjCppV14(build());
  assert.match(source, /Generated by Patch AppKit GUI backend 1\.4/);
  assert.match(source, /NSSlider/);
  assert.match(source, /control\.continuous = NO/);
  assert.match(source, /PatchSliderValue_/);
  assert.match(source, /static void Event_0\(double eventValue\)/);
  assert.doesNotMatch(source, /__patch_native_slider_shadow_/);
});

test('GTK backend 1.4 emits GtkScale and numeric value-changed dispatch', () => {
  const source = emitGtkGuiCppV14(build());
  assert.match(source, /Generated by Patch GTK GUI backend 1\.4/);
  assert.match(source, /gtk_scale_new_with_range/);
  assert.match(source, /value-changed/);
  assert.match(source, /PatchSliderValue_/);
  assert.match(source, /static void Event_0\(double eventValue\)/);
  assert.doesNotMatch(source, /__patch_native_slider_shadow_/);
});
