import test from 'node:test';
import assert from 'node:assert/strict';
import { compile } from '../src/compiler.js';
import { buildNativeGuiIRV08 } from '../src/native-gui-ir-v08.js';
import { emitWin32GuiCppV09, PATCH_WIN32_GUI_BACKEND_V09_VERSION } from '../src/win32-gui-v09.js';

const source = `create text status = "idle"

window "People" as main size 520, 320:
  table "Name", "Role" as people at 24, 64 size 440, 180:
    row "Ada", "Engineer"
    row "Grace", "Scientist"

when people changed:
  change status:
    set = "selected"
`;

test('Win32 backend v0.9 maps Native GUI IR 0.8 Table to report-mode ListView', () => {
  const ir = buildNativeGuiIRV08(compile(source, { kind: 'window', name: 'People' }));
  const cpp = emitWin32GuiCppV09(ir);

  assert.equal(PATCH_WIN32_GUI_BACKEND_V09_VERSION, '0.9');
  assert.match(cpp, /Generated by Patch Win32 GUI backend 0\.9/);
  assert.match(cpp, /ICC_TAB_CLASSES \| ICC_LISTVIEW_CLASSES/);
  assert.match(cpp, /WC_LISTVIEWW/);
  assert.match(cpp, /LVS_REPORT \| LVS_SINGLESEL \| LVS_SHOWSELALWAYS/);
  assert.match(cpp, /ListView_InsertColumn/);
  assert.match(cpp, /ListView_InsertItem/);
  assert.match(cpp, /ListView_SetItemText/);
  assert.match(cpp, /L"Name"/);
  assert.match(cpp, /L"Engineer"/);
  assert.match(cpp, /LVN_ITEMCHANGED/);
  assert.match(cpp, /HandleTableNotify/);
  assert.match(cpp, /std::vector<std::wstring> PatchTableRow_0/);
  assert.match(cpp, /static void Event_0\(const std::vector<std::wstring>& eventValue\);/);
  assert.match(cpp, /static void Event_0\(const std::vector<std::wstring>& eventValue\) \{/);
  assert.ok(
    cpp.indexOf('static void Event_0(const std::vector<std::wstring>& eventValue);') < cpp.indexOf('static bool HandleTableNotify'),
    'Table event must be declared before Win32 notification dispatch'
  );
  assert.match(cpp, /gPatchTableSelectionCount/);
  assert.doesNotMatch(cpp, /__patch_native_table_shadow_/);
  assert.doesNotMatch(cpp, /LBN_SELCHANGE\) \{ Event_0\(ListBoxText/);
});

test('Win32 backend v0.9 retains backend v0.8 accessibility and responsive hooks', () => {
  const responsive = source.replace(
    'table "Name", "Role" as people at 24, 64 size 440, 180:',
    '# @layout anchor left right top\n  table "Name", "Role" as people at 24, 64 size 440, 180:'
  );
  const ir = buildNativeGuiIRV08(compile(responsive, { kind: 'window', name: 'People' }));
  const cpp = emitWin32GuiCppV09(ir);
  assert.match(cpp, /ApplyPatchAccessibility/);
  assert.match(cpp, /SetPatchAccessibleName/);
  assert.match(cpp, /case WM_SIZE:/);
  assert.match(cpp, /ApplyPatchResponsiveLayout/);
  assert.match(cpp, /MoveWindow\(gControls\[0\]/);
});
