// Patch sealed AppKit GUI runtime v1.1.
// Payload v10 adds persistent text-list state and list-backed multi-select
// ListBox while preserving payload v9/runtime-v1.0 Table behavior.
#import <Cocoa/Cocoa.h>
#include <algorithm>
#include <fstream>

#define PATCH_APPKIT_RUNTIME_V09_ENTRY PatchSealedRuntimeV09Main
#include "appkit-sealed-gui-v09.mm"
#undef PATCH_APPKIT_RUNTIME_V09_ENTRY
#include "sealed-table-v10.hpp"
#include "sealed-list-v11.hpp"

static std::vector<PatchTableV10> gPatchTablesV10;
static std::vector<std::string> gPatchLastTableRowV10;
static NSInteger gPatchTableSelectionCountV10=0;
static std::vector<PatchListStateV11> gPatchListStatesV11;
static std::vector<PatchListBoxV11> gPatchListBoxesV11;
static std::vector<PatchListEventV11> gPatchListEventsV11;
static bool gPatchListRuntimeErrorV11=false;
static std::string gPatchListRuntimeErrorMessageV11;

static bool ReadSelfPayloadV11(std::vector<uint8_t>& payload){std::string path;if(!SelfPath(path))return false;std::ifstream file(path,std::ios::binary|std::ios::ate);if(!file)return false;std::streamoff size=file.tellg();if(size<20)return false;file.seekg(size-20);uint8_t footer[20]{};file.read(reinterpret_cast<char*>(footer),20);if(!file||memcmp(footer,PATCH_MAGIC,8)!=0)return false;auto le32=[](const uint8_t*p){return(uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);};const uint32_t version=le32(footer+8),length=le32(footer+12),crc=le32(footer+16);if(version!=10||!length||(uint64_t)length>(uint64_t)(size-20))return false;file.seekg(size-20-(std::streamoff)length);payload.resize(length);file.read(reinterpret_cast<char*>(payload.data()),(std::streamsize)length);return file&&Crc32(payload.data(),payload.size())==crc;}

static const PatchTableV10* PatchTableForIndexV10(int index){return PatchFindTableV10(gPatchTablesV10,index);}
static bool PatchResolveTablesV10(){for(const auto& table:gPatchTablesV10){if(table.nativeIndex<0||table.nativeIndex>=(int)gControls.size())return false;auto it=gControlById.find(table.id);if(it==gControlById.end()||it->second!=table.nativeIndex)return false;auto& c=gControls[(size_t)table.nativeIndex];if(c.kind!=CK_LISTBOX||c.binding!=table.shadowState)return false;}return true;}
static bool PatchResolveListsV11(){for(const auto& box:gPatchListBoxesV11){if(box.nativeIndex<0||box.nativeIndex>=(int)gControls.size())return false;auto it=gControlById.find(box.id);if(it==gControlById.end()||it->second!=box.nativeIndex)return false;auto& c=gControls[(size_t)box.nativeIndex];if(c.kind!=CK_LISTBOX||c.binding!=box.binding)return false;auto state=gStateByName.find(box.binding);if(state==gStateByName.end()||gStates[(size_t)state->second].type!=ST_TEXT)return false;if(!PatchFindListStateV11(gPatchListStatesV11,box.binding))return false;}return true;}

static std::vector<std::string> PatchSelectedListValuesV11(const PatchListBoxV11& box){std::vector<std::string> out;if(box.nativeIndex<0||box.nativeIndex>=(int)gControls.size())return out;auto& c=gControls[(size_t)box.nativeIndex];NSTableView* table=(NSTableView*)c.widget;if(!table)return out;NSIndexSet* selected=table.selectedRowIndexes;for(NSUInteger index=selected.firstIndex;index!=NSNotFound;index=[selected indexGreaterThanIndex:index])if(index<c.options.size())out.push_back(c.options[index]);return out;}
static void PatchSyncListShadowsV11(){for(const auto& state:gPatchListStatesV11){auto it=gStateByName.find(state.name);if(it!=gStateByName.end())gStates[(size_t)it->second].text=state.value.empty()?std::string():state.value.front();}}
static void PatchRefreshListsV11(){bool previous=gRefreshing;gRefreshing=true;for(const auto& box:gPatchListBoxesV11){if(box.nativeIndex<0||box.nativeIndex>=(int)gControls.size())continue;auto& c=gControls[(size_t)box.nativeIndex];auto* state=PatchFindListStateV11(gPatchListStatesV11,box.binding);NSTableView* table=(NSTableView*)c.widget;if(!state||!table)continue;NSMutableIndexSet* indexes=[NSMutableIndexSet indexSet];for(size_t index=0;index<c.options.size();++index)if(std::find(state->value.begin(),state->value.end(),c.options[index])!=state->value.end())[indexes addIndex:(NSUInteger)index];[table selectRowIndexes:indexes byExtendingSelection:NO];}gRefreshing=previous;}
static void PatchReportListErrorV11(const std::string& message){gPatchListRuntimeErrorV11=true;gPatchListRuntimeErrorMessageV11=message;if(gSmokeMode)return;NSAlert* alert=[NSAlert new];alert.alertStyle=NSAlertStyleCritical;alert.messageText=@"Patch stopped";alert.informativeText=NS(message);[alert addButtonWithTitle:@"OK"];[alert runModal];}
static bool PatchApplyListActionV11(const PatchListActionV11& action,const std::vector<std::string>* eventList){auto* state=PatchFindListStateV11(gPatchListStatesV11,action.target);if(!state)return false;for(const auto& op:action.ops){if(op.op==4){state->value.clear();continue;}if(op.op==1){if(op.valueKind==2){if(!eventList)return false;state->value=*eventList;}else if(op.valueKind==1)state->value=op.listValue;else return false;continue;}if(op.valueKind!=1)return false;if(op.op==2){state->value.push_back(op.textValue);continue;}if(op.op==3){auto it=std::find(state->value.begin(),state->value.end(),op.textValue);if(it==state->value.end()){PatchReportListErrorV11("Cannot remove "+op.textValue+" because it is not in the list.");return false;}state->value.erase(it);continue;}return false;}return true;}
static const PatchListActionV11* PatchListActionAtV11(const PatchListEventV11* meta,uint32_t index){if(!meta)return nullptr;for(const auto& action:meta->actions)if(action.actionIndex==index)return &action;return nullptr;}

static void PatchExecuteEventV11(const Event& event,bool eventBool,const std::string& eventText,const std::vector<std::string>* eventList=nullptr);
static void PatchDispatchResultV11(const std::string& id,uint8_t kind,const std::string& value={}){for(const auto& event:gEvents)if(event.control==id&&event.kind==kind)PatchExecuteEventV11(event,false,value,nullptr);}
static void PatchExecuteEventV11(const Event& event,bool eventBool,const std::string& eventText,const std::vector<std::string>* eventList){const auto* meta=PatchFindListEventV11(gPatchListEventsV11,event.control,event.kind);for(uint32_t index=0;index<(uint32_t)event.actions.size();++index){if(const auto* listAction=PatchListActionAtV11(meta,index)){if(!PatchApplyListActionV11(*listAction,eventList)){if(!gPatchListRuntimeErrorV11)PatchReportListErrorV11("Invalid sealed list operation.");return;}continue;}const auto& action=event.actions[index];if(action.kind==ACT_OPEN)[gForms[gFormById[action.form]].window makeKeyAndOrderFront:nil];else if(action.kind==ACT_CLOSE)[gForms[gFormById[action.form]].window orderOut:nil];else if(action.kind==ACT_DIALOG)ShowInfoDialog(action);else if(action.kind==ACT_CONFIRM){bool accepted=ShowConfirmDialog(action);gLastResultSource=NS(action.id);gLastResultValue=@"";gLastResultEvent=accepted?EV_CONFIRMED:EV_CANCELLED;PatchDispatchResultV11(action.id,accepted?EV_CONFIRMED:EV_CANCELLED);}else if(action.kind==ACT_OPEN_FILE||action.kind==ACT_SAVE_FILE){std::string value;bool chosen=ShowFileDialog(action,value);gLastResultSource=NS(action.id);gLastResultValue=chosen?NS(value):@"";gLastResultEvent=chosen?EV_CHOSEN:EV_CANCELLED;PatchDispatchResultV11(action.id,chosen?EV_CHOSEN:EV_CANCELLED,chosen?value:std::string());}else if(action.kind==ACT_CHANGE){State& state=gStates[gStateByName[action.target]];for(const auto& op:action.ops)ApplyOperation(state,op,eventBool,eventText);}}PatchSyncListShadowsV11();RefreshUI();PatchRefreshListsV11();}

static void PatchDispatchControlV11(int index,uint8_t kind,id sender=nil){if(gRefreshing||index<0||index>=(int)gControls.size())return;auto& control=gControls[(size_t)index];if(control.id.empty())return;for(const auto& event:gEvents){if(event.control!=control.id||event.kind!=kind)continue;bool eventBool=false;std::string eventText;std::vector<std::string> eventList;const std::vector<std::string>* eventListPtr=nullptr;if(event.valueType==1&&control.kind==CK_CHECKBOX)eventBool=[(NSButton*)control.widget state]==NSControlStateValueOn;else if(event.valueType==2&&control.kind==CK_INPUT)eventText=UTF8([(NSTextField*)control.widget stringValue]);else if(event.valueType==2&&control.kind==CK_COMBO)eventText=UTF8([(NSPopUpButton*)control.widget titleOfSelectedItem]);else if(event.valueType==2&&control.kind==CK_LISTBOX){const auto* box=PatchFindListBoxV11(gPatchListBoxesV11,control.id);if(box){eventList=PatchSelectedListValuesV11(*box);eventListPtr=&eventList;}else{NSInteger row=[(NSTableView*)control.widget selectedRow];if(row>=0&&(size_t)row<control.options.size())eventText=control.options[(size_t)row];}}else if(event.valueType==2&&control.kind==CK_RADIO)eventText=UTF8([(NSButton*)sender title]);PatchExecuteEventV11(event,eventBool,eventText,eventListPtr);}}
static void PatchDispatchMenuV11(int index){if(gRefreshing||index<0||index>=(int)gMenuItems.size())return;auto& item=gMenuItems[(size_t)index];for(const auto& event:gEvents)if(event.control==item.id&&event.kind==EV_CLICKED)PatchExecuteEventV11(event,false,{},nullptr);}

@interface PatchEventTargetV11 : PatchEventTarget
@end
@implementation PatchEventTargetV11
- (void)handleControl:(id)sender{NSInteger tag=[sender tag];if(tag>=20000){PatchDispatchMenuV11((int)(tag-20000));return;}NSInteger index=tag-1000;if(index<0||index>=(NSInteger)gControls.size())return;auto& c=gControls[(size_t)index];if(c.kind==CK_RADIO){for(NSButton* item in gRadioItems[(size_t)index])item.state=(item==sender)?NSControlStateValueOn:NSControlStateValueOff;}PatchDispatchControlV11((int)index,(c.kind==CK_CHECKBOX||c.kind==CK_COMBO||c.kind==CK_LISTBOX||c.kind==CK_RADIO)?EV_CHANGED:EV_CLICKED,sender);}
- (void)controlTextDidChange:(NSNotification*)notification{NSInteger index=[(NSTextField*)notification.object tag]-1000;PatchDispatchControlV11((int)index,EV_CHANGED,notification.object);}
- (void)tableViewSelectionDidChange:(NSNotification*)notification{if(!gRefreshing)[self handleControl:notification.object];}
@end

static void PatchDispatchTableV10(int controlIndex,NSInteger row){const PatchTableV10* table=PatchTableForIndexV10(controlIndex);if(!table||gRefreshing||row<0||row>=(NSInteger)table->rows.size())return;gPatchLastTableRowV10=table->rows[(size_t)row];++gPatchTableSelectionCountV10;for(const auto& event:gEvents)if(event.control==table->id&&event.kind==EV_CHANGED)PatchExecuteEventV11(event,false,{},nullptr);}
@interface PatchTableTargetV11 : NSObject <NSTableViewDataSource,NSTableViewDelegate>
@end
@implementation PatchTableTargetV11
- (NSInteger)numberOfRowsInTableView:(NSTableView*)tableView{NSInteger index=tableView.tag-1000;const PatchTableV10* table=PatchTableForIndexV10((int)index);return table?(NSInteger)table->rows.size():0;}
- (NSView*)tableView:(NSTableView*)tableView viewForTableColumn:(NSTableColumn*)column row:(NSInteger)row{NSInteger index=tableView.tag-1000;const PatchTableV10* table=PatchTableForIndexV10((int)index);if(!table||row<0||row>=(NSInteger)table->rows.size())return nil;NSInteger columnIndex=[column.identifier integerValue];if(columnIndex<0||columnIndex>=(NSInteger)table->columns.size())return nil;NSTextField* label=[NSTextField labelWithString:NS(table->rows[(size_t)row][(size_t)columnIndex])];label.lineBreakMode=NSLineBreakByTruncatingTail;return label;}
- (void)tableViewSelectionDidChange:(NSNotification*)notification{NSTableView* table=(NSTableView*)notification.object;if(table)PatchDispatchTableV10((int)(table.tag-1000),table.selectedRow);}
@end
static PatchTableTargetV11* gPatchTableTargetV11=nil;

static bool PatchInstallTableV10(const PatchTableV10& table){auto& c=gControls[(size_t)table.nativeIndex];NSTableView* legacy=(NSTableView*)c.widget;NSScrollView* scroll=legacy?[legacy enclosingScrollView]:nil;if(!scroll)return false;NSTableView* view=[[NSTableView alloc]initWithFrame:scroll.bounds];const CGFloat baseWidth=std::max(40,c.width/(int)std::max<size_t>(1,table.columns.size()));for(size_t columnIndex=0;columnIndex<table.columns.size();++columnIndex){NSTableColumn* column=[[NSTableColumn alloc]initWithIdentifier:[NSString stringWithFormat:@"%zu",columnIndex]];column.title=NS(table.columns[columnIndex]);column.width=columnIndex+1==table.columns.size()?std::max<CGFloat>(40,c.width-baseWidth*(CGFloat)columnIndex):baseWidth;[view addTableColumn:column];}view.allowsMultipleSelection=NO;view.allowsEmptySelection=YES;view.tag=1000+table.nativeIndex;view.dataSource=gPatchTableTargetV11;view.delegate=gPatchTableTargetV11;scroll.documentView=view;c.widget=view;c.kind=9;return true;}
static bool PatchInstallTablesV10(){gPatchTableTargetV11=[PatchTableTargetV11 new];for(const auto& table:gPatchTablesV10)if(!PatchInstallTableV10(table))return false;return true;}
static bool PatchInstallListsV11(){for(const auto& box:gPatchListBoxesV11){auto& c=gControls[(size_t)box.nativeIndex];NSTableView* table=(NSTableView*)c.widget;if(!table)return false;table.allowsMultipleSelection=YES;table.allowsEmptySelection=YES;table.delegate=gEventTarget;table.dataSource=gEventTarget;}return true;}
static void ApplyPatchTableAccessibilityV10(){for(const auto& table:gPatchTablesV10){auto& c=gControls[(size_t)table.nativeIndex];if(c.widget)[c.widget setAccessibilityLabel:NS(PatchControlNameV09(c))];}}
static int RunPatchTableAccessibilitySmokeV10(){int code=210;for(const auto& table:gPatchTablesV10){auto& c=gControls[(size_t)table.nativeIndex];if(!c.widget||![[c.widget accessibilityLabel]isEqualToString:NS(PatchControlNameV09(c))])return code++;}return 0;}
static void MovePatchControlV10(int index,int x,int y,int width,int height,int formHeight){if(index<0||index>=(int)gControls.size())return;auto& c=gControls[(size_t)index];if(c.kind!=9){MovePatchControlV09(index,x,y,width,height,formHeight);return;}NSTableView* table=(NSTableView*)c.widget;NSScrollView* scroll=table?[table enclosingScrollView]:nil;if(!scroll)return;const int nativeY=std::max(0,formHeight-y-height);scroll.frame=NSMakeRect(x,nativeY,width,height);table.frame=NSMakeRect(0,0,width,height);const NSInteger count=[table numberOfColumns];if(count>0){const CGFloat columnWidth=std::max<CGFloat>(40,width/(CGFloat)count);for(NSInteger column=0;column<count;++column){NSTableColumn* item=[[table tableColumns]objectAtIndex:(NSUInteger)column];item.width=column+1==count?std::max<CGFloat>(40,width-columnWidth*(CGFloat)column):columnWidth;}}}
static void ApplyPatchResponsiveLayoutV10(int formIndex,int formWidth,int formHeight){if(formIndex<0||formIndex>=(int)gForms.size()||formWidth<=0||formHeight<=0||gPatchLayoutPoliciesV09.size()!=gControls.size())return;const auto& form=gForms[(size_t)formIndex];for(int index=0;index<(int)gControls.size();++index){auto& c=gControls[(size_t)index];if(c.formIndex!=formIndex||c.parentTabIndex>=0||!PatchPolicyResponsiveV09(gPatchLayoutPoliciesV09[(size_t)index]))continue;int x=c.x,y=c.y,width=c.width,height=c.height;PatchApplyLayoutPolicyV09(gPatchLayoutPoliciesV09[(size_t)index],form.width,form.height,formWidth,formHeight,x,y,width,height);MovePatchControlV10(index,x,y,width,height,formHeight);}}
@interface PatchResponsiveObserverV11 : NSObject
- (void)windowDidResize:(NSNotification*)notification;
@end
@implementation PatchResponsiveObserverV11
- (void)windowDidResize:(NSNotification*)notification{NSWindow* window=(NSWindow*)notification.object;for(size_t index=0;index<gForms.size();++index)if(gForms[index].window==window){const NSSize size=window.contentView.bounds.size;ApplyPatchResponsiveLayoutV10((int)index,(int)llround(size.width),(int)llround(size.height));break;}}
@end
static PatchResponsiveObserverV11* gPatchResponsiveObserverV11=nil;
static int RunPatchResponsiveSmokeV10(){if(gPatchLayoutPoliciesV09.size()!=gControls.size())return 180;for(int index=0;index<(int)gControls.size();++index){auto& c=gControls[(size_t)index];const auto policy=gPatchLayoutPoliciesV09[(size_t)index];if(c.parentTabIndex>=0||!PatchPolicyResponsiveV09(policy))continue;const auto& form=gForms[(size_t)c.formIndex];int x=c.x,y=c.y,width=c.width,height=c.height;PatchApplyLayoutPolicyV09(policy,form.width,form.height,form.width+80,form.height+60,x,y,width,height);ApplyPatchResponsiveLayoutV10(c.formIndex,form.width+80,form.height+60);if(c.kind==CK_RADIO)return 0;NSView* measured=(c.kind==CK_LISTBOX||c.kind==9)?[(NSTableView*)c.widget enclosingScrollView]:c.widget;if(!measured)return 181;NSRect frame=measured.frame;if((int)llround(frame.origin.x)!=x||(int)llround(frame.size.width)!=width||(int)llround(frame.size.height)!=height)return 182;return 0;}return 0;}
static int RunPatchTableSmokeV10(){int code=220;for(const auto& table:gPatchTablesV10){auto& c=gControls[(size_t)table.nativeIndex];NSTableView* view=(NSTableView*)c.widget;if(!view||c.kind!=9)return code++;if([view numberOfColumns]!=(NSInteger)table.columns.size()||[view numberOfRows]!=(NSInteger)table.rows.size())return code++;if(table.rows.empty())return code++;const NSInteger row=(NSInteger)table.rows.size()-1;const NSInteger before=gPatchTableSelectionCountV10;[view selectRowIndexes:[NSIndexSet indexSetWithIndex:(NSUInteger)row]byExtendingSelection:NO];[gPatchTableTargetV11 tableViewSelectionDidChange:[NSNotification notificationWithName:NSTableViewSelectionDidChangeNotification object:view]];if(gPatchTableSelectionCountV10<=before)return code++;if(gPatchLastTableRowV10!=table.rows[(size_t)row])return code++;}return 0;}
static int RunPatchListSmokeV11(){int code=240;for(const auto& box:gPatchListBoxesV11){auto& c=gControls[(size_t)box.nativeIndex];auto* state=PatchFindListStateV11(gPatchListStatesV11,box.binding);NSTableView* table=(NSTableView*)c.widget;if(!state||!table||!table.allowsMultipleSelection)return code++;PatchRefreshListsV11();if(PatchSelectedListValuesV11(box)!=state->value)return code++;if(c.options.size()<2)return code++;NSMutableIndexSet* indexes=[NSMutableIndexSet indexSet];[indexes addIndex:0];[indexes addIndex:c.options.size()-1];bool previous=gRefreshing;gRefreshing=true;[table selectRowIndexes:indexes byExtendingSelection:NO];gRefreshing=previous;auto selected=PatchSelectedListValuesV11(box);[gEventTarget tableViewSelectionDidChange:[NSNotification notificationWithName:NSTableViewSelectionDidChangeNotification object:table]];if(gPatchListRuntimeErrorV11)return code++;if(state->value!=selected)return code++;if(PatchSelectedListValuesV11(box)!=state->value)return code++;}return 0;}

int main(int argc,const char* argv[]){@autoreleasepool{[NSApplication sharedApplication];[NSApp setActivationPolicy:NSApplicationActivationPolicyRegular];gSmokeMode=HasArg(argc,argv,"--patch-smoke");std::vector<uint8_t> payloadV10,payloadV9,payloadV8,payloadV7;if(!ReadSelfPayloadV11(payloadV10)||!PatchConvertPayloadV10ToV9(payloadV10,payloadV9,gPatchListStatesV11,gPatchListBoxesV11,gPatchListEventsV11)||!PatchConvertPayloadV9ToV8(payloadV9,payloadV8,gPatchTablesV10)||!PatchConvertPayloadV8ToV7(payloadV8,payloadV7,gPatchLayoutPoliciesV09)||!ParsePayload(payloadV7))return 20;if(gPatchLayoutPoliciesV09.size()!=gControls.size()||!PatchResolveTablesV10()||!PatchResolveListsV11())return 22;PatchSyncListShadowsV11();gEventTarget=[PatchEventTargetV11 new];gWindowDelegates=[NSMutableArray arrayWithCapacity:gForms.size()];CreateMenus();if(!CreateForms()||!PatchInstallTablesV10()||!PatchInstallListsV11())return 21;gPatchResponsiveObserverV11=[PatchResponsiveObserverV11 new];[[NSNotificationCenter defaultCenter]addObserver:gPatchResponsiveObserverV11 selector:@selector(windowDidResize:) name:NSWindowDidResizeNotification object:nil];ApplyPatchAccessibilityV09();ApplyPatchTableAccessibilityV10();RefreshUI();PatchRefreshListsV11();[NSApp finishLaunching];for(auto& f:gForms)if(f.visible)[f.window makeKeyAndOrderFront:nil];if(gSmokeMode){int result=RunSmoke();if(!result)result=RunPatchAccessibilitySmokeV09();if(!result)result=RunPatchTableAccessibilitySmokeV10();if(!result)result=RunPatchResponsiveSmokeV10();if(!result)result=RunPatchTableSmokeV10();if(!result)result=RunPatchListSmokeV11();return result;}[NSApp activateIgnoringOtherApps:YES];[NSApp run];}return 0;}
