// Patch sealed GTK3 GUI runtime v1.3.
// Payload v12 adds TreeView hierarchy over frozen payload-v11/runtime-v1.2.
#include <gtk/gtk.h>
#include <algorithm>
#include <fstream>
#include <vector>

#define PATCH_RUNTIME_V13_RESTORE_MAIN PatchRuntimeV12CompatibilityMain
#include "gtk-sealed-gui-v12.cpp"
#undef main
#undef PATCH_RUNTIME_V13_RESTORE_MAIN
#include "sealed-tree-v13.hpp"

struct PatchGtkTreeV13 { GtkWidget* scroll=nullptr; GtkWidget* view=nullptr; GtkTreeStore* store=nullptr; };
static std::vector<PatchTreeV13> gPatchTreesV13;
static std::vector<PatchGtkTreeV13> gPatchGtkTreesV13;
static int gPatchTreeSelectionCountV13=0;

static bool ReadSelfPayloadV13(std::vector<uint8_t>& payload){std::string path;if(!SelfPath(path))return false;std::ifstream file(path,std::ios::binary|std::ios::ate);if(!file)return false;std::streamoff size=file.tellg();if(size<20)return false;file.seekg(size-20);uint8_t footer[20]{};file.read(reinterpret_cast<char*>(footer),20);if(!file||memcmp(footer,PATCH_MAGIC,8)!=0)return false;auto le32=[](const uint8_t*p){return(uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);};const uint32_t version=le32(footer+8),length=le32(footer+12),crc=le32(footer+16);if(version!=12||!length||(uint64_t)length>(uint64_t)(size-20))return false;file.seekg(size-20-(std::streamoff)length);payload.resize(length);file.read(reinterpret_cast<char*>(payload.data()),(std::streamsize)length);return file&&Crc32(payload.data(),payload.size())==crc;}
static bool PatchResolveTreesV13(){for(const auto& tree:gPatchTreesV13){if(tree.nativeIndex<0||tree.nativeIndex>=(int)gControls.size())return false;auto it=gControlById.find(tree.id);if(it==gControlById.end()||it->second!=tree.nativeIndex)return false;auto& c=gControls[(size_t)tree.nativeIndex];if(c.kind!=CK_LISTBOX||!PatchFindListBoxV11(gPatchListBoxesV11,tree.id)||c.options.size()<tree.nodes.size())return false;}return true;}
static std::string PatchTreeTextV13(const PatchTreeNodeV13& node){return RenderText(node.text);}

static void PatchPopulateTreeV13(const PatchTreeV13& tree){auto& native=gPatchGtkTreesV13[(size_t)tree.nativeIndex];auto& c=gControls[(size_t)tree.nativeIndex];if(!native.store)return;gtk_tree_store_clear(native.store);std::vector<GtkTreeIter> iters;iters.reserve(tree.nodes.size());for(size_t index=0;index<tree.nodes.size();++index){const auto& node=tree.nodes[index];GtkTreeIter iter;GtkTreeIter* parent=node.parent<0?nullptr:&iters[(size_t)node.parent];gtk_tree_store_append(native.store,&iter,parent);std::string text=PatchTreeTextV13(node);c.options[index]=text;gtk_tree_store_set(native.store,&iter,0,text.c_str(),1,(gint)index,-1);iters.push_back(iter);}if(native.view)gtk_tree_view_expand_all(GTK_TREE_VIEW(native.view));}

static void PatchRefreshShadowRowsV13(const PatchTreeV13& tree){auto& c=gControls[(size_t)tree.nativeIndex];if(!c.widget||!GTK_IS_LIST_BOX(c.widget))return;for(size_t index=0;index<tree.nodes.size();++index){GtkListBoxRow* row=gtk_list_box_get_row_at_index(GTK_LIST_BOX(c.widget),(gint)index);if(!row)continue;GtkWidget* child=gtk_bin_get_child(GTK_BIN(row));if(child&&GTK_IS_LABEL(child))gtk_label_set_text(GTK_LABEL(child),c.options[index].c_str());}}

static void PatchRefreshTreesV13(){bool previous=gRefreshing;gRefreshing=true;for(const auto& tree:gPatchTreesV13){auto& c=gControls[(size_t)tree.nativeIndex];auto& native=gPatchGtkTreesV13[(size_t)tree.nativeIndex];if(!c.widget||!native.scroll)continue;PatchPopulateTreeV13(tree);PatchRefreshShadowRowsV13(tree);GtkWidget* parent=gtk_widget_get_parent(c.widget);if(parent&&GTK_IS_FIXED(parent)){GtkAllocation allocation{};gtk_widget_get_allocation(c.widget,&allocation);gtk_fixed_move(GTK_FIXED(parent),native.scroll,allocation.x,allocation.y);gtk_widget_set_size_request(native.scroll,std::max(1,allocation.width),std::max(1,allocation.height));}gtk_widget_hide(c.widget);gtk_widget_show_all(native.scroll);}gRefreshing=previous;}

static bool PatchDispatchTreeSelectionV13(const PatchTreeV13& tree,int nodeIndex){if(nodeIndex<0||nodeIndex>=(int)tree.nodes.size())return false;auto path=PatchTreePathIndicesV13(tree,nodeIndex);if(path.empty())return false;auto& c=gControls[(size_t)tree.nativeIndex];if(!c.widget||!GTK_IS_LIST_BOX(c.widget))return false;const auto* box=PatchFindListBoxV11(gPatchListBoxesV11,tree.id);if(!box)return false;PatchRefreshTreesV13();bool previous=gRefreshing;gRefreshing=true;gtk_list_box_unselect_all(GTK_LIST_BOX(c.widget));for(int index:path){GtkListBoxRow* row=gtk_list_box_get_row_at_index(GTK_LIST_BOX(c.widget),index);if(row)gtk_list_box_select_row(GTK_LIST_BOX(c.widget),row);}gRefreshing=previous;auto values=PatchSelectedListValuesV11(*box);++gPatchTreeSelectionCountV13;PatchDispatchControlV11(tree.nativeIndex,EV_CHANGED,false,{},&values);PatchRefreshMenusV12();PatchRefreshTreesV13();return true;}

static void PatchOnTreeChangedV13(GtkTreeSelection* selection,gpointer data){if(gRefreshing)return;int nativeIndex=GPOINTER_TO_INT(data);const auto* tree=PatchTreeForNativeIndexV13(gPatchTreesV13,nativeIndex);if(!tree)return;GtkTreeModel* model=nullptr;GtkTreeIter iter;if(!gtk_tree_selection_get_selected(selection,&model,&iter))return;gint flat=-1;gtk_tree_model_get(model,&iter,1,&flat,-1);PatchDispatchTreeSelectionV13(*tree,flat);}

static bool PatchInstallTreesV13(){gPatchGtkTreesV13.assign(gControls.size(),{});for(const auto& tree:gPatchTreesV13){auto& c=gControls[(size_t)tree.nativeIndex];if(!c.widget)return false;GtkWidget* parent=gtk_widget_get_parent(c.widget);if(!parent||!GTK_IS_FIXED(parent))return false;GtkAllocation allocation{};gtk_widget_get_allocation(c.widget,&allocation);auto& native=gPatchGtkTreesV13[(size_t)tree.nativeIndex];native.store=gtk_tree_store_new(2,G_TYPE_STRING,G_TYPE_INT);native.view=gtk_tree_view_new_with_model(GTK_TREE_MODEL(native.store));GtkCellRenderer* renderer=gtk_cell_renderer_text_new();GtkTreeViewColumn* column=gtk_tree_view_column_new_with_attributes("",renderer,"text",0,nullptr);gtk_tree_view_append_column(GTK_TREE_VIEW(native.view),column);gtk_tree_view_set_headers_visible(GTK_TREE_VIEW(native.view),FALSE);GtkTreeSelection* selection=gtk_tree_view_get_selection(GTK_TREE_VIEW(native.view));gtk_tree_selection_set_mode(selection,GTK_SELECTION_SINGLE);g_signal_connect(selection,"changed",G_CALLBACK(PatchOnTreeChangedV13),GINT_TO_POINTER(tree.nativeIndex));native.scroll=gtk_scrolled_window_new(nullptr,nullptr);gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(native.scroll),GTK_POLICY_AUTOMATIC,GTK_POLICY_AUTOMATIC);gtk_container_add(GTK_CONTAINER(native.scroll),native.view);gtk_widget_set_size_request(native.scroll,std::max(1,allocation.width),std::max(1,allocation.height));gtk_fixed_put(GTK_FIXED(parent),native.scroll,allocation.x,allocation.y);AtkObject* accessible=gtk_widget_get_accessible(native.view);if(accessible)atk_object_set_name(accessible,PatchControlNameV09(c).c_str());PatchPopulateTreeV13(tree);gtk_widget_hide(c.widget);gtk_widget_show_all(native.scroll);}return true;}

static void PatchOnClickedV13(GtkWidget* widget,gpointer data){PatchOnClickedV12(widget,data);PatchRefreshTreesV13();}
static void PatchOnToggledV13(GtkToggleButton* widget,gpointer data){PatchOnToggledV12(widget,data);PatchRefreshTreesV13();}
static void PatchOnRadioV13(GtkToggleButton* widget,gpointer data){PatchOnRadioV12(widget,data);PatchRefreshTreesV13();}
static void PatchOnInputV13(GtkEditable* widget,gpointer data){PatchOnInputV12(widget,data);PatchRefreshTreesV13();}
static void PatchOnComboV13(GtkComboBox* widget,gpointer data){PatchOnComboV12(widget,data);PatchRefreshTreesV13();}
static void PatchOnListSingleV13(GtkListBox* box,GtkListBoxRow* row,gpointer data){PatchOnListSingleV12(box,row,data);PatchRefreshTreesV13();}
static void PatchOnListMultiV13(GtkListBox* box,gpointer data){PatchOnListMultiV12(box,data);PatchRefreshTreesV13();}
static void PatchOnTableChangedV13(GtkTreeSelection* selection,gpointer data){PatchOnTableChangedV12(selection,data);PatchRefreshTreesV13();}
static void PatchOnFormAllocateV13(GtkWidget*,GtkAllocation*,gpointer){PatchRefreshTreesV13();}

static bool PatchRewireEventsV13(){for(int index=0;index<(int)gControls.size();++index){auto& c=gControls[(size_t)index];if(c.kind==9)continue;gpointer data=GINT_TO_POINTER(index);if(c.kind==CK_BUTTON){g_signal_handlers_disconnect_by_func(c.widget,(gpointer)PatchOnClickedV12,data);g_signal_connect(c.widget,"clicked",G_CALLBACK(PatchOnClickedV13),data);}else if(c.kind==CK_CHECKBOX){g_signal_handlers_disconnect_by_func(c.widget,(gpointer)PatchOnToggledV12,data);g_signal_connect(c.widget,"toggled",G_CALLBACK(PatchOnToggledV13),data);}else if(c.kind==CK_INPUT){g_signal_handlers_disconnect_by_func(c.widget,(gpointer)PatchOnInputV12,data);g_signal_connect(c.widget,"changed",G_CALLBACK(PatchOnInputV13),data);}else if(c.kind==CK_COMBO){g_signal_handlers_disconnect_by_func(c.widget,(gpointer)PatchOnComboV12,data);g_signal_connect(c.widget,"changed",G_CALLBACK(PatchOnComboV13),data);}else if(c.kind==CK_LISTBOX){const bool multi=PatchFindListBoxV11(gPatchListBoxesV11,c.id)!=nullptr;if(multi){g_signal_handlers_disconnect_by_func(c.widget,(gpointer)PatchOnListMultiV12,data);g_signal_connect(c.widget,"selected-rows-changed",G_CALLBACK(PatchOnListMultiV13),data);}else{g_signal_handlers_disconnect_by_func(c.widget,(gpointer)PatchOnListSingleV12,data);g_signal_connect(c.widget,"row-selected",G_CALLBACK(PatchOnListSingleV13),data);}}else if(c.kind==CK_RADIO){for(GtkWidget* item:c.radioItems){g_signal_handlers_disconnect_by_func(item,(gpointer)PatchOnRadioV12,data);g_signal_connect(item,"toggled",G_CALLBACK(PatchOnRadioV13),data);}}}for(const auto& table:gPatchTablesV10){GtkWidget* view=gPatchTableViewsV10[(size_t)table.nativeIndex];if(!view)return false;GtkTreeSelection* selection=gtk_tree_view_get_selection(GTK_TREE_VIEW(view));gpointer data=GINT_TO_POINTER(table.nativeIndex);g_signal_handlers_disconnect_by_func(selection,(gpointer)PatchOnTableChangedV12,data);g_signal_connect(selection,"changed",G_CALLBACK(PatchOnTableChangedV13),data);}return true;}

static int RunPatchTreeSmokeV13(){for(const auto& tree:gPatchTreesV13){auto& native=gPatchGtkTreesV13[(size_t)tree.nativeIndex];if(!native.view){g_printerr("Patch TreeView v1.3 smoke: '%s' has no GTK TreeView.\n",tree.id.c_str());return 200;}if(!native.store){g_printerr("Patch TreeView v1.3 smoke: '%s' has no GTK TreeStore.\n",tree.id.c_str());return 201;}const int modelCount=PatchTreeModelCount(GTK_TREE_MODEL(native.store),nullptr);if(modelCount!=(int)tree.nodes.size()){g_printerr("Patch TreeView v1.3 smoke: '%s' model has %d nodes; expected %zu.\n",tree.id.c_str(),modelCount,tree.nodes.size());return 202;}if(tree.id=="files"&&!tree.nodes.empty()){auto* selected=PatchFindListStateV11(gPatchListStatesV11,"selected");if(selected){int before=gPatchTreeSelectionCountV13;if(!PatchDispatchTreeSelectionV13(tree,(int)tree.nodes.size()-1)||gPatchTreeSelectionCountV13!=before+1){g_printerr("Patch TreeView v1.3 smoke: '%s' selection dispatch failed.\n",tree.id.c_str());return 203;}auto path=PatchTreePathIndicesV13(tree,(int)tree.nodes.size()-1);std::vector<std::string> expected;for(int node:path)expected.push_back(PatchTreeTextV13(tree.nodes[(size_t)node]));if(selected->value!=expected){g_printerr("Patch TreeView v1.3 smoke: '%s' selected path did not persist through semantic change.\n",tree.id.c_str());return 204;}}}}return 0;}

int main(int argc,char* argv[]){gSmokeMode=HasArg(argc,argv,"--patch-smoke");std::vector<uint8_t> payloadV12,payloadV11,payloadV10,payloadV9,payloadV8,payloadV7;if(!ReadSelfPayloadV13(payloadV12)||!PatchConvertPayloadV12ToV11(payloadV12,payloadV11,gPatchTreesV13)||!PatchConvertPayloadV11ToV10(payloadV11,payloadV10,gPatchMenuEntriesV12)||!PatchConvertPayloadV10ToV9(payloadV10,payloadV9,gPatchListStatesV11,gPatchListBoxesV11,gPatchListEventsV11)||!PatchConvertPayloadV9ToV8(payloadV9,payloadV8,gPatchTablesV10)||!PatchConvertPayloadV8ToV7(payloadV8,payloadV7,gPatchLayoutPoliciesV09)||!ParsePayload(payloadV7))return 20;if(gPatchLayoutPoliciesV09.size()!=gControls.size()||!PatchResolveTablesV10()||!PatchResolveListsV11()||!PatchResolveTreesV13())return 22;PatchSyncListShadowsV11();gtk_init(&argc,&argv);if(!CreateForms()||!PatchInstallTablesV10()||!PatchRewireEventsV11()||!PatchInstallMenusV12()||!PatchRewireEventsV12()||!PatchRewireTableEventsV12()||!PatchInstallTreesV13()||!PatchRewireEventsV13())return 21;for(int index=0;index<(int)gForms.size();++index)if(gForms[(size_t)index].fixed){g_signal_connect(gForms[(size_t)index].fixed,"size-allocate",G_CALLBACK(OnPatchFormAllocateV09),GINT_TO_POINTER(index));g_signal_connect(gForms[(size_t)index].fixed,"size-allocate",G_CALLBACK(PatchOnFormAllocateV13),GINT_TO_POINTER(index));}ApplyPatchAccessibilityV09();ApplyPatchTableAccessibilityV10();RefreshUI();PatchRefreshListsV11();PatchRefreshMenusV12();PatchRefreshTreesV13();for(auto& f:gForms)if(f.visible)gtk_widget_show_all(f.window);PatchRefreshTreesV13();while(gtk_events_pending())gtk_main_iteration();if(gSmokeMode){int result=RunSmoke();if(!result)result=RunPatchAccessibilitySmokeV09();if(!result)result=RunPatchTableAccessibilitySmokeV10();if(!result)result=RunPatchResponsiveSmokeV09();if(!result)result=RunPatchTableSmokeV10();if(!result)result=RunPatchListSmokeV11();if(!result)result=RunPatchMenuSmokeV12();if(!result)result=RunPatchTreeSmokeV13();PatchDestroyMenusV12();return result;}gtk_main();PatchDestroyMenusV12();return 0;}
