// Patch sealed GTK3 GUI runtime v1.4.
// Payload v13 adds native Slider metadata over frozen payload-v12/runtime-v1.3.
#define PATCH_RUNTIME_V14_RESTORE_MAIN PatchRuntimeV13CompatibilityMain
#include "gtk-sealed-gui-v13.cpp"
#undef main
#undef PATCH_RUNTIME_V14_RESTORE_MAIN
#include "sealed-slider-v14.hpp"

static std::vector<PatchSliderV14> gPatchSlidersV14;
static std::vector<GtkWidget*> gPatchSliderViewsV14;
static int gPatchSliderDispatchCountV14=0;

static bool ReadSelfPayloadV14(std::vector<uint8_t>& payload){std::string path;if(!SelfPath(path))return false;std::ifstream file(path,std::ios::binary|std::ios::ate);if(!file)return false;std::streamoff size=file.tellg();if(size<20)return false;file.seekg(size-20);uint8_t footer[20]{};file.read(reinterpret_cast<char*>(footer),20);if(!file||memcmp(footer,PATCH_MAGIC,8)!=0)return false;auto le32=[](const uint8_t*p){return(uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);};const uint32_t version=le32(footer+8),length=le32(footer+12),crc=le32(footer+16);if(version!=13||!length||(uint64_t)length>(uint64_t)(size-20))return false;file.seekg(size-20-(std::streamoff)length);payload.resize(length);file.read(reinterpret_cast<char*>(payload.data()),(std::streamsize)length);return file&&Crc32(payload.data(),payload.size())==crc;}

static bool PatchSliderStateValueV14(const PatchSliderV14& slider,double& value){if(slider.binding.empty()){value=slider.min;return true;}auto it=gStateByName.find(slider.binding);if(it==gStateByName.end())return false;const auto& state=gStates[(size_t)it->second];if(state.type!=ST_NUMBER||!std::isfinite(state.number))return false;value=state.number;return true;}
static double PatchSliderValueV14(const PatchSliderV14& slider,GtkRange* range){double raw=range?gtk_range_get_value(range):slider.min;double steps=std::round((raw-slider.min)/slider.step);double value=slider.min+steps*slider.step;return std::max(slider.min,std::min(slider.max,value));}
static bool PatchResolveSlidersV14(){for(const auto& slider:gPatchSlidersV14){if(slider.nativeIndex<0||slider.nativeIndex>=(int)gControls.size())return false;auto it=gControlById.find(slider.id);if(it==gControlById.end()||it->second!=slider.nativeIndex)return false;const auto& c=gControls[(size_t)slider.nativeIndex];if(c.kind!=CK_INPUT)return false;double initial=0;if(!PatchSliderStateValueV14(slider,initial))return false;for(const auto& patch:slider.events){if(patch.eventIndex>=gEvents.size())return false;const auto& event=gEvents[(size_t)patch.eventIndex];if(event.control!=slider.id||event.kind!=EV_CHANGED)return false;}}return true;}

struct PatchSliderSentinelRestoreV14{Operation* op=nullptr;double value=0;};
static bool PatchExecuteSliderEventV14(const PatchSliderV14& slider,const PatchSliderEventPatchV14& patch,double value){if(patch.eventIndex>=gEvents.size())return false;Event& event=gEvents[(size_t)patch.eventIndex];std::vector<PatchSliderSentinelRestoreV14> restore;for(auto& action:event.actions)for(auto& op:action.ops)if(op.valueKind==VK_LITERAL&&action.stateType==ST_NUMBER)for(double sentinel:patch.sentinels)if(op.number==sentinel){restore.push_back({&op,op.number});op.number=value;break;}if(restore.size()!=patch.sentinels.size()){for(auto& item:restore)item.op->number=item.value;return false;}PatchExecuteEventV11(event,false,{},nullptr);for(auto& item:restore)item.op->number=item.value;++gPatchSliderDispatchCountV14;return true;}

static void PatchRefreshSlidersV14(){bool previous=gRefreshing;gRefreshing=true;for(const auto& slider:gPatchSlidersV14){if(slider.nativeIndex<0||slider.nativeIndex>=(int)gPatchSliderViewsV14.size())continue;GtkWidget* view=gPatchSliderViewsV14[(size_t)slider.nativeIndex];auto& c=gControls[(size_t)slider.nativeIndex];if(!view||!c.widget)continue;if(!slider.binding.empty()){double value=slider.min;if(PatchSliderStateValueV14(slider,value))gtk_range_set_value(GTK_RANGE(view),value);}GtkWidget* parent=gtk_widget_get_parent(c.widget);if(parent&&GTK_IS_FIXED(parent)){GtkAllocation allocation{};gtk_widget_get_allocation(c.widget,&allocation);gtk_fixed_move(GTK_FIXED(parent),view,allocation.x,allocation.y);gtk_widget_set_size_request(view,std::max(1,allocation.width),std::max(1,allocation.height));}gtk_widget_hide(c.widget);gtk_widget_show(view);}gRefreshing=previous;}
static bool PatchDispatchSliderV14(const PatchSliderV14& slider,GtkRange* range){if(gRefreshing||!range)return false;double value=PatchSliderValueV14(slider,range);gtk_range_set_value(range,value);for(const auto& patch:slider.events)if(!PatchExecuteSliderEventV14(slider,patch,value))return false;PatchRefreshMenusV12();PatchRefreshTreesV13();PatchRefreshSlidersV14();return true;}
static void PatchOnSliderChangedV14(GtkRange* range,gpointer data){if(gRefreshing)return;const auto* slider=PatchSliderForNativeIndexV14(gPatchSlidersV14,GPOINTER_TO_INT(data));if(slider)PatchDispatchSliderV14(*slider,range);}

static bool PatchInstallSlidersV14(){gPatchSliderViewsV14.assign(gControls.size(),nullptr);for(const auto& slider:gPatchSlidersV14){auto& c=gControls[(size_t)slider.nativeIndex];if(!c.widget)return false;GtkWidget* parent=gtk_widget_get_parent(c.widget);if(!parent||!GTK_IS_FIXED(parent))return false;GtkAllocation allocation{};gtk_widget_get_allocation(c.widget,&allocation);GtkWidget* view=gtk_scale_new_with_range(GTK_ORIENTATION_HORIZONTAL,slider.min,slider.max,slider.step);if(!view)return false;gtk_scale_set_draw_value(GTK_SCALE(view),FALSE);gtk_widget_set_size_request(view,std::max(1,allocation.width),std::max(1,allocation.height));gtk_fixed_put(GTK_FIXED(parent),view,allocation.x,allocation.y);double initial=slider.min;if(!PatchSliderStateValueV14(slider,initial))return false;gtk_range_set_value(GTK_RANGE(view),initial);g_signal_connect(view,"value-changed",G_CALLBACK(PatchOnSliderChangedV14),GINT_TO_POINTER(slider.nativeIndex));AtkObject* accessible=gtk_widget_get_accessible(view);if(accessible)atk_object_set_name(accessible,PatchControlNameV09(c).c_str());gPatchSliderViewsV14[(size_t)slider.nativeIndex]=view;gtk_widget_hide(c.widget);gtk_widget_show(view);}return true;}

static void PatchOnClickedV14(GtkWidget* widget,gpointer data){PatchOnClickedV13(widget,data);PatchRefreshSlidersV14();}
static void PatchOnToggledV14(GtkToggleButton* widget,gpointer data){PatchOnToggledV13(widget,data);PatchRefreshSlidersV14();}
static void PatchOnRadioV14(GtkToggleButton* widget,gpointer data){PatchOnRadioV13(widget,data);PatchRefreshSlidersV14();}
static void PatchOnInputV14(GtkEditable* widget,gpointer data){PatchOnInputV13(widget,data);PatchRefreshSlidersV14();}
static void PatchOnComboV14(GtkComboBox* widget,gpointer data){PatchOnComboV13(widget,data);PatchRefreshSlidersV14();}
static void PatchOnListSingleV14(GtkListBox* box,GtkListBoxRow* row,gpointer data){PatchOnListSingleV13(box,row,data);PatchRefreshSlidersV14();}
static void PatchOnListMultiV14(GtkListBox* box,gpointer data){PatchOnListMultiV13(box,data);PatchRefreshSlidersV14();}
static void PatchOnTableChangedV14(GtkTreeSelection* selection,gpointer data){PatchOnTableChangedV13(selection,data);PatchRefreshSlidersV14();}
static void PatchOnMenuV14(GtkWidget* widget,gpointer data){PatchOnMenuV12(widget,data);PatchRefreshTreesV13();PatchRefreshSlidersV14();}
static void PatchOnTreeRefreshV14(GtkTreeSelection*,gpointer){PatchRefreshSlidersV14();}
static void PatchOnFormAllocateV14(GtkWidget*,GtkAllocation*,gpointer){PatchRefreshSlidersV14();}

static bool PatchRewireEventsV14(){for(int index=0;index<(int)gControls.size();++index){auto& c=gControls[(size_t)index];if(c.kind==9)continue;gpointer data=GINT_TO_POINTER(index);if(PatchSliderForNativeIndexV14(gPatchSlidersV14,index))continue;if(c.kind==CK_BUTTON){g_signal_handlers_disconnect_by_func(c.widget,(gpointer)PatchOnClickedV13,data);g_signal_connect(c.widget,"clicked",G_CALLBACK(PatchOnClickedV14),data);}else if(c.kind==CK_CHECKBOX){g_signal_handlers_disconnect_by_func(c.widget,(gpointer)PatchOnToggledV13,data);g_signal_connect(c.widget,"toggled",G_CALLBACK(PatchOnToggledV14),data);}else if(c.kind==CK_INPUT){g_signal_handlers_disconnect_by_func(c.widget,(gpointer)PatchOnInputV13,data);g_signal_connect(c.widget,"changed",G_CALLBACK(PatchOnInputV14),data);}else if(c.kind==CK_COMBO){g_signal_handlers_disconnect_by_func(c.widget,(gpointer)PatchOnComboV13,data);g_signal_connect(c.widget,"changed",G_CALLBACK(PatchOnComboV14),data);}else if(c.kind==CK_LISTBOX){const bool multi=PatchFindListBoxV11(gPatchListBoxesV11,c.id)!=nullptr;if(multi){g_signal_handlers_disconnect_by_func(c.widget,(gpointer)PatchOnListMultiV13,data);g_signal_connect(c.widget,"selected-rows-changed",G_CALLBACK(PatchOnListMultiV14),data);}else{g_signal_handlers_disconnect_by_func(c.widget,(gpointer)PatchOnListSingleV13,data);g_signal_connect(c.widget,"row-selected",G_CALLBACK(PatchOnListSingleV14),data);}}else if(c.kind==CK_RADIO){for(GtkWidget* item:c.radioItems){g_signal_handlers_disconnect_by_func(item,(gpointer)PatchOnRadioV13,data);g_signal_connect(item,"toggled",G_CALLBACK(PatchOnRadioV14),data);}}}
  for(const auto& table:gPatchTablesV10){GtkWidget* view=gPatchTableViewsV10[(size_t)table.nativeIndex];if(!view)return false;GtkTreeSelection* selection=gtk_tree_view_get_selection(GTK_TREE_VIEW(view));gpointer data=GINT_TO_POINTER(table.nativeIndex);g_signal_handlers_disconnect_by_func(selection,(gpointer)PatchOnTableChangedV13,data);g_signal_connect(selection,"changed",G_CALLBACK(PatchOnTableChangedV14),data);}
  for(int index=0;index<(int)gMenuItems.size();++index){auto& item=gMenuItems[(size_t)index];if(!item.widget)continue;gpointer data=GINT_TO_POINTER(index);g_signal_handlers_disconnect_by_func(item.widget,(gpointer)PatchOnMenuV12,data);g_signal_connect(item.widget,"activate",G_CALLBACK(PatchOnMenuV14),data);}
  for(const auto& tree:gPatchTreesV13){auto& native=gPatchGtkTreesV13[(size_t)tree.nativeIndex];if(!native.view)return false;GtkTreeSelection* selection=gtk_tree_view_get_selection(GTK_TREE_VIEW(native.view));g_signal_connect_after(selection,"changed",G_CALLBACK(PatchOnTreeRefreshV14),nullptr);}return true;}

static const std::string* PatchSliderSetTargetV14(const PatchSliderV14& slider){for(const auto& patch:slider.events){if(patch.eventIndex>=gEvents.size())continue;const auto& event=gEvents[(size_t)patch.eventIndex];for(const auto& action:event.actions)if(action.kind==ACT_CHANGE&&action.stateType==ST_NUMBER)for(const auto& op:action.ops)if(op.op==OP_SET&&op.valueKind==VK_LITERAL)for(double sentinel:patch.sentinels)if(op.number==sentinel)return &action.target;}return nullptr;}
static int RunPatchSliderSmokeV14(){int code=340;for(const auto& slider:gPatchSlidersV14){GtkWidget* view=gPatchSliderViewsV14[(size_t)slider.nativeIndex];if(!view||!GTK_IS_SCALE(view))return code++;GtkAdjustment* adjustment=gtk_range_get_adjustment(GTK_RANGE(view));if(!adjustment||std::fabs(gtk_adjustment_get_lower(adjustment)-slider.min)>1e-9||std::fabs(gtk_adjustment_get_upper(adjustment)-slider.max)>1e-9)return code++;if(!slider.events.empty()){int before=gPatchSliderDispatchCountV14;gtk_range_set_value(GTK_RANGE(view),slider.max);if(!PatchDispatchSliderV14(slider,GTK_RANGE(view))||gPatchSliderDispatchCountV14<=before)return code++;if(const auto* target=PatchSliderSetTargetV14(slider)){auto it=gStateByName.find(*target);if(it==gStateByName.end()||gStates[(size_t)it->second].type!=ST_NUMBER||std::fabs(gStates[(size_t)it->second].number-PatchSliderValueV14(slider,GTK_RANGE(view)))>1e-9)return code++;}}}return 0;}

int main(int argc,char* argv[]){gSmokeMode=HasArg(argc,argv,"--patch-smoke");std::vector<uint8_t> payloadV13,payloadV12,payloadV11,payloadV10,payloadV9,payloadV8,payloadV7;if(!ReadSelfPayloadV14(payloadV13)||!PatchConvertPayloadV13ToV12(payloadV13,payloadV12,gPatchSlidersV14)||!PatchConvertPayloadV12ToV11(payloadV12,payloadV11,gPatchTreesV13)||!PatchConvertPayloadV11ToV10(payloadV11,payloadV10,gPatchMenuEntriesV12)||!PatchConvertPayloadV10ToV9(payloadV10,payloadV9,gPatchListStatesV11,gPatchListBoxesV11,gPatchListEventsV11)||!PatchConvertPayloadV9ToV8(payloadV9,payloadV8,gPatchTablesV10)||!PatchConvertPayloadV8ToV7(payloadV8,payloadV7,gPatchLayoutPoliciesV09)||!ParsePayload(payloadV7))return 20;if(gPatchLayoutPoliciesV09.size()!=gControls.size()||!PatchResolveTablesV10()||!PatchResolveListsV11()||!PatchResolveTreesV13()||!PatchResolveSlidersV14())return 22;PatchSyncListShadowsV11();gtk_init(&argc,&argv);if(!CreateForms()||!PatchInstallTablesV10()||!PatchRewireEventsV11()||!PatchInstallMenusV12()||!PatchRewireEventsV12()||!PatchRewireTableEventsV12()||!PatchInstallTreesV13()||!PatchRewireEventsV13()||!PatchInstallSlidersV14()||!PatchRewireEventsV14())return 21;for(int index=0;index<(int)gForms.size();++index)if(gForms[(size_t)index].fixed){g_signal_connect(gForms[(size_t)index].fixed,"size-allocate",G_CALLBACK(OnPatchFormAllocateV09),GINT_TO_POINTER(index));g_signal_connect(gForms[(size_t)index].fixed,"size-allocate",G_CALLBACK(PatchOnFormAllocateV13),GINT_TO_POINTER(index));g_signal_connect_after(gForms[(size_t)index].fixed,"size-allocate",G_CALLBACK(PatchOnFormAllocateV14),GINT_TO_POINTER(index));}ApplyPatchAccessibilityV09();ApplyPatchTableAccessibilityV10();RefreshUI();PatchRefreshListsV11();PatchRefreshMenusV12();PatchRefreshTreesV13();PatchRefreshSlidersV14();for(auto& f:gForms)if(f.visible)gtk_widget_show_all(f.window);PatchRefreshTreesV13();PatchRefreshSlidersV14();while(gtk_events_pending())gtk_main_iteration();if(gSmokeMode){int result=RunSmoke();if(!result)result=RunPatchAccessibilitySmokeV09();if(!result)result=RunPatchTableAccessibilitySmokeV10();if(!result)result=RunPatchResponsiveSmokeV09();if(!result)result=RunPatchTableSmokeV10();if(!result)result=RunPatchListSmokeV11();if(!result)result=RunPatchMenuSmokeV12();if(!result)result=RunPatchTreeSmokeV13();if(!result)result=RunPatchSliderSmokeV14();PatchDestroyMenusV12();return result;}gtk_main();PatchDestroyMenusV12();return 0;}
