// Patch sealed Win32 GUI runtime v1.1.
// Payload v10 adds persistent text-list state and list-backed multi-select
// ListBox while preserving payload v9/runtime-v1.0 Table behavior.
#include <windows.h>
#include <commctrl.h>
#include <algorithm>
#include <fstream>

#define PATCH_WIN32_RUNTIME_V09_ENTRY PatchSealedRuntimeV09WinMain
#include "win32-sealed-gui-v09.cpp"
#undef PATCH_WIN32_RUNTIME_V09_ENTRY
#include "sealed-table-v10.hpp"
#include "sealed-list-v11.hpp"

static std::vector<PatchTableV10> gPatchTablesV10;
static std::vector<std::wstring> gPatchLastTableRowV10;
static int gPatchTableSelectionCountV10=0;
static std::vector<PatchListStateV11> gPatchListStatesV11;
static std::vector<PatchListBoxV11> gPatchListBoxesV11;
static std::vector<PatchListEventV11> gPatchListEventsV11;
static bool gPatchListRuntimeErrorV11=false;
static std::string gPatchListRuntimeErrorMessageV11;

static std::wstring PatchWideV11(const std::string& value){return Utf8ToWide(reinterpret_cast<const uint8_t*>(value.data()),value.size());}
static std::string PatchUtf8V11(const std::wstring& value){if(value.empty())return {};int needed=WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,value.data(),(int)value.size(),nullptr,0,nullptr,nullptr);if(needed<=0)throw 1;std::string out((size_t)needed,'\0');if(WideCharToMultiByte(CP_UTF8,WC_ERR_INVALID_CHARS,value.data(),(int)value.size(),out.data(),needed,nullptr,nullptr)!=needed)throw 1;return out;}

static bool ReadSelfPayloadV11(std::vector<uint8_t>& payload){wchar_t path[MAX_PATH];DWORD n=GetModuleFileNameW(nullptr,path,MAX_PATH);if(!n||n>=MAX_PATH)return false;HANDLE file=CreateFileW(path,GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);if(file==INVALID_HANDLE_VALUE)return false;LARGE_INTEGER size{};if(!GetFileSizeEx(file,&size)||size.QuadPart<20){CloseHandle(file);return false;}LARGE_INTEGER pos{};pos.QuadPart=size.QuadPart-20;if(!SetFilePointerEx(file,pos,nullptr,FILE_BEGIN)){CloseHandle(file);return false;}uint8_t footer[20]{};DWORD got=0;if(!ReadFile(file,footer,20,&got,nullptr)||got!=20||memcmp(footer,PATCH_MAGIC,8)!=0){CloseHandle(file);return false;}auto le32=[](const uint8_t*p){return(uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);};const uint32_t version=le32(footer+8),length=le32(footer+12),crc=le32(footer+16);if(version!=10||!length||(uint64_t)length>(uint64_t)(size.QuadPart-20)){CloseHandle(file);return false;}pos.QuadPart=size.QuadPart-20-length;if(!SetFilePointerEx(file,pos,nullptr,FILE_BEGIN)){CloseHandle(file);return false;}payload.resize(length);got=0;BOOL ok=ReadFile(file,payload.data(),length,&got,nullptr);CloseHandle(file);return ok&&got==length&&Crc32(payload.data(),payload.size())==crc;}

static bool PatchResolveTablesV10(){for(const auto& table:gPatchTablesV10){if(table.nativeIndex<0||table.nativeIndex>=(int)gControls.size())return false;auto it=gControlById.find(PatchWideV11(table.id));if(it==gControlById.end()||it->second!=table.nativeIndex)return false;auto& c=gControls[(size_t)table.nativeIndex];if(c.kind!=CK_LISTBOX||c.binding!=PatchWideV11(table.shadowState))return false;}return true;}
static bool PatchResolveListsV11(){for(const auto& box:gPatchListBoxesV11){if(box.nativeIndex<0||box.nativeIndex>=(int)gControls.size())return false;auto it=gControlById.find(PatchWideV11(box.id));if(it==gControlById.end()||it->second!=box.nativeIndex)return false;auto& c=gControls[(size_t)box.nativeIndex];if(c.kind!=CK_LISTBOX||c.binding!=PatchWideV11(box.binding))return false;auto state=gStateByName.find(PatchWideV11(box.binding));if(state==gStateByName.end()||gStates[(size_t)state->second].type!=ST_TEXT)return false;if(!PatchFindListStateV11(gPatchListStatesV11,box.binding))return false;}return true;}

static std::vector<std::string> PatchSelectedListValuesV11(const PatchListBoxV11& box){std::vector<std::string> out;if(box.nativeIndex<0||box.nativeIndex>=(int)gControls.size())return out;auto& c=gControls[(size_t)box.nativeIndex];if(!c.hwnd)return out;LRESULT count=SendMessageW(c.hwnd,LB_GETSELCOUNT,0,0);if(count==LB_ERR||count<=0)return out;std::vector<int> indices((size_t)count);LRESULT got=SendMessageW(c.hwnd,LB_GETSELITEMS,(WPARAM)indices.size(),(LPARAM)indices.data());if(got==LB_ERR)return out;for(int n=0;n<(int)got;++n){int index=indices[(size_t)n];if(index>=0&&index<(int)c.options.size())out.push_back(PatchUtf8V11(c.options[(size_t)index]));}return out;}
static void PatchSyncListShadowsV11(){for(const auto& state:gPatchListStatesV11){auto it=gStateByName.find(PatchWideV11(state.name));if(it!=gStateByName.end())gStates[(size_t)it->second].text=state.value.empty()?L"":PatchWideV11(state.value.front());}}
static void PatchRefreshListsV11(){bool previous=gRefreshing;gRefreshing=true;for(const auto& box:gPatchListBoxesV11){if(box.nativeIndex<0||box.nativeIndex>=(int)gControls.size())continue;auto& c=gControls[(size_t)box.nativeIndex];auto* state=PatchFindListStateV11(gPatchListStatesV11,box.binding);if(!state||!c.hwnd)continue;SendMessageW(c.hwnd,LB_SETSEL,FALSE,(LPARAM)-1);for(size_t index=0;index<c.options.size();++index){std::string option=PatchUtf8V11(c.options[index]);if(std::find(state->value.begin(),state->value.end(),option)!=state->value.end())SendMessageW(c.hwnd,LB_SETSEL,TRUE,(LPARAM)index);}}gRefreshing=previous;}
static void PatchReportListErrorV11(const std::string& message){gPatchListRuntimeErrorV11=true;gPatchListRuntimeErrorMessageV11=message;if(!gSmokeMode)MessageBoxW(nullptr,PatchWideV11(message).c_str(),L"Patch stopped",MB_OK|MB_ICONERROR);}
static bool PatchApplyListActionV11(const PatchListActionV11& action,const std::vector<std::string>* eventList){auto* state=PatchFindListStateV11(gPatchListStatesV11,action.target);if(!state)return false;for(const auto& op:action.ops){if(op.op==4){state->value.clear();continue;}if(op.op==1){if(op.valueKind==2){if(!eventList)return false;state->value=*eventList;}else if(op.valueKind==1)state->value=op.listValue;else return false;continue;}if(op.valueKind!=1)return false;if(op.op==2){state->value.push_back(op.textValue);continue;}if(op.op==3){auto it=std::find(state->value.begin(),state->value.end(),op.textValue);if(it==state->value.end()){PatchReportListErrorV11("Cannot remove "+op.textValue+" because it is not in the list.");return false;}state->value.erase(it);continue;}return false;}return true;}
static const PatchListActionV11* PatchListActionAtV11(const PatchListEventV11* meta,uint32_t index){if(!meta)return nullptr;for(const auto& action:meta->actions)if(action.actionIndex==index)return &action;return nullptr;}

static void PatchExecuteEventV11(const Event& event,bool eventBool,const std::wstring& eventText,const std::vector<std::string>* eventList=nullptr);
static void PatchDispatchResultV11(const std::wstring& id,uint8_t kind,const std::wstring& value=L""){for(const auto& event:gEvents)if(event.control==id&&event.kind==kind)PatchExecuteEventV11(event,false,value,nullptr);}
static void PatchExecuteEventV11(const Event& event,bool eventBool,const std::wstring& eventText,const std::vector<std::string>* eventList){const auto* meta=PatchFindListEventV11(gPatchListEventsV11,PatchUtf8V11(event.control),event.kind);for(uint32_t index=0;index<(uint32_t)event.actions.size();++index){if(const auto* listAction=PatchListActionAtV11(meta,index)){if(!PatchApplyListActionV11(*listAction,eventList)){if(!gPatchListRuntimeErrorV11)PatchReportListErrorV11("Invalid sealed list operation.");return;}continue;}const auto& action=event.actions[index];if(action.kind==ACT_OPEN)ShowWindow(gForms[gFormById[action.form]].hwnd,SW_SHOW);else if(action.kind==ACT_CLOSE)ShowWindow(gForms[gFormById[action.form]].hwnd,SW_HIDE);else if(action.kind==ACT_DIALOG)ShowInfoDialog(action);else if(action.kind==ACT_CONFIRM){bool accepted=ShowConfirmDialog(action);gLastResultSource=action.id;gLastResultValue.clear();gLastResultEvent=accepted?EV_CONFIRMED:EV_CANCELLED;PatchDispatchResultV11(action.id,accepted?EV_CONFIRMED:EV_CANCELLED);}else if(action.kind==ACT_OPEN_FILE||action.kind==ACT_SAVE_FILE){std::wstring value;bool chosen=ShowFileDialog(action,value);gLastResultSource=action.id;gLastResultValue=chosen?value:L"";gLastResultEvent=chosen?EV_CHOSEN:EV_CANCELLED;PatchDispatchResultV11(action.id,chosen?EV_CHOSEN:EV_CANCELLED,chosen?value:L"");}else if(action.kind==ACT_CHANGE){State& state=gStates[gStateByName[action.target]];for(const auto& op:action.ops)ApplyOperation(state,op,eventBool,eventText);}}PatchSyncListShadowsV11();RefreshUI();PatchRefreshListsV11();}

static void PatchDispatchControlV11(int index,uint8_t kind,HWND eventHwnd=nullptr){if(gRefreshing||index<0||index>=(int)gControls.size())return;auto& control=gControls[(size_t)index];if(control.id.empty())return;for(const auto& event:gEvents){if(event.control!=control.id||event.kind!=kind)continue;bool eventBool=false;std::wstring eventText;std::vector<std::string> eventList;const std::vector<std::string>* eventListPtr=nullptr;if(event.valueType==1&&control.kind==CK_CHECKBOX)eventBool=SendMessageW(control.hwnd,BM_GETCHECK,0,0)==BST_CHECKED;else if(event.valueType==2&&control.kind==CK_INPUT)eventText=WindowText(control.hwnd);else if(event.valueType==2&&control.kind==CK_COMBO)eventText=ComboText(control.hwnd);else if(event.valueType==2&&control.kind==CK_LISTBOX){const auto* box=PatchFindListBoxV11(gPatchListBoxesV11,PatchUtf8V11(control.id));if(box){eventList=PatchSelectedListValuesV11(*box);eventListPtr=&eventList;}else eventText=ListBoxText(control.hwnd);}else if(event.valueType==2&&control.kind==CK_RADIO)eventText=WindowText(eventHwnd?eventHwnd:control.hwnd);PatchExecuteEventV11(event,eventBool,eventText,eventListPtr);}}
static void PatchDispatchMenuV11(int index){if(gRefreshing||index<0||index>=(int)gMenuItems.size())return;const auto& item=gMenuItems[(size_t)index];for(const auto& event:gEvents)if(event.control==item.id&&event.kind==EV_CLICKED)PatchExecuteEventV11(event,false,L"",nullptr);}

static const PatchTableV10* PatchTableForIndexV10(int index){return PatchFindTableV10(gPatchTablesV10,index);}
static void PatchDispatchTableV10(const PatchTableV10& table,int row){if(gRefreshing||row<0||row>=(int)table.rows.size())return;gPatchLastTableRowV10.clear();for(const auto& cell:table.rows[(size_t)row])gPatchLastTableRowV10.push_back(PatchWideV11(cell));++gPatchTableSelectionCountV10;const std::wstring id=PatchWideV11(table.id);for(const auto& event:gEvents)if(event.control==id&&event.kind==EV_CHANGED)PatchExecuteEventV11(event,false,L"",nullptr);}
static bool PatchHandleTableNotifyV10(NMHDR* header){if(!header||header->code!=LVN_ITEMCHANGED)return false;for(const auto& table:gPatchTablesV10){auto& c=gControls[(size_t)table.nativeIndex];if(c.hwnd!=header->hwndFrom)continue;auto* change=reinterpret_cast<NMLISTVIEW*>(header);if(change->iItem>=0&&(change->uNewState&LVIS_SELECTED)&&!(change->uOldState&LVIS_SELECTED))PatchDispatchTableV10(table,change->iItem);return true;}return false;}
static LRESULT CALLBACK PatchWndProcV11(HWND hwnd,UINT msg,WPARAM wParam,LPARAM lParam){if(msg==WM_COMMAND){int id=LOWORD(wParam),notification=HIWORD(wParam);HWND eventHwnd=reinterpret_cast<HWND>(lParam);if(notification==0&&eventHwnd==nullptr){for(int i=0;i<(int)gMenuItems.size();++i)if(gMenuItems[(size_t)i].commandId==id){PatchDispatchMenuV11(i);return 0;}}for(int i=0;i<(int)gControls.size();++i){auto& c=gControls[(size_t)i];if(c.commandId!=id)continue;if(c.kind==CK_BUTTON&&notification==BN_CLICKED)PatchDispatchControlV11(i,EV_CLICKED,eventHwnd);else if(c.kind==CK_CHECKBOX&&notification==BN_CLICKED)PatchDispatchControlV11(i,EV_CHANGED,eventHwnd);else if(c.kind==CK_RADIO&&notification==BN_CLICKED)PatchDispatchControlV11(i,EV_CHANGED,eventHwnd);else if(c.kind==CK_INPUT&&notification==EN_CHANGE)PatchDispatchControlV11(i,EV_CHANGED,eventHwnd);else if(c.kind==CK_COMBO&&notification==CBN_SELCHANGE)PatchDispatchControlV11(i,EV_CHANGED,eventHwnd);else if(c.kind==CK_LISTBOX&&notification==LBN_SELCHANGE)PatchDispatchControlV11(i,EV_CHANGED,eventHwnd);break;}return 0;}if(msg==WM_NOTIFY){if(PatchHandleTableNotifyV10(reinterpret_cast<NMHDR*>(lParam)))return 0;if(HandleTabNotify(reinterpret_cast<NMHDR*>(lParam)))return 0;}return PatchWndProcV09(hwnd,msg,wParam,lParam);}

static bool PatchInstallTableV10(const PatchTableV10& table){auto& c=gControls[(size_t)table.nativeIndex];HWND parent=gForms[(size_t)c.formIndex].hwnd;int x=c.x,y=c.y;if(c.parentTabIndex>=0){if(c.parentTabIndex>=(int)gControls.size())return false;const auto& tab=gControls[(size_t)c.parentTabIndex];x=tab.x+10+c.x;y=tab.y+30+c.y;}if(c.hwnd)DestroyWindow(c.hwnd);c.hwnd=CreateWindowExW(WS_EX_CLIENTEDGE,WC_LISTVIEWW,L"",WS_CHILD|WS_VISIBLE|WS_TABSTOP|LVS_REPORT|LVS_SINGLESEL|LVS_SHOWSELALWAYS,x,y,c.width,c.height,parent,reinterpret_cast<HMENU>((INT_PTR)c.commandId),gInstance,nullptr);if(!c.hwnd)return false;if(gGuiFont)SendMessageW(c.hwnd,WM_SETFONT,(WPARAM)gGuiFont,TRUE);ListView_SetExtendedListViewStyle(c.hwnd,LVS_EX_FULLROWSELECT|LVS_EX_GRIDLINES|LVS_EX_DOUBLEBUFFER);const int columnWidth=table.columns.empty()?c.width:max(40,c.width/(int)table.columns.size());for(int columnIndex=0;columnIndex<(int)table.columns.size();++columnIndex){std::wstring title=PatchWideV11(table.columns[(size_t)columnIndex]);LVCOLUMNW column{};column.mask=LVCF_TEXT|LVCF_WIDTH|LVCF_SUBITEM;column.cx=columnIndex+1==(int)table.columns.size()?max(40,c.width-columnWidth*columnIndex):columnWidth;column.iSubItem=columnIndex;column.pszText=title.data();if(ListView_InsertColumn(c.hwnd,columnIndex,&column)<0)return false;}for(int rowIndex=0;rowIndex<(int)table.rows.size();++rowIndex){const auto& row=table.rows[(size_t)rowIndex];std::wstring first=PatchWideV11(row.empty()?std::string():row[0]);LVITEMW item{};item.mask=LVIF_TEXT;item.iItem=rowIndex;item.iSubItem=0;item.pszText=first.data();if(ListView_InsertItem(c.hwnd,&item)<0)return false;for(int columnIndex=1;columnIndex<(int)row.size();++columnIndex){std::wstring value=PatchWideV11(row[(size_t)columnIndex]);ListView_SetItemText(c.hwnd,rowIndex,columnIndex,value.data());}}c.kind=9;return true;}
static bool PatchInstallTablesV10(){for(const auto& table:gPatchTablesV10)if(!PatchInstallTableV10(table))return false;RefreshTabVisibility();return true;}
static bool PatchInstallListsV11(){for(const auto& box:gPatchListBoxesV11){auto& c=gControls[(size_t)box.nativeIndex];HWND parent=gForms[(size_t)c.formIndex].hwnd;int x=c.x,y=c.y;if(c.parentTabIndex>=0){const auto& tab=gControls[(size_t)c.parentTabIndex];x=tab.x+10+c.x;y=tab.y+30+c.y;}if(c.hwnd)DestroyWindow(c.hwnd);c.hwnd=CreateWindowExW(WS_EX_CLIENTEDGE,L"LISTBOX",L"",WS_CHILD|WS_VISIBLE|WS_TABSTOP|WS_VSCROLL|WS_BORDER|LBS_NOTIFY|LBS_EXTENDEDSEL,x,y,c.width,c.height,parent,reinterpret_cast<HMENU>((INT_PTR)c.commandId),gInstance,nullptr);if(!c.hwnd)return false;if(gGuiFont)SendMessageW(c.hwnd,WM_SETFONT,(WPARAM)gGuiFont,TRUE);for(const auto& option:c.options)SendMessageW(c.hwnd,LB_ADDSTRING,0,(LPARAM)option.c_str());}RefreshTabVisibility();return true;}
static void ApplyPatchTableAccessibilityV10(){for(const auto& table:gPatchTablesV10){auto& c=gControls[(size_t)table.nativeIndex];PatchSetAccessibleNameV09(c.hwnd,PatchControlNameV09(c));}}
static int RunPatchTableAccessibilitySmokeV10(){int code=210;for(const auto& table:gPatchTablesV10){const auto& c=gControls[(size_t)table.nativeIndex];if(!c.hwnd||PatchReadAccessibleNameV09(c.hwnd)!=PatchControlNameV09(c))return code++;}return 0;}
static int RunPatchTableSmokeV10(){int code=220;for(const auto& table:gPatchTablesV10){auto& c=gControls[(size_t)table.nativeIndex];if(!c.hwnd||c.kind!=9)return code++;if(ListView_GetItemCount(c.hwnd)!=(int)table.rows.size())return code++;HWND header=ListView_GetHeader(c.hwnd);if(!header||Header_GetItemCount(header)!=(int)table.columns.size())return code++;if(table.rows.empty())return code++;const int row=(int)table.rows.size()-1;const int before=gPatchTableSelectionCountV10;NMLISTVIEW change{};change.hdr.hwndFrom=c.hwnd;change.hdr.idFrom=c.commandId;change.hdr.code=LVN_ITEMCHANGED;change.iItem=row;change.uOldState=0;change.uNewState=LVIS_SELECTED;SendMessageW(gForms[(size_t)c.formIndex].hwnd,WM_NOTIFY,c.commandId,(LPARAM)&change);if(gPatchTableSelectionCountV10!=before+1)return code++;if(gPatchLastTableRowV10.size()!=table.columns.size())return code++;}return 0;}
static int RunPatchListSmokeV11(){int code=240;for(const auto& box:gPatchListBoxesV11){auto& c=gControls[(size_t)box.nativeIndex];auto* state=PatchFindListStateV11(gPatchListStatesV11,box.binding);if(!state||!c.hwnd)return code++;LONG_PTR style=GetWindowLongPtrW(c.hwnd,GWL_STYLE);if(!(style&LBS_EXTENDEDSEL))return code++;PatchRefreshListsV11();if(PatchSelectedListValuesV11(box)!=state->value)return code++;if(c.options.size()<2)return code++;bool previous=gRefreshing;gRefreshing=true;SendMessageW(c.hwnd,LB_SETSEL,FALSE,(LPARAM)-1);SendMessageW(c.hwnd,LB_SETSEL,TRUE,0);SendMessageW(c.hwnd,LB_SETSEL,TRUE,(LPARAM)(c.options.size()-1));gRefreshing=previous;auto selected=PatchSelectedListValuesV11(box);PatchDispatchControlV11(box.nativeIndex,EV_CHANGED,c.hwnd);if(gPatchListRuntimeErrorV11)return code++;if(state->value!=selected)return code++;if(PatchSelectedListValuesV11(box)!=state->value)return code++;}return 0;}

int WINAPI wWinMain(HINSTANCE instance,HINSTANCE,PWSTR,int showCommand){PatchComScopeV09 patchCom;gInstance=instance;gGuiFont=(HFONT)GetStockObject(DEFAULT_GUI_FONT);gSmokeMode=HasArg(L"--patch-smoke");std::vector<uint8_t> payloadV10,payloadV9,payloadV8,payloadV7;if(!ReadSelfPayloadV11(payloadV10)||!PatchConvertPayloadV10ToV9(payloadV10,payloadV9,gPatchListStatesV11,gPatchListBoxesV11,gPatchListEventsV11)||!PatchConvertPayloadV9ToV8(payloadV9,payloadV8,gPatchTablesV10)||!PatchConvertPayloadV8ToV7(payloadV8,payloadV7,gPatchLayoutPoliciesV09)||!ParsePayload(payloadV7))return 20;if(gPatchLayoutPoliciesV09.size()!=gControls.size()||!PatchResolveTablesV10()||!PatchResolveListsV11())return 24;PatchSyncListShadowsV11();INITCOMMONCONTROLSEX common{};common.dwSize=sizeof(common);common.dwICC=ICC_TAB_CLASSES|ICC_LISTVIEW_CLASSES;if(!InitCommonControlsEx(&common))return 21;WNDCLASSEXW wc{};wc.cbSize=sizeof(wc);wc.hInstance=instance;wc.lpfnWndProc=PatchWndProcV11;wc.lpszClassName=PATCH_WINDOW_CLASS;wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hIcon=LoadIcon(nullptr,IDI_APPLICATION);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);if(!RegisterClassExW(&wc))return 22;if(!CreateForms()||!PatchInstallTablesV10()||!PatchInstallListsV11())return 23;ApplyPatchAccessibilityV09();ApplyPatchTableAccessibilityV10();RefreshUI();PatchRefreshListsV11();for(auto& f:gForms)if(f.visible)ShowWindow(f.hwnd,showCommand==0?SW_SHOWNORMAL:showCommand);if(gSmokeMode){int result=RunSmoke();if(!result)result=RunPatchAccessibilitySmokeV09();if(!result)result=RunPatchTableAccessibilitySmokeV10();if(!result)result=RunPatchResponsiveSmokeV09();if(!result)result=RunPatchTableSmokeV10();if(!result)result=RunPatchListSmokeV11();ClearPatchAccessibilityV09();return result;}MSG msg{};while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}ClearPatchAccessibilityV09();return(int)msg.wParam;}
