import { flattenNativeGuiControls, NativeGuiError } from './native-gui-ir.js';
import { emitAppKitGuiObjCpp as emitAppKitGuiObjCppV07 } from './appkit-gui-v07.js';
import {
  nativeAccessibleName,
  nativeRadioItemAccessibleName,
  needsExplicitNativeAccessibleName
} from './native-accessibility.js';

export const PATCH_APPKIT_GUI_BACKEND_VERSION = '0.8';

export function emitAppKitGuiObjCpp(input) {
  const controls = flattenNativeGuiControls(input);
  let source = emitAppKitGuiObjCppV07(input)
    .replace(/Generated by Patch AppKit GUI backend 0\.7\./, `Generated by Patch AppKit GUI backend ${PATCH_APPKIT_GUI_BACKEND_VERSION}.`);

  source = replaceRequired(source, 'static void RefreshUI();', `${appKitAccessibilityHelpers(controls)}\nstatic void RefreshUI();`, 'AppKit accessibility helper insertion');
  source = replaceRequired(
    source,
    'for (int i = 0; i < FORM_COUNT; ++i) if (!CreatePatchForm(i)) return 10 + i;\n    RefreshUI();',
    'for (int i = 0; i < FORM_COUNT; ++i) if (!CreatePatchForm(i)) return 10 + i;\n    ApplyPatchAccessibility();\n    RefreshUI();',
    'AppKit accessibility application'
  );
  return injectAccessibilitySmoke(source, controls);
}

function appKitAccessibilityHelpers(controls) {
  const lines = [];
  for (const control of controls) {
    if (!needsExplicitNativeAccessibleName(control)) continue;
    if (control.type === 'radio') {
      for (let optionIndex = 0; optionIndex < control.options.length; optionIndex += 1) {
        const name = nativeRadioItemAccessibleName(control, control.options[optionIndex]);
        lines.push(`  if ([gRadioItems[${control.nativeIndex}] count] > ${optionIndex}) [(NSButton *)[gRadioItems[${control.nativeIndex}] objectAtIndex:${optionIndex}] setAccessibilityLabel:${objcLiteral(name)}];`);
      }
      continue;
    }
    const name = nativeAccessibleName(control);
    if (!name) continue;
    lines.push(`  if (gControls[${control.nativeIndex}]) [gControls[${control.nativeIndex}] setAccessibilityLabel:${objcLiteral(name)}];`);
  }
  return `static void ApplyPatchAccessibility() {\n${lines.join('\n') || '  // Standard AppKit control names need no Patch override.'}\n}\n`;
}

function injectAccessibilitySmoke(source, controls) {
  const checks = [];
  let code = 130;
  for (const control of controls) {
    if (!needsExplicitNativeAccessibleName(control)) continue;
    if (control.type === 'radio') {
      for (let optionIndex = 0; optionIndex < control.options.length; optionIndex += 1) {
        const expected = nativeRadioItemAccessibleName(control, control.options[optionIndex]);
        checks.push(`  if ([gRadioItems[${control.nativeIndex}] count] <= ${optionIndex} || ![[gRadioItems[${control.nativeIndex}] objectAtIndex:${optionIndex}].accessibilityLabel isEqualToString:${objcLiteral(expected)}]) return ${code++};`);
      }
      continue;
    }
    const expected = nativeAccessibleName(control);
    if (!expected) continue;
    checks.push(`  if (![[gControls[${control.nativeIndex}] accessibilityLabel] isEqualToString:${objcLiteral(expected)}]) return ${code++};`);
  }
  if (!checks.length) return source;
  const start = source.indexOf('static int RunPatchSmoke() {');
  if (start < 0) throw new NativeGuiError('Generated AppKit source is missing RunPatchSmoke for accessibility verification.');
  const stop = source.indexOf('  [NSApp stop:nil];', start);
  if (stop < 0) throw new NativeGuiError('Generated AppKit smoke has an unexpected shape for accessibility verification.');
  return source.slice(0, stop) + checks.join('\n') + '\n' + source.slice(stop);
}

function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated AppKit source.`);
  return source.replace(marker, replacement);
}

function objcLiteral(value) { return `@${JSON.stringify(String(value ?? ''))}`; }
