import { NativeGuiError } from './native-gui-ir.js';
import { emitAppKitGuiObjCppV12 } from './appkit-gui-v12.js';
import { adaptNativeTreesForV12Backend, treePersistentPathTarget } from './native-tree-backend-adapter.js';

export const PATCH_APPKIT_GUI_BACKEND_V13_VERSION = '1.3';

/** Emit AppKit backend 1.3 with a real NSOutlineView TreeView. */
export function emitAppKitGuiObjCppV13(input) {
  const adapted = adaptNativeTreesForV12Backend(input);
  let source = emitAppKitGuiObjCppV12(adapted.compatibleIr)
    .replace(/Generated by Patch AppKit GUI backend 1\.2\./, `Generated by Patch AppKit GUI backend ${PATCH_APPKIT_GUI_BACKEND_V13_VERSION}.`);
  if (!adapted.trees.length) return source;

  source = replaceRequired(
    source,
    `static NSMutableArray *gRadioItems[${Math.max(1, adapted.controls.length)}] = {};`,
    `static NSMutableArray *gRadioItems[${Math.max(1, adapted.controls.length)}] = {};\nstatic NSMutableArray *gTreeRoots[${Math.max(1, adapted.controls.length)}] = {};\nstatic NSMutableArray *gTreeItems[${Math.max(1, adapted.controls.length)}] = {};\nstatic NSInteger gPatchTreeSelectionCount = 0;`,
    'AppKit TreeView storage'
  );

  for (const tree of adapted.trees) {
    source = removeShadowState(source, tree);
    source = removeShadowRefresh(source, tree);
    source = replaceControlBlock(source, tree, treeCreate(adapted, tree));
    const event = adapted.events.find(item => item.control === tree.id && item.event === 'changed');
    if (event) source = replaceRequired(source, `  if (commandId == ${tree.commandId}) { Event_${event.eventIndex}(PatchSelectedListValues((NSTableView *)sender)); return; }\n`, '', `AppKit TreeView '${tree.id}' legacy ListBox dispatch`);
  }

  source = replaceRequired(
    source,
    '@interface PatchEventTarget : NSObject <NSTextFieldDelegate, NSTableViewDataSource, NSTableViewDelegate>',
    '@interface PatchEventTarget : NSObject <NSTextFieldDelegate, NSTableViewDataSource, NSTableViewDelegate, NSOutlineViewDataSource, NSOutlineViewDelegate>',
    'AppKit TreeView event-target protocols'
  );

  const helperMarker = '@interface PatchEventTarget : NSObject';
  source = replaceRequired(source, helperMarker, `${emitTreeHelpers(adapted)}\n\n${helperMarker}`, 'AppKit TreeView helper insertion');
  const delegateMarker = '- (void)tableViewSelectionDidChange:(NSNotification *)notification {\n  if (gRefreshing) return;\n  [self handleControl:notification.object];\n}\n@end';
  const delegateReplacement = `- (void)tableViewSelectionDidChange:(NSNotification *)notification {\n  if (gRefreshing) return;\n  if ([notification.object isKindOfClass:[NSOutlineView class]]) return;\n  [self handleControl:notification.object];\n}\n- (NSInteger)outlineView:(NSOutlineView *)outlineView numberOfChildrenOfItem:(id)item { NSArray *children = item ? [item objectForKey:@"children"] : PatchTreeRoots(outlineView.tag); return children ? (NSInteger)children.count : 0; }\n- (id)outlineView:(NSOutlineView *)outlineView child:(NSInteger)index ofItem:(id)item { NSArray *children = item ? [item objectForKey:@"children"] : PatchTreeRoots(outlineView.tag); return (index >= 0 && index < (NSInteger)children.count) ? [children objectAtIndex:(NSUInteger)index] : nil; }\n- (BOOL)outlineView:(NSOutlineView *)outlineView isItemExpandable:(id)item { (void)outlineView; return [[item objectForKey:@"children"] count] > 0; }\n- (NSView *)outlineView:(NSOutlineView *)outlineView viewForTableColumn:(NSTableColumn *)tableColumn item:(id)item { (void)outlineView; (void)tableColumn; NSTextField *label = [NSTextField labelWithString:[item objectForKey:@"text"] ?: @""]; label.lineBreakMode = NSLineBreakByTruncatingTail; return label; }\n- (void)outlineViewSelectionDidChange:(NSNotification *)notification { if (gRefreshing) return; PatchDispatchTreeSelection((NSOutlineView *)notification.object); }\n@end`;
  source = replaceRequired(source, delegateMarker, delegateReplacement, 'AppKit TreeView datasource/delegate methods');
  source = injectTreeRefresh(source, adapted);
  source = injectTreeSmoke(source, adapted);
  assertNoShadowState(source, adapted);
  return source;
}

function emitTreeHelpers(adapted) {
  const textFunctions = [];
  const rootCases = [], dispatch = [];
  for (const tree of adapted.trees) {
    for (const node of tree.flatNodes) textFunctions.push(emitTextFunction(tree.nativeIndex, node.flatIndex, node.text, adapted.states));
    rootCases.push(`    case ${tree.commandId}: return gTreeRoots[${tree.nativeIndex}] ?: @[];`);
    const event = adapted.events.find(item => item.control === tree.id && item.event === 'changed');
    const call = event ? ` Event_${event.eventIndex}(PatchTreePath(outline, item));` : '';
    dispatch.push(`  if (commandId == ${tree.commandId}) { NSInteger row = outline.selectedRow; id item = row >= 0 ? [outline itemAtRow:row] : nil; if (item) { ++gPatchTreeSelectionCount;${call} } return; }`);
  }
  return `${textFunctions.join('\n')}\nstatic NSArray *PatchTreeRoots(NSInteger commandId) { switch (commandId) {\n${rootCases.join('\n')}\n    default: return @[];\n  } }\nstatic NSArray<NSString *> *PatchTreePath(NSOutlineView *outline, id item) { NSMutableArray<NSString *> *path = [NSMutableArray array]; while (item) { NSString *text = [item objectForKey:@"text"] ?: @""; [path insertObject:text atIndex:0]; item = [outline parentForItem:item]; } return [path copy]; }\nstatic void PatchDispatchTreeSelection(NSOutlineView *outline) { if (!outline) return; NSInteger commandId = outline.tag;\n${dispatch.join('\n')}\n}`;
}

function emitTextFunction(treeIndex, nodeIndex, text, states) {
  const lines = ['  NSMutableString *out = [NSMutableString string];']; let cursor=0; const re=/\{([A-Za-z_]\w*)\}/g; let match;
  while ((match=re.exec(text))) {
    if (match.index>cursor) lines.push(`  [out appendString:${objc(text.slice(cursor,match.index))}];`);
    const state=states.get(match[1]);
    if(state.type==='boolean')lines.push(`  [out appendString:PatchBoolean(${stateName(state.name)})];`);
    else if(state.type==='number')lines.push(`  [out appendString:PatchNumber(${stateName(state.name)})];`);
    else lines.push(`  [out appendString:${stateName(state.name)}];`);
    cursor=match.index+match[0].length;
  }
  if(cursor<text.length)lines.push(`  [out appendString:${objc(text.slice(cursor))}];`);
  lines.push('  return out;');
  return `static NSString *TreeNodeText_${treeIndex}_${nodeIndex}() {\n${lines.join('\n')}\n}`;
}

function treeCreate(adapted, tree) {
  const control=adapted.controls[tree.nativeIndex]; const form=adapted.ir.forms[control.formIndex]; const rect=appKitRect(control,form,adapted.controls);
  const width=positiveInt(control.layout?.width,220), height=positiveInt(control.layout?.height,120);
  const target=control.parentTabIndex>=0?`(NSView *)[gTabPages[${control.parentTabIndex}] objectAtIndex:${control.pageIndex}]`:'window.contentView';
  const lines=[`    gTreeRoots[${tree.nativeIndex}] = [NSMutableArray array]; gTreeItems[${tree.nativeIndex}] = [NSMutableArray arrayWithCapacity:${tree.flatNodes.length}];`];
  const vars=new Map();
  for(const node of tree.flatNodes){const variable=`treeNode_${tree.nativeIndex}_${node.flatIndex}`;vars.set(node.flatIndex,variable);lines.push(`    NSMutableDictionary *${variable} = [@{@"text": TreeNodeText_${tree.nativeIndex}_${node.flatIndex}(), @"children": [NSMutableArray array]} mutableCopy]; [gTreeItems[${tree.nativeIndex}] addObject:${variable}];`); const parentFlat=node.flatIndexPath.length>1?node.flatIndexPath[node.flatIndexPath.length-2]:null; if(parentFlat===null)lines.push(`    [gTreeRoots[${tree.nativeIndex}] addObject:${variable}];`);else lines.push(`    [[${vars.get(parentFlat)} objectForKey:@"children"] addObject:${variable}];`);}
  return `  if (${control.formIndex} == index) {\n${lines.join('\n')}\n    NSScrollView *scroll = [[NSScrollView alloc] initWithFrame:${rect}]; scroll.hasVerticalScroller = YES; scroll.autohidesScrollers = YES; scroll.borderType = NSBezelBorder; NSOutlineView *control = [[NSOutlineView alloc] initWithFrame:NSMakeRect(0, 0, ${width}, ${height})]; NSTableColumn *column = [[NSTableColumn alloc] initWithIdentifier:@"tree"]; column.width = ${width}; [control addTableColumn:column]; control.outlineTableColumn = column; control.headerView = nil; control.allowsMultipleSelection = NO; control.allowsEmptySelection = YES; control.tag = ${tree.commandId}; control.dataSource = gEventTarget; control.delegate = gEventTarget; scroll.documentView = control; gControls[${tree.nativeIndex}] = control; [${target} addSubview:scroll]; [control reloadData]; [control expandItem:nil expandChildren:YES];\n  }`;
}

function injectTreeRefresh(source, adapted) {
  const start=source.indexOf('static void RefreshUI() {'); if(start<0)throw new NativeGuiError('Generated AppKit source is missing RefreshUI for TreeView labels.');
  const marker='  gRefreshing = false;'; const at=source.indexOf(marker,start); if(at<0)throw new NativeGuiError('Generated AppKit TreeView refresh insertion point is missing.');
  const lines=[]; for(const tree of adapted.trees){for(const node of tree.flatNodes)lines.push(`  if (gTreeItems[${tree.nativeIndex}] && [gTreeItems[${tree.nativeIndex}] count] > ${node.flatIndex}) [[gTreeItems[${tree.nativeIndex}] objectAtIndex:${node.flatIndex}] setObject:TreeNodeText_${tree.nativeIndex}_${node.flatIndex}() forKey:@"text"];`);lines.push(`  if (gControls[${tree.nativeIndex}]) { NSOutlineView *outline=(NSOutlineView *)gControls[${tree.nativeIndex}]; [outline reloadData]; [outline expandItem:nil expandChildren:YES]; }`);}
  return source.slice(0,at)+lines.join('\n')+'\n'+source.slice(at);
}

function injectTreeSmoke(source, adapted) {
  const start=source.indexOf('static int RunPatchSmoke() {'); if(start<0)throw new NativeGuiError('Generated AppKit source is missing TreeView smoke function.');
  const at=source.indexOf('  [NSApp stop:nil];',start); if(at<0)throw new NativeGuiError('Generated AppKit TreeView smoke insertion point is missing.');
  const checks=[];let code=210;
  for(const tree of adapted.trees){checks.push(`  if (!gControls[${tree.nativeIndex}] || ![gControls[${tree.nativeIndex}] isKindOfClass:[NSOutlineView class]] || [gTreeItems[${tree.nativeIndex}] count] != ${tree.flatNodes.length} || [(NSOutlineView *)gControls[${tree.nativeIndex}] numberOfRows] != ${tree.flatNodes.length}) return ${code++};`);const event=adapted.events.find(item=>item.control===tree.id&&item.event==='changed');if(!event||!tree.flatNodes.length)continue;const last=tree.flatNodes.at(-1).flatIndex;checks.push(`  { NSOutlineView *outline=(NSOutlineView *)gControls[${tree.nativeIndex}]; NSInteger row=[outline rowForItem:[gTreeItems[${tree.nativeIndex}] objectAtIndex:${last}]]; int before=(int)gPatchTreeSelectionCount; [outline selectRowIndexes:[NSIndexSet indexSetWithIndex:(NSUInteger)row] byExtendingSelection:NO]; if (gPatchTreeSelectionCount == before) [gEventTarget outlineViewSelectionDidChange:[NSNotification notificationWithName:NSOutlineViewSelectionDidChangeNotification object:outline]]; if (gPatchTreeSelectionCount <= before) return ${code++}; }`);const target=treePersistentPathTarget(event,adapted.states);if(target)checks.push(`  if (![${stateName(target)} isEqualToArray:PatchTreePath((NSOutlineView *)gControls[${tree.nativeIndex}], [gTreeItems[${tree.nativeIndex}] objectAtIndex:${last}])]) return ${code++};`);}
  return source.slice(0,at)+checks.join('\n')+'\n'+source.slice(at);
}

function replaceControlBlock(source,tree,replacement){const anchor=`  if (${tree.formIndex} == index) {\n    NSScrollView *scroll = [[NSScrollView alloc] initWithFrame:`;let start=source.indexOf(anchor);while(start>=0){const tag=source.indexOf(`control.tag = ${tree.commandId};`,start);const end=source.indexOf('\n  }',start);if(tag>=0&&tag<end)return source.slice(0,start)+replacement+source.slice(end+4);start=source.indexOf(anchor,start+anchor.length);}throw new NativeGuiError(`AppKit TreeView '${tree.id}' shadow control block is missing.`);}
function removeShadowState(source,tree){return replaceRequired(source,`static NSArray<NSString *> *${stateName(tree.shadowState)} = @[];\n`,'',`AppKit TreeView '${tree.id}' shadow state`);} function removeShadowRefresh(source,tree){return replaceRequired(source,`  if (gControls[${tree.nativeIndex}]) SetListSelections((NSTableView *)gControls[${tree.nativeIndex}], ${tree.commandId}, ${stateName(tree.shadowState)});\n`,'',`AppKit TreeView '${tree.id}' shadow refresh`);} function assertNoShadowState(source,adapted){for(const tree of adapted.trees)if(source.includes(tree.shadowState))throw new NativeGuiError(`AppKit TreeView '${tree.id}' leaked backend shadow state.`);}
function appKitRect(control,form,controls){const width=positiveInt(control.layout?.width,120),height=positiveInt(control.layout?.height,36),x=layoutInt(control.layout?.x,control.parentTabIndex>=0?12:24),sourceY=layoutInt(control.layout?.y,control.parentTabIndex>=0?12:24);if(control.parentTabIndex<0)return `NSMakeRect(${x}, ${Math.max(0,positiveInt(form.height,420)-sourceY-height)}, ${width}, ${height})`;const tab=controls[control.parentTabIndex];if(!tab||tab.type!=='tabs')throw new NativeGuiError(`AppKit TreeView '${control.id}' has an invalid Tabs parent.`);const pageHeight=Math.max(1,positiveInt(tab.layout?.height,240)-30);return `NSMakeRect(${x}, ${Math.max(0,pageHeight-sourceY-height)}, ${width}, ${height})`;}
function stateName(name){return `patch_state_${identifier(name)}`;} function identifier(value){return String(value).replace(/[^A-Za-z0-9_]/g,'_').replace(/^[0-9]/,'_$&');} function objc(value){return `@${JSON.stringify(String(value??''))}`;} function layoutInt(value,fallback){return Number.isFinite(Number(value))?Math.max(0,Math.round(Number(value))):fallback;} function positiveInt(value,fallback){return Number.isFinite(Number(value))?Math.max(1,Math.round(Number(value))):fallback;} function replaceRequired(source,marker,replacement,label){if(!source.includes(marker))throw new NativeGuiError(`${label} marker is missing from generated AppKit source.`);return source.replace(marker,replacement);}
