import { flattenNativeGuiControls, NativeGuiError } from './native-gui-ir.js';
import { emitAppKitGuiObjCpp as emitAppKitGuiObjCppV07 } from './appkit-gui-v07.js';
import {
  nativeAccessibleName,
  nativeRadioItemAccessibleName,
  needsExplicitNativeAccessibleName
} from './native-accessibility.js';

export const PATCH_APPKIT_GUI_BACKEND_VERSION = '0.8';

export function emitAppKitGuiObjCpp(input) {
  const controls = flattenNativeGuiControls(input);
  let source = emitAppKitGuiObjCppV07(input)
    .replace(/Generated by Patch AppKit GUI backend 0\.7\./, `Generated by Patch AppKit GUI backend ${PATCH_APPKIT_GUI_BACKEND_VERSION}.`);

  source = replaceRequired(source, 'static void RefreshUI();', `${appKitAccessibilityHelpers(controls)}\n${appKitResponsiveHelpers(input, controls)}\nstatic void RefreshUI();`, 'AppKit accessibility/responsive helper insertion');
  if (hasResponsiveLayout(controls)) {
    source = replaceRequired(
      source,
      '@implementation PatchWindowDelegate\n- (BOOL)windowShouldClose:(NSWindow *)sender {',
      '@implementation PatchWindowDelegate\n- (void)windowDidResize:(NSNotification *)notification {\n  (void)notification;\n  if (self.formIndex < 0 || self.formIndex >= FORM_COUNT || !gForms[self.formIndex]) return;\n  NSSize size = gForms[self.formIndex].contentView.bounds.size;\n  ApplyPatchResponsiveLayout((int)self.formIndex, (int)llround(size.width), (int)llround(size.height));\n}\n- (BOOL)windowShouldClose:(NSWindow *)sender {',
      'AppKit resize delegate dispatch'
    );
  }
  source = replaceRequired(
    source,
    'for (int i = 0; i < FORM_COUNT; ++i) if (!CreatePatchForm(i)) return 10 + i;\n    RefreshUI();',
    'for (int i = 0; i < FORM_COUNT; ++i) if (!CreatePatchForm(i)) return 10 + i;\n    ApplyPatchAccessibility();\n    RefreshUI();',
    'AppKit accessibility application'
  );
  return injectAccessibilitySmoke(source, controls);
}

function appKitResponsiveHelpers(ir, controls) {
  const responsive = controls.filter(control => control.parentTabIndex < 0 && isResponsive(control));
  if (!responsive.length) return '';
  const blocks = responsive.map(control => emitAppKitResponsiveControl(ir, control)).join('\n');
  return `static void ApplyPatchResponsiveLayout(int formIndex, int formWidth, int formHeight) {\n  if (formWidth <= 0 || formHeight <= 0) return;\n${blocks}\n}\n`;
}

function emitAppKitResponsiveControl(ir, control) {
  const form = ir.forms[control.formIndex];
  const base = control.layout ?? {};
  const policy = base.policy;
  const x = int(base.x, 24), y = int(base.y, 24), width = int(base.width, 120), height = int(base.height, 36);
  const lines = [`  if (formIndex == ${control.formIndex}) {`, `    int x=${x}, y=${y}, width=${width}, height=${height};`, `    const int dw=formWidth-${int(form.width, 640)}, dh=formHeight-${int(form.height, 420)};`];
  if (policy.kind === 'dock') {
    if (policy.side === 'fill') lines.push('    x=0; y=0; width=formWidth; height=formHeight;');
    if (policy.side === 'top') lines.push('    x=0; y=0; width=formWidth;');
    if (policy.side === 'bottom') lines.push('    x=0; y=(formHeight-height>0?formHeight-height:0); width=formWidth;');
    if (policy.side === 'left') lines.push('    x=0; y=0; height=formHeight;');
    if (policy.side === 'right') lines.push('    x=(formWidth-width>0?formWidth-width:0); y=0; height=formHeight;');
  } else if (policy.kind === 'anchor') {
    const edges = new Set(policy.edges ?? []);
    if (edges.has('left') && edges.has('right')) lines.push('    width=(width+dw>16?width+dw:16);');
    else if (!edges.has('left') && edges.has('right')) lines.push('    x=(x+dw>0?x+dw:0);');
    if (edges.has('top') && edges.has('bottom')) lines.push('    height=(height+dh>16?height+dh:16);');
    else if (!edges.has('top') && edges.has('bottom')) lines.push('    y=(y+dh>0?y+dh:0);');
  }
  lines.push('    const int appKitY=(formHeight-y-height>0?formHeight-y-height:0);');
  if (control.type === 'radio') {
    const count = Math.max(1, control.options?.length ?? 1);
    lines.push(`    { int itemHeight=height/${count}; if(itemHeight<22)itemHeight=22; if(itemHeight>30)itemHeight=30;`);
    lines.push(`      for (NSUInteger optionIndex=0; optionIndex<[gRadioItems[${control.nativeIndex}] count]; ++optionIndex) { NSButton *item=(NSButton *)[gRadioItems[${control.nativeIndex}] objectAtIndex:optionIndex]; item.frame=NSMakeRect(x, appKitY + (${count}-1-(int)optionIndex)*itemHeight, width, itemHeight); } }`);
  } else if (control.type === 'listbox') {
    lines.push(`    if (gControls[${control.nativeIndex}]) { NSScrollView *scroll=[(NSTableView *)gControls[${control.nativeIndex}] enclosingScrollView]; if(scroll) scroll.frame=NSMakeRect(x, appKitY, width, height); gControls[${control.nativeIndex}].frame=NSMakeRect(0,0,width,height); }`);
  } else {
    lines.push(`    if (gControls[${control.nativeIndex}]) gControls[${control.nativeIndex}].frame=NSMakeRect(x, appKitY, width, height);`);
  }
  lines.push('  }');
  return lines.join('\n');
}

function hasResponsiveLayout(controls) { return controls.some(control => control.parentTabIndex < 0 && isResponsive(control)); }
function isResponsive(control) { return control.layout?.policy?.kind && control.layout.policy.kind !== 'fixed'; }
function int(value, fallback) { const number = Number(value); return Number.isFinite(number) ? Math.round(number) : fallback; }

function appKitAccessibilityHelpers(controls) {
  const lines = [];
  for (const control of controls) {
    if (!needsExplicitNativeAccessibleName(control)) continue;
    if (control.type === 'radio') {
      for (let optionIndex = 0; optionIndex < control.options.length; optionIndex += 1) {
        const name = nativeRadioItemAccessibleName(control, control.options[optionIndex]);
        lines.push(`  if ([gRadioItems[${control.nativeIndex}] count] > ${optionIndex}) [(NSButton *)[gRadioItems[${control.nativeIndex}] objectAtIndex:${optionIndex}] setAccessibilityLabel:${objcLiteral(name)}];`);
      }
      continue;
    }
    const name = nativeAccessibleName(control);
    if (!name) continue;
    lines.push(`  if (gControls[${control.nativeIndex}]) [gControls[${control.nativeIndex}] setAccessibilityLabel:${objcLiteral(name)}];`);
  }
  return `static void ApplyPatchAccessibility() {\n${lines.join('\n') || '  // Standard AppKit control names need no Patch override.'}\n}\n`;
}

function injectAccessibilitySmoke(source, controls) {
  const checks = [];
  let code = 130;
  for (const control of controls) {
    if (!needsExplicitNativeAccessibleName(control)) continue;
    if (control.type === 'radio') {
      for (let optionIndex = 0; optionIndex < control.options.length; optionIndex += 1) {
        const expected = nativeRadioItemAccessibleName(control, control.options[optionIndex]);
        checks.push(`  if ([gRadioItems[${control.nativeIndex}] count] <= ${optionIndex} || ![[((NSButton *)[gRadioItems[${control.nativeIndex}] objectAtIndex:${optionIndex}]) accessibilityLabel] isEqualToString:${objcLiteral(expected)}]) return ${code++};`);
      }
      continue;
    }
    const expected = nativeAccessibleName(control);
    if (!expected) continue;
    checks.push(`  if (![[gControls[${control.nativeIndex}] accessibilityLabel] isEqualToString:${objcLiteral(expected)}]) return ${code++};`);
  }
  if (!checks.length) return source;
  const start = source.indexOf('static int RunPatchSmoke() {');
  if (start < 0) throw new NativeGuiError('Generated AppKit source is missing RunPatchSmoke for accessibility verification.');
  const stop = source.indexOf('  [NSApp stop:nil];', start);
  if (stop < 0) throw new NativeGuiError('Generated AppKit smoke has an unexpected shape for accessibility verification.');
  return source.slice(0, stop) + checks.join('\n') + '\n' + source.slice(stop);
}

function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated AppKit source.`);
  return source.replace(marker, replacement);
}

function objcLiteral(value) { return `@${JSON.stringify(String(value ?? ''))}`; }
