import { NativeGuiError } from './native-gui-ir.js';
import { emitAppKitGuiObjCppV13 } from './appkit-gui-v13.js';
import { adaptNativeSlidersForV13Backend, sliderPersistentNumberTarget } from './native-slider-backend-adapter.js';

export const PATCH_APPKIT_GUI_BACKEND_V14_VERSION = '1.4';

/** Emit AppKit backend 1.4 with real NSSlider controls. */
export function emitAppKitGuiObjCppV14(input) {
  const adapted = adaptNativeSlidersForV13Backend(input);
  let source = emitAppKitGuiObjCppV13(adapted.compatibleIr)
    .replace(/Generated by Patch AppKit GUI backend 1\.3\./, `Generated by Patch AppKit GUI backend ${PATCH_APPKIT_GUI_BACKEND_V14_VERSION}.`);
  if (!adapted.sliders.length) return source;

  for (const slider of adapted.sliders) {
    source = removeShadowState(source, slider);
    source = removeShadowRefresh(source, slider);
    source = replaceControlBlock(source, slider, sliderCreate(adapted, slider));
  }

  for (const patch of adapted.eventPatches) {
    source = patchSliderEventFunction(source, patch);
    const slider = adapted.sliders.find(item => item.id === patch.control);
    if (!slider) continue;
    source = replaceRequired(
      source,
      `  if (commandId == ${slider.commandId}) { Event_${patch.eventIndex}([field stringValue]); return; }\n`,
      '',
      `AppKit Slider '${slider.id}' legacy Input dispatch`
    );
  }

  source = replaceRequired(
    source,
    '- (void)handleControl:(id)sender {\n  if (gRefreshing) return;\n  NSInteger commandId = [sender tag];',
    `- (void)handleControl:(id)sender {\n  if (gRefreshing) return;\n  NSInteger commandId = [sender tag];\n${emitSliderDispatch(adapted)}`,
    'AppKit Slider action dispatch'
  );
  source = replaceRequired(
    source,
    '@interface PatchEventTarget : NSObject',
    `${emitSliderHelpers(adapted)}\n\n@interface PatchEventTarget : NSObject`,
    'AppKit Slider helper insertion'
  );
  source = injectSliderRefresh(source, adapted);
  source = injectSliderSmoke(source, adapted);
  assertNoShadowState(source, adapted);
  return source;
}

function patchSliderEventFunction(source, patch) {
  const oldSignature = `static void Event_${patch.eventIndex}(NSString *eventValue) {`;
  const newSignature = `static void Event_${patch.eventIndex}(double eventValue) {`;
  const start = source.indexOf(oldSignature);
  if (start < 0) throw new NativeGuiError(`AppKit Slider Event_${patch.eventIndex} signature marker is missing.`);
  const endMarker = '\n  RefreshUI();\n}';
  const end = source.indexOf(endMarker, start);
  if (end < 0) throw new NativeGuiError(`AppKit Slider Event_${patch.eventIndex} body marker is missing.`);
  let body = source.slice(start, end + endMarker.length).replace(oldSignature, newSignature);
  for (const sentinel of patch.sentinels) body = body.replaceAll(String(sentinel), 'eventValue');
  return source.slice(0, start) + body + source.slice(end + endMarker.length);
}

function emitSliderHelpers(adapted) {
  return adapted.sliders.map(slider =>
    `static double PatchSliderValue_${slider.nativeIndex}(NSSlider *slider) { if (!slider) return ${number(slider.min)}; double raw=slider.doubleValue; double steps=std::round((raw-${number(slider.min)})/${number(slider.step)}); double value=${number(slider.min)}+steps*${number(slider.step)}; if(value<${number(slider.min)})value=${number(slider.min)}; if(value>${number(slider.max)})value=${number(slider.max)}; return value; }`
  ).join('\n');
}

function emitSliderDispatch(adapted) {
  const lines = [];
  for (const slider of adapted.sliders) {
    const eventIndex = adapted.events.findIndex(event => event.control === slider.id && event.event === 'changed');
    if (eventIndex >= 0) lines.push(`  if (commandId == ${slider.commandId}) { Event_${eventIndex}(PatchSliderValue_${slider.nativeIndex}((NSSlider *)sender)); return; }`);
  }
  return lines.join('\n');
}

function sliderCreate(adapted, slider) {
  const control = adapted.controls[slider.nativeIndex];
  const form = adapted.ir.forms[control.formIndex];
  const rect = appKitRect(control, form, adapted.controls);
  const target = control.parentTabIndex >= 0 ? `(NSView *)[gTabPages[${control.parentTabIndex}] objectAtIndex:${control.pageIndex}]` : 'window.contentView';
  const initialExpr = slider.binding ? stateName(slider.binding) : number(slider.min);
  return `  if (${control.formIndex} == index) {\n    NSSlider *control = [[NSSlider alloc] initWithFrame:${rect}]; control.minValue = ${number(slider.min)}; control.maxValue = ${number(slider.max)}; control.doubleValue = ${initialExpr}; control.continuous = NO; control.tag = ${slider.commandId}; control.target = gEventTarget; control.action = @selector(handleControl:); gControls[${slider.nativeIndex}] = control; [${target} addSubview:control];\n  }`;
}

function injectSliderRefresh(source, adapted) {
  const start = source.indexOf('static void RefreshUI() {');
  if (start < 0) throw new NativeGuiError('Generated AppKit source is missing RefreshUI for Slider state.');
  const marker = '  gRefreshing = false;';
  const at = source.indexOf(marker, start);
  if (at < 0) throw new NativeGuiError('Generated AppKit Slider refresh insertion point is missing.');
  const lines = adapted.sliders.filter(slider => slider.binding).map(slider =>
    `  if (gControls[${slider.nativeIndex}]) [(NSSlider *)gControls[${slider.nativeIndex}] setDoubleValue:${stateName(slider.binding)}];`
  );
  return source.slice(0, at) + (lines.length ? lines.join('\n') + '\n' : '') + source.slice(at);
}

function injectSliderSmoke(source, adapted) {
  const start = source.indexOf('static int RunPatchSmoke() {');
  if (start < 0) throw new NativeGuiError('Generated AppKit source is missing Slider smoke function.');
  const at = source.indexOf('  [NSApp stop:nil];', start);
  if (at < 0) throw new NativeGuiError('Generated AppKit Slider smoke insertion point is missing.');
  const checks = [];
  let code = 240;
  for (const slider of adapted.sliders) {
    checks.push(`  if (!gControls[${slider.nativeIndex}] || ![gControls[${slider.nativeIndex}] isKindOfClass:[NSSlider class]]) return ${code++};`);
    const eventIndex = adapted.events.findIndex(event => event.control === slider.id && event.event === 'changed');
    if (eventIndex < 0) continue;
    checks.push(`  [(NSSlider *)gControls[${slider.nativeIndex}] setDoubleValue:${number(slider.max)}]; [gEventTarget handleControl:gControls[${slider.nativeIndex}]];`);
    const target = sliderPersistentNumberTarget(adapted.events[eventIndex], adapted.states);
    if (target) checks.push(`  if (std::fabs(${stateName(target)} - PatchSliderValue_${slider.nativeIndex}((NSSlider *)gControls[${slider.nativeIndex}])) > 1e-9) return ${code++};`);
  }
  return source.slice(0, at) + checks.join('\n') + '\n' + source.slice(at);
}

function replaceControlBlock(source, slider, replacement) {
  const tag = `control.tag = ${slider.commandId}; control.delegate = gEventTarget;`;
  const tagAt = source.indexOf(tag);
  if (tagAt < 0) throw new NativeGuiError(`AppKit Slider '${slider.id}' shadow command is missing.`);
  const start = source.lastIndexOf(`  if (${slider.formIndex} == index) {`, tagAt);
  const end = source.indexOf('\n  }', tagAt);
  if (start < 0 || end < 0) throw new NativeGuiError(`AppKit Slider '${slider.id}' shadow control block is missing.`);
  return source.slice(0, start) + replacement + source.slice(end + 4);
}
function removeShadowState(source, slider) { return replaceRequired(source, `static NSString *${stateName(slider.shadowState)} = ${objc(String(slider.initial))};\n`, '', `AppKit Slider '${slider.id}' shadow state`); }
function removeShadowRefresh(source, slider) { return replaceRequired(source, `  if (gControls[${slider.nativeIndex}]) SetStringIfDifferent((NSControl *)gControls[${slider.nativeIndex}], ${stateName(slider.shadowState)});\n`, '', `AppKit Slider '${slider.id}' shadow refresh`); }
function assertNoShadowState(source, adapted) { for (const slider of adapted.sliders) if (source.includes(slider.shadowState)) throw new NativeGuiError(`AppKit Slider '${slider.id}' leaked backend shadow state.`); }
function appKitRect(control,form,controls){const width=positiveInt(control.layout?.width,260),height=positiveInt(control.layout?.height,44),x=layoutInt(control.layout?.x,control.parentTabIndex>=0?12:24),sourceY=layoutInt(control.layout?.y,control.parentTabIndex>=0?12:24);if(control.parentTabIndex<0)return `NSMakeRect(${x}, ${Math.max(0,positiveInt(form.height,420)-sourceY-height)}, ${width}, ${height})`;const tab=controls[control.parentTabIndex];if(!tab||tab.type!=='tabs')throw new NativeGuiError(`AppKit Slider '${control.id}' has an invalid Tabs parent.`);const pageHeight=Math.max(1,positiveInt(tab.layout?.height,240)-30);return `NSMakeRect(${x}, ${Math.max(0,pageHeight-sourceY-height)}, ${width}, ${height})`;}
function stateName(name){return `patch_state_${identifier(name)}`;} function identifier(value){return String(value).replace(/[^A-Za-z0-9_]/g,'_').replace(/^[0-9]/,'_$&');} function objc(value){return `@${JSON.stringify(String(value??''))}`;} function number(value){return String(Number(value));} function layoutInt(value,fallback){return Number.isFinite(Number(value))?Math.max(0,Math.round(Number(value))):fallback;} function positiveInt(value,fallback){return Number.isFinite(Number(value))?Math.max(1,Math.round(Number(value))):fallback;} function replaceRequired(source,marker,replacement,label){if(!source.includes(marker))throw new NativeGuiError(`${label} marker is missing from generated AppKit source.`);return source.replace(marker,replacement);}
