import { NativeGuiError } from './native-gui-ir.js';
import { emitAppKitGuiObjCppV11 } from './appkit-gui-v11.js';
import { adaptNativeListsForV11Backend } from './native-list-backend-adapter.js';

export const PATCH_APPKIT_GUI_BACKEND_V12_VERSION = '1.2';

/** Emit AppKit backend 1.2 with persistent list state and native multi-select ListBox. */
export function emitAppKitGuiObjCppV12(input) {
  const adapted = adaptNativeListsForV11Backend(input);
  let source = emitAppKitGuiObjCppV11(adapted.compatibleIr)
    .replace(/Generated by Patch AppKit GUI backend 1\.1\./, `Generated by Patch AppKit GUI backend ${PATCH_APPKIT_GUI_BACKEND_V12_VERSION}.`);

  if (!adapted.listStates.size) return source;
  source = injectListHelpers(source);

  for (const state of adapted.listStates.values()) {
    source = replaceRequired(
      source,
      `static NSString *${stateName(state.name)} = ${objcLiteral(state.initial?.[0] ?? '')};`,
      `static NSArray<NSString *> *${stateName(state.name)} = ${objcArray(state.initial ?? [])};`,
      `AppKit list state '${state.name}' declaration`
    );
  }

  for (const control of adapted.multiControls) {
    const createMarker = `control.allowsMultipleSelection = NO; control.allowsEmptySelection = YES; control.tag = ${control.commandId};`;
    const createReplacement = `control.allowsMultipleSelection = YES; control.allowsEmptySelection = YES; control.tag = ${control.commandId};`;
    source = replaceRequired(source, createMarker, createReplacement, `AppKit multi-select ListBox '${control.id}' creation`);
    source = replaceRequired(
      source,
      compatibleRefresh(control),
      `  if (gControls[${control.nativeIndex}]) SetListSelections((NSTableView *)gControls[${control.nativeIndex}], ${control.commandId}, ${stateName(control.binding)});`,
      `AppKit multi-select ListBox '${control.id}' refresh`
    );
  }

  for (const event of adapted.events) {
    source = patchListEventFunction(source, event);
    const control = adapted.multiControls.find(item => item.id === event.control);
    if (!control) continue;
    const marker = `  if (commandId == ${control.commandId}) { NSInteger row = [(NSTableView *)sender selectedRow]; Event_${event.eventIndex}(row >= 0 ? PatchListOptionValue(commandId, row) : @""); return; }`;
    const replacement = `  if (commandId == ${control.commandId}) { Event_${event.eventIndex}(PatchSelectedListValues((NSTableView *)sender)); return; }`;
    source = replaceRequired(source, marker, replacement, `AppKit multi-select ListBox '${event.control}' event dispatch`);
  }

  source = injectSmoke(source, adapted);
  return source;
}

function injectListHelpers(source) {
  const marker = 'static void ShowInfoDialog(int formIndex, NSString *title, NSString *message) {';
  const helpers = `static NSArray<NSString *> *PatchSelectedListValues(NSTableView *tableView) {\n  if (!tableView) return @[];\n  NSMutableArray<NSString *> *out = [NSMutableArray array];\n  NSIndexSet *selected = tableView.selectedRowIndexes;\n  NSUInteger row = selected.firstIndex;\n  while (row != NSNotFound) { [out addObject:PatchListOptionValue(tableView.tag, (NSInteger)row) ?: @""]; row = [selected indexGreaterThanIndex:row]; }\n  return [out copy];\n}\nstatic void SetListSelections(NSTableView *tableView, NSInteger commandId, NSArray<NSString *> *values) {\n  if (!tableView) return;\n  NSMutableIndexSet *selected = [NSMutableIndexSet indexSet];\n  NSInteger count = PatchListOptionCount(commandId);\n  for (NSInteger row = 0; row < count; ++row) { NSString *value = PatchListOptionValue(commandId, row); if ([values containsObject:value]) [selected addIndex:(NSUInteger)row]; }\n  [tableView selectRowIndexes:selected byExtendingSelection:NO];\n}\nstatic NSArray<NSString *> *PatchListRemoving(NSArray<NSString *> *values, NSString *removeValue) {\n  NSMutableArray<NSString *> *out = [values mutableCopy] ?: [NSMutableArray array];\n  NSUInteger index = [out indexOfObject:removeValue ?: @""];\n  if (index != NSNotFound) [out removeObjectAtIndex:index];\n  return [out copy];\n}\n`;
  return replaceRequired(source, marker, helpers + marker, 'AppKit multi-select ListBox helpers');
}

function patchListEventFunction(source, event) {
  const oldSignature = `static void Event_${event.eventIndex}(NSString *eventValue) {`;
  const newSignature = `static void Event_${event.eventIndex}(NSArray<NSString *> *eventValue) {`;
  const start = source.indexOf(oldSignature);
  if (start < 0) throw new NativeGuiError(`AppKit list Event_${event.eventIndex} signature marker is missing.`);
  const endMarker = '\n  RefreshUI();\n}';
  const end = source.indexOf(endMarker, start);
  if (end < 0) throw new NativeGuiError(`AppKit list Event_${event.eventIndex} body marker is missing.`);
  let body = source.slice(start, end + endMarker.length).replace(oldSignature, newSignature);

  for (const action of event.actions ?? []) {
    if (action.kind !== 'change' || action.stateType !== 'list') continue;
    const target = stateName(action.target);
    for (const op of action.ops ?? []) {
      if (op.value?.kind === 'eventValue') continue;
      if (op.op === 'clear') {
        body = replaceInBody(body, `  ${target} = @"";`, `  ${target} = @[];`, `AppKit list clear '${action.target}'`);
      } else if (op.op === 'add') {
        body = replaceInBody(body, `  ${target} = [${target} stringByAppendingString:@""];`, `  ${target} = [${target} arrayByAddingObject:${objcLiteral(op.value.value)}];`, `AppKit list add '${action.target}'`);
      } else if (op.op === 'remove') {
        body = replaceInBody(body, `  ${target} = @"";`, `  ${target} = PatchListRemoving(${target}, ${objcLiteral(op.value.value)});`, `AppKit list remove '${action.target}'`);
      } else if (op.op === 'set') {
        body = replaceInBody(body, `  ${target} = @"";`, `  ${target} = ${objcArray(op.value.value)};`, `AppKit list set '${action.target}'`);
      }
    }
  }
  return source.slice(0, start) + body + source.slice(end + endMarker.length);
}

function compatibleRefresh(control) {
  const state = stateName(control.binding);
  const checks = control.options.map((option, optionIndex) => `if ([${state} isEqualToString:${objcLiteral(option)}]) selected = ${optionIndex};`).join(' else ');
  return `  if (gControls[${control.nativeIndex}]) { NSInteger selected = -1; ${checks} if (selected >= 0) [(NSTableView *)gControls[${control.nativeIndex}] selectRowIndexes:[NSIndexSet indexSetWithIndex:(NSUInteger)selected] byExtendingSelection:NO]; else [(NSTableView *)gControls[${control.nativeIndex}] deselectAll:nil]; }`;
}

function injectSmoke(source, adapted) {
  const candidate = adapted.multiControls.find(control => {
    const event = adapted.events.find(item => item.control === control.id && item.event === 'changed');
    return event && event.actions?.some(action => action.kind === 'change' && action.target === control.binding && action.ops?.some(op => op.op === 'set' && op.value?.kind === 'eventValue'));
  });
  if (!candidate || candidate.options.length < 2) return source;
  const first = candidate.options[0];
  const last = candidate.options[candidate.options.length - 1];
  const smoke = `  { NSMutableIndexSet *selected = [NSMutableIndexSet indexSetWithIndex:0]; [selected addIndex:${candidate.options.length - 1}]; [(NSTableView *)gControls[${candidate.nativeIndex}] selectRowIndexes:selected byExtendingSelection:NO]; [gEventTarget handleControl:gControls[${candidate.nativeIndex}]]; if ([${stateName(candidate.binding)} count] != 2 || ![${stateName(candidate.binding)}[0] isEqualToString:${objcLiteral(first)}] || ![${stateName(candidate.binding)}[1] isEqualToString:${objcLiteral(last)}]) return 91; }\n`;
  const start = source.indexOf('static int RunPatchSmoke() {');
  if (start < 0) throw new NativeGuiError('Generated AppKit source is missing RunPatchSmoke for multi-select verification.');
  const stop = source.indexOf('  [NSApp stop:nil];', start);
  if (stop < 0) throw new NativeGuiError('Generated AppKit smoke has an unexpected shape for multi-select verification.');
  return source.slice(0, stop) + smoke + source.slice(stop);
}

function replaceInBody(body, marker, replacement, label) {
  if (!body.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated AppKit event body.`);
  return body.replace(marker, replacement);
}
function stateName(name) { return `patch_state_${identifier(name)}`; }
function identifier(value) { return String(value).replace(/[^A-Za-z0-9_]/g, '_').replace(/^[0-9]/, '_$&'); }
function objcLiteral(value) { return `@${JSON.stringify(String(value ?? ''))}`; }
function objcArray(values) { return `@[${(values ?? []).map(value => objcLiteral(value)).join(', ')}]`; }
function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated AppKit source.`);
  return source.replace(marker, replacement);
}
