import { flattenNativeGuiControls, flattenNativeGuiMenuItems, NativeGuiError } from './native-gui-ir.js';
import { emitAppKitGuiObjCpp as emitAppKitGuiObjCppV06 } from './appkit-gui.js';
import {
  planNativeResultDialogs,
  buildAuxiliaryResultIr,
  resultHandlerName,
  resultHandler,
  injectIntoEvent,
  extractEventZero,
  insertAfter,
  insertBefore,
  identifier
} from './native-result-dialog-overlay.js';

export const PATCH_APPKIT_GUI_BACKEND_VERSION = '0.7';

export function emitAppKitGuiObjCpp(input) {
  const plan = planNativeResultDialogs(input);
  let source = emitAppKitGuiObjCppV06(plan.baseIr)
    .replace(/Generated by Patch AppKit GUI backend 0\.6\./, `Generated by Patch AppKit GUI backend ${PATCH_APPKIT_GUI_BACKEND_VERSION}.`);
  if (!plan.triggers.length) return source;

  const resultFunctions = plan.resultEvents.map(event => {
    const aux = buildAuxiliaryResultIr(plan.ir, event);
    return extractEventZero(emitAppKitGuiObjCppV06(aux), resultHandlerName(event.control, event.event));
  }).join('\n\n');

  source = insertBefore(source, 'static void RefreshUI();', `${appKitHelpers()}\n`);
  source = insertAfter(source, 'static void RefreshUI();', `\n\n${resultFunctions}\n`);
  for (const trigger of plan.triggers) source = injectIntoEvent(source, trigger.baseIndex, appKitResultAction(plan, trigger.action));
  return injectSmoke(source, plan);
}

function appKitHelpers() {
  return `static NSString *gLastResultSource = @\"\";\nstatic NSString *gLastResultValue = @\"\";\nstatic NSInteger gLastResultEvent = 0;\nstatic bool PatchConfirmDialog(int formIndex, NSString *title, NSString *message) {\n  (void)formIndex;\n  if (gSmokeMode) return true;\n  NSAlert *alert = [NSAlert new];\n  alert.alertStyle = NSAlertStyleWarning;\n  alert.messageText = title ?: @\"\";\n  alert.informativeText = message ?: @\"\";\n  [alert addButtonWithTitle:@\"Yes\"];\n  [alert addButtonWithTitle:@\"No\"];\n  return [alert runModal] == NSAlertFirstButtonReturn;\n}\nstatic bool PatchFileDialog(int formIndex, NSString *title, bool save, NSString **result) {\n  (void)formIndex;\n  if (gSmokeMode) { if (result) *result = save ? @\"/tmp/patch-saved.patch\" : @\"/tmp/patch-opened.patch\"; return true; }\n  NSSavePanel *panel = save ? [NSSavePanel savePanel] : [NSOpenPanel openPanel];\n  panel.title = title ?: @\"\";\n  if (!save) { ((NSOpenPanel *)panel).canChooseFiles = YES; ((NSOpenPanel *)panel).canChooseDirectories = NO; ((NSOpenPanel *)panel).allowsMultipleSelection = NO; }\n  if ([panel runModal] != NSModalResponseOK) return false;\n  if (result) *result = panel.URL.path ?: @\"\";\n  return true;\n}\n`;
}

function appKitResultAction(plan, action) {
  const formIndex = plan.ir.forms.findIndex(form => form.id === action.form);
  if (formIndex < 0) throw new NativeGuiError(`AppKit result dialog Form '${action.form}' is missing.`);
  const confirmed = resultHandler(plan, action.id, 'confirmed');
  const chosen = resultHandler(plan, action.id, 'chosen');
  const cancelled = resultHandler(plan, action.id, 'cancelled');
  const onConfirmed = confirmed ? `${resultHandlerName(action.id, 'confirmed')}();` : '';
  const onChosen = chosen ? `${resultHandlerName(action.id, 'chosen')}(patchResultValue);` : '';
  const onCancelled = cancelled ? `${resultHandlerName(action.id, 'cancelled')}();` : '';

  if (action.kind === 'confirmDialog') {
    return `  {\n    const bool patchAccepted = PatchConfirmDialog(${formIndex}, ${objcLiteral(action.title)}, ${objcLiteral(action.message)});\n    gLastResultSource = ${objcLiteral(action.id)}; gLastResultValue = @\"\"; gLastResultEvent = patchAccepted ? 3 : 5;\n    if (patchAccepted) { ${onConfirmed} } else { ${onCancelled} }\n  }`;
  }
  const save = action.kind === 'saveFileDialog';
  return `  {\n    NSString *patchResultValue = @\"\";\n    const bool patchChosen = PatchFileDialog(${formIndex}, ${objcLiteral(action.title)}, ${save ? 'true' : 'false'}, &patchResultValue);\n    gLastResultSource = ${objcLiteral(action.id)}; gLastResultValue = patchChosen ? patchResultValue : @\"\"; gLastResultEvent = patchChosen ? 4 : 5;\n    if (patchChosen) { ${onChosen} } else { ${onCancelled} }\n  }`;
}

function injectSmoke(source, plan) {
  const controls = new Map(flattenNativeGuiControls(plan.baseIr).filter(control => control.id).map(control => [control.id, control]));
  const menus = new Map(flattenNativeGuiMenuItems(plan.baseIr).map(item => [item.id, item]));
  const checks = [];
  let code = 90;
  for (const trigger of plan.triggers) {
    const control = controls.get(trigger.event.control);
    const menu = menus.get(trigger.event.control);
    if (control?.type === 'button') checks.push(`  [(NSButton *)gControls[${control.nativeIndex}] performClick:nil];`);
    else if (menu) checks.push(`  [NSApp sendAction:gMenuItems[${menu.nativeIndex}].action to:gMenuItems[${menu.nativeIndex}].target from:gMenuItems[${menu.nativeIndex}]];`);
    else continue;

    const expectedEvent = trigger.action.kind === 'confirmDialog' ? 3 : 4;
    const expectedValue = trigger.action.kind === 'openFileDialog' ? '/tmp/patch-opened.patch' : trigger.action.kind === 'saveFileDialog' ? '/tmp/patch-saved.patch' : '';
    checks.push(`  if (![gLastResultSource isEqualToString:${objcLiteral(trigger.action.id)}] || gLastResultEvent != ${expectedEvent}) return ${code++};`);
    if (expectedValue) checks.push(`  if (![gLastResultValue isEqualToString:${objcLiteral(expectedValue)}]) return ${code++};`);
    const handler = trigger.action.kind === 'confirmDialog'
      ? resultHandler(plan, trigger.action.id, 'confirmed')
      : resultHandler(plan, trigger.action.id, 'chosen');
    const eventValueChange = handler?.actions?.find(action => action.kind === 'change' && action.stateType === 'text' && action.ops?.some(op => op.value?.kind === 'eventValue'));
    if (expectedValue && eventValueChange) checks.push(`  if (![patch_state_${identifier(eventValueChange.target)} isEqualToString:${objcLiteral(expectedValue)}]) return ${code++};`);
  }
  if (!checks.length) return source;
  const start = source.indexOf('static int RunPatchSmoke() {');
  if (start < 0) throw new NativeGuiError('Generated AppKit source is missing RunPatchSmoke.');
  const stop = source.indexOf('  [NSApp stop:nil];', start);
  if (stop < 0) throw new NativeGuiError('Generated AppKit smoke has an unexpected shape.');
  return source.slice(0, stop) + checks.join('\n') + '\n' + source.slice(stop);
}

function objcLiteral(value) { return `@${JSON.stringify(String(value ?? ''))}`; }
