import { NativeGuiError } from './native-gui-ir.js';
import { emitAppKitGuiObjCppV10 } from './appkit-gui-v10.js';
import { adaptNativeMenuStateForV10Backend } from './native-menu-state-backend-adapter.js';

export const PATCH_APPKIT_GUI_BACKEND_V11_VERSION = '1.1';

/** Emit AppKit backend 1.1 with source-backed enabled/checked MenuItem state. */
export function emitAppKitGuiObjCppV11(input) {
  const adapted = adaptNativeMenuStateForV10Backend(input);
  let source = emitAppKitGuiObjCppV10(adapted.compatibleIr)
    .replace(/Generated by Patch AppKit GUI backend 1\.0\./, `Generated by Patch AppKit GUI backend ${PATCH_APPKIT_GUI_BACKEND_V11_VERSION}.`);

  if (!adapted.statefulItems.length) return source;

  const refreshLines = [];
  for (const item of adapted.statefulItems) {
    const changes = [];
    if (item.enabledState) changes.push(`[gMenuItems[${item.legacyNativeIndex}] setEnabled:${stateName(item.enabledState)} ? YES : NO];`);
    if (item.checkedState) changes.push(`[gMenuItems[${item.legacyNativeIndex}] setState:${stateName(item.checkedState)} ? NSControlStateValueOn : NSControlStateValueOff];`);
    refreshLines.push(`  if (gMenuItems[${item.legacyNativeIndex}]) { ${changes.join(' ')} }`);
  }

  source = replaceRequired(
    source,
    'static void RefreshUI() {\n  gRefreshing = true;',
    `static void RefreshUI() {\n  gRefreshing = true;\n${refreshLines.join('\n')}`,
    'AppKit Menu state RefreshUI insertion'
  );

  const enabledById = new Map(adapted.enabledItems.map(item => [item.id, item]));
  for (let eventIndex = 0; eventIndex < adapted.ir.events.length; eventIndex += 1) {
    const event = adapted.ir.events[eventIndex];
    const item = enabledById.get(event.control);
    if (!item || event.event !== 'clicked') continue;
    const marker = `  if (commandId == ${item.commandId}) { Event_${eventIndex}(); return; }`;
    const replacement = `  if (commandId == ${item.commandId}) { if (!${stateName(item.enabledState)}) return; Event_${eventIndex}(); return; }`;
    source = replaceRequired(source, marker, replacement, `AppKit enabled MenuItem '${item.id}' dispatch guard`);
  }

  return source;
}

function stateName(name) { return `patch_state_${identifier(name)}`; }
function identifier(value) { return String(value).replace(/[^A-Za-z0-9_]/g, '_').replace(/^[0-9]/, '_$&'); }
function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated AppKit source.`);
  return source.replace(marker, replacement);
}
