import { flattenNativeGuiControls, validateNativeGuiIR, NativeGuiError } from './native-gui-ir.js';

export const PATCH_APPKIT_GUI_BACKEND_VERSION = '0.5';

export function emitAppKitGuiObjCpp(input) {
  const ir = validateNativeGuiIR(input);
  const forms = new Map(ir.forms.map((form, index) => [form.id, index]));
  const controls = flattenNativeGuiControls(ir).map(control => ({
    ...control,
    commandId: 1000 + control.nativeIndex,
    handleIndex: control.nativeIndex
  }));
  const controlsById = new Map(controls.filter(control => control.id).map(control => [control.id, control]));
  const states = new Map(ir.states.map(state => [state.name, state]));
  validateReferences(ir, forms, controlsById);

  const stateDecls = ir.states.map(stateDeclaration).join('\n');
  const formDefs = ir.forms.map((form, index) =>
    `  {${objcLiteral(form.id)}, ${objcLiteral(form.title)}, ${positiveInt(form.width, 640)}, ${positiveInt(form.height, 420)}, ${form.visible ? 'true' : 'false'}}${index + 1 === ir.forms.length ? '' : ','}`
  ).join('\n');
  const controlDefs = controls.map((control, index) =>
    `  {${control.commandId}, ${control.formIndex}, ${controlKind(control.type)}, ${objcLiteral(control.id ?? '')}, ${layoutInt(control.layout?.x, 24)}, ${layoutInt(control.layout?.y, 24)}, ${positiveInt(control.layout?.width, 120)}, ${positiveInt(control.layout?.height, 36)}, ${control.parentTabIndex ?? -1}, ${control.pageIndex ?? -1}}${index + 1 === controls.length ? '' : ','}`
  ).join('\n');
  const textFunctions = controls.map((control, index) => emitControlTextFunction(control, index, states)).join('\n\n');
  const eventFunctions = ir.events.map((event, index) => emitEventFunction(event, index, forms, states)).join('\n\n');
  const actionDispatch = ir.events.map((event, index) => emitActionDispatch(event, index, controlsById)).filter(Boolean).join('\n');
  const inputDispatch = ir.events.map((event, index) => emitInputDispatch(event, index, controlsById)).filter(Boolean).join('\n');
  const refresh = controls.map((control, index) => emitRefresh(control, index, states)).filter(Boolean).join('\n');
  const create = controls.map((control, index) => emitCreateControl(control, index, ir.forms[control.formIndex], controls)).join('\n');
  const listCountCases = controls.filter(control => control.type === 'listbox').map(control => `    case ${control.commandId}: return ${control.options.length};`).join('\n');
  const listValueCases = controls.filter(control => control.type === 'listbox').map(control =>
    `    case ${control.commandId}: switch (row) { ${control.options.map((option, optionIndex) => `case ${optionIndex}: return ${objcLiteral(option)};`).join(' ')} default: return @""; }`
  ).join('\n');
  const smoke = emitSmoke(forms, controlsById, states);

  return `// Generated by Patch AppKit GUI backend ${PATCH_APPKIT_GUI_BACKEND_VERSION}.
// Direct native AppKit controls: no Electron/Chromium runtime.
#import <Cocoa/Cocoa.h>
#include <cmath>
#include <cstring>

static bool gRefreshing = false;

enum ControlKind { CK_TEXT=1, CK_BUTTON=2, CK_INPUT=3, CK_CHECKBOX=4, CK_COMBO=5, CK_LISTBOX=6, CK_TABS=7, CK_RADIO=8 };
struct FormDef { NSString *formId; NSString *title; int width; int height; bool visible; };
struct ControlDef { NSInteger commandId; int formIndex; ControlKind kind; NSString *name; int x; int y; int width; int height; int parentTabIndex; int pageIndex; };

${stateDecls}

static const FormDef FORMS[] = {
${formDefs}
};
static const int FORM_COUNT = ${ir.forms.length};
static NSWindow *gForms[${Math.max(1, ir.forms.length)}] = {};
static NSMutableArray *gFormDelegates = nil;

static const ControlDef CONTROLS[] = {
${controlDefs || '  {0,0,CK_TEXT,@"",0,0,0,0,-1,-1}'}
};
static const int CONTROL_COUNT = ${controls.length};
static NSView *gControls[${Math.max(1, controls.length)}] = {};
static NSMutableArray *gTabPages[${Math.max(1, controls.length)}] = {};
static NSMutableArray *gRadioItems[${Math.max(1, controls.length)}] = {};

static NSString *PatchNumber(double value) {
  if (std::isfinite(value) && std::floor(value) == value) return [NSString stringWithFormat:@"%lld", (long long)value];
  return [NSString stringWithFormat:@"%.15g", value];
}
static NSString *PatchBoolean(bool value) { return value ? @"true" : @"false"; }
static void SetStringIfDifferent(NSControl *control, NSString *value) {
  if (![control.stringValue isEqualToString:value]) control.stringValue = value;
}
static void SetRadioSelection(NSInteger index, NSString *value) {
  if (index < 0 || index >= CONTROL_COUNT || !gRadioItems[index]) return;
  for (NSButton *item in gRadioItems[index]) {
    item.state = [item.title isEqualToString:value] ? NSControlStateValueOn : NSControlStateValueOff;
  }
}
static NSInteger PatchListOptionCount(NSInteger commandId) {
  switch (commandId) {
${listCountCases}
    default: return 0;
  }
}
static NSString *PatchListOptionValue(NSInteger commandId, NSInteger row) {
  switch (commandId) {
${listValueCases}
    default: return @"";
  }
}

${textFunctions}

static void RefreshUI();

${eventFunctions}

@interface PatchEventTarget : NSObject <NSTextFieldDelegate, NSTableViewDataSource, NSTableViewDelegate>
- (void)handleControl:(id)sender;
@end

@implementation PatchEventTarget
- (void)handleControl:(id)sender {
  if (gRefreshing) return;
  NSInteger commandId = [sender tag];
${actionDispatch || '  (void)commandId;'}
}
- (void)controlTextDidChange:(NSNotification *)notification {
  if (gRefreshing) return;
  NSTextField *field = (NSTextField *)notification.object;
  NSInteger commandId = field.tag;
${inputDispatch || '  (void)commandId;'}
}
- (NSInteger)numberOfRowsInTableView:(NSTableView *)tableView {
  return PatchListOptionCount(tableView.tag);
}
- (NSView *)tableView:(NSTableView *)tableView viewForTableColumn:(NSTableColumn *)tableColumn row:(NSInteger)row {
  (void)tableColumn;
  NSTextField *label = [NSTextField labelWithString:PatchListOptionValue(tableView.tag, row)];
  label.lineBreakMode = NSLineBreakByTruncatingTail;
  return label;
}
- (void)tableViewSelectionDidChange:(NSNotification *)notification {
  if (gRefreshing) return;
  [self handleControl:notification.object];
}
@end

static PatchEventTarget *gEventTarget = nil;

@interface PatchWindowDelegate : NSObject <NSWindowDelegate>
@property(nonatomic) NSInteger formIndex;
@end
@implementation PatchWindowDelegate
- (BOOL)windowShouldClose:(NSWindow *)sender {
  if (self.formIndex == 0) [NSApp terminate:nil];
  else [sender orderOut:nil];
  return NO;
}
@end

static void RefreshUI() {
  gRefreshing = true;
${refresh}
  gRefreshing = false;
}

static NSWindow *CreatePatchForm(int index) {
  NSRect rect = NSMakeRect(0, 0, FORMS[index].width, FORMS[index].height);
  NSWindowStyleMask style = NSWindowStyleMaskTitled | NSWindowStyleMaskClosable | NSWindowStyleMaskMiniaturizable | NSWindowStyleMaskResizable;
  NSWindow *window = [[NSWindow alloc] initWithContentRect:rect styleMask:style backing:NSBackingStoreBuffered defer:NO];
  window.title = FORMS[index].title;
  [window center];
  gForms[index] = window;
  PatchWindowDelegate *delegate = [PatchWindowDelegate new];
  delegate.formIndex = index;
  [gFormDelegates addObject:delegate];
  window.delegate = delegate;
${create}
  return window;
}

static bool HasArg(int argc, const char *argv[], const char *value) {
  for (int i = 1; i < argc; ++i) if (strcmp(argv[i], value) == 0) return true;
  return false;
}

${smoke}

int main(int argc, const char *argv[]) {
  @autoreleasepool {
    [NSApplication sharedApplication];
    [NSApp setActivationPolicy:NSApplicationActivationPolicyRegular];
    gEventTarget = [PatchEventTarget new];
    gFormDelegates = [NSMutableArray arrayWithCapacity:FORM_COUNT];
    for (int i = 0; i < FORM_COUNT; ++i) if (!CreatePatchForm(i)) return 10 + i;
    RefreshUI();
    for (int i = 0; i < FORM_COUNT; ++i) if (FORMS[i].visible) [gForms[i] makeKeyAndOrderFront:nil];
    [NSApp finishLaunching];
    if (HasArg(argc, argv, "--patch-smoke")) return RunPatchSmoke();
    [NSApp activateIgnoringOtherApps:YES];
    [NSApp run];
  }
  return 0;
}
`;
}

function validateReferences(ir, forms, controls) {
  for (const event of ir.events) {
    if (!controls.has(event.control)) throw new NativeGuiError(`AppKit event control '${event.control}' is missing.`);
    for (const action of event.actions ?? []) {
      if ((action.kind === 'openForm' || action.kind === 'closeForm') && !forms.has(action.form)) throw new NativeGuiError(`AppKit Form '${action.form}' is missing.`);
    }
  }
}
function stateDeclaration(state) {
  const name = stateName(state.name);
  if (state.type === 'boolean') return `static bool ${name} = ${state.initial ? 'true' : 'false'};`;
  if (state.type === 'number') return `static double ${name} = ${Number(state.initial)};`;
  if (state.type === 'text') return `static NSString *${name} = ${objcLiteral(state.initial)};`;
  throw new NativeGuiError(`AppKit state type '${state.type}' is unsupported.`);
}
function emitControlTextFunction(control, index, states) {
  const text = String(control.text ?? '');
  const lines = ['  NSMutableString *out = [NSMutableString string];'];
  let cursor = 0;
  const re = /\{([A-Za-z_]\w*)\}/g;
  let match;
  while ((match = re.exec(text))) {
    if (match.index > cursor) lines.push(`  [out appendString:${objcLiteral(text.slice(cursor, match.index))}];`);
    const state = states.get(match[1]);
    if (!state) throw new NativeGuiError(`AppKit text '${text}' refers to unknown state '${match[1]}'.`);
    if (state.type === 'boolean') lines.push(`  [out appendString:PatchBoolean(${stateName(state.name)})];`);
    else if (state.type === 'number') lines.push(`  [out appendString:PatchNumber(${stateName(state.name)})];`);
    else lines.push(`  [out appendString:${stateName(state.name)}];`);
    cursor = match.index + match[0].length;
  }
  if (cursor < text.length) lines.push(`  [out appendString:${objcLiteral(text.slice(cursor))}];`);
  lines.push('  return out;');
  return `static NSString *ControlText_${index}() {\n${lines.join('\n')}\n}`;
}
function emitEventFunction(event, index, forms, states) {
  const param = event.valueType === 'boolean' ? 'bool eventValue' : event.valueType === 'text' ? 'NSString *eventValue' : '';
  const actions = (event.actions ?? []).map(action => emitAction(action, event, forms, states)).join('\n');
  return `static void Event_${index}(${param}) {\n${actions || '  // no-op'}\n  RefreshUI();\n}`;
}
function emitAction(action, event, forms, states) {
  if (action.kind === 'openForm') return `  [gForms[${forms.get(action.form)}] makeKeyAndOrderFront:nil];`;
  if (action.kind === 'closeForm') return `  [gForms[${forms.get(action.form)}] orderOut:nil];`;
  if (action.kind !== 'change') throw new NativeGuiError(`AppKit action '${action.kind}' is unsupported.`);
  const state = states.get(action.target);
  if (!state) throw new NativeGuiError(`AppKit change target '${action.target}' is missing.`);
  return (action.ops ?? []).map(op => emitOperation(state, op, event)).join('\n');
}
function emitOperation(state, op, event) {
  const target = stateName(state.name);
  if (op.op === 'clear') {
    if (state.type === 'boolean') return `  ${target} = false;`;
    if (state.type === 'number') return `  ${target} = 0.0;`;
    return `  ${target} = @"";`;
  }
  const value = emitNativeValue(state, op.value, event);
  if (op.op === 'set') return `  ${target} = ${value};`;
  if (op.op === 'add' && state.type === 'number') return `  ${target} += ${value};`;
  if (op.op === 'remove' && state.type === 'number') return `  ${target} -= ${value};`;
  if (op.op === 'add' && state.type === 'text') return `  ${target} = [${target} stringByAppendingString:${value}];`;
  throw new NativeGuiError(`AppKit native GUI cannot apply '${op.op}' to ${state.type} state '${state.name}'.`);
}
function emitNativeValue(state, value, event) {
  if (value?.kind === 'eventValue') {
    if (state.type !== event.valueType) throw new NativeGuiError(`AppKit event value type ${event.valueType ?? 'none'} cannot be assigned to ${state.type} state '${state.name}'.`);
    return state.type === 'text' ? '[eventValue copy]' : 'eventValue';
  }
  if (state.type === 'boolean') return value?.value ? 'true' : 'false';
  if (state.type === 'number') return String(Number(value?.value));
  if (state.type === 'text') return objcLiteral(value?.value);
  throw new NativeGuiError(`AppKit literal type '${state.type}' is unsupported.`);
}
function emitActionDispatch(event, index, controls) {
  const control = controls.get(event.control);
  if (!control || !['button', 'checkbox', 'combo', 'listbox', 'radio'].includes(control.type)) return '';
  if (event.valueType === 'boolean') return `  if (commandId == ${control.commandId}) { Event_${index}([(NSButton *)sender state] == NSControlStateValueOn); return; }`;
  if (control.type === 'combo' && event.valueType === 'text') return `  if (commandId == ${control.commandId}) { Event_${index}([(NSPopUpButton *)sender titleOfSelectedItem] ?: @""); return; }`;
  if (control.type === 'listbox' && event.valueType === 'text') return `  if (commandId == ${control.commandId}) { NSInteger row = [(NSTableView *)sender selectedRow]; Event_${index}(row >= 0 ? PatchListOptionValue(commandId, row) : @""); return; }`;
  if (control.type === 'radio' && event.valueType === 'text') return `  if (commandId == ${control.commandId}) { for (NSButton *item in gRadioItems[${control.handleIndex}]) item.state = (item == sender) ? NSControlStateValueOn : NSControlStateValueOff; Event_${index}([(NSButton *)sender title] ?: @""); return; }`;
  return `  if (commandId == ${control.commandId}) { Event_${index}(); return; }`;
}
function emitInputDispatch(event, index, controls) {
  const control = controls.get(event.control);
  return control?.type === 'input' ? `  if (commandId == ${control.commandId}) { Event_${index}([field stringValue]); return; }` : '';
}
function emitRefresh(control, index, states) {
  if (control.type === 'tabs') return '';
  if (control.type === 'text' || control.type === 'button') return `  if (gControls[${index}]) SetStringIfDifferent((NSControl *)gControls[${index}], ControlText_${index}());`;
  if (control.type === 'checkbox') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) { SetStringIfDifferent((NSControl *)gControls[${index}], ControlText_${index}()); [(NSButton *)gControls[${index}] setState:${stateName(state.name)} ? NSControlStateValueOn : NSControlStateValueOff]; }`;
  }
  if (control.type === 'input') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) SetStringIfDifferent((NSControl *)gControls[${index}], ${stateName(state.name)});`;
  }
  if (control.type === 'combo') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) [(NSPopUpButton *)gControls[${index}] selectItemWithTitle:${stateName(state.name)}];`;
  }
  if (control.type === 'listbox') {
    const state = states.get(control.binding);
    const checks = control.options.map((option, optionIndex) => `if ([${stateName(state.name)} isEqualToString:${objcLiteral(option)}]) selected = ${optionIndex};`).join(' else ');
    return `  if (gControls[${index}]) { NSInteger selected = -1; ${checks} if (selected >= 0) [(NSTableView *)gControls[${index}] selectRowIndexes:[NSIndexSet indexSetWithIndex:(NSUInteger)selected] byExtendingSelection:NO]; else [(NSTableView *)gControls[${index}] deselectAll:nil]; }`;
  }
  if (control.type === 'radio') {
    const state = states.get(control.binding);
    return `  SetRadioSelection(${index}, ${stateName(state.name)});`;
  }
  return '';
}
function emitCreateControl(control, index, form, controls) {
  const width = positiveInt(control.layout?.width, 120);
  const height = positiveInt(control.layout?.height, 36);
  const rect = appKitRect(control, form, controls);
  if (control.type === 'tabs') {
    const pageHeight = Math.max(1, height - 30);
    const pages = control.pageTitles.map(title =>
      `    { NSTabViewItem *item = [[NSTabViewItem alloc] initWithIdentifier:nil]; item.label = ${objcLiteral(title)}; NSView *pageView = [[NSView alloc] initWithFrame:NSMakeRect(0, 0, ${width}, ${pageHeight})]; item.view = pageView; [control addTabViewItem:item]; [gTabPages[${index}] addObject:pageView]; }`
    ).join('\n');
    return `  if (${control.formIndex} == index) {\n    NSTabView *control = [[NSTabView alloc] initWithFrame:${rect}]; gTabPages[${index}] = [NSMutableArray arrayWithCapacity:${control.pageTitles.length}];\n${pages}\n    [control selectTabViewItemAtIndex:0]; gControls[${index}] = control; [window.contentView addSubview:control];\n  }`;
  }
  const target = control.parentTabIndex >= 0
    ? `(NSView *)[gTabPages[${control.parentTabIndex}] objectAtIndex:${control.pageIndex}]`
    : 'window.contentView';
  if (control.type === 'text') return `  if (${control.formIndex} == index) {\n    NSTextField *control = [[NSTextField alloc] initWithFrame:${rect}]; control.editable = NO; control.selectable = NO; control.bezeled = NO; control.drawsBackground = NO; gControls[${index}] = control; [${target} addSubview:control];\n  }`;
  if (control.type === 'input') return `  if (${control.formIndex} == index) {\n    NSTextField *control = [[NSTextField alloc] initWithFrame:${rect}]; control.tag = ${control.commandId}; control.delegate = gEventTarget; gControls[${index}] = control; [${target} addSubview:control];\n  }`;
  if (control.type === 'combo') {
    const options = control.options.map(objcLiteral).join(', ');
    return `  if (${control.formIndex} == index) {\n    NSPopUpButton *control = [[NSPopUpButton alloc] initWithFrame:${rect} pullsDown:NO]; [control addItemsWithTitles:@[${options}]]; control.tag = ${control.commandId}; control.target = gEventTarget; control.action = @selector(handleControl:); gControls[${index}] = control; [${target} addSubview:control];\n  }`;
  }
  if (control.type === 'listbox') return `  if (${control.formIndex} == index) {\n    NSScrollView *scroll = [[NSScrollView alloc] initWithFrame:${rect}]; scroll.hasVerticalScroller = YES; scroll.autohidesScrollers = YES; scroll.borderType = NSBezelBorder; NSTableView *control = [[NSTableView alloc] initWithFrame:NSMakeRect(0, 0, ${width}, ${height})]; NSTableColumn *column = [[NSTableColumn alloc] initWithIdentifier:@"value"]; column.width = ${width}; [control addTableColumn:column]; control.headerView = nil; control.allowsMultipleSelection = NO; control.allowsEmptySelection = YES; control.tag = ${control.commandId}; control.dataSource = gEventTarget; control.delegate = gEventTarget; scroll.documentView = control; gControls[${index}] = control; [${target} addSubview:scroll];\n  }`;
  if (control.type === 'radio') {
    const count = Math.max(1, control.options.length);
    const itemHeight = Math.max(22, Math.min(30, Math.floor(height / count) || 26));
    const items = control.options.map((option, optionIndex) =>
      `    { NSButton *item = [[NSButton alloc] initWithFrame:NSMakeRect(groupRect.origin.x, groupRect.origin.y + ${count - 1 - optionIndex} * ${itemHeight}, groupRect.size.width, ${itemHeight})]; item.buttonType = NSButtonTypeRadio; item.title = ${objcLiteral(option)}; item.tag = ${control.commandId}; item.target = gEventTarget; item.action = @selector(handleControl:); [gRadioItems[${index}] addObject:item]; if (!gControls[${index}]) gControls[${index}] = item; [${target} addSubview:item]; }`
    ).join('\n');
    return `  if (${control.formIndex} == index) {\n    NSRect groupRect = ${rect}; gRadioItems[${index}] = [NSMutableArray arrayWithCapacity:${count}];\n${items}\n  }`;
  }
  const buttonType = control.type === 'checkbox' ? 'NSButtonTypeSwitch' : 'NSButtonTypeMomentaryPushIn';
  const bezel = control.type === 'button' ? 'control.bezelStyle = NSBezelStyleRounded;' : '';
  return `  if (${control.formIndex} == index) {\n    NSButton *control = [[NSButton alloc] initWithFrame:${rect}]; control.buttonType = ${buttonType}; ${bezel} control.tag = ${control.commandId}; control.target = gEventTarget; control.action = @selector(handleControl:); gControls[${index}] = control; [${target} addSubview:control];\n  }`;
}
function appKitRect(control, form, controls) {
  const width = positiveInt(control.layout?.width, 120);
  const height = positiveInt(control.layout?.height, 36);
  const x = layoutInt(control.layout?.x, control.parentTabIndex >= 0 ? 12 : 24);
  const sourceY = layoutInt(control.layout?.y, control.parentTabIndex >= 0 ? 12 : 24);
  if (control.parentTabIndex < 0) {
    const y = Math.max(0, positiveInt(form.height, 420) - sourceY - height);
    return `NSMakeRect(${x}, ${y}, ${width}, ${height})`;
  }
  const tab = controls[control.parentTabIndex];
  if (!tab || tab.type !== 'tabs') throw new NativeGuiError(`AppKit child control '${control.id}' has an invalid Tabs parent.`);
  const pageHeight = Math.max(1, positiveInt(tab.layout?.height, 240) - 30);
  const y = Math.max(0, pageHeight - sourceY - height);
  return `NSMakeRect(${x}, ${y}, ${width}, ${height})`;
}
function emitSmoke(forms, controls, states) {
  const mainIndex = forms.has('main') ? forms.get('main') : 0;
  const settingsIndex = forms.get('settings');
  const open = controls.get('open_settings');
  const close = controls.get('close_settings');
  const checkbox = controls.get('notifications');
  const checkboxState = states.get('notifications');
  const combo = controls.get('size');
  const comboState = states.get('size');
  const listbox = controls.get('fruit');
  const listboxState = states.get('fruit');
  const radio = controls.get('mode');
  const radioState = states.get('mode');
  const tabs = controls.get('settings');
  const lines = ['static int RunPatchSmoke() {', `  if (!gForms[${mainIndex}] || !gForms[${mainIndex}].visible) return 70;`];
  if (settingsIndex !== undefined) lines.push(`  if (gForms[${settingsIndex}].visible) return 71;`);
  if (open && settingsIndex !== undefined) { lines.push(`  [(NSButton *)gControls[${open.handleIndex}] performClick:nil];`); lines.push(`  if (!gForms[${settingsIndex}].visible) return 72;`); }
  if (checkbox && checkboxState?.type === 'boolean') { lines.push(`  [(NSButton *)gControls[${checkbox.handleIndex}] performClick:nil];`); lines.push(`  if (!${stateName(checkboxState.name)}) return 73;`); }
  if (combo && comboState?.type === 'text' && combo.options.length) { const last = combo.options.length - 1; lines.push(`  [(NSPopUpButton *)gControls[${combo.handleIndex}] selectItemAtIndex:${last}];`); lines.push(`  [gEventTarget handleControl:gControls[${combo.handleIndex}]];`); lines.push(`  if (![${stateName(comboState.name)} isEqualToString:${objcLiteral(combo.options[last])}]) return 75;`); }
  if (listbox && listboxState?.type === 'text' && listbox.options.length) { const last = listbox.options.length - 1; lines.push(`  [(NSTableView *)gControls[${listbox.handleIndex}] selectRowIndexes:[NSIndexSet indexSetWithIndex:${last}] byExtendingSelection:NO];`); lines.push(`  [gEventTarget handleControl:gControls[${listbox.handleIndex}]];`); lines.push(`  if (![${stateName(listboxState.name)} isEqualToString:${objcLiteral(listbox.options[last])}]) return 76;`); }
  if (radio && radioState?.type === 'text' && radio.options.length) { const last = radio.options.length - 1; lines.push(`  if ([gRadioItems[${radio.handleIndex}] count] != ${radio.options.length}) return 81;`); lines.push(`  [(NSButton *)[gRadioItems[${radio.handleIndex}] objectAtIndex:${last}] performClick:nil];`); lines.push(`  if (![${stateName(radioState.name)} isEqualToString:${objcLiteral(radio.options[last])}]) return 82;`); }
  if (tabs?.type === 'tabs' && tabs.pageTitles.length > 1) {
    lines.push(`  if ([(NSTabView *)gControls[${tabs.handleIndex}] numberOfTabViewItems] != ${tabs.pageTitles.length}) return 77;`);
    lines.push(`  [(NSTabView *)gControls[${tabs.handleIndex}] selectTabViewItemAtIndex:1];`);
    lines.push(`  if (![[[(NSTabView *)gControls[${tabs.handleIndex}] selectedTabViewItem] label] isEqualToString:${objcLiteral(tabs.pageTitles[1])}]) return 78;`);
  }
  if (close && settingsIndex !== undefined) { lines.push(`  [(NSButton *)gControls[${close.handleIndex}] performClick:nil];`); lines.push(`  if (gForms[${settingsIndex}].visible) return 74;`); }
  lines.push('  [NSApp stop:nil];', '  return 0;', '}');
  return lines.join('\n');
}
function controlKind(type) { return ({ text: 'CK_TEXT', button: 'CK_BUTTON', input: 'CK_INPUT', checkbox: 'CK_CHECKBOX', combo: 'CK_COMBO', listbox: 'CK_LISTBOX', tabs: 'CK_TABS', radio: 'CK_RADIO' })[type] ?? 'CK_TEXT'; }
function stateName(name) { return `patch_state_${identifier(name)}`; }
function identifier(value) { return String(value).replace(/[^A-Za-z0-9_]/g, '_').replace(/^[0-9]/, '_$&'); }
function layoutInt(value, fallback) { return Number.isFinite(Number(value)) ? Math.max(0, Math.round(Number(value))) : fallback; }
function positiveInt(value, fallback) { return Number.isFinite(Number(value)) ? Math.max(1, Math.round(Number(value))) : fallback; }
function objcLiteral(value) { return `@${JSON.stringify(String(value ?? ''))}`; }
