import { NativeGuiError } from './native-gui-ir.js';
import { emitAppKitGuiObjCppV09 } from './appkit-gui-v09.js';
import { adaptNativeMenusForLegacyBackend } from './native-menu-backend-adapter.js';

export const PATCH_APPKIT_GUI_BACKEND_V10_VERSION = '1.0';

/** Emit AppKit backend 1.0 with NSMenu separators and portable shortcuts. */
export function emitAppKitGuiObjCppV10(input) {
  const adapted = adaptNativeMenusForLegacyBackend(input);
  let source = emitAppKitGuiObjCppV09(adapted.legacyIr)
    .replace(/Generated by Patch AppKit GUI backend 0\.9\./, `Generated by Patch AppKit GUI backend ${PATCH_APPKIT_GUI_BACKEND_V10_VERSION}.`);

  for (const entry of adapted.separators) {
    source = replaceRequired(
      source,
      appKitMenuBlock(entry, '@""', ''),
      `[menu_${entry.formIndex}_${entry.menuIndex} addItem:[NSMenuItem separatorItem]];`,
      `AppKit Menu separator ${entry.formIndex + 1}/${entry.menuIndex + 1}/${entry.itemIndex + 1}`
    );
  }

  for (const entry of adapted.shortcuts) {
    const keyEquivalent = appKitKeyEquivalent(entry.shortcut.key);
    const modifier = appKitModifiers(entry.shortcut);
    source = replaceRequired(
      source,
      appKitMenuBlock(entry, '@""', ''),
      appKitMenuBlock(entry, keyEquivalent, ` entry.keyEquivalentModifierMask = ${modifier};`),
      `AppKit Menu shortcut '${entry.id}'`
    );
  }

  return source;
}

function appKitMenuBlock(entry, keyEquivalent, extra) {
  return `{ NSMenuItem *entry = [[NSMenuItem alloc] initWithTitle:${objcLiteral(entry.legacyText)} action:@selector(handleControl:) keyEquivalent:${keyEquivalent}]; entry.tag = ${entry.commandId}; entry.target = gEventTarget;${extra} [menu_${entry.formIndex}_${entry.menuIndex} addItem:entry]; gMenuItems[${entry.legacyNativeIndex}] = entry; }`;
}

function appKitKeyEquivalent(key) {
  if (/^[A-Z]$/.test(key)) return objcLiteral(key.toLowerCase());
  if (/^[0-9]$/.test(key)) return objcLiteral(key);
  if (/^F(?:[1-9]|1[0-2])$/.test(key)) return `[NSString stringWithFormat:@"%C", NS${key.slice(1)}FunctionKey]`;
  throw new NativeGuiError(`AppKit shortcut key '${key}' is unsupported.`);
}

function appKitModifiers(shortcut) {
  const flags = [];
  if (shortcut.primary) flags.push('NSEventModifierFlagCommand');
  if (shortcut.shift) flags.push('NSEventModifierFlagShift');
  if (shortcut.alt) flags.push('NSEventModifierFlagOption');
  return flags.length ? flags.join(' | ') : '0';
}

function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated AppKit source.`);
  return source.replace(marker, replacement);
}

function objcLiteral(value) { return `@${JSON.stringify(String(value ?? ''))}`; }
