import { emitAppKitGuiObjCpp as emitAppKitGuiObjCppV08 } from './appkit-gui-v08.js';
import { adaptNativeTablesForLegacyBackend, tableEventIndexById } from './native-table-backend-adapter.js';
import { applyAppKitTableOverlayV09 } from './appkit-table-overlay-v09.js';

export const PATCH_APPKIT_GUI_BACKEND_V09_VERSION = '0.9';

/** Emit AppKit backend v0.9 with real multi-column NSTableView Tables. */
export function emitAppKitGuiObjCppV09(input) {
  const adapted = adaptNativeTablesForLegacyBackend(input);
  let source = emitAppKitGuiObjCppV08(adapted.legacyIr)
    .replace(/Generated by Patch AppKit GUI backend 0\.8\./, `Generated by Patch AppKit GUI backend ${PATCH_APPKIT_GUI_BACKEND_V09_VERSION}.`);
  if (!adapted.tables.length) return source;
  return applyAppKitTableOverlayV09(source, adapted, tableEventIndexById(adapted.ir));
}
