import { validateNativeGuiIR, NativeGuiError } from './native-gui-ir.js';

export const PATCH_APPKIT_GUI_BACKEND_VERSION = '0.2';

export function emitAppKitGuiObjCpp(input) {
  const ir = validateNativeGuiIR(input);
  const formIndex = new Map(ir.forms.map((form, index) => [form.id, index]));
  const controlRecords = [];
  let nextCommandId = 1000;

  for (let f = 0; f < ir.forms.length; f++) {
    for (const control of ir.forms[f].controls) {
      controlRecords.push({ ...control, formIndex: f, commandId: nextCommandId++, handleIndex: controlRecords.length });
    }
  }

  const controlById = new Map(controlRecords.filter(control => control.id).map(control => [control.id, control]));
  const stateByName = new Map(ir.states.map(state => [state.name, state]));
  for (const event of ir.events) {
    if (!controlById.has(event.control)) throw new NativeGuiError(`AppKit event control '${event.control}' is missing.`);
    for (const action of event.actions) {
      if ((action.kind === 'openForm' || action.kind === 'closeForm') && !formIndex.has(action.form)) {
        throw new NativeGuiError(`AppKit Form '${action.form}' is missing.`);
      }
    }
  }

  const stateDecls = ir.states.map(stateDeclaration).join('\n');
  const formDefs = ir.forms.map((form, index) =>
    `  {${objcLiteral(form.id)}, ${objcLiteral(form.title)}, ${positiveInt(form.width, 640)}, ${positiveInt(form.height, 420)}, ${form.visible ? 'true' : 'false'}}${index + 1 === ir.forms.length ? '' : ','}`
  ).join('\n');
  const controlDefs = controlRecords.map((control, index) =>
    `  {${control.commandId}, ${control.formIndex}, ${controlKind(control.type)}, ${objcLiteral(control.id ?? '')}, ${layoutInt(control.layout?.x, 24)}, ${layoutInt(control.layout?.y, 24)}, ${positiveInt(control.layout?.width, 120)}, ${positiveInt(control.layout?.height, 36)}}${index + 1 === controlRecords.length ? '' : ','}`
  ).join('\n');
  const textFunctions = controlRecords.map((control, index) => emitControlTextFunction(control, index, stateByName)).join('\n\n');
  const eventFunctions = ir.events.map((event, index) => emitEventFunction(event, index, formIndex, stateByName)).join('\n\n');
  const actionDispatch = ir.events.map((event, index) => emitActionDispatch(event, index, controlById)).filter(Boolean).join('\n');
  const inputDispatch = ir.events.map((event, index) => emitInputDispatch(event, index, controlById)).filter(Boolean).join('\n');
  const refreshCases = controlRecords.map((control, index) => emitRefresh(control, index, stateByName)).join('\n');
  const createCases = controlRecords.map((control, index) => emitCreateControl(control, index, ir.forms[control.formIndex])).join('\n');
  const smoke = emitSmoke(formIndex, controlById, stateByName);

  return `// Generated by Patch AppKit GUI backend ${PATCH_APPKIT_GUI_BACKEND_VERSION}.\n// Direct native AppKit controls: no Electron/Chromium runtime.\n#import <Cocoa/Cocoa.h>\n#include <cmath>\n#include <cstring>\n\nstatic bool gRefreshing = false;\n\nenum ControlKind { CK_TEXT=1, CK_BUTTON=2, CK_INPUT=3, CK_CHECKBOX=4, CK_COMBO=5 };\nstruct FormDef { NSString *formId; NSString *title; int width; int height; bool visible; };\nstruct ControlDef { NSInteger commandId; int formIndex; ControlKind kind; NSString *name; int x; int y; int width; int height; };\n\n${stateDecls}\n\nstatic const FormDef FORMS[] = {\n${formDefs}\n};\nstatic const int FORM_COUNT = ${ir.forms.length};\nstatic NSWindow *gForms[${Math.max(1, ir.forms.length)}] = {};\nstatic NSMutableArray *gFormDelegates = nil;\n\nstatic const ControlDef CONTROLS[] = {\n${controlDefs || '  {0,0,CK_TEXT,@"",0,0,0,0}'}\n};\nstatic const int CONTROL_COUNT = ${controlRecords.length};\nstatic NSControl *gControls[${Math.max(1, controlRecords.length)}] = {};\n\nstatic NSString *PatchNumber(double value) {\n  if (std::isfinite(value) && std::floor(value) == value) return [NSString stringWithFormat:@"%lld", (long long)value];\n  return [NSString stringWithFormat:@"%.15g", value];\n}\nstatic NSString *PatchBoolean(bool value) { return value ? @"true" : @"false"; }\nstatic void SetStringIfDifferent(NSControl *control, NSString *value) {\n  if (![control.stringValue isEqualToString:value]) control.stringValue = value;\n}\n\n${textFunctions}\n\nstatic void RefreshUI();\n\n${eventFunctions}\n\n@interface PatchEventTarget : NSObject <NSTextFieldDelegate>\n- (void)handleControl:(id)sender;\n@end\n\n@implementation PatchEventTarget\n- (void)handleControl:(id)sender {\n  if (gRefreshing) return;\n  NSInteger commandId = [sender tag];\n${actionDispatch || '  (void)commandId;'}\n}\n- (void)controlTextDidChange:(NSNotification *)notification {\n  if (gRefreshing) return;\n  NSTextField *field = (NSTextField *)notification.object;\n  NSInteger commandId = field.tag;\n${inputDispatch || '  (void)commandId;'}\n}\n@end\n\nstatic PatchEventTarget *gEventTarget = nil;\n\n@interface PatchWindowDelegate : NSObject <NSWindowDelegate>\n@property(nonatomic) NSInteger formIndex;\n@end\n\n@implementation PatchWindowDelegate\n- (BOOL)windowShouldClose:(NSWindow *)sender {\n  if (self.formIndex == 0) [NSApp terminate:nil];\n  else [sender orderOut:nil];\n  return NO;\n}\n@end\n\nstatic void RefreshUI() {\n  gRefreshing = true;\n${refreshCases}\n  gRefreshing = false;\n}\n\nstatic NSWindow *CreatePatchForm(int index) {\n  NSRect rect = NSMakeRect(0, 0, FORMS[index].width, FORMS[index].height);\n  NSWindowStyleMask style = NSWindowStyleMaskTitled | NSWindowStyleMaskClosable | NSWindowStyleMaskMiniaturizable | NSWindowStyleMaskResizable;\n  NSWindow *window = [[NSWindow alloc] initWithContentRect:rect styleMask:style backing:NSBackingStoreBuffered defer:NO];\n  window.title = FORMS[index].title;\n  [window center];\n  gForms[index] = window;\n  PatchWindowDelegate *delegate = [PatchWindowDelegate new];\n  delegate.formIndex = index;\n  [gFormDelegates addObject:delegate];\n  window.delegate = delegate;\n${createCases}\n  return window;\n}\n\nstatic bool HasArg(int argc, const char *argv[], const char *value) {\n  for (int i = 1; i < argc; ++i) if (strcmp(argv[i], value) == 0) return true;\n  return false;\n}\n\n${smoke}\n\nint main(int argc, const char *argv[]) {\n  @autoreleasepool {\n    [NSApplication sharedApplication];\n    [NSApp setActivationPolicy:NSApplicationActivationPolicyRegular];\n    gEventTarget = [PatchEventTarget new];\n    gFormDelegates = [NSMutableArray arrayWithCapacity:FORM_COUNT];\n    for (int i = 0; i < FORM_COUNT; ++i) {\n      if (!CreatePatchForm(i)) return 10 + i;\n    }\n    RefreshUI();\n    for (int i = 0; i < FORM_COUNT; ++i) {\n      if (FORMS[i].visible) [gForms[i] makeKeyAndOrderFront:nil];\n    }\n    [NSApp finishLaunching];\n    if (HasArg(argc, argv, "--patch-smoke")) return RunPatchSmoke();\n    [NSApp activateIgnoringOtherApps:YES];\n    [NSApp run];\n  }\n  return 0;\n}\n`;
}

function stateDeclaration(state) {
  const name = stateName(state.name);
  if (state.type === 'boolean') return `static bool ${name} = ${state.initial ? 'true' : 'false'};`;
  if (state.type === 'number') return `static double ${name} = ${Number(state.initial)};`;
  if (state.type === 'text') return `static NSString *${name} = ${objcLiteral(state.initial)};`;
  throw new NativeGuiError(`AppKit state type '${state.type}' is unsupported.`);
}

function emitControlTextFunction(control, index, states) {
  const text = String(control.text ?? '');
  const lines = ['  NSMutableString *out = [NSMutableString string];'];
  let cursor = 0;
  const re = /\{([A-Za-z_]\w*)\}/g;
  let match;
  while ((match = re.exec(text))) {
    if (match.index > cursor) lines.push(`  [out appendString:${objcLiteral(text.slice(cursor, match.index))}];`);
    const state = states.get(match[1]);
    if (!state) throw new NativeGuiError(`AppKit text '${text}' refers to unknown state '${match[1]}'.`);
    if (state.type === 'boolean') lines.push(`  [out appendString:PatchBoolean(${stateName(state.name)})];`);
    else if (state.type === 'number') lines.push(`  [out appendString:PatchNumber(${stateName(state.name)})];`);
    else lines.push(`  [out appendString:${stateName(state.name)}];`);
    cursor = match.index + match[0].length;
  }
  if (cursor < text.length) lines.push(`  [out appendString:${objcLiteral(text.slice(cursor))}];`);
  if (text.length === 0) lines.push('  [out appendString:@""];');
  lines.push('  return out;');
  return `static NSString *ControlText_${index}() {\n${lines.join('\n')}\n}`;
}

function emitEventFunction(event, index, forms, states) {
  const param = event.valueType === 'boolean' ? 'bool eventValue' : event.valueType === 'text' ? 'NSString *eventValue' : '';
  const actions = event.actions.map(action => emitAction(action, event, forms, states)).join('\n');
  return `static void Event_${index}(${param}) {\n${actions || '  // no-op'}\n  RefreshUI();\n}`;
}

function emitAction(action, event, forms, states) {
  if (action.kind === 'openForm') return `  [gForms[${forms.get(action.form)}] makeKeyAndOrderFront:nil];`;
  if (action.kind === 'closeForm') return `  [gForms[${forms.get(action.form)}] orderOut:nil];`;
  if (action.kind !== 'change') throw new NativeGuiError(`AppKit action '${action.kind}' is unsupported.`);
  const state = states.get(action.target);
  if (!state) throw new NativeGuiError(`AppKit change target '${action.target}' is missing.`);
  return action.ops.map(op => emitOperation(state, op, event)).join('\n');
}

function emitOperation(state, op, event) {
  const target = stateName(state.name);
  if (op.op === 'clear') {
    if (state.type === 'boolean') return `  ${target} = false;`;
    if (state.type === 'number') return `  ${target} = 0.0;`;
    if (state.type === 'text') return `  ${target} = @"";`;
  }
  const value = emitNativeValue(state, op.value, event);
  if (op.op === 'set') return `  ${target} = ${value};`;
  if (op.op === 'add' && state.type === 'number') return `  ${target} += ${value};`;
  if (op.op === 'remove' && state.type === 'number') return `  ${target} -= ${value};`;
  if (op.op === 'add' && state.type === 'text') return `  ${target} = [${target} stringByAppendingString:${value}];`;
  throw new NativeGuiError(`AppKit native GUI cannot apply '${op.op}' to ${state.type} state '${state.name}'.`);
}

function emitNativeValue(state, value, event) {
  if (value?.kind === 'eventValue') {
    if (state.type !== event.valueType) throw new NativeGuiError(`AppKit event value type ${event.valueType ?? 'none'} cannot be assigned to ${state.type} state '${state.name}'.`);
    return state.type === 'text' ? '[eventValue copy]' : 'eventValue';
  }
  const literal = value?.value;
  if (state.type === 'boolean') return literal ? 'true' : 'false';
  if (state.type === 'number') return String(Number(literal));
  if (state.type === 'text') return objcLiteral(literal);
  throw new NativeGuiError(`AppKit literal type '${state.type}' is unsupported.`);
}

function emitActionDispatch(event, index, controls) {
  const control = controls.get(event.control);
  if (!control || !['button', 'checkbox', 'combo'].includes(control.type)) return '';
  if (event.valueType === 'boolean') return `  if (commandId == ${control.commandId}) { Event_${index}([(NSButton *)sender state] == NSControlStateValueOn); return; }`;
  if (control.type === 'combo' && event.valueType === 'text') return `  if (commandId == ${control.commandId}) { Event_${index}([(NSPopUpButton *)sender titleOfSelectedItem] ?: @""); return; }`;
  return `  if (commandId == ${control.commandId}) { Event_${index}(); return; }`;
}

function emitInputDispatch(event, index, controls) {
  const control = controls.get(event.control);
  if (!control || control.type !== 'input') return '';
  return `  if (commandId == ${control.commandId}) { Event_${index}([field stringValue]); return; }`;
}

function emitRefresh(control, index, states) {
  if (control.type === 'text' || control.type === 'button') return `  if (gControls[${index}]) SetStringIfDifferent(gControls[${index}], ControlText_${index}());`;
  if (control.type === 'checkbox') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) { SetStringIfDifferent(gControls[${index}], ControlText_${index}()); [(NSButton *)gControls[${index}] setState:${stateName(state.name)} ? NSControlStateValueOn : NSControlStateValueOff]; }`;
  }
  if (control.type === 'input') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) SetStringIfDifferent(gControls[${index}], ${stateName(state.name)});`;
  }
  if (control.type === 'combo') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) [(NSPopUpButton *)gControls[${index}] selectItemWithTitle:${stateName(state.name)}];`;
  }
  return '';
}

function emitCreateControl(control, index, form) {
  const y = Math.max(0, positiveInt(form.height, 420) - layoutInt(control.layout?.y, 24) - positiveInt(control.layout?.height, 36));
  const rect = `NSMakeRect(${layoutInt(control.layout?.x, 24)}, ${y}, ${positiveInt(control.layout?.width, 120)}, ${positiveInt(control.layout?.height, 36)})`;
  if (control.type === 'text') {
    return `  if (${control.formIndex} == index) {\n    NSTextField *control = [[NSTextField alloc] initWithFrame:${rect}];\n    control.editable = NO; control.selectable = NO; control.bezeled = NO; control.drawsBackground = NO;\n    gControls[${index}] = control;\n    [window.contentView addSubview:control];\n  }`;
  }
  if (control.type === 'input') {
    return `  if (${control.formIndex} == index) {\n    NSTextField *control = [[NSTextField alloc] initWithFrame:${rect}];\n    control.tag = ${control.commandId}; control.delegate = gEventTarget;\n    gControls[${index}] = control;\n    [window.contentView addSubview:control];\n  }`;
  }
  if (control.type === 'combo') {
    const options = control.options.map(objcLiteral).join(', ');
    return `  if (${control.formIndex} == index) {\n    NSPopUpButton *control = [[NSPopUpButton alloc] initWithFrame:${rect} pullsDown:NO];\n    [control addItemsWithTitles:@[${options}]];\n    control.tag = ${control.commandId}; control.target = gEventTarget; control.action = @selector(handleControl:);\n    gControls[${index}] = control;\n    [window.contentView addSubview:control];\n  }`;
  }
  const buttonType = control.type === 'checkbox' ? 'NSButtonTypeSwitch' : 'NSButtonTypeMomentaryPushIn';
  const bezel = control.type === 'button' ? 'control.bezelStyle = NSBezelStyleRounded;' : '';
  return `  if (${control.formIndex} == index) {\n    NSButton *control = [[NSButton alloc] initWithFrame:${rect}];\n    control.buttonType = ${buttonType}; ${bezel}\n    control.tag = ${control.commandId}; control.target = gEventTarget; control.action = @selector(handleControl:);\n    gControls[${index}] = control;\n    [window.contentView addSubview:control];\n  }`;
}

function emitSmoke(forms, controls, states) {
  const mainIndex = forms.has('main') ? forms.get('main') : 0;
  const settingsIndex = forms.get('settings');
  const open = controls.get('open_settings');
  const close = controls.get('close_settings');
  const checkbox = controls.get('notifications');
  const notifications = states.get('notifications');
  const combo = controls.get('size');
  const comboState = states.get('size');
  const lines = ['static int RunPatchSmoke() {', `  if (!gForms[${mainIndex}] || !gForms[${mainIndex}].visible) return 70;`];
  if (settingsIndex !== undefined) lines.push(`  if (gForms[${settingsIndex}].visible) return 71;`);
  if (open && settingsIndex !== undefined) {
    lines.push(`  [(NSButton *)gControls[${open.handleIndex}] performClick:nil];`);
    lines.push(`  if (!gForms[${settingsIndex}].visible) return 72;`);
  }
  if (checkbox && notifications?.type === 'boolean') {
    lines.push(`  [(NSButton *)gControls[${checkbox.handleIndex}] performClick:nil];`);
    lines.push(`  if (!${stateName(notifications.name)}) return 73;`);
  }
  if (combo && comboState?.type === 'text' && combo.options.length) {
    const last = combo.options.length - 1;
    lines.push(`  [(NSPopUpButton *)gControls[${combo.handleIndex}] selectItemAtIndex:${last}];`);
    lines.push(`  [gEventTarget handleControl:gControls[${combo.handleIndex}]];`);
    lines.push(`  if (![${stateName(comboState.name)} isEqualToString:${objcLiteral(combo.options[last])}]) return 75;`);
  }
  if (close && settingsIndex !== undefined) {
    lines.push(`  [(NSButton *)gControls[${close.handleIndex}] performClick:nil];`);
    lines.push(`  if (gForms[${settingsIndex}].visible) return 74;`);
  }
  lines.push('  [NSApp stop:nil];', '  return 0;', '}');
  return lines.join('\n');
}

function controlKind(type) {
  return ({ text: 'CK_TEXT', button: 'CK_BUTTON', input: 'CK_INPUT', checkbox: 'CK_CHECKBOX', combo: 'CK_COMBO' })[type] ?? 'CK_TEXT';
}
function stateName(name) { return `patch_state_${identifier(name)}`; }
function identifier(value) { return String(value).replace(/[^A-Za-z0-9_]/g, '_').replace(/^[0-9]/, '_$&'); }
function layoutInt(value, fallback) { return Number.isFinite(Number(value)) ? Math.max(0, Math.round(Number(value))) : fallback; }
function positiveInt(value, fallback) { return Number.isFinite(Number(value)) ? Math.max(1, Math.round(Number(value))) : fallback; }
function objcLiteral(value) { return `@${JSON.stringify(String(value ?? ''))}`; }
