import { flattenNativeGuiControls, flattenNativeGuiMenuItems, NativeGuiError } from './native-gui-ir.js';
import { emitGtkGuiCpp as emitGtkGuiCppV06 } from './gtk-gui.js';
import {
  planNativeResultDialogs,
  buildAuxiliaryResultIr,
  resultHandlerName,
  resultHandler,
  injectIntoEvent,
  extractEventZero,
  insertAfter,
  insertBefore,
  identifier
} from './native-result-dialog-overlay.js';

export const PATCH_GTK_GUI_BACKEND_VERSION = '0.7';

export function emitGtkGuiCpp(input) {
  const plan = planNativeResultDialogs(input);
  let source = emitGtkGuiCppV06(plan.baseIr)
    .replace(/Generated by Patch GTK GUI backend 0\.6\./, `Generated by Patch GTK GUI backend ${PATCH_GTK_GUI_BACKEND_VERSION}.`);
  if (!plan.triggers.length) return source;

  const resultFunctions = plan.resultEvents.map(event => {
    const aux = buildAuxiliaryResultIr(plan.ir, event);
    return extractEventZero(emitGtkGuiCppV06(aux), resultHandlerName(event.control, event.event));
  }).join('\n\n');

  source = insertBefore(source, 'static void RefreshUI();', `${gtkHelpers()}\n`);
  source = insertAfter(source, 'static void RefreshUI();', `\n\n${resultFunctions}\n`);
  for (const trigger of plan.triggers) source = injectIntoEvent(source, trigger.baseIndex, gtkResultAction(plan, trigger.action));
  return injectSmoke(source, plan);
}

function gtkHelpers() {
  return `static std::string gLastResultSource;\nstatic std::string gLastResultValue;\nstatic int gLastResultEvent = 0;\nstatic bool PatchConfirmDialog(int formIndex, const char *title, const char *message) {\n  if (gSmokeMode) return true;\n  GtkWindow *owner = formIndex >= 0 && formIndex < FORM_COUNT ? GTK_WINDOW(gForms[formIndex]) : nullptr;\n  GtkWidget *dialog = gtk_message_dialog_new(owner, static_cast<GtkDialogFlags>(GTK_DIALOG_MODAL | GTK_DIALOG_DESTROY_WITH_PARENT), GTK_MESSAGE_QUESTION, GTK_BUTTONS_YES_NO, \"%s\", message ? message : \"\");\n  gtk_window_set_title(GTK_WINDOW(dialog), title ? title : \"\");\n  const gint response = gtk_dialog_run(GTK_DIALOG(dialog));\n  gtk_widget_destroy(dialog);\n  return response == GTK_RESPONSE_YES;\n}\nstatic bool PatchFileDialog(int formIndex, const char *title, bool save, std::string& result) {\n  if (gSmokeMode) { result = save ? \"/tmp/patch-saved.patch\" : \"/tmp/patch-opened.patch\"; return true; }\n  GtkWindow *owner = formIndex >= 0 && formIndex < FORM_COUNT ? GTK_WINDOW(gForms[formIndex]) : nullptr;\n  GtkWidget *dialog = gtk_file_chooser_dialog_new(title ? title : \"\", owner, save ? GTK_FILE_CHOOSER_ACTION_SAVE : GTK_FILE_CHOOSER_ACTION_OPEN, \"_Cancel\", GTK_RESPONSE_CANCEL, save ? \"_Save\" : \"_Open\", GTK_RESPONSE_ACCEPT, nullptr);\n  if (save) gtk_file_chooser_set_do_overwrite_confirmation(GTK_FILE_CHOOSER(dialog), TRUE);\n  const gint response = gtk_dialog_run(GTK_DIALOG(dialog));\n  if (response != GTK_RESPONSE_ACCEPT) { gtk_widget_destroy(dialog); return false; }\n  char *filename = gtk_file_chooser_get_filename(GTK_FILE_CHOOSER(dialog));\n  result = filename ? filename : \"\";\n  if (filename) g_free(filename);\n  gtk_widget_destroy(dialog);\n  return true;\n}\n`;
}

function gtkResultAction(plan, action) {
  const formIndex = plan.ir.forms.findIndex(form => form.id === action.form);
  if (formIndex < 0) throw new NativeGuiError(`GTK result dialog Form '${action.form}' is missing.`);
  const confirmed = resultHandler(plan, action.id, 'confirmed');
  const chosen = resultHandler(plan, action.id, 'chosen');
  const cancelled = resultHandler(plan, action.id, 'cancelled');
  const onConfirmed = confirmed ? `${resultHandlerName(action.id, 'confirmed')}();` : '';
  const onChosen = chosen ? `${resultHandlerName(action.id, 'chosen')}(patchResultValue);` : '';
  const onCancelled = cancelled ? `${resultHandlerName(action.id, 'cancelled')}();` : '';

  if (action.kind === 'confirmDialog') {
    return `  {\n    const bool patchAccepted = PatchConfirmDialog(${formIndex}, ${cString(action.title)}, ${cString(action.message)});\n    gLastResultSource = ${cString(action.id)}; gLastResultValue.clear(); gLastResultEvent = patchAccepted ? 3 : 5;\n    if (patchAccepted) { ${onConfirmed} } else { ${onCancelled} }\n  }`;
  }
  const save = action.kind === 'saveFileDialog';
  return `  {\n    std::string patchResultValue;\n    const bool patchChosen = PatchFileDialog(${formIndex}, ${cString(action.title)}, ${save ? 'true' : 'false'}, patchResultValue);\n    gLastResultSource = ${cString(action.id)}; gLastResultValue = patchChosen ? patchResultValue : \"\"; gLastResultEvent = patchChosen ? 4 : 5;\n    if (patchChosen) { ${onChosen} } else { ${onCancelled} }\n  }`;
}

function injectSmoke(source, plan) {
  const controls = new Map(flattenNativeGuiControls(plan.baseIr).filter(control => control.id).map(control => [control.id, control]));
  const menus = new Map(flattenNativeGuiMenuItems(plan.baseIr).map(item => [item.id, item]));
  const checks = [];
  let code = 90;
  for (const trigger of plan.triggers) {
    const control = controls.get(trigger.event.control);
    const menu = menus.get(trigger.event.control);
    if (control?.type === 'button') checks.push(`  gtk_button_clicked(GTK_BUTTON(gControls[${control.nativeIndex}]));`);
    else if (menu) checks.push(`  g_signal_emit_by_name(gMenuItems[${menu.nativeIndex}], \"activate\");`);
    else continue;

    const expectedEvent = trigger.action.kind === 'confirmDialog' ? 3 : 4;
    const expectedValue = trigger.action.kind === 'openFileDialog' ? '/tmp/patch-opened.patch' : trigger.action.kind === 'saveFileDialog' ? '/tmp/patch-saved.patch' : '';
    checks.push(`  if (gLastResultSource != ${cString(trigger.action.id)} || gLastResultEvent != ${expectedEvent}) return ${code++};`);
    if (expectedValue) checks.push(`  if (gLastResultValue != ${cString(expectedValue)}) return ${code++};`);
    const handler = trigger.action.kind === 'confirmDialog'
      ? resultHandler(plan, trigger.action.id, 'confirmed')
      : resultHandler(plan, trigger.action.id, 'chosen');
    const eventValueChange = handler?.actions?.find(action => action.kind === 'change' && action.stateType === 'text' && action.ops?.some(op => op.value?.kind === 'eventValue'));
    if (expectedValue && eventValueChange) checks.push(`  if (patch_state_${identifier(eventValueChange.target)} != ${cString(expectedValue)}) return ${code++};`);
  }
  if (!checks.length) return source;
  const start = source.indexOf('static int RunPatchSmoke() {');
  if (start < 0) throw new NativeGuiError('Generated GTK source is missing RunPatchSmoke.');
  const end = source.indexOf('  return 0;', start);
  if (end < 0) throw new NativeGuiError('Generated GTK smoke has an unexpected shape.');
  return source.slice(0, end) + checks.join('\n') + '\n' + source.slice(end);
}

function cString(value) { return JSON.stringify(String(value ?? '')); }
