import { flattenNativeGuiControls, NativeGuiError } from './native-gui-ir.js';
import { emitGtkGuiCpp as emitGtkGuiCppV07 } from './gtk-gui-v07.js';
import {
  nativeAccessibleName,
  nativeRadioItemAccessibleName,
  needsExplicitNativeAccessibleName
} from './native-accessibility.js';

export const PATCH_GTK_GUI_BACKEND_VERSION = '0.8';

export function emitGtkGuiCpp(input) {
  const controls = flattenNativeGuiControls(input);
  let source = emitGtkGuiCppV07(input)
    .replace(/Generated by Patch GTK GUI backend 0\.7\./, `Generated by Patch GTK GUI backend ${PATCH_GTK_GUI_BACKEND_VERSION}.`);

  source = replaceRequired(source, '#include <gtk/gtk.h>\n', '#include <gtk/gtk.h>\n#include <atk/atk.h>\n', 'GTK accessibility include');
  source = replaceRequired(source, 'static void RefreshUI();', `${gtkAccessibilityHelpers(controls)}\nstatic void RefreshUI();`, 'GTK accessibility helper insertion');
  source = replaceRequired(
    source,
    'for (int i = 0; i < FORM_COUNT; ++i) if (!CreatePatchForm(i)) return 10 + i;\n  RefreshUI();',
    'for (int i = 0; i < FORM_COUNT; ++i) if (!CreatePatchForm(i)) return 10 + i;\n  ApplyPatchAccessibility();\n  RefreshUI();',
    'GTK accessibility application'
  );
  return source;
}

function gtkAccessibilityHelpers(controls) {
  const lines = [];
  for (const control of controls) {
    if (!needsExplicitNativeAccessibleName(control)) continue;
    if (control.type === 'radio') {
      for (let optionIndex = 0; optionIndex < control.options.length; optionIndex += 1) {
        const name = nativeRadioItemAccessibleName(control, control.options[optionIndex]);
        lines.push(`  if (gRadioItems[${control.nativeIndex}].size() > ${optionIndex}) SetPatchAccessibleName(gRadioItems[${control.nativeIndex}][${optionIndex}], ${cString(name)});`);
      }
      continue;
    }
    const name = nativeAccessibleName(control);
    if (!name) continue;
    lines.push(`  SetPatchAccessibleName(gControls[${control.nativeIndex}], ${cString(name)});`);
  }
  return `static void SetPatchAccessibleName(GtkWidget *widget, const char *name) {\n  if (!widget || !name || !*name) return;\n  AtkObject *accessible = gtk_widget_get_accessible(widget);\n  if (accessible) atk_object_set_name(accessible, name);\n}\nstatic void ApplyPatchAccessibility() {\n${lines.join('\n') || '  // Standard GTK control names need no Patch override.'}\n}\n`;
}

function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated GTK source.`);
  return source.replace(marker, replacement);
}

function cString(value) { return JSON.stringify(String(value ?? '')); }
