import { flattenNativeGuiControls, NativeGuiError } from './native-gui-ir.js';
import { emitGtkGuiCpp as emitGtkGuiCppV07 } from './gtk-gui-v07.js';
import {
  nativeAccessibleName,
  nativeRadioItemAccessibleName,
  needsExplicitNativeAccessibleName
} from './native-accessibility.js';

export const PATCH_GTK_GUI_BACKEND_VERSION = '0.8';

export function emitGtkGuiCpp(input) {
  const controls = flattenNativeGuiControls(input);
  let source = emitGtkGuiCppV07(input)
    .replace(/Generated by Patch GTK GUI backend 0\.7\./, `Generated by Patch GTK GUI backend ${PATCH_GTK_GUI_BACKEND_VERSION}.`);

  source = replaceRequired(source, '#include <gtk/gtk.h>\n', '#include <gtk/gtk.h>\n#include <atk/atk.h>\n', 'GTK accessibility include');
  source = replaceRequired(source, 'static void RefreshUI();', `${gtkAccessibilityHelpers(controls)}\n${gtkResponsiveHelpers(input, controls)}\nstatic void RefreshUI();`, 'GTK accessibility/responsive helper insertion');
  if (hasResponsiveLayout(controls)) {
    source = replaceRequired(
      source,
      '  gFixed[index] = fixed;\n',
      '  gFixed[index] = fixed;\n  g_signal_connect(fixed, "size-allocate", G_CALLBACK(OnPatchFormAllocate), GINT_TO_POINTER(index));\n',
      'GTK responsive size-allocate hook'
    );
  }
  source = replaceRequired(
    source,
    'for (int i = 0; i < FORM_COUNT; ++i) if (!CreatePatchForm(i)) return 10 + i;\n  RefreshUI();',
    'for (int i = 0; i < FORM_COUNT; ++i) if (!CreatePatchForm(i)) return 10 + i;\n  ApplyPatchAccessibility();\n  RefreshUI();',
    'GTK accessibility application'
  );
  return injectAccessibilitySmoke(source, controls);
}

function gtkResponsiveHelpers(ir, controls) {
  const responsive = controls.filter(control => control.parentTabIndex < 0 && isResponsive(control));
  if (!responsive.length) return '';
  const blocks = responsive.map(control => emitGtkResponsiveControl(ir, control)).join('\n');
  return `static void ApplyPatchResponsiveLayout(int formIndex, int formWidth, int formHeight) {\n  if (formWidth <= 0 || formHeight <= 0 || formIndex < 0 || formIndex >= FORM_COUNT || !gFixed[formIndex]) return;\n${blocks}\n}\nstatic void OnPatchFormAllocate(GtkWidget *, GtkAllocation *allocation, gpointer data) {\n  if (!allocation) return;\n  ApplyPatchResponsiveLayout(GPOINTER_TO_INT(data), allocation->width, allocation->height);\n}\n`;
}

function emitGtkResponsiveControl(ir, control) {
  const form = ir.forms[control.formIndex];
  const base = control.layout ?? {};
  const policy = base.policy;
  const x = int(base.x, 24), y = int(base.y, 24), width = int(base.width, 120), height = int(base.height, 36);
  const lines = [`  if (formIndex == ${control.formIndex}) {`, `    int x=${x}, y=${y}, width=${width}, height=${height};`, `    const int dw=formWidth-${int(form.width, 640)}, dh=formHeight-${int(form.height, 420)};`];
  if (policy.kind === 'dock') {
    if (policy.side === 'fill') lines.push('    x=0; y=0; width=formWidth; height=formHeight;');
    if (policy.side === 'top') lines.push('    x=0; y=0; width=formWidth;');
    if (policy.side === 'bottom') lines.push('    x=0; y=(formHeight-height>0?formHeight-height:0); width=formWidth;');
    if (policy.side === 'left') lines.push('    x=0; y=0; height=formHeight;');
    if (policy.side === 'right') lines.push('    x=(formWidth-width>0?formWidth-width:0); y=0; height=formHeight;');
  } else if (policy.kind === 'anchor') {
    const edges = new Set(policy.edges ?? []);
    if (edges.has('left') && edges.has('right')) lines.push('    width=(width+dw>16?width+dw:16);');
    else if (!edges.has('left') && edges.has('right')) lines.push('    x=(x+dw>0?x+dw:0);');
    if (edges.has('top') && edges.has('bottom')) lines.push('    height=(height+dh>16?height+dh:16);');
    else if (!edges.has('top') && edges.has('bottom')) lines.push('    y=(y+dh>0?y+dh:0);');
  }
  lines.push(`    if (gControls[${control.nativeIndex}]) { gtk_fixed_move(GTK_FIXED(gFixed[formIndex]), gControls[${control.nativeIndex}], x, y); gtk_widget_set_size_request(gControls[${control.nativeIndex}], width, height); }`);
  lines.push('  }');
  return lines.join('\n');
}

function hasResponsiveLayout(controls) { return controls.some(control => control.parentTabIndex < 0 && isResponsive(control)); }
function isResponsive(control) { return control.layout?.policy?.kind && control.layout.policy.kind !== 'fixed'; }
function int(value, fallback) { const number = Number(value); return Number.isFinite(number) ? Math.round(number) : fallback; }

function gtkAccessibilityHelpers(controls) {
  const lines = [];
  for (const control of controls) {
    if (!needsExplicitNativeAccessibleName(control)) continue;
    if (control.type === 'radio') {
      for (let optionIndex = 0; optionIndex < control.options.length; optionIndex += 1) {
        const name = nativeRadioItemAccessibleName(control, control.options[optionIndex]);
        lines.push(`  if (gRadioItems[${control.nativeIndex}].size() > ${optionIndex}) SetPatchAccessibleName(gRadioItems[${control.nativeIndex}][${optionIndex}], ${cString(name)});`);
      }
      continue;
    }
    const name = nativeAccessibleName(control);
    if (!name) continue;
    lines.push(`  SetPatchAccessibleName(gControls[${control.nativeIndex}], ${cString(name)});`);
  }
  return `static void SetPatchAccessibleName(GtkWidget *widget, const char *name) {\n  if (!widget || !name || !*name) return;\n  AtkObject *accessible = gtk_widget_get_accessible(widget);\n  if (accessible) atk_object_set_name(accessible, name);\n}\nstatic const char *PatchAccessibleName(GtkWidget *widget) {\n  if (!widget) return nullptr;\n  AtkObject *accessible = gtk_widget_get_accessible(widget);\n  return accessible ? atk_object_get_name(accessible) : nullptr;\n}\nstatic void ApplyPatchAccessibility() {\n${lines.join('\n') || '  // Standard GTK control names need no Patch override.'}\n}\n`;
}

function injectAccessibilitySmoke(source, controls) {
  const checks = [];
  let code = 130;
  for (const control of controls) {
    if (!needsExplicitNativeAccessibleName(control)) continue;
    if (control.type === 'radio') {
      for (let optionIndex = 0; optionIndex < control.options.length; optionIndex += 1) {
        const expected = nativeRadioItemAccessibleName(control, control.options[optionIndex]);
        checks.push(`  { const char *name = gRadioItems[${control.nativeIndex}].size() > ${optionIndex} ? PatchAccessibleName(gRadioItems[${control.nativeIndex}][${optionIndex}]) : nullptr; if (!name || std::string(name) != ${cString(expected)}) return ${code++}; }`);
      }
      continue;
    }
    const expected = nativeAccessibleName(control);
    if (!expected) continue;
    checks.push(`  { const char *name = PatchAccessibleName(gControls[${control.nativeIndex}]); if (!name || std::string(name) != ${cString(expected)}) return ${code++}; }`);
  }
  if (!checks.length) return source;
  const start = source.indexOf('static int RunPatchSmoke() {');
  if (start < 0) throw new NativeGuiError('Generated GTK source is missing RunPatchSmoke for accessibility verification.');
  let stop = source.indexOf('  gtk_widget_destroy(gForms[', start);
  if (stop < 0) stop = source.indexOf('  return 0;', start);
  if (stop < 0) throw new NativeGuiError('Generated GTK smoke has an unexpected shape for accessibility verification.');
  return source.slice(0, stop) + checks.join('\n') + '\n' + source.slice(stop);
}

function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated GTK source.`);
  return source.replace(marker, replacement);
}

function cString(value) { return JSON.stringify(String(value ?? '')); }
