import { NativeGuiError } from './native-gui-ir.js';
import { emitGtkGuiCppV11 } from './gtk-gui-v11.js';
import { adaptNativeListsForV11Backend } from './native-list-backend-adapter.js';

export const PATCH_GTK_GUI_BACKEND_V12_VERSION = '1.2';

/** Emit GTK backend 1.2 with persistent list state and native multi-select ListBox. */
export function emitGtkGuiCppV12(input) {
  const adapted = adaptNativeListsForV11Backend(input);
  let source = emitGtkGuiCppV11(adapted.compatibleIr)
    .replace(/Generated by Patch GTK GUI backend 1\.1\./, `Generated by Patch GTK GUI backend ${PATCH_GTK_GUI_BACKEND_V12_VERSION}.`);

  if (!adapted.listStates.size) return source;
  source = replaceRequired(source, '#include <cmath>', '#include <algorithm>\n#include <cmath>', 'GTK list algorithm include');
  source = injectListHelpers(source);

  for (const state of adapted.listStates.values()) {
    source = replaceRequired(
      source,
      `static std::string ${stateName(state.name)} = ${cString(state.initial?.[0] ?? '')};`,
      `static std::vector<std::string> ${stateName(state.name)} = ${stringVector(state.initial ?? [])};`,
      `GTK list state '${state.name}' declaration`
    );
  }

  for (const control of adapted.multiControls) {
    source = patchControlBlock(source, control, block => block
      .replace('gtk_list_box_set_selection_mode(GTK_LIST_BOX(control), GTK_SELECTION_SINGLE);', 'gtk_list_box_set_selection_mode(GTK_LIST_BOX(control), GTK_SELECTION_MULTIPLE);')
      .replace(
        `g_signal_connect(control, "row-selected", G_CALLBACK(OnListChanged), GINT_TO_POINTER(${control.commandId}));`,
        `g_signal_connect(control, "selected-rows-changed", G_CALLBACK(OnListMultiChanged), GINT_TO_POINTER(${control.commandId}));`
      ));
    source = replaceRequired(
      source,
      compatibleRefresh(control),
      `  if (gControls[${control.nativeIndex}]) SetListSelections(GTK_LIST_BOX(gControls[${control.nativeIndex}]), ${stateName(control.binding)});`,
      `GTK multi-select ListBox '${control.id}' refresh`
    );
  }

  for (const event of adapted.events) {
    source = patchListEventFunction(source, event);
    const control = adapted.multiControls.find(item => item.id === event.control);
    if (control) source = patchLegacySingleListDispatch(source, control, event);
  }
  source = injectMultiCallback(source, adapted);
  source = injectSmoke(source, adapted);
  return source;
}

function injectListHelpers(source) {
  const marker = 'static void ShowInfoDialog(int formIndex, const char *title, const char *message) {';
  const helpers = `static std::string ListBoxRowText(GtkListBoxRow *row) {\n  if (!row) return std::string();\n  GtkWidget *child = gtk_bin_get_child(GTK_BIN(row));\n  const char *value = child ? gtk_label_get_text(GTK_LABEL(child)) : "";\n  return value ? std::string(value) : std::string();\n}\nstatic std::vector<std::string> ListBoxTexts(GtkListBox *box) {\n  std::vector<std::string> out;\n  if (!box) return out;\n  GList *rows = gtk_list_box_get_selected_rows(box);\n  for (GList *it = rows; it; it = it->next) out.push_back(ListBoxRowText(GTK_LIST_BOX_ROW(it->data)));\n  g_list_free(rows);\n  return out;\n}\nstatic void SetListSelections(GtkListBox *box, const std::vector<std::string>& values) {\n  if (!box) return;\n  gtk_list_box_unselect_all(box);\n  int index = 0;\n  while (GtkListBoxRow *row = gtk_list_box_get_row_at_index(box, index++)) {\n    std::string value = ListBoxRowText(row);\n    if (std::find(values.begin(), values.end(), value) != values.end()) gtk_list_box_select_row(box, row);\n  }\n}\n`;
  return replaceRequired(source, marker, helpers + marker, 'GTK multi-select ListBox helpers');
}

function injectMultiCallback(source, adapted) {
  const lines = [];
  for (const event of adapted.events) {
    const control = adapted.multiControls.find(item => item.id === event.control);
    if (!control) continue;
    lines.push(`  if (commandId == ${control.commandId}) { Event_${event.eventIndex}(ListBoxTexts(box)); return; }`);
  }
  if (!lines.length) return source;
  const marker = 'static gboolean OnDelete(GtkWidget *widget, GdkEvent *, gpointer data) {';
  const callback = `static void OnListMultiChanged(GtkListBox *box, gpointer data) {\n  if (gRefreshing) return;\n  int commandId = GPOINTER_TO_INT(data);\n${lines.join('\n')}\n}\n\n`;
  return replaceRequired(source, marker, callback + marker, 'GTK multi-select callback insertion');
}

function patchLegacySingleListDispatch(source, control, event) {
  const marker = `  if (commandId == ${control.commandId}) { if (!row) { Event_${event.eventIndex}(std::string()); return; } GtkWidget *child = gtk_bin_get_child(GTK_BIN(row)); const char *value = child ? gtk_label_get_text(GTK_LABEL(child)) : ""; Event_${event.eventIndex}(value ? std::string(value) : std::string()); return; }`;
  const replacement = `  if (commandId == ${control.commandId}) { (void)box; (void)row; return; }`;
  return replaceRequired(source, marker, replacement, `GTK legacy single-select dispatch '${control.id}'`);
}

function patchListEventFunction(source, event) {
  const oldSignature = `static void Event_${event.eventIndex}(const std::string& eventValue) {`;
  const newSignature = `static void Event_${event.eventIndex}(const std::vector<std::string>& eventValue) {`;
  const start = source.indexOf(oldSignature);
  if (start < 0) throw new NativeGuiError(`GTK list Event_${event.eventIndex} signature marker is missing.`);
  const endMarker = '\n  RefreshUI();\n}';
  const end = source.indexOf(endMarker, start);
  if (end < 0) throw new NativeGuiError(`GTK list Event_${event.eventIndex} body marker is missing.`);
  let body = source.slice(start, end + endMarker.length).replace(oldSignature, newSignature);

  for (const action of event.actions ?? []) {
    if (action.kind !== 'change' || action.stateType !== 'list') continue;
    const target = stateName(action.target);
    for (const op of action.ops ?? []) {
      if (op.op === 'clear' || op.value?.kind === 'eventValue') continue;
      if (op.op === 'add') {
        body = replaceInBody(body, `  ${target} += std::string(${cString('')});`, `  ${target}.push_back(std::string(${cString(op.value.value)}));`, `GTK list add '${action.target}'`);
      } else if (op.op === 'remove') {
        body = replaceInBody(body, `  ${target} = std::string(${cString('')});`, `  ${target}.erase(std::remove(${target}.begin(), ${target}.end(), std::string(${cString(op.value.value)})), ${target}.end());`, `GTK list remove '${action.target}'`);
      } else if (op.op === 'set') {
        body = replaceInBody(body, `  ${target} = std::string(${cString('')});`, `  ${target} = ${stringVector(op.value.value)};`, `GTK list set '${action.target}'`);
      }
    }
  }
  return source.slice(0, start) + body + source.slice(end + endMarker.length);
}

function patchControlBlock(source, control, transform) {
  const endMarker = `    gControls[${control.nativeIndex}] = control;\n  }`;
  const end = source.indexOf(endMarker);
  if (end < 0) throw new NativeGuiError(`GTK multi-select ListBox '${control.id}' control block end is missing.`);
  const start = source.lastIndexOf(`  if (${control.formIndex} == index) {`, end);
  if (start < 0) throw new NativeGuiError(`GTK multi-select ListBox '${control.id}' control block start is missing.`);
  const original = source.slice(start, end + endMarker.length);
  const replacement = transform(original);
  if (replacement === original || !replacement.includes('GTK_SELECTION_MULTIPLE') || !replacement.includes('selected-rows-changed')) {
    throw new NativeGuiError(`GTK multi-select ListBox '${control.id}' control block did not adapt.`);
  }
  return source.slice(0, start) + replacement + source.slice(end + endMarker.length);
}

function compatibleRefresh(control) {
  const state = stateName(control.binding);
  const checks = control.options.map((option, optionIndex) => `if (${state} == ${cString(option)}) selected = ${optionIndex};`).join(' else ');
  return `  if (gControls[${control.nativeIndex}]) { int selected = -1; ${checks} GtkListBoxRow *row = selected >= 0 ? gtk_list_box_get_row_at_index(GTK_LIST_BOX(gControls[${control.nativeIndex}]), selected) : nullptr; gtk_list_box_select_row(GTK_LIST_BOX(gControls[${control.nativeIndex}]), row); }`;
}

function injectSmoke(source, adapted) {
  const candidate = adapted.multiControls.find(control => {
    const event = adapted.events.find(item => item.control === control.id && item.event === 'changed');
    return event && event.actions?.some(action => action.kind === 'change' && action.target === control.binding && action.ops?.some(op => op.op === 'set' && op.value?.kind === 'eventValue'));
  });
  if (!candidate || candidate.options.length < 2) return source;
  const start = source.indexOf('static int RunPatchSmoke() {');
  if (start < 0) throw new NativeGuiError('GTK multi-select smoke function is missing.');
  const marker = '\n  return 0;\n}';
  const end = source.indexOf(marker, start);
  if (end < 0) throw new NativeGuiError('GTK multi-select smoke return marker is missing.');
  const first = candidate.options[0];
  const last = candidate.options[candidate.options.length - 1];
  const smoke = `\n  gtk_list_box_unselect_all(GTK_LIST_BOX(gControls[${candidate.nativeIndex}]));\n  gtk_list_box_select_row(GTK_LIST_BOX(gControls[${candidate.nativeIndex}]), gtk_list_box_get_row_at_index(GTK_LIST_BOX(gControls[${candidate.nativeIndex}]), 0));\n  gtk_list_box_select_row(GTK_LIST_BOX(gControls[${candidate.nativeIndex}]), gtk_list_box_get_row_at_index(GTK_LIST_BOX(gControls[${candidate.nativeIndex}]), ${candidate.options.length - 1}));\n  if (${stateName(candidate.binding)}.size() != 2 || ${stateName(candidate.binding)}[0] != ${cString(first)} || ${stateName(candidate.binding)}[1] != ${cString(last)}) return 91;`;
  return source.slice(0, end) + smoke + source.slice(end);
}

function replaceInBody(body, marker, replacement, label) {
  if (!body.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated GTK event body.`);
  return body.replace(marker, replacement);
}
function stateName(name) { return `patch_state_${identifier(name)}`; }
function identifier(value) { return String(value).replace(/[^A-Za-z0-9_]/g, '_').replace(/^[0-9]/, '_$&'); }
function cString(value) { return JSON.stringify(String(value ?? '')); }
function stringVector(values) { return `{${(values ?? []).map(value => `std::string(${cString(value)})`).join(', ')}}`; }
function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated GTK source.`);
  return source.replace(marker, replacement);
}
