import { NativeGuiError } from './native-gui-ir.js';
import { nativeAccessibleName } from './native-accessibility.js';
import { emitGtkGuiCppV12 } from './gtk-gui-v12.js';
import { adaptNativeTreesForV12Backend, treePersistentPathTarget } from './native-tree-backend-adapter.js';

export const PATCH_GTK_GUI_BACKEND_V13_VERSION = '1.3';

/** Emit GTK backend 1.3 with a real GtkTreeView/GtkTreeStore TreeView. */
export function emitGtkGuiCppV13(input) {
  const adapted = adaptNativeTreesForV12Backend(input);
  let source = emitGtkGuiCppV12(adapted.compatibleIr)
    .replace(/Generated by Patch GTK GUI backend 1\.2\./, `Generated by Patch GTK GUI backend ${PATCH_GTK_GUI_BACKEND_V13_VERSION}.`);
  if (!adapted.trees.length) return source;

  source = replaceRequired(
    source,
    `static GtkWidget *gControls[${Math.max(1, adapted.controls.length)}] = {};`,
    `static GtkWidget *gControls[${Math.max(1, adapted.controls.length)}] = {};\nstatic GtkWidget *gPatchTreeViews[${Math.max(1, adapted.controls.length)}] = {};\nstatic int gPatchTreeSelectionCount = 0;`,
    'GTK TreeView storage'
  );

  for (const tree of adapted.trees) {
    source = removeShadowState(source, tree);
    source = removeShadowRefresh(source, tree);
    source = replaceControlBlock(source, tree, treeCreate(adapted, tree));
    const event = adapted.events.find(item => item.control === tree.id && item.event === 'changed');
    if (event) source = replaceRequired(source, `  if (commandId == ${tree.commandId}) { Event_${event.eventIndex}(ListBoxTexts(box)); return; }\n`, '', `GTK TreeView '${tree.id}' legacy multi-list dispatch`);
  }

  const marker = 'static gboolean OnDelete(GtkWidget *widget, GdkEvent *, gpointer data) {';
  source = replaceRequired(source, marker, `${emitTreeHelpers(adapted)}\n\n${marker}`, 'GTK TreeView helper insertion');
  source = injectTreeRefresh(source, adapted);
  source = injectTreeSmoke(source, adapted);
  assertNoShadowState(source, adapted);
  return source;
}

function emitTreeHelpers(adapted) {
  const textFunctions = [], dispatch=[];
  for (const tree of adapted.trees) {
    for (const node of tree.flatNodes) textFunctions.push(emitTextFunction(tree.nativeIndex,node.flatIndex,node.text,adapted.states));
    const event=adapted.events.find(item=>item.control===tree.id&&item.event==='changed');
    const call=event?` Event_${event.eventIndex}(PatchTreeSelectedPath(selection));`:'';
    dispatch.push(`  if (commandId == ${tree.commandId}) { GtkTreeModel *model=nullptr; GtkTreeIter iter; if (gtk_tree_selection_get_selected(selection,&model,&iter)) { ++gPatchTreeSelectionCount;${call} } return; }`);
  }
  return `${textFunctions.join('\n')}\nstatic std::vector<std::string> PatchTreeSelectedPath(GtkTreeSelection *selection) { std::vector<std::string> reversed; GtkTreeModel *model=nullptr; GtkTreeIter iter; if (!selection || !gtk_tree_selection_get_selected(selection,&model,&iter)) return {}; GtkTreeIter current=iter; while (true) { gchar *text=nullptr; gtk_tree_model_get(model,&current,0,&text,-1); reversed.push_back(text?std::string(text):std::string()); if(text)g_free(text); GtkTreeIter parent; if(!gtk_tree_model_iter_parent(model,&parent,&current))break; current=parent; } return std::vector<std::string>(reversed.rbegin(),reversed.rend()); }\nstatic int PatchTreeModelCount(GtkTreeModel *model, GtkTreeIter *parent) { int count=0; GtkTreeIter iter; gboolean ok=gtk_tree_model_iter_children(model,&iter,parent); while(ok){ ++count; count += PatchTreeModelCount(model,&iter); ok=gtk_tree_model_iter_next(model,&iter); } return count; }\nstatic void OnTreeChanged(GtkTreeSelection *selection, gpointer data) { if (gRefreshing) return; int commandId=GPOINTER_TO_INT(data);\n${dispatch.join('\n')}\n}`;
}

function emitTextFunction(treeIndex,nodeIndex,text,states){const lines=['  std::string out;'];let cursor=0;const re=/\{([A-Za-z_]\w*)\}/g;let match;while((match=re.exec(text))){if(match.index>cursor)lines.push(`  out += ${cString(text.slice(cursor,match.index))};`);const state=states.get(match[1]);if(state.type==='boolean')lines.push(`  out += PatchBoolean(${stateName(state.name)});`);else if(state.type==='number')lines.push(`  out += PatchNumber(${stateName(state.name)});`);else lines.push(`  out += ${stateName(state.name)};`);cursor=match.index+match[0].length;}if(cursor<text.length)lines.push(`  out += ${cString(text.slice(cursor))};`);lines.push('  return out;');return `static std::string TreeNodeText_${treeIndex}_${nodeIndex}() {\n${lines.join('\n')}\n}`;}

function treeCreate(adapted,tree){const control=adapted.controls[tree.nativeIndex];const x=layoutInt(control.layout?.x,control.parentTabIndex>=0?12:24),y=layoutInt(control.layout?.y,control.parentTabIndex>=0?12:24),width=positiveInt(control.layout?.width,220),height=positiveInt(control.layout?.height,120);const put=control.parentTabIndex>=0?`GtkWidget *parent = gTabPages[${control.parentTabIndex}].at(${control.pageIndex}); gtk_fixed_put(GTK_FIXED(parent), control, ${x}, ${y});`:`gtk_fixed_put(GTK_FIXED(fixed), control, ${x}, ${y});`;const lines=[];const vars=new Map();for(const node of tree.flatNodes){const variable=`treeIter_${tree.nativeIndex}_${node.flatIndex}`;vars.set(node.flatIndex,variable);const parentFlat=node.flatIndexPath.length>1?node.flatIndexPath[node.flatIndexPath.length-2]:null;const parent=parentFlat===null?'nullptr':`&${vars.get(parentFlat)}`;lines.push(`    GtkTreeIter ${variable}; gtk_tree_store_append(store, &${variable}, ${parent}); { std::string label=TreeNodeText_${tree.nativeIndex}_${node.flatIndex}(); gtk_tree_store_set(store, &${variable}, 0, label.c_str(), -1); }`);}const accessibleName=nativeAccessibleName(control)??tree.id;return `  if (${control.formIndex} == index) {\n    GtkTreeStore *store = gtk_tree_store_new(1, G_TYPE_STRING);\n${lines.join('\n')}\n    GtkWidget *view = gtk_tree_view_new_with_model(GTK_TREE_MODEL(store)); g_object_unref(store); GtkCellRenderer *renderer=gtk_cell_renderer_text_new(); GtkTreeViewColumn *column=gtk_tree_view_column_new_with_attributes("",renderer,"text",0,nullptr); gtk_tree_view_append_column(GTK_TREE_VIEW(view),column); gtk_tree_view_set_headers_visible(GTK_TREE_VIEW(view),FALSE); GtkTreeSelection *selection=gtk_tree_view_get_selection(GTK_TREE_VIEW(view)); gtk_tree_selection_set_mode(selection,GTK_SELECTION_SINGLE); g_signal_connect(selection,"changed",G_CALLBACK(OnTreeChanged),GINT_TO_POINTER(${tree.commandId})); GtkWidget *control=gtk_scrolled_window_new(nullptr,nullptr); gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(control),GTK_POLICY_AUTOMATIC,GTK_POLICY_AUTOMATIC); gtk_container_add(GTK_CONTAINER(control),view); gtk_widget_set_size_request(control,${width},${height}); ${put} gControls[${tree.nativeIndex}]=control; gPatchTreeViews[${tree.nativeIndex}]=view; gtk_tree_view_expand_all(GTK_TREE_VIEW(view)); AtkObject *accessible=gtk_widget_get_accessible(view); if(accessible)atk_object_set_name(accessible,${cString(accessibleName)});\n  }`;}

function injectTreeRefresh(source,adapted){const start=source.indexOf('static void RefreshUI() {');if(start<0)throw new NativeGuiError('Generated GTK source is missing RefreshUI for TreeView labels.');const marker='  gRefreshing = false;';const at=source.indexOf(marker,start);if(at<0)throw new NativeGuiError('Generated GTK TreeView refresh insertion point is missing.');const lines=[];for(const tree of adapted.trees){for(const node of tree.flatNodes){const path=node.indexPath.join(':');lines.push(`  if (gPatchTreeViews[${tree.nativeIndex}]) { GtkTreeModel *model=gtk_tree_view_get_model(GTK_TREE_VIEW(gPatchTreeViews[${tree.nativeIndex}])); GtkTreeIter iter; if(model && gtk_tree_model_get_iter_from_string(model,&iter,${cString(path)})) { std::string label=TreeNodeText_${tree.nativeIndex}_${node.flatIndex}(); gtk_tree_store_set(GTK_TREE_STORE(model),&iter,0,label.c_str(),-1); } }`);}}return source.slice(0,at)+lines.join('\n')+'\n'+source.slice(at);}

function injectTreeSmoke(source,adapted){const start=source.indexOf('static int RunPatchSmoke() {');if(start<0)throw new NativeGuiError('Generated GTK source is missing TreeView smoke function.');let at=source.indexOf('  gtk_widget_destroy(gForms[',start);if(at<0)at=source.indexOf('  return 0;',start);if(at<0)throw new NativeGuiError('Generated GTK TreeView smoke insertion point is missing.');const checks=[];let code=210;for(const tree of adapted.trees){checks.push(`  if (!gControls[${tree.nativeIndex}] || !gPatchTreeViews[${tree.nativeIndex}] || PatchTreeModelCount(gtk_tree_view_get_model(GTK_TREE_VIEW(gPatchTreeViews[${tree.nativeIndex}])), nullptr) != ${tree.flatNodes.length}) return ${code++};`);const event=adapted.events.find(item=>item.control===tree.id&&item.event==='changed');if(!event||!tree.flatNodes.length)continue;const last=tree.flatNodes.at(-1),path=last.indexPath.join(':');checks.push(`  { GtkTreeSelection *selection=gtk_tree_view_get_selection(GTK_TREE_VIEW(gPatchTreeViews[${tree.nativeIndex}])); GtkTreePath *path=gtk_tree_path_new_from_string(${cString(path)}); int before=gPatchTreeSelectionCount; gtk_tree_selection_select_path(selection,path); gtk_tree_path_free(path); if(gPatchTreeSelectionCount==before)OnTreeChanged(selection,GINT_TO_POINTER(${tree.commandId})); if(gPatchTreeSelectionCount<=before)return ${code++}; }`);const target=treePersistentPathTarget(event,adapted.states);if(target)checks.push(`  if (${stateName(target)} != PatchTreeSelectedPath(gtk_tree_view_get_selection(GTK_TREE_VIEW(gPatchTreeViews[${tree.nativeIndex}])))) return ${code++};`);}return source.slice(0,at)+checks.join('\n')+'\n'+source.slice(at);}

function replaceControlBlock(source,tree,replacement){const tag=`GINT_TO_POINTER(${tree.commandId})`;const tagAt=source.indexOf(tag);if(tagAt<0)throw new NativeGuiError(`GTK TreeView '${tree.id}' shadow command is missing.`);const start=source.lastIndexOf(`  if (${tree.formIndex} == index) {`,tagAt);const end=source.indexOf('\n  }',tagAt);if(start<0||end<0)throw new NativeGuiError(`GTK TreeView '${tree.id}' shadow control block is missing.`);return source.slice(0,start)+replacement+source.slice(end+4);}
function removeShadowState(source,tree){return replaceRequired(source,`static std::vector<std::string> ${stateName(tree.shadowState)} = {};\n`,'',`GTK TreeView '${tree.id}' shadow state`);}function removeShadowRefresh(source,tree){return replaceRequired(source,`  if (gControls[${tree.nativeIndex}]) SetListSelections(GTK_LIST_BOX(gControls[${tree.nativeIndex}]), ${stateName(tree.shadowState)});\n`,'',`GTK TreeView '${tree.id}' shadow refresh`);}function assertNoShadowState(source,adapted){for(const tree of adapted.trees)if(source.includes(tree.shadowState))throw new NativeGuiError(`GTK TreeView '${tree.id}' leaked backend shadow state.`);}
function stateName(name){return `patch_state_${identifier(name)}`;}function identifier(value){return String(value).replace(/[^A-Za-z0-9_]/g,'_').replace(/^[0-9]/,'_$&');}function cString(value){return JSON.stringify(String(value??''));}function layoutInt(value,fallback){return Number.isFinite(Number(value))?Math.max(0,Math.round(Number(value))):fallback;}function positiveInt(value,fallback){return Number.isFinite(Number(value))?Math.max(1,Math.round(Number(value))):fallback;}function replaceRequired(source,marker,replacement,label){if(!source.includes(marker))throw new NativeGuiError(`${label} marker is missing from generated GTK source.`);return source.replace(marker,replacement);}
