import { validateNativeGuiIR, NativeGuiError } from './native-gui-ir.js';

export const PATCH_GTK_GUI_BACKEND_VERSION = '0.1';

export function emitGtkGuiCpp(input) {
  const ir = validateNativeGuiIR(input);
  const formIndex = new Map(ir.forms.map((form, index) => [form.id, index]));
  const controlRecords = [];
  let nextCommandId = 1000;

  for (let f = 0; f < ir.forms.length; f++) {
    for (const control of ir.forms[f].controls) {
      controlRecords.push({ ...control, formIndex: f, commandId: nextCommandId++, handleIndex: controlRecords.length });
    }
  }

  const controlById = new Map(controlRecords.filter(control => control.id).map(control => [control.id, control]));
  const stateByName = new Map(ir.states.map(state => [state.name, state]));
  for (const event of ir.events) {
    if (!controlById.has(event.control)) throw new NativeGuiError(`GTK event control '${event.control}' is missing.`);
    for (const action of event.actions) {
      if ((action.kind === 'openForm' || action.kind === 'closeForm') && !formIndex.has(action.form)) {
        throw new NativeGuiError(`GTK Form '${action.form}' is missing.`);
      }
    }
  }

  const stateDecls = ir.states.map(stateDeclaration).join('\n');
  const formDefs = ir.forms.map((form, index) =>
    `  {${cString(form.id)}, ${cString(form.title)}, ${positiveInt(form.width, 640)}, ${positiveInt(form.height, 420)}, ${form.visible ? 'true' : 'false'}}${index + 1 === ir.forms.length ? '' : ','}`
  ).join('\n');
  const controlDefs = controlRecords.map((control, index) =>
    `  {${control.commandId}, ${control.formIndex}, ${controlKind(control.type)}, ${cString(control.id ?? '')}, ${layoutInt(control.layout?.x, 24)}, ${layoutInt(control.layout?.y, 24)}, ${positiveInt(control.layout?.width, 120)}, ${positiveInt(control.layout?.height, 36)}}${index + 1 === controlRecords.length ? '' : ','}`
  ).join('\n');
  const textFunctions = controlRecords.map((control, index) => emitControlTextFunction(control, index, stateByName)).join('\n\n');
  const eventFunctions = ir.events.map((event, index) => emitEventFunction(event, index, formIndex, stateByName)).join('\n\n');
  const clickedDispatch = ir.events.map((event, index) => emitClickedDispatch(event, index, controlById)).filter(Boolean).join('\n');
  const toggledDispatch = ir.events.map((event, index) => emitToggledDispatch(event, index, controlById)).filter(Boolean).join('\n');
  const changedDispatch = ir.events.map((event, index) => emitChangedDispatch(event, index, controlById)).filter(Boolean).join('\n');
  const refreshCases = controlRecords.map((control, index) => emitRefresh(control, index, stateByName)).join('\n');
  const createCases = controlRecords.map((control, index) => emitCreateControl(control, index)).join('\n');
  const smoke = emitSmoke(formIndex, controlById, stateByName);

  return `// Generated by Patch GTK GUI backend ${PATCH_GTK_GUI_BACKEND_VERSION}.\n// Direct native GTK controls: no Electron/Chromium runtime.\n#include <gtk/gtk.h>\n#include <cmath>\n#include <cstring>\n#include <sstream>\n#include <string>\n\nstatic bool gRefreshing = false;\n\nenum ControlKind { CK_TEXT=1, CK_BUTTON=2, CK_INPUT=3, CK_CHECKBOX=4 };\nstruct FormDef { const char *formId; const char *title; int width; int height; bool visible; };\nstruct ControlDef { int commandId; int formIndex; ControlKind kind; const char *name; int x; int y; int width; int height; };\n\n${stateDecls}\n\nstatic const FormDef FORMS[] = {\n${formDefs}\n};\nstatic const int FORM_COUNT = ${ir.forms.length};\nstatic GtkWidget *gForms[${Math.max(1, ir.forms.length)}] = {};\nstatic GtkWidget *gFixed[${Math.max(1, ir.forms.length)}] = {};\n\nstatic const ControlDef CONTROLS[] = {\n${controlDefs || '  {0,0,CK_TEXT,"",0,0,0,0}'}\n};\nstatic const int CONTROL_COUNT = ${controlRecords.length};\nstatic GtkWidget *gControls[${Math.max(1, controlRecords.length)}] = {};\n\nstatic std::string PatchNumber(double value) {\n  if (std::isfinite(value) && std::floor(value) == value) return std::to_string((long long)value);\n  std::ostringstream out; out.precision(15); out << value; return out.str();\n}\nstatic std::string PatchBoolean(bool value) { return value ? "true" : "false"; }\n\n${textFunctions}\n\nstatic void RefreshUI();\n\n${eventFunctions}\n\nstatic void OnClicked(GtkWidget *, gpointer data) {\n  if (gRefreshing) return;\n  int commandId = GPOINTER_TO_INT(data);\n${clickedDispatch || '  (void)commandId;'}\n}\n\nstatic void OnToggled(GtkToggleButton *button, gpointer data) {\n  if (gRefreshing) return;\n  int commandId = GPOINTER_TO_INT(data);\n${toggledDispatch || '  (void)commandId; (void)button;'}\n}\n\nstatic void OnChanged(GtkEditable *editable, gpointer data) {\n  if (gRefreshing) return;\n  int commandId = GPOINTER_TO_INT(data);\n${changedDispatch || '  (void)commandId; (void)editable;'}\n}\n\nstatic gboolean OnDelete(GtkWidget *widget, GdkEvent *, gpointer data) {\n  int formIndex = GPOINTER_TO_INT(data);\n  if (formIndex == 0) {\n    gtk_main_quit();\n    return FALSE;\n  }\n  gtk_widget_hide(widget);\n  return TRUE;\n}\n\nstatic void RefreshUI() {\n  gRefreshing = true;\n${refreshCases}\n  gRefreshing = false;\n}\n\nstatic GtkWidget *CreatePatchForm(int index) {\n  GtkWidget *window = gtk_window_new(GTK_WINDOW_TOPLEVEL);\n  gtk_window_set_title(GTK_WINDOW(window), FORMS[index].title);\n  gtk_window_set_default_size(GTK_WINDOW(window), FORMS[index].width, FORMS[index].height);\n  gtk_window_set_resizable(GTK_WINDOW(window), TRUE);\n  g_signal_connect(window, "delete-event", G_CALLBACK(OnDelete), GINT_TO_POINTER(index));\n  GtkWidget *fixed = gtk_fixed_new();\n  gtk_container_add(GTK_CONTAINER(window), fixed);\n  gForms[index] = window;\n  gFixed[index] = fixed;\n${createCases}\n  return window;\n}\n\nstatic bool HasArg(int argc, char *argv[], const char *value) {\n  for (int i = 1; i < argc; ++i) if (strcmp(argv[i], value) == 0) return true;\n  return false;\n}\n\n${smoke}\n\nint main(int argc, char *argv[]) {\n  bool smoke = HasArg(argc, argv, "--patch-smoke");\n  gtk_init(&argc, &argv);\n  for (int i = 0; i < FORM_COUNT; ++i) {\n    if (!CreatePatchForm(i)) return 10 + i;\n  }\n  RefreshUI();\n  for (int i = 0; i < FORM_COUNT; ++i) {\n    if (FORMS[i].visible) gtk_widget_show_all(gForms[i]);\n  }\n  if (smoke) return RunPatchSmoke();\n  gtk_main();\n  return 0;\n}\n`;
}

function stateDeclaration(state) {
  const name = stateName(state.name);
  if (state.type === 'boolean') return `static bool ${name} = ${state.initial ? 'true' : 'false'};`;
  if (state.type === 'number') return `static double ${name} = ${Number(state.initial)};`;
  if (state.type === 'text') return `static std::string ${name} = ${cString(state.initial)};`;
  throw new NativeGuiError(`GTK state type '${state.type}' is unsupported.`);
}

function emitControlTextFunction(control, index, states) {
  const text = String(control.text ?? '');
  const lines = ['  std::string out;'];
  let cursor = 0;
  const re = /\{([A-Za-z_]\w*)\}/g;
  let match;
  while ((match = re.exec(text))) {
    if (match.index > cursor) lines.push(`  out += ${cString(text.slice(cursor, match.index))};`);
    const state = states.get(match[1]);
    if (!state) throw new NativeGuiError(`GTK text '${text}' refers to unknown state '${match[1]}'.`);
    if (state.type === 'boolean') lines.push(`  out += PatchBoolean(${stateName(state.name)});`);
    else if (state.type === 'number') lines.push(`  out += PatchNumber(${stateName(state.name)});`);
    else lines.push(`  out += ${stateName(state.name)};`);
    cursor = match.index + match[0].length;
  }
  if (cursor < text.length) lines.push(`  out += ${cString(text.slice(cursor))};`);
  lines.push('  return out;');
  return `static std::string ControlText_${index}() {\n${lines.join('\n')}\n}`;
}

function emitEventFunction(event, index, forms, states) {
  const param = event.valueType === 'boolean' ? 'bool eventValue' : event.valueType === 'text' ? 'const std::string& eventValue' : '';
  const actions = event.actions.map(action => emitAction(action, event, forms, states)).join('\n');
  return `static void Event_${index}(${param}) {\n${actions || '  // no-op'}\n  RefreshUI();\n}`;
}

function emitAction(action, event, forms, states) {
  if (action.kind === 'openForm') return `  gtk_widget_show_all(gForms[${forms.get(action.form)}]); gtk_window_present(GTK_WINDOW(gForms[${forms.get(action.form)}]));`;
  if (action.kind === 'closeForm') return `  gtk_widget_hide(gForms[${forms.get(action.form)}]);`;
  if (action.kind !== 'change') throw new NativeGuiError(`GTK action '${action.kind}' is unsupported.`);
  const state = states.get(action.target);
  if (!state) throw new NativeGuiError(`GTK change target '${action.target}' is missing.`);
  return action.ops.map(op => emitOperation(state, op, event)).join('\n');
}

function emitOperation(state, op, event) {
  const target = stateName(state.name);
  if (op.op === 'clear') {
    if (state.type === 'boolean') return `  ${target} = false;`;
    if (state.type === 'number') return `  ${target} = 0.0;`;
    if (state.type === 'text') return `  ${target}.clear();`;
  }
  const value = emitNativeValue(state, op.value, event);
  if (op.op === 'set') return `  ${target} = ${value};`;
  if (op.op === 'add' && state.type === 'number') return `  ${target} += ${value};`;
  if (op.op === 'remove' && state.type === 'number') return `  ${target} -= ${value};`;
  if (op.op === 'add' && state.type === 'text') return `  ${target} += ${value};`;
  throw new NativeGuiError(`GTK native GUI cannot apply '${op.op}' to ${state.type} state '${state.name}'.`);
}

function emitNativeValue(state, value, event) {
  if (value?.kind === 'eventValue') {
    if (state.type !== event.valueType) throw new NativeGuiError(`GTK event value type ${event.valueType ?? 'none'} cannot be assigned to ${state.type} state '${state.name}'.`);
    return 'eventValue';
  }
  const literal = value?.value;
  if (state.type === 'boolean') return literal ? 'true' : 'false';
  if (state.type === 'number') return String(Number(literal));
  if (state.type === 'text') return `std::string(${cString(literal)})`;
  throw new NativeGuiError(`GTK literal type '${state.type}' is unsupported.`);
}

function emitClickedDispatch(event, index, controls) {
  const control = controls.get(event.control);
  if (!control || control.type !== 'button') return '';
  return `  if (commandId == ${control.commandId}) { Event_${index}(); return; }`;
}
function emitToggledDispatch(event, index, controls) {
  const control = controls.get(event.control);
  if (!control || control.type !== 'checkbox') return '';
  return `  if (commandId == ${control.commandId}) { Event_${index}(gtk_toggle_button_get_active(button)); return; }`;
}
function emitChangedDispatch(event, index, controls) {
  const control = controls.get(event.control);
  if (!control || control.type !== 'input') return '';
  return `  if (commandId == ${control.commandId}) { Event_${index}(gtk_entry_get_text(GTK_ENTRY(editable))); return; }`;
}

function emitRefresh(control, index, states) {
  if (control.type === 'text') return `  if (gControls[${index}]) { auto value = ControlText_${index}(); if (value != gtk_label_get_text(GTK_LABEL(gControls[${index}]))) gtk_label_set_text(GTK_LABEL(gControls[${index}]), value.c_str()); }`;
  if (control.type === 'button') return `  if (gControls[${index}]) { auto value = ControlText_${index}(); const char *old = gtk_button_get_label(GTK_BUTTON(gControls[${index}])); if (!old || value != old) gtk_button_set_label(GTK_BUTTON(gControls[${index}]), value.c_str()); }`;
  if (control.type === 'checkbox') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) { auto value = ControlText_${index}(); const char *old = gtk_button_get_label(GTK_BUTTON(gControls[${index}])); if (!old || value != old) gtk_button_set_label(GTK_BUTTON(gControls[${index}]), value.c_str()); gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(gControls[${index}]), ${stateName(state.name)} ? TRUE : FALSE); }`;
  }
  if (control.type === 'input') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) { const char *old = gtk_entry_get_text(GTK_ENTRY(gControls[${index}])); if (!old || ${stateName(state.name)} != old) gtk_entry_set_text(GTK_ENTRY(gControls[${index}]), ${stateName(state.name)}.c_str()); }`;
  }
  return '';
}

function emitCreateControl(control, index) {
  const x = layoutInt(control.layout?.x, 24);
  const y = layoutInt(control.layout?.y, 24);
  const width = positiveInt(control.layout?.width, 120);
  const height = positiveInt(control.layout?.height, 36);
  let create;
  if (control.type === 'text') create = 'GtkWidget *control = gtk_label_new(""); gtk_label_set_xalign(GTK_LABEL(control), 0.0f);';
  else if (control.type === 'button') create = 'GtkWidget *control = gtk_button_new_with_label("");';
  else if (control.type === 'input') create = 'GtkWidget *control = gtk_entry_new();';
  else create = 'GtkWidget *control = gtk_check_button_new_with_label("");';
  const signal = control.type === 'button'
    ? `g_signal_connect(control, "clicked", G_CALLBACK(OnClicked), GINT_TO_POINTER(${control.commandId}));`
    : control.type === 'checkbox'
      ? `g_signal_connect(control, "toggled", G_CALLBACK(OnToggled), GINT_TO_POINTER(${control.commandId}));`
      : control.type === 'input'
        ? `g_signal_connect(control, "changed", G_CALLBACK(OnChanged), GINT_TO_POINTER(${control.commandId}));`
        : '';
  return `  if (${control.formIndex} == index) {\n    ${create}\n    gtk_widget_set_size_request(control, ${width}, ${height});\n    gtk_fixed_put(GTK_FIXED(fixed), control, ${x}, ${y});\n    ${signal}\n    gControls[${index}] = control;\n  }`;
}

function emitSmoke(forms, controls, states) {
  const mainIndex = forms.has('main') ? forms.get('main') : 0;
  const settingsIndex = forms.get('settings');
  const open = controls.get('open_settings');
  const close = controls.get('close_settings');
  const checkbox = controls.get('notifications');
  const notifications = states.get('notifications');
  const lines = ['static int RunPatchSmoke() {', `  if (!gForms[${mainIndex}] || !gtk_widget_get_visible(gForms[${mainIndex}])) return 70;`];
  if (settingsIndex !== undefined) lines.push(`  if (gtk_widget_get_visible(gForms[${settingsIndex}])) return 71;`);
  if (open && settingsIndex !== undefined) {
    lines.push(`  gtk_button_clicked(GTK_BUTTON(gControls[${open.handleIndex}]));`);
    lines.push(`  if (!gtk_widget_get_visible(gForms[${settingsIndex}])) return 72;`);
  }
  if (checkbox && notifications?.type === 'boolean') {
    lines.push(`  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(gControls[${checkbox.handleIndex}]), TRUE);`);
    lines.push(`  if (!${stateName(notifications.name)}) return 73;`);
  }
  if (close && settingsIndex !== undefined) {
    lines.push(`  gtk_button_clicked(GTK_BUTTON(gControls[${close.handleIndex}]));`);
    lines.push(`  if (gtk_widget_get_visible(gForms[${settingsIndex}])) return 74;`);
  }
  lines.push(`  gtk_widget_destroy(gForms[${mainIndex}]);`, '  return 0;', '}');
  return lines.join('\n');
}

function controlKind(type) { return ({ text: 'CK_TEXT', button: 'CK_BUTTON', input: 'CK_INPUT', checkbox: 'CK_CHECKBOX' })[type] ?? 'CK_TEXT'; }
function stateName(name) { return `patch_state_${identifier(name)}`; }
function identifier(value) { return String(value).replace(/[^A-Za-z0-9_]/g, '_').replace(/^[0-9]/, '_$&'); }
function layoutInt(value, fallback) { return Number.isFinite(Number(value)) ? Math.max(0, Math.round(Number(value))) : fallback; }
function positiveInt(value, fallback) { return Number.isFinite(Number(value)) ? Math.max(1, Math.round(Number(value))) : fallback; }
function cString(value) { return JSON.stringify(String(value ?? '')); }
