import { emitGtkGuiCpp as emitGtkGuiCppV08 } from './gtk-gui-v08.js';
import { adaptNativeTablesForLegacyBackend, tableEventIndexById } from './native-table-backend-adapter.js';
import { applyGtkTableOverlayV09 } from './gtk-table-overlay-v09.js';

export const PATCH_GTK_GUI_BACKEND_V09_VERSION = '0.9';

/** Emit GTK backend v0.9 with real GtkTreeView/GtkListStore Tables. */
export function emitGtkGuiCppV09(input) {
  const adapted = adaptNativeTablesForLegacyBackend(input);
  let source = emitGtkGuiCppV08(adapted.legacyIr)
    .replace(/Generated by Patch GTK GUI backend 0\.8\./, `Generated by Patch GTK GUI backend ${PATCH_GTK_GUI_BACKEND_V09_VERSION}.`);
  if (!adapted.tables.length) return source;
  return applyGtkTableOverlayV09(source, adapted, tableEventIndexById(adapted.ir));
}
