import { NativeGuiError } from './native-gui-ir.js';
import { emitGtkGuiCppV10 } from './gtk-gui-v10.js';
import { adaptNativeMenuStateForV10Backend } from './native-menu-state-backend-adapter.js';

export const PATCH_GTK_GUI_BACKEND_V11_VERSION = '1.1';

/** Emit GTK backend 1.1 with source-backed enabled/checked MenuItem state. */
export function emitGtkGuiCppV11(input) {
  const adapted = adaptNativeMenuStateForV10Backend(input);
  let source = emitGtkGuiCppV10(adapted.compatibleIr)
    .replace(/Generated by Patch GTK GUI backend 1\.0\./, `Generated by Patch GTK GUI backend ${PATCH_GTK_GUI_BACKEND_V11_VERSION}.`);

  if (!adapted.statefulItems.length) return source;

  for (const item of adapted.checkedItems) {
    const marker = `GtkWidget *entry = gtk_menu_item_new_with_label(${cString(item.legacyText)}); gtk_menu_shell_append(GTK_MENU_SHELL(submenu_${item.formIndex}_${item.menuIndex}), entry); g_signal_connect(entry, "activate", G_CALLBACK(OnClicked), GINT_TO_POINTER(${item.commandId}));`;
    const replacement = `GtkWidget *entry = gtk_check_menu_item_new_with_label(${cString(item.legacyText)}); gtk_check_menu_item_set_draw_as_radio(GTK_CHECK_MENU_ITEM(entry), FALSE); gtk_menu_shell_append(GTK_MENU_SHELL(submenu_${item.formIndex}_${item.menuIndex}), entry); g_signal_connect(entry, "activate", G_CALLBACK(OnClicked), GINT_TO_POINTER(${item.commandId}));`;
    source = replaceRequired(source, marker, replacement, `GTK checked MenuItem '${item.id}' creation`);
  }

  const refreshLines = [];
  for (const item of adapted.statefulItems) {
    if (item.enabledState) {
      refreshLines.push(`  if (gMenuItems[${item.legacyNativeIndex}]) gtk_widget_set_sensitive(gMenuItems[${item.legacyNativeIndex}], ${stateName(item.enabledState)} ? TRUE : FALSE);`);
    }
    if (item.checkedState) {
      refreshLines.push(`  if (gMenuItems[${item.legacyNativeIndex}]) gtk_check_menu_item_set_active(GTK_CHECK_MENU_ITEM(gMenuItems[${item.legacyNativeIndex}]), ${stateName(item.checkedState)} ? TRUE : FALSE);`);
    }
  }

  source = replaceRequired(
    source,
    'static void RefreshUI() {\n  gRefreshing = true;',
    `static void RefreshUI() {\n  gRefreshing = true;\n${refreshLines.join('\n')}`,
    'GTK Menu state RefreshUI insertion'
  );

  const enabledById = new Map(adapted.enabledItems.map(item => [item.id, item]));
  for (let eventIndex = 0; eventIndex < adapted.ir.events.length; eventIndex += 1) {
    const event = adapted.ir.events[eventIndex];
    const item = enabledById.get(event.control);
    if (!item || event.event !== 'clicked') continue;
    const marker = `  if (commandId == ${item.commandId}) { Event_${eventIndex}(); return; }`;
    const replacement = `  if (commandId == ${item.commandId}) { if (!${stateName(item.enabledState)}) return; Event_${eventIndex}(); return; }`;
    source = replaceRequired(source, marker, replacement, `GTK enabled MenuItem '${item.id}' dispatch guard`);
  }

  return source;
}

function stateName(name) { return `patch_state_${identifier(name)}`; }
function identifier(value) { return String(value).replace(/[^A-Za-z0-9_]/g, '_').replace(/^[0-9]/, '_$&'); }
function cString(value) { return JSON.stringify(String(value ?? '')); }
function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated GTK source.`);
  return source.replace(marker, replacement);
}
