import { NativeGuiError } from './native-gui-ir.js';
import { nativeAccessibleName } from './native-accessibility.js';
import { emitGtkGuiCppV13 } from './gtk-gui-v13.js';
import { adaptNativeSlidersForV13Backend, sliderPersistentNumberTarget } from './native-slider-backend-adapter.js';

export const PATCH_GTK_GUI_BACKEND_V14_VERSION = '1.4';

/** Emit GTK backend 1.4 with real GtkScale controls. */
export function emitGtkGuiCppV14(input) {
  const adapted = adaptNativeSlidersForV13Backend(input);
  let source = emitGtkGuiCppV13(adapted.compatibleIr)
    .replace(/Generated by Patch GTK GUI backend 1\.3\./, `Generated by Patch GTK GUI backend ${PATCH_GTK_GUI_BACKEND_V14_VERSION}.`);
  if (!adapted.sliders.length) return source;

  for (const slider of adapted.sliders) {
    source = removeShadowState(source, slider);
    source = removeShadowRefresh(source, slider);
    source = replaceControlBlock(source, slider, sliderCreate(adapted, slider));
  }

  for (const patch of adapted.eventPatches) {
    source = patchSliderEventFunction(source, patch);
    const slider = adapted.sliders.find(item => item.id === patch.control);
    if (!slider) continue;
    source = replaceRequired(
      source,
      `  if (commandId == ${slider.commandId}) { Event_${patch.eventIndex}(gtk_entry_get_text(GTK_ENTRY(editable))); return; }\n`,
      '',
      `GTK Slider '${slider.id}' legacy Input dispatch`
    );
  }

  const marker = 'static gboolean OnDelete(GtkWidget *widget, GdkEvent *, gpointer data) {';
  source = replaceRequired(source, marker, `${emitSliderHelpers(adapted)}\n\n${marker}`, 'GTK Slider helper insertion');
  source = injectSliderRefresh(source, adapted);
  source = injectSliderSmoke(source, adapted);
  assertNoShadowState(source, adapted);
  return source;
}

function patchSliderEventFunction(source, patch) {
  const oldSignature = `static void Event_${patch.eventIndex}(const std::string& eventValue) {`;
  const newSignature = `static void Event_${patch.eventIndex}(double eventValue) {`;
  const start = source.indexOf(oldSignature);
  if (start < 0) throw new NativeGuiError(`GTK Slider Event_${patch.eventIndex} signature marker is missing.`);
  const endMarker = '\n  RefreshUI();\n}';
  const end = source.indexOf(endMarker, start);
  if (end < 0) throw new NativeGuiError(`GTK Slider Event_${patch.eventIndex} body marker is missing.`);
  let body = source.slice(start, end + endMarker.length).replace(oldSignature, newSignature);
  for (const sentinel of patch.sentinels) body = body.replaceAll(String(sentinel), 'eventValue');
  return source.slice(0, start) + body + source.slice(end + endMarker.length);
}

function emitSliderHelpers(adapted) {
  const valueFns = adapted.sliders.map(slider =>
    `static double PatchSliderValue_${slider.nativeIndex}(GtkRange *range) { if (!range) return ${number(slider.min)}; double raw=gtk_range_get_value(range); double steps=std::round((raw-${number(slider.min)})/${number(slider.step)}); double value=${number(slider.min)}+steps*${number(slider.step)}; if(value<${number(slider.min)})value=${number(slider.min)}; if(value>${number(slider.max)})value=${number(slider.max)}; return value; }`
  ).join('\n');
  const dispatch = adapted.sliders.map(slider => {
    const eventIndex = adapted.events.findIndex(event => event.control === slider.id && event.event === 'changed');
    return eventIndex >= 0 ? `  if (commandId == ${slider.commandId}) { Event_${eventIndex}(PatchSliderValue_${slider.nativeIndex}(range)); return; }` : '';
  }).filter(Boolean).join('\n');
  return `${valueFns}\nstatic void OnPatchSliderChanged(GtkRange *range, gpointer data) {\n  if (gRefreshing) return;\n  int commandId=GPOINTER_TO_INT(data);\n${dispatch || '  (void)commandId; (void)range;'}\n}`;
}

function sliderCreate(adapted, slider) {
  const control = adapted.controls[slider.nativeIndex];
  const x = layoutInt(control.layout?.x, control.parentTabIndex >= 0 ? 12 : 24);
  const y = layoutInt(control.layout?.y, control.parentTabIndex >= 0 ? 12 : 24);
  const width = positiveInt(control.layout?.width, 260), height = positiveInt(control.layout?.height, 44);
  const put = control.parentTabIndex >= 0
    ? `GtkWidget *parent = gTabPages[${control.parentTabIndex}].at(${control.pageIndex}); gtk_fixed_put(GTK_FIXED(parent), control, ${x}, ${y});`
    : `gtk_fixed_put(GTK_FIXED(fixed), control, ${x}, ${y});`;
  const initialExpr = slider.binding ? stateName(slider.binding) : number(slider.min);
  const accessibleName = nativeAccessibleName(control) ?? slider.id;
  return `  if (${control.formIndex} == index) {\n    GtkWidget *control = gtk_scale_new_with_range(GTK_ORIENTATION_HORIZONTAL, ${number(slider.min)}, ${number(slider.max)}, ${number(slider.step)}); gtk_scale_set_draw_value(GTK_SCALE(control), FALSE); gtk_range_set_value(GTK_RANGE(control), ${initialExpr}); gtk_widget_set_size_request(control, ${width}, ${height}); g_signal_connect(control, "value-changed", G_CALLBACK(OnPatchSliderChanged), GINT_TO_POINTER(${slider.commandId})); ${put} gControls[${slider.nativeIndex}] = control; AtkObject *accessible=gtk_widget_get_accessible(control); if(accessible)atk_object_set_name(accessible,${cString(accessibleName)});\n  }`;
}

function injectSliderRefresh(source, adapted) {
  const start = source.indexOf('static void RefreshUI() {');
  if (start < 0) throw new NativeGuiError('Generated GTK source is missing RefreshUI for Slider state.');
  const marker = '  gRefreshing = false;';
  const at = source.indexOf(marker, start);
  if (at < 0) throw new NativeGuiError('Generated GTK Slider refresh insertion point is missing.');
  const lines = adapted.sliders.filter(slider => slider.binding).map(slider =>
    `  if (gControls[${slider.nativeIndex}]) gtk_range_set_value(GTK_RANGE(gControls[${slider.nativeIndex}]), ${stateName(slider.binding)});`
  );
  return source.slice(0, at) + (lines.length ? lines.join('\n') + '\n' : '') + source.slice(at);
}

function injectSliderSmoke(source, adapted) {
  const start = source.indexOf('static int RunPatchSmoke() {');
  if (start < 0) throw new NativeGuiError('Generated GTK source is missing Slider smoke function.');
  let at = source.indexOf('  gtk_widget_destroy(gForms[', start);
  if (at < 0) at = source.indexOf('  return 0;', start);
  if (at < 0) throw new NativeGuiError('Generated GTK Slider smoke insertion point is missing.');
  const checks = [];
  let code = 240;
  for (const slider of adapted.sliders) {
    checks.push(`  if (!gControls[${slider.nativeIndex}] || !GTK_IS_SCALE(gControls[${slider.nativeIndex}])) return ${code++};`);
    const eventIndex = adapted.events.findIndex(event => event.control === slider.id && event.event === 'changed');
    if (eventIndex < 0) continue;
    checks.push(`  gtk_range_set_value(GTK_RANGE(gControls[${slider.nativeIndex}]), ${number(slider.max)}); OnPatchSliderChanged(GTK_RANGE(gControls[${slider.nativeIndex}]), GINT_TO_POINTER(${slider.commandId}));`);
    const target = sliderPersistentNumberTarget(adapted.events[eventIndex], adapted.states);
    if (target) checks.push(`  if (std::fabs(${stateName(target)} - PatchSliderValue_${slider.nativeIndex}(GTK_RANGE(gControls[${slider.nativeIndex}]))) > 1e-9) return ${code++};`);
  }
  return source.slice(0, at) + checks.join('\n') + '\n' + source.slice(at);
}

function replaceControlBlock(source, slider, replacement) {
  const tag = `GINT_TO_POINTER(${slider.commandId})`;
  const tagAt = source.indexOf(tag);
  if (tagAt < 0) throw new NativeGuiError(`GTK Slider '${slider.id}' shadow command is missing.`);
  const start = source.lastIndexOf(`  if (${slider.formIndex} == index) {`, tagAt);
  const end = source.indexOf('\n  }', tagAt);
  if (start < 0 || end < 0) throw new NativeGuiError(`GTK Slider '${slider.id}' shadow control block is missing.`);
  return source.slice(0, start) + replacement + source.slice(end + 4);
}
function removeShadowState(source, slider) { return replaceRequired(source, `static std::string ${stateName(slider.shadowState)} = ${cString(String(slider.initial))};\n`, '', `GTK Slider '${slider.id}' shadow state`); }
function removeShadowRefresh(source, slider) { return replaceRequired(source, `  if (gControls[${slider.nativeIndex}]) gtk_entry_set_text(GTK_ENTRY(gControls[${slider.nativeIndex}]), ${stateName(slider.shadowState)}.c_str());\n`, '', `GTK Slider '${slider.id}' shadow refresh`); }
function assertNoShadowState(source, adapted) { for (const slider of adapted.sliders) if (source.includes(slider.shadowState)) throw new NativeGuiError(`GTK Slider '${slider.id}' leaked backend shadow state.`); }
function stateName(name){return `patch_state_${identifier(name)}`;} function identifier(value){return String(value).replace(/[^A-Za-z0-9_]/g,'_').replace(/^[0-9]/,'_$&');} function cString(value){return JSON.stringify(String(value??''));} function number(value){return String(Number(value));} function layoutInt(value,fallback){return Number.isFinite(Number(value))?Math.max(0,Math.round(Number(value))):fallback;} function positiveInt(value,fallback){return Number.isFinite(Number(value))?Math.max(1,Math.round(Number(value))):fallback;} function replaceRequired(source,marker,replacement,label){if(!source.includes(marker))throw new NativeGuiError(`${label} marker is missing from generated GTK source.`);return source.replace(marker,replacement);}
