import { flattenNativeGuiControls, flattenNativeGuiMenuItems, validateNativeGuiIR, NativeGuiError } from './native-gui-ir.js';

export const PATCH_GTK_GUI_BACKEND_VERSION = '0.6';

export function emitGtkGuiCpp(input) {
  const ir = validateNativeGuiIR(input);
  const forms = new Map(ir.forms.map((form, index) => [form.id, index]));
  const controls = flattenNativeGuiControls(ir).map(control => ({
    ...control,
    commandId: 1000 + control.nativeIndex,
    handleIndex: control.nativeIndex
  }));
  const menuItems = flattenNativeGuiMenuItems(ir).map(item => ({ ...item, commandId: 20000 + item.nativeIndex }));
  const controlsById = new Map(controls.filter(control => control.id).map(control => [control.id, control]));
  const menuById = new Map(menuItems.map(item => [item.id, item]));
  const sourcesById = new Map([...controlsById, ...menuById]);
  const states = new Map(ir.states.map(state => [state.name, state]));
  validateReferences(ir, forms, sourcesById);

  const stateDecls = ir.states.map(stateDeclaration).join('\n');
  const formDefs = ir.forms.map((form, index) =>
    `  {${cString(form.id)}, ${cString(form.title)}, ${positiveInt(form.width, 640)}, ${positiveInt(form.height, 420)}, ${form.visible ? 'true' : 'false'}}${index + 1 === ir.forms.length ? '' : ','}`
  ).join('\n');
  const controlDefs = controls.map((control, index) =>
    `  {${control.commandId}, ${control.formIndex}, ${controlKind(control.type)}, ${cString(control.id ?? '')}, ${layoutInt(control.layout?.x, 24)}, ${layoutInt(control.layout?.y, 24)}, ${positiveInt(control.layout?.width, 120)}, ${positiveInt(control.layout?.height, 36)}, ${control.parentTabIndex ?? -1}, ${control.pageIndex ?? -1}}${index + 1 === controls.length ? '' : ','}`
  ).join('\n');
  const textFunctions = controls.map((control, index) => emitControlTextFunction(control, index, states)).join('\n\n');
  const eventFunctions = ir.events.map((event, index) => emitEventFunction(event, index, forms, states)).join('\n\n');
  const clickedDispatch = ir.events.map((event, index) => emitClickedDispatch(event, index, controlsById, menuById)).filter(Boolean).join('\n');
  const toggledDispatch = ir.events.map((event, index) => emitToggledDispatch(event, index, controlsById)).filter(Boolean).join('\n');
  const radioDispatch = ir.events.map((event, index) => emitRadioDispatch(event, index, controlsById)).filter(Boolean).join('\n');
  const changedDispatch = ir.events.map((event, index) => emitChangedDispatch(event, index, controlsById)).filter(Boolean).join('\n');
  const comboDispatch = ir.events.map((event, index) => emitComboDispatch(event, index, controlsById)).filter(Boolean).join('\n');
  const listDispatch = ir.events.map((event, index) => emitListDispatch(event, index, controlsById)).filter(Boolean).join('\n');
  const refresh = controls.map((control, index) => emitRefresh(control, index, states)).filter(Boolean).join('\n');
  const create = controls.map((control, index) => emitCreateControl(control, index)).join('\n');
  const createMenus = ir.forms.map((form, index) => emitCreateMenus(form, index, menuById)).filter(Boolean).join('\n');
  const smoke = emitSmoke(forms, controlsById, menuById, states);

  return `// Generated by Patch GTK GUI backend ${PATCH_GTK_GUI_BACKEND_VERSION}.
// Direct native GTK controls: no Electron/Chromium runtime.
#include <gtk/gtk.h>
#include <cmath>
#include <cstring>
#include <sstream>
#include <string>
#include <vector>

static bool gRefreshing = false;
static bool gSmokeMode = false;
static std::string gLastDialogTitle;
static std::string gLastDialogMessage;

enum ControlKind { CK_TEXT=1, CK_BUTTON=2, CK_INPUT=3, CK_CHECKBOX=4, CK_COMBO=5, CK_LISTBOX=6, CK_TABS=7, CK_RADIO=8 };
struct FormDef { const char *formId; const char *title; int width; int height; bool visible; };
struct ControlDef { int commandId; int formIndex; ControlKind kind; const char *name; int x; int y; int width; int height; int parentTabIndex; int pageIndex; };

${stateDecls}

static const FormDef FORMS[] = {
${formDefs}
};
static const int FORM_COUNT = ${ir.forms.length};
static GtkWidget *gForms[${Math.max(1, ir.forms.length)}] = {};
static GtkWidget *gFixed[${Math.max(1, ir.forms.length)}] = {};

static const ControlDef CONTROLS[] = {
${controlDefs || '  {0,0,CK_TEXT,"",0,0,0,0,-1,-1}'}
};
static const int CONTROL_COUNT = ${controls.length};
static GtkWidget *gControls[${Math.max(1, controls.length)}] = {};
static std::vector<GtkWidget*> gTabPages[${Math.max(1, controls.length)}];
static std::vector<GtkWidget*> gRadioItems[${Math.max(1, controls.length)}];
static GtkWidget *gMenuItems[${Math.max(1, menuItems.length)}] = {};

static std::string PatchNumber(double value) {
  if (std::isfinite(value) && std::floor(value) == value) return std::to_string((long long)value);
  std::ostringstream out; out.precision(15); out << value; return out.str();
}
static std::string PatchBoolean(bool value) { return value ? "true" : "false"; }
static void ShowInfoDialog(int formIndex, const char *title, const char *message) {
  if (gSmokeMode) { gLastDialogTitle = title ? title : ""; gLastDialogMessage = message ? message : ""; return; }
  GtkWidget *dialog = gtk_message_dialog_new(
    formIndex >= 0 && formIndex < FORM_COUNT ? GTK_WINDOW(gForms[formIndex]) : nullptr,
    GTK_DIALOG_MODAL | GTK_DIALOG_DESTROY_WITH_PARENT,
    GTK_MESSAGE_INFO,
    GTK_BUTTONS_OK,
    "%s", message ? message : "");
  gtk_window_set_title(GTK_WINDOW(dialog), title ? title : "");
  gtk_dialog_run(GTK_DIALOG(dialog));
  gtk_widget_destroy(dialog);
}

${textFunctions}

static void RefreshUI();

${eventFunctions}

static void OnClicked(GtkWidget *, gpointer data) {
  if (gRefreshing) return;
  int commandId = GPOINTER_TO_INT(data);
${clickedDispatch || '  (void)commandId;'}
}
static void OnToggled(GtkToggleButton *button, gpointer data) {
  if (gRefreshing) return;
  int commandId = GPOINTER_TO_INT(data);
${toggledDispatch || '  (void)commandId; (void)button;'}
}
static void OnRadioToggled(GtkToggleButton *button, gpointer data) {
  if (gRefreshing || !gtk_toggle_button_get_active(button)) return;
  int commandId = GPOINTER_TO_INT(data);
${radioDispatch || '  (void)commandId; (void)button;'}
}
static void OnChanged(GtkEditable *editable, gpointer data) {
  if (gRefreshing) return;
  int commandId = GPOINTER_TO_INT(data);
${changedDispatch || '  (void)commandId; (void)editable;'}
}
static void OnComboChanged(GtkComboBox *combo, gpointer data) {
  if (gRefreshing) return;
  int commandId = GPOINTER_TO_INT(data);
${comboDispatch || '  (void)commandId; (void)combo;'}
}
static void OnListChanged(GtkListBox *box, GtkListBoxRow *row, gpointer data) {
  if (gRefreshing) return;
  int commandId = GPOINTER_TO_INT(data);
${listDispatch || '  (void)commandId; (void)box; (void)row;'}
}

static gboolean OnDelete(GtkWidget *widget, GdkEvent *, gpointer data) {
  int formIndex = GPOINTER_TO_INT(data);
  if (formIndex == 0) { gtk_main_quit(); return FALSE; }
  gtk_widget_hide(widget);
  return TRUE;
}

static void RefreshUI() {
  gRefreshing = true;
${refresh}
  gRefreshing = false;
}

static GtkWidget *CreatePatchForm(int index) {
  GtkWidget *window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title(GTK_WINDOW(window), FORMS[index].title);
  gtk_window_set_default_size(GTK_WINDOW(window), FORMS[index].width, FORMS[index].height);
  gtk_window_set_resizable(GTK_WINDOW(window), TRUE);
  g_signal_connect(window, "delete-event", G_CALLBACK(OnDelete), GINT_TO_POINTER(index));
  GtkWidget *root = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
  gtk_container_add(GTK_CONTAINER(window), root);
${createMenus}
  GtkWidget *fixed = gtk_fixed_new();
  gtk_box_pack_start(GTK_BOX(root), fixed, TRUE, TRUE, 0);
  gForms[index] = window;
  gFixed[index] = fixed;
${create}
  return window;
}

static bool HasArg(int argc, char *argv[], const char *value) {
  for (int i = 1; i < argc; ++i) if (strcmp(argv[i], value) == 0) return true;
  return false;
}

${smoke}

int main(int argc, char *argv[]) {
  gSmokeMode = HasArg(argc, argv, "--patch-smoke");
  gtk_init(&argc, &argv);
  for (int i = 0; i < FORM_COUNT; ++i) if (!CreatePatchForm(i)) return 10 + i;
  RefreshUI();
  for (int i = 0; i < FORM_COUNT; ++i) if (FORMS[i].visible) gtk_widget_show_all(gForms[i]);
  if (gSmokeMode) return RunPatchSmoke();
  gtk_main();
  return 0;
}
`;
}

function validateReferences(ir, forms, sources) {
  for (const event of ir.events) {
    if (!sources.has(event.control)) throw new NativeGuiError(`GTK event source '${event.control}' is missing.`);
    for (const action of event.actions ?? []) {
      if ((action.kind === 'openForm' || action.kind === 'closeForm' || action.kind === 'dialog') && !forms.has(action.form)) throw new NativeGuiError(`GTK Form '${action.form}' is missing.`);
    }
  }
}
function stateDeclaration(state) {
  const name = stateName(state.name);
  if (state.type === 'boolean') return `static bool ${name} = ${state.initial ? 'true' : 'false'};`;
  if (state.type === 'number') return `static double ${name} = ${Number(state.initial)};`;
  if (state.type === 'text') return `static std::string ${name} = ${cString(state.initial)};`;
  throw new NativeGuiError(`GTK state type '${state.type}' is unsupported.`);
}
function emitControlTextFunction(control, index, states) {
  const text = String(control.text ?? '');
  const lines = ['  std::string out;'];
  let cursor = 0;
  const re = /\{([A-Za-z_]\w*)\}/g;
  let match;
  while ((match = re.exec(text))) {
    if (match.index > cursor) lines.push(`  out += ${cString(text.slice(cursor, match.index))};`);
    const state = states.get(match[1]);
    if (!state) throw new NativeGuiError(`GTK text '${text}' refers to unknown state '${match[1]}'.`);
    if (state.type === 'boolean') lines.push(`  out += PatchBoolean(${stateName(state.name)});`);
    else if (state.type === 'number') lines.push(`  out += PatchNumber(${stateName(state.name)});`);
    else lines.push(`  out += ${stateName(state.name)};`);
    cursor = match.index + match[0].length;
  }
  if (cursor < text.length) lines.push(`  out += ${cString(text.slice(cursor))};`);
  lines.push('  return out;');
  return `static std::string ControlText_${index}() {\n${lines.join('\n')}\n}`;
}
function emitEventFunction(event, index, forms, states) {
  const param = event.valueType === 'boolean' ? 'bool eventValue' : event.valueType === 'text' ? 'const std::string& eventValue' : '';
  const actions = (event.actions ?? []).map(action => emitAction(action, event, forms, states)).join('\n');
  return `static void Event_${index}(${param}) {\n${actions || '  // no-op'}\n  RefreshUI();\n}`;
}
function emitAction(action, event, forms, states) {
  if (action.kind === 'openForm') return `  gtk_widget_show_all(gForms[${forms.get(action.form)}]); gtk_window_present(GTK_WINDOW(gForms[${forms.get(action.form)}]));`;
  if (action.kind === 'closeForm') return `  gtk_widget_hide(gForms[${forms.get(action.form)}]);`;
  if (action.kind === 'dialog') return `  ShowInfoDialog(${forms.get(action.form)}, ${cString(action.title)}, ${cString(action.message)});`;
  if (action.kind !== 'change') throw new NativeGuiError(`GTK action '${action.kind}' is unsupported.`);
  const state = states.get(action.target);
  if (!state) throw new NativeGuiError(`GTK change target '${action.target}' is missing.`);
  return (action.ops ?? []).map(op => emitOperation(state, op, event)).join('\n');
}
function emitOperation(state, op, event) {
  const target = stateName(state.name);
  if (op.op === 'clear') {
    if (state.type === 'boolean') return `  ${target} = false;`;
    if (state.type === 'number') return `  ${target} = 0.0;`;
    return `  ${target}.clear();`;
  }
  const value = emitNativeValue(state, op.value, event);
  if (op.op === 'set') return `  ${target} = ${value};`;
  if (op.op === 'add' && state.type === 'number') return `  ${target} += ${value};`;
  if (op.op === 'remove' && state.type === 'number') return `  ${target} -= ${value};`;
  if (op.op === 'add' && state.type === 'text') return `  ${target} += ${value};`;
  throw new NativeGuiError(`GTK native GUI cannot apply '${op.op}' to ${state.type} state '${state.name}'.`);
}
function emitNativeValue(state, value, event) {
  if (value?.kind === 'eventValue') {
    if (state.type !== event.valueType) throw new NativeGuiError(`GTK event value type ${event.valueType ?? 'none'} cannot be assigned to ${state.type} state '${state.name}'.`);
    return 'eventValue';
  }
  if (state.type === 'boolean') return value?.value ? 'true' : 'false';
  if (state.type === 'number') return String(Number(value?.value));
  if (state.type === 'text') return `std::string(${cString(value?.value)})`;
  throw new NativeGuiError(`GTK literal type '${state.type}' is unsupported.`);
}
function emitClickedDispatch(event, index, controls, menus) {
  const menu = menus.get(event.control);
  if (menu) return `  if (commandId == ${menu.commandId}) { Event_${index}(); return; }`;
  const control = controls.get(event.control);
  return control?.type === 'button' ? `  if (commandId == ${control.commandId}) { Event_${index}(); return; }` : '';
}
function emitToggledDispatch(event, index, controls) {
  const control = controls.get(event.control);
  return control?.type === 'checkbox' ? `  if (commandId == ${control.commandId}) { Event_${index}(gtk_toggle_button_get_active(button)); return; }` : '';
}
function emitRadioDispatch(event, index, controls) {
  const control = controls.get(event.control);
  if (control?.type !== 'radio') return '';
  return `  if (commandId == ${control.commandId}) { const char *value = gtk_button_get_label(GTK_BUTTON(button)); Event_${index}(value ? std::string(value) : std::string()); return; }`;
}
function emitChangedDispatch(event, index, controls) {
  const control = controls.get(event.control);
  return control?.type === 'input' ? `  if (commandId == ${control.commandId}) { Event_${index}(gtk_entry_get_text(GTK_ENTRY(editable))); return; }` : '';
}
function emitComboDispatch(event, index, controls) {
  const control = controls.get(event.control);
  return control?.type === 'combo' ? `  if (commandId == ${control.commandId}) { gchar *value = gtk_combo_box_text_get_active_text(GTK_COMBO_BOX_TEXT(combo)); Event_${index}(value ? std::string(value) : std::string()); if (value) g_free(value); return; }` : '';
}
function emitListDispatch(event, index, controls) {
  const control = controls.get(event.control);
  if (control?.type !== 'listbox') return '';
  return `  if (commandId == ${control.commandId}) { if (!row) { Event_${index}(std::string()); return; } GtkWidget *child = gtk_bin_get_child(GTK_BIN(row)); const char *value = child ? gtk_label_get_text(GTK_LABEL(child)) : ""; Event_${index}(value ? std::string(value) : std::string()); return; }`;
}
function emitRefresh(control, index, states) {
  if (control.type === 'tabs') return '';
  if (control.type === 'text') return `  if (gControls[${index}]) { auto value = ControlText_${index}(); if (value != gtk_label_get_text(GTK_LABEL(gControls[${index}]))) gtk_label_set_text(GTK_LABEL(gControls[${index}]), value.c_str()); }`;
  if (control.type === 'button') return `  if (gControls[${index}]) { auto value = ControlText_${index}(); const char *old = gtk_button_get_label(GTK_BUTTON(gControls[${index}])); if (!old || value != old) gtk_button_set_label(GTK_BUTTON(gControls[${index}]), value.c_str()); }`;
  if (control.type === 'checkbox') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) { auto value = ControlText_${index}(); const char *old = gtk_button_get_label(GTK_BUTTON(gControls[${index}])); if (!old || value != old) gtk_button_set_label(GTK_BUTTON(gControls[${index}]), value.c_str()); gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(gControls[${index}]), ${stateName(state.name)} ? TRUE : FALSE); }`;
  }
  if (control.type === 'input') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) { const char *old = gtk_entry_get_text(GTK_ENTRY(gControls[${index}])); if (!old || ${stateName(state.name)} != old) gtk_entry_set_text(GTK_ENTRY(gControls[${index}]), ${stateName(state.name)}.c_str()); }`;
  }
  if (control.type === 'combo') {
    const state = states.get(control.binding);
    const checks = control.options.map((option, optionIndex) => `if (${stateName(state.name)} == ${cString(option)}) selected = ${optionIndex};`).join(' else ');
    return `  if (gControls[${index}]) { int selected = -1; ${checks} gtk_combo_box_set_active(GTK_COMBO_BOX(gControls[${index}]), selected); }`;
  }
  if (control.type === 'listbox') {
    const state = states.get(control.binding);
    const checks = control.options.map((option, optionIndex) => `if (${stateName(state.name)} == ${cString(option)}) selected = ${optionIndex};`).join(' else ');
    return `  if (gControls[${index}]) { int selected = -1; ${checks} GtkListBoxRow *row = selected >= 0 ? gtk_list_box_get_row_at_index(GTK_LIST_BOX(gControls[${index}]), selected) : nullptr; gtk_list_box_select_row(GTK_LIST_BOX(gControls[${index}]), row); }`;
  }
  if (control.type === 'radio') {
    const state = states.get(control.binding);
    return `  for (GtkWidget *item : gRadioItems[${index}]) { const char *label = gtk_button_get_label(GTK_BUTTON(item)); gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(item), label && ${stateName(state.name)} == label ? TRUE : FALSE); }`;
  }
  return '';
}
function emitCreateMenus(form, formIndex, menuById) {
  if (!form.menus.length) return '';
  const menus = form.menus.map((menu, menuIndex) => {
    const items = menu.items.map(item => {
      const native = menuById.get(item.id);
      return `    { GtkWidget *entry = gtk_menu_item_new_with_label(${cString(item.text)}); gtk_menu_shell_append(GTK_MENU_SHELL(submenu_${formIndex}_${menuIndex}), entry); g_signal_connect(entry, "activate", G_CALLBACK(OnClicked), GINT_TO_POINTER(${native.commandId})); gMenuItems[${native.nativeIndex}] = entry; }`;
    }).join('\n');
    return `    GtkWidget *root_${formIndex}_${menuIndex} = gtk_menu_item_new_with_label(${cString(menu.title)});\n    GtkWidget *submenu_${formIndex}_${menuIndex} = gtk_menu_new();\n    gtk_menu_item_set_submenu(GTK_MENU_ITEM(root_${formIndex}_${menuIndex}), submenu_${formIndex}_${menuIndex});\n${items}\n    gtk_menu_shell_append(GTK_MENU_SHELL(menuBar), root_${formIndex}_${menuIndex});`;
  }).join('\n');
  return `  if (${formIndex} == index) {\n    GtkWidget *menuBar = gtk_menu_bar_new();\n${menus}\n    gtk_box_pack_start(GTK_BOX(root), menuBar, FALSE, FALSE, 0);\n  }`;
}
function emitCreateControl(control, index) {
  const x = layoutInt(control.layout?.x, control.parentTabIndex >= 0 ? 12 : 24);
  const y = layoutInt(control.layout?.y, control.parentTabIndex >= 0 ? 12 : 24);
  const width = positiveInt(control.layout?.width, 120);
  const height = positiveInt(control.layout?.height, 36);
  if (control.type === 'tabs') {
    const pages = control.pageTitles.map((title, pageIndex) =>
      `    { GtkWidget *page = gtk_fixed_new(); GtkWidget *label = gtk_label_new(${cString(title)}); gtk_notebook_append_page(GTK_NOTEBOOK(control), page, label); gTabPages[${index}].push_back(page); }`
    ).join('\n');
    return `  if (${control.formIndex} == index) {\n    GtkWidget *control = gtk_notebook_new();\n    gtk_widget_set_size_request(control, ${width}, ${height});\n    gtk_fixed_put(GTK_FIXED(fixed), control, ${x}, ${y});\n${pages}\n    gtk_notebook_set_current_page(GTK_NOTEBOOK(control), 0);\n    gControls[${index}] = control;\n  }`;
  }
  if (control.type === 'radio') {
    const target = control.parentTabIndex >= 0
      ? `GtkWidget *parent = gTabPages[${control.parentTabIndex}].at(${control.pageIndex}); gtk_fixed_put(GTK_FIXED(parent), control, ${x}, ${y});`
      : `gtk_fixed_put(GTK_FIXED(fixed), control, ${x}, ${y});`;
    const items = control.options.map((option, optionIndex) =>
      `    GtkWidget *radio_${index}_${optionIndex} = gtk_radio_button_new_with_label(group, ${cString(option)}); group = gtk_radio_button_get_group(GTK_RADIO_BUTTON(radio_${index}_${optionIndex})); gtk_box_pack_start(GTK_BOX(control), radio_${index}_${optionIndex}, FALSE, FALSE, 0); g_signal_connect(radio_${index}_${optionIndex}, "toggled", G_CALLBACK(OnRadioToggled), GINT_TO_POINTER(${control.commandId})); gRadioItems[${index}].push_back(radio_${index}_${optionIndex});`
    ).join('\n');
    return `  if (${control.formIndex} == index) {\n    GtkWidget *control = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0); GSList *group = nullptr;\n${items}\n    gtk_widget_set_size_request(control, ${width}, ${height});\n    ${target}\n    gControls[${index}] = control;\n  }`;
  }
  let create = '';
  if (control.type === 'text') create = 'GtkWidget *control = gtk_label_new(""); gtk_label_set_xalign(GTK_LABEL(control), 0.0f);';
  else if (control.type === 'button') create = 'GtkWidget *control = gtk_button_new_with_label("");';
  else if (control.type === 'input') create = 'GtkWidget *control = gtk_entry_new();';
  else if (control.type === 'checkbox') create = 'GtkWidget *control = gtk_check_button_new_with_label("");';
  else if (control.type === 'combo') create = `GtkWidget *control = gtk_combo_box_text_new(); ${control.options.map(option => `gtk_combo_box_text_append_text(GTK_COMBO_BOX_TEXT(control), ${cString(option)});`).join(' ')}`;
  else if (control.type === 'listbox') create = `GtkWidget *control = gtk_list_box_new(); gtk_list_box_set_selection_mode(GTK_LIST_BOX(control), GTK_SELECTION_SINGLE); ${control.options.map((option, optionIndex) => `GtkWidget *label_${index}_${optionIndex} = gtk_label_new(${cString(option)}); gtk_widget_set_halign(label_${index}_${optionIndex}, GTK_ALIGN_START); gtk_widget_set_margin_start(label_${index}_${optionIndex}, 8); gtk_widget_set_margin_end(label_${index}_${optionIndex}, 8); gtk_widget_set_margin_top(label_${index}_${optionIndex}, 5); gtk_widget_set_margin_bottom(label_${index}_${optionIndex}, 5); gtk_list_box_insert(GTK_LIST_BOX(control), label_${index}_${optionIndex}, -1);`).join(' ')}`;
  else throw new NativeGuiError(`GTK control '${control.type}' is unsupported.`);
  let signal = '';
  if (control.type === 'button') signal = `g_signal_connect(control, "clicked", G_CALLBACK(OnClicked), GINT_TO_POINTER(${control.commandId}));`;
  if (control.type === 'checkbox') signal = `g_signal_connect(control, "toggled", G_CALLBACK(OnToggled), GINT_TO_POINTER(${control.commandId}));`;
  if (control.type === 'input') signal = `g_signal_connect(control, "changed", G_CALLBACK(OnChanged), GINT_TO_POINTER(${control.commandId}));`;
  if (control.type === 'combo') signal = `g_signal_connect(control, "changed", G_CALLBACK(OnComboChanged), GINT_TO_POINTER(${control.commandId}));`;
  if (control.type === 'listbox') signal = `g_signal_connect(control, "row-selected", G_CALLBACK(OnListChanged), GINT_TO_POINTER(${control.commandId}));`;
  const put = control.parentTabIndex >= 0
    ? `GtkWidget *parent = gTabPages[${control.parentTabIndex}].at(${control.pageIndex}); gtk_fixed_put(GTK_FIXED(parent), control, ${x}, ${y});`
    : `gtk_fixed_put(GTK_FIXED(fixed), control, ${x}, ${y});`;
  return `  if (${control.formIndex} == index) {\n    ${create}\n    gtk_widget_set_size_request(control, ${width}, ${height});\n    ${put}\n    ${signal}\n    gControls[${index}] = control;\n  }`;
}
function emitSmoke(forms, controls, menus, states) {
  const mainIndex = forms.has('main') ? forms.get('main') : 0;
  const settingsIndex = forms.get('settings');
  const open = controls.get('open_settings');
  const close = controls.get('close_settings');
  const checkbox = controls.get('notifications');
  const checkboxState = states.get('notifications');
  const combo = controls.get('size');
  const comboState = states.get('size');
  const listbox = controls.get('fruit');
  const listboxState = states.get('fruit');
  const radio = controls.get('mode');
  const radioState = states.get('mode');
  const tabs = controls.get('settings');
  const about = menus.get('about_item');
  const lines = ['static int RunPatchSmoke() {', `  if (!gForms[${mainIndex}] || !gtk_widget_get_visible(gForms[${mainIndex}])) return 70;`];
  if (settingsIndex !== undefined) lines.push(`  if (gtk_widget_get_visible(gForms[${settingsIndex}])) return 71;`);
  if (open && settingsIndex !== undefined) { lines.push(`  gtk_button_clicked(GTK_BUTTON(gControls[${open.handleIndex}]));`); lines.push(`  if (!gtk_widget_get_visible(gForms[${settingsIndex}])) return 72;`); }
  if (checkbox && checkboxState?.type === 'boolean') { lines.push(`  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(gControls[${checkbox.handleIndex}]), TRUE);`); lines.push(`  if (!${stateName(checkboxState.name)}) return 73;`); }
  if (combo && comboState?.type === 'text' && combo.options.length) { const last = combo.options.length - 1; lines.push(`  gtk_combo_box_set_active(GTK_COMBO_BOX(gControls[${combo.handleIndex}]), ${last});`); lines.push(`  if (${stateName(comboState.name)} != ${cString(combo.options[last])}) return 75;`); }
  if (listbox && listboxState?.type === 'text' && listbox.options.length) { const last = listbox.options.length - 1; lines.push(`  GtkListBoxRow *listRow = gtk_list_box_get_row_at_index(GTK_LIST_BOX(gControls[${listbox.handleIndex}]), ${last});`); lines.push(`  gtk_list_box_select_row(GTK_LIST_BOX(gControls[${listbox.handleIndex}]), listRow);`); lines.push(`  if (${stateName(listboxState.name)} != ${cString(listbox.options[last])}) return 76;`); }
  if (radio && radioState?.type === 'text' && radio.options.length) { const last = radio.options.length - 1; lines.push(`  if ((int)gRadioItems[${radio.handleIndex}].size() != ${radio.options.length}) return 81;`); lines.push(`  gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(gRadioItems[${radio.handleIndex}][${last}]), TRUE);`); lines.push(`  if (${stateName(radioState.name)} != ${cString(radio.options[last])}) return 82;`); }
  if (tabs?.type === 'tabs' && tabs.pageTitles.length > 1) {
    lines.push(`  if (gtk_notebook_get_n_pages(GTK_NOTEBOOK(gControls[${tabs.handleIndex}])) != ${tabs.pageTitles.length}) return 77;`);
    lines.push(`  gtk_notebook_set_current_page(GTK_NOTEBOOK(gControls[${tabs.handleIndex}]), 1);`);
    lines.push(`  if (gtk_notebook_get_current_page(GTK_NOTEBOOK(gControls[${tabs.handleIndex}])) != 1) return 78;`);
  }
  if (about) {
    lines.push(`  if (!gMenuItems[${about.nativeIndex}]) return 83;`);
    lines.push(`  g_signal_emit_by_name(gMenuItems[${about.nativeIndex}], "activate");`);
    lines.push(`  if (gLastDialogTitle != "About Patch" || gLastDialogMessage != "Native menus and informational dialogs") return 84;`);
  }
  if (close && settingsIndex !== undefined) { lines.push(`  gtk_button_clicked(GTK_BUTTON(gControls[${close.handleIndex}]));`); lines.push(`  if (gtk_widget_get_visible(gForms[${settingsIndex}])) return 74;`); }
  lines.push(`  gtk_widget_destroy(gForms[${mainIndex}]);`, '  return 0;', '}');
  return lines.join('\n');
}
function controlKind(type) { return ({ text: 'CK_TEXT', button: 'CK_BUTTON', input: 'CK_INPUT', checkbox: 'CK_CHECKBOX', combo: 'CK_COMBO', listbox: 'CK_LISTBOX', tabs: 'CK_TABS', radio: 'CK_RADIO' })[type] ?? 'CK_TEXT'; }
function stateName(name) { return `patch_state_${identifier(name)}`; }
function identifier(value) { return String(value).replace(/[^A-Za-z0-9_]/g, '_').replace(/^[0-9]/, '_$&'); }
function layoutInt(value, fallback) { return Number.isFinite(Number(value)) ? Math.max(0, Math.round(Number(value))) : fallback; }
function positiveInt(value, fallback) { return Number.isFinite(Number(value)) ? Math.max(1, Math.round(Number(value))) : fallback; }
function cString(value) { return JSON.stringify(String(value ?? '')); }
