import { NativeGuiError } from './native-gui-ir.js';
import { emitGtkGuiCppV09 } from './gtk-gui-v09.js';
import { adaptNativeMenusForLegacyBackend } from './native-menu-backend-adapter.js';

export const PATCH_GTK_GUI_BACKEND_V10_VERSION = '1.0';

/** Emit GTK backend 1.0 with GtkSeparatorMenuItem and portable accelerators. */
export function emitGtkGuiCppV10(input) {
  const adapted = adaptNativeMenusForLegacyBackend(input);
  let source = emitGtkGuiCppV09(adapted.legacyIr)
    .replace(/Generated by Patch GTK GUI backend 0\.9\./, `Generated by Patch GTK GUI backend ${PATCH_GTK_GUI_BACKEND_V10_VERSION}.`);

  if (adapted.shortcuts.length) {
    source = replaceRequired(
      source,
      '  GtkWidget *root = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);\n  gtk_container_add(GTK_CONTAINER(window), root);',
      '  GtkWidget *root = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);\n  gtk_container_add(GTK_CONTAINER(window), root);\n  GtkAccelGroup *patchAccelGroup = gtk_accel_group_new();\n  gtk_window_add_accel_group(GTK_WINDOW(window), patchAccelGroup);',
      'GTK accelerator group initialization'
    );
  }

  for (const entry of adapted.separators) {
    source = replaceRequired(
      source,
      gtkMenuBlock(entry, ''),
      `{ GtkWidget *entry = gtk_separator_menu_item_new(); gtk_menu_shell_append(GTK_MENU_SHELL(submenu_${entry.formIndex}_${entry.menuIndex}), entry); }`,
      `GTK Menu separator ${entry.formIndex + 1}/${entry.menuIndex + 1}/${entry.itemIndex + 1}`
    );
  }

  for (const entry of adapted.shortcuts) {
    const accelerator = ` gtk_widget_add_accelerator(entry, "activate", patchAccelGroup, ${gtkKey(entry.shortcut.key)}, ${gtkModifiers(entry.shortcut)}, GTK_ACCEL_VISIBLE);`;
    source = replaceRequired(
      source,
      gtkMenuBlock(entry, ''),
      gtkMenuBlock(entry, accelerator),
      `GTK Menu shortcut '${entry.id}'`
    );
  }

  return source;
}

function gtkMenuBlock(entry, extra) {
  return `{ GtkWidget *entry = gtk_menu_item_new_with_label(${cString(entry.legacyText)}); gtk_menu_shell_append(GTK_MENU_SHELL(submenu_${entry.formIndex}_${entry.menuIndex}), entry); g_signal_connect(entry, "activate", G_CALLBACK(OnClicked), GINT_TO_POINTER(${entry.commandId}));${extra} gMenuItems[${entry.legacyNativeIndex}] = entry; }`;
}

function gtkKey(key) {
  if (/^[A-Z]$/.test(key)) return `GDK_KEY_${key.toLowerCase()}`;
  if (/^[0-9]$/.test(key)) return `GDK_KEY_${key}`;
  if (/^F(?:[1-9]|1[0-2])$/.test(key)) return `GDK_KEY_${key}`;
  throw new NativeGuiError(`GTK shortcut key '${key}' is unsupported.`);
}

function gtkModifiers(shortcut) {
  const flags = [];
  if (shortcut.primary) flags.push('GDK_CONTROL_MASK');
  if (shortcut.shift) flags.push('GDK_SHIFT_MASK');
  if (shortcut.alt) flags.push('GDK_MOD1_MASK');
  return flags.length ? flags.join(' | ') : '0';
}

function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated GTK source.`);
  return source.replace(marker, replacement);
}

function cString(value) { return JSON.stringify(String(value ?? '')); }
