import { NativeGuiError } from './native-gui-ir.js';
import { emitWin32GuiCppV10 } from './win32-gui-v10.js';
import { adaptNativeMenuStateForV10Backend } from './native-menu-state-backend-adapter.js';

export const PATCH_WIN32_GUI_BACKEND_V11_VERSION = '1.1';

/** Emit Win32 backend 1.1 with source-backed enabled/checked MenuItem state. */
export function emitWin32GuiCppV11(input) {
  const adapted = adaptNativeMenuStateForV10Backend(input);
  let source = emitWin32GuiCppV10(adapted.compatibleIr)
    .replace(/Generated by Patch Win32 GUI backend 1\.0\./, `Generated by Patch Win32 GUI backend ${PATCH_WIN32_GUI_BACKEND_V11_VERSION}.`);

  if (!adapted.statefulItems.length) return source;

  const refreshLines = [];
  const touchedForms = new Set();
  for (const item of adapted.statefulItems) {
    touchedForms.add(item.formIndex);
    const menuExpr = `GetSubMenu(GetMenu(gForms[${item.formIndex}]), ${item.menuIndex})`;
    refreshLines.push(`  { HMENU patchMenu = ${menuExpr}; if (patchMenu) {`);
    if (item.enabledState) {
      refreshLines.push(
        `    EnableMenuItem(patchMenu, ${item.commandId}, MF_BYCOMMAND | (${stateName(item.enabledState)} ? MF_ENABLED : MF_GRAYED));`
      );
    }
    if (item.checkedState) {
      refreshLines.push(
        `    CheckMenuItem(patchMenu, ${item.commandId}, MF_BYCOMMAND | (${stateName(item.checkedState)} ? MF_CHECKED : MF_UNCHECKED));`
      );
    }
    refreshLines.push('  } }');
  }
  for (const formIndex of touchedForms) {
    refreshLines.push(`  if (gForms[${formIndex}]) DrawMenuBar(gForms[${formIndex}]);`);
  }

  source = replaceRequired(
    source,
    '  RefreshTabVisibility();',
    `${refreshLines.join('\n')}\n  RefreshTabVisibility();`,
    'Win32 Menu state RefreshUI insertion'
  );

  const enabledById = new Map(adapted.enabledItems.map(item => [item.id, item]));
  for (let eventIndex = 0; eventIndex < adapted.ir.events.length; eventIndex += 1) {
    const event = adapted.ir.events[eventIndex];
    const item = enabledById.get(event.control);
    if (!item || event.event !== 'clicked') continue;
    const marker = `  if (commandId == ${item.commandId} && notification == 0 && controlHwnd == nullptr) { Event_${eventIndex}(); return; }`;
    const replacement = `  if (commandId == ${item.commandId} && notification == 0 && controlHwnd == nullptr) { if (!${stateName(item.enabledState)}) return; Event_${eventIndex}(); return; }`;
    source = replaceRequired(source, marker, replacement, `Win32 enabled MenuItem '${item.id}' dispatch guard`);
  }

  return source;
}

function stateName(name) { return `patch_state_${identifier(name)}`; }
function identifier(value) { return String(value).replace(/[^A-Za-z0-9_]/g, '_').replace(/^[0-9]/, '_$&'); }
function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated Win32 source.`);
  return source.replace(marker, replacement);
}
