import { flattenNativeGuiControls, NativeGuiError } from './native-gui-ir.js';
import { emitWin32GuiCpp as emitWin32GuiCppV07 } from './win32-gui-v07.js';
import {
  nativeAccessibleName,
  nativeRadioItemAccessibleName,
  needsExplicitNativeAccessibleName
} from './native-accessibility.js';

export const PATCH_WIN32_GUI_BACKEND_VERSION = '0.8';

export function emitWin32GuiCpp(input) {
  const controls = flattenNativeGuiControls(input);
  let source = emitWin32GuiCppV07(input)
    .replace(/Generated by Patch Win32 GUI backend 0\.7\./, `Generated by Patch Win32 GUI backend ${PATCH_WIN32_GUI_BACKEND_VERSION}.`);

  source = replaceRequired(source, '#include <windows.h>\n', '#include <windows.h>\n#include <initguid.h>\n#include <oleacc.h>\n#include <objbase.h>\n', 'Win32 include block');
  source = replaceRequired(
    source,
    '#pragma comment(lib, "comctl32.lib")',
    '#pragma comment(lib, "comctl32.lib")\n#pragma comment(lib, "oleacc.lib")\n#pragma comment(lib, "ole32.lib")\n#pragma comment(lib, "oleaut32.lib")',
    'Win32 library block'
  );
  source = replaceRequired(source, 'static void RefreshTabVisibility() {', `${win32AccessibilityHelpers(controls)}\n${win32ResponsiveHelpers(input, controls)}\nstatic void RefreshTabVisibility() {`, 'Win32 accessibility/responsive helper insertion');
  if (hasResponsiveLayout(controls)) {
    source = replaceRequired(
      source,
      '  switch (msg) {\n    case WM_COMMAND:',
      '  switch (msg) {\n    case WM_SIZE:\n      if (form >= 0 && form < FORM_COUNT) ApplyPatchResponsiveLayout(form, LOWORD(lParam), HIWORD(lParam));\n      return 0;\n    case WM_COMMAND:',
      'Win32 WM_SIZE responsive dispatch'
    );
  }
  source = replaceRequired(
    source,
    'int WINAPI wWinMain(HINSTANCE instance, HINSTANCE, PWSTR, int showCommand) {\n  gInstance = instance;',
    'int WINAPI wWinMain(HINSTANCE instance, HINSTANCE, PWSTR, int showCommand) {\n  PatchComScope patchCom;\n  gInstance = instance;',
    'Win32 COM initialization'
  );
  source = replaceRequired(
    source,
    'for (int i = 0; i < FORM_COUNT; ++i) if (!CreatePatchForm(i)) return 11 + i;\n  RefreshUI();',
    'for (int i = 0; i < FORM_COUNT; ++i) if (!CreatePatchForm(i)) return 11 + i;\n  ApplyPatchAccessibility();\n  RefreshUI();',
    'Win32 accessibility application'
  );
  source = replaceRequired(
    source,
    'if (form == 0) DestroyWindow(hwnd); else ShowWindow(hwnd, SW_HIDE);',
    'if (form == 0) { ClearPatchAccessibleNames(); DestroyWindow(hwnd); } else ShowWindow(hwnd, SW_HIDE);',
    'Win32 accessibility cleanup on close'
  );
  source = injectAccessibilitySmoke(source, controls);
  source = source.replace(/  DestroyWindow\(gForms\[(\d+)\]\);/g, '  ClearPatchAccessibleNames();\n  DestroyWindow(gForms[$1]);');
  return source;
}

function win32ResponsiveHelpers(ir, controls) {
  const responsive = controls.filter(control => control.parentTabIndex < 0 && isResponsive(control));
  if (!responsive.length) return '';
  const blocks = responsive.map(control => emitWin32ResponsiveControl(ir, control, controls)).join('\n');
  return `static void ApplyPatchResponsiveLayout(int formIndex, int formWidth, int formHeight) {\n  if (formWidth <= 0 || formHeight <= 0) return;\n${blocks}\n}\n`;
}

function emitWin32ResponsiveControl(ir, control, controls) {
  const form = ir.forms[control.formIndex];
  const base = control.layout ?? {};
  const policy = base.policy;
  const x = int(base.x, 24); const y = int(base.y, 24); const width = int(base.width, 120); const height = int(base.height, 36);
  const lines = [`  if (formIndex == ${control.formIndex}) {`, `    int x=${x}, y=${y}, width=${width}, height=${height};`, `    const int dw=formWidth-${int(form.width, 640)}, dh=formHeight-${int(form.height, 420)};`];
  if (policy.kind === 'dock') {
    if (policy.side === 'fill') lines.push('    x=0; y=0; width=formWidth; height=formHeight;');
    if (policy.side === 'top') lines.push('    x=0; y=0; width=formWidth;');
    if (policy.side === 'bottom') lines.push('    x=0; y=(formHeight-height>0?formHeight-height:0); width=formWidth;');
    if (policy.side === 'left') lines.push('    x=0; y=0; height=formHeight;');
    if (policy.side === 'right') lines.push('    x=(formWidth-width>0?formWidth-width:0); y=0; height=formHeight;');
  } else if (policy.kind === 'anchor') {
    const edges = new Set(policy.edges ?? []);
    if (edges.has('left') && edges.has('right')) lines.push('    width=(width+dw>16?width+dw:16);');
    else if (!edges.has('left') && edges.has('right')) lines.push('    x=(x+dw>0?x+dw:0);');
    if (edges.has('top') && edges.has('bottom')) lines.push('    height=(height+dh>16?height+dh:16);');
    else if (!edges.has('top') && edges.has('bottom')) lines.push('    y=(y+dh>0?y+dh:0);');
  }
  lines.push(...win32MoveLines(control, 'x', 'y', 'width', 'height'));
  if (control.type === 'tabs') {
    for (const child of controls.filter(item => item.parentTabIndex === control.nativeIndex)) {
      const childX = int(child.layout?.x, 12); const childY = int(child.layout?.y, 12); const childW = int(child.layout?.width, 120); const childH = int(child.layout?.height, 36);
      lines.push(`    { int cx=x+10+${childX}, cy=y+30+${childY}, cw=${childW}, ch=${childH};`);
      lines.push(...win32MoveLines(child, 'cx', 'cy', 'cw', 'ch').map(line => `  ${line}`));
      lines.push('    }');
    }
  }
  lines.push('  }');
  return lines.join('\n');
}

function win32MoveLines(control, x, y, width, height) {
  if (control.type === 'radio') {
    const count = Math.max(1, control.options?.length ?? 1);
    return [
      `    { int itemHeight=${height}/${count}; if(itemHeight<22)itemHeight=22; if(itemHeight>30)itemHeight=30;`,
      `      for (size_t optionIndex=0; optionIndex<gRadioItems[${control.nativeIndex}].size(); ++optionIndex) MoveWindow(gRadioItems[${control.nativeIndex}][optionIndex], ${x}, ${y}+(int)optionIndex*itemHeight, ${width}, itemHeight, TRUE); }`
    ];
  }
  const renderHeight = control.type === 'combo' ? `(${height}+120>160?${height}+120:160)` : height;
  return [`    if (gControls[${control.nativeIndex}]) MoveWindow(gControls[${control.nativeIndex}], ${x}, ${y}, ${width}, ${renderHeight}, TRUE);`];
}

function hasResponsiveLayout(controls) { return controls.some(control => control.parentTabIndex < 0 && isResponsive(control)); }
function isResponsive(control) { return control.layout?.policy?.kind && control.layout.policy.kind !== 'fixed'; }
function int(value, fallback) { const number = Number(value); return Number.isFinite(number) ? Math.round(number) : fallback; }

function win32AccessibilityHelpers(controls) {
  const apply = [];
  const clear = [];
  for (const control of controls) {
    if (!needsExplicitNativeAccessibleName(control)) continue;
    if (control.type === 'radio') {
      for (let optionIndex = 0; optionIndex < control.options.length; optionIndex += 1) {
        const name = nativeRadioItemAccessibleName(control, control.options[optionIndex]);
        apply.push(`  if (gRadioItems[${control.nativeIndex}].size() > ${optionIndex}) SetPatchAccessibleName(gRadioItems[${control.nativeIndex}][${optionIndex}], L${cppString(name)});`);
        clear.push(`  if (gRadioItems[${control.nativeIndex}].size() > ${optionIndex}) ClearPatchAccessibleName(gRadioItems[${control.nativeIndex}][${optionIndex}]);`);
      }
      continue;
    }
    const name = nativeAccessibleName(control);
    if (!name) continue;
    apply.push(`  SetPatchAccessibleName(gControls[${control.nativeIndex}], L${cppString(name)});`);
    clear.push(`  ClearPatchAccessibleName(gControls[${control.nativeIndex}]);`);
  }

  return `struct PatchComScope {\n  HRESULT result;\n  PatchComScope() : result(CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED)) {}\n  ~PatchComScope() { if (SUCCEEDED(result)) CoUninitialize(); }\n};\nstatic void SetPatchAccessibleName(HWND hwnd, const wchar_t *name) {\n  if (!hwnd || !name || !*name) return;\n  IAccPropServices *service = nullptr;\n  const HRESULT created = CoCreateInstance(CLSID_AccPropServices, nullptr, CLSCTX_SERVER, IID_IAccPropServices, reinterpret_cast<void **>(&service));\n  if (SUCCEEDED(created) && service) {\n    service->SetHwndPropStr(hwnd, OBJID_CLIENT, CHILDID_SELF, PROPID_ACC_NAME, name);\n    service->Release();\n  }\n}\nstatic void ClearPatchAccessibleName(HWND hwnd) {\n  if (!hwnd) return;\n  IAccPropServices *service = nullptr;\n  const HRESULT created = CoCreateInstance(CLSID_AccPropServices, nullptr, CLSCTX_SERVER, IID_IAccPropServices, reinterpret_cast<void **>(&service));\n  if (SUCCEEDED(created) && service) {\n    MSAAPROPID property = PROPID_ACC_NAME;\n    service->ClearHwndProps(hwnd, OBJID_CLIENT, CHILDID_SELF, &property, 1);\n    service->Release();\n  }\n}\nstatic std::wstring PatchAccessibleName(HWND hwnd) {\n  if (!hwnd) return L\"\";\n  IAccessible *accessible = nullptr;\n  const HRESULT opened = AccessibleObjectFromWindow(hwnd, OBJID_CLIENT, IID_IAccessible, reinterpret_cast<void **>(&accessible));\n  if (FAILED(opened) || !accessible) return L\"\";\n  VARIANT child{}; child.vt = VT_I4; child.lVal = CHILDID_SELF;\n  BSTR value = nullptr;\n  const HRESULT read = accessible->get_accName(child, &value);\n  std::wstring result = SUCCEEDED(read) && value ? std::wstring(value) : std::wstring();\n  if (value) SysFreeString(value);\n  accessible->Release();\n  return result;\n}\nstatic void ApplyPatchAccessibility() {\n${apply.join('\n') || '  // Standard native control names need no Patch annotation.'}\n}\nstatic void ClearPatchAccessibleNames() {\n${clear.join('\n') || '  // No Patch accessibility annotations to clear.'}\n}\n`;
}

function injectAccessibilitySmoke(source, controls) {
  const checks = [];
  let code = 130;
  for (const control of controls) {
    if (!needsExplicitNativeAccessibleName(control)) continue;
    if (control.type === 'radio') {
      for (let optionIndex = 0; optionIndex < control.options.length; optionIndex += 1) {
        const expected = nativeRadioItemAccessibleName(control, control.options[optionIndex]);
        checks.push(`  if (gRadioItems[${control.nativeIndex}].size() <= ${optionIndex} || PatchAccessibleName(gRadioItems[${control.nativeIndex}][${optionIndex}]) != L${cppString(expected)}) return ${code++};`);
      }
      continue;
    }
    const expected = nativeAccessibleName(control);
    if (!expected) continue;
    checks.push(`  if (PatchAccessibleName(gControls[${control.nativeIndex}]) != L${cppString(expected)}) return ${code++};`);
  }
  if (!checks.length) return source;
  const start = source.indexOf('static int RunPatchSmoke() {');
  if (start < 0) throw new NativeGuiError('Generated Win32 source is missing RunPatchSmoke for accessibility verification.');
  const destroy = source.indexOf('  DestroyWindow(gForms[', start);
  if (destroy < 0) throw new NativeGuiError('Generated Win32 smoke has an unexpected shape for accessibility verification.');
  return source.slice(0, destroy) + checks.join('\n') + '\n' + source.slice(destroy);
}

function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated Win32 source.`);
  return source.replace(marker, replacement);
}

function cppString(value) {
  return JSON.stringify(String(value ?? '')).replace(/\\u([0-9a-fA-F]{4})/g, (_, hex) => `\\x${hex}`);
}
