import { NativeGuiError } from './native-gui-ir.js';
import { emitWin32GuiCppV13 } from './win32-gui-v13.js';
import { adaptNativeSlidersForV13Backend, sliderPersistentNumberTarget } from './native-slider-backend-adapter.js';

export const PATCH_WIN32_GUI_BACKEND_V14_VERSION = '1.4';

/** Emit Win32 backend 1.4 with real TRACKBAR_CLASS Slider controls. */
export function emitWin32GuiCppV14(input) {
  const adapted = adaptNativeSlidersForV13Backend(input);
  let source = emitWin32GuiCppV13(adapted.compatibleIr)
    .replace(/Generated by Patch Win32 GUI backend 1\.3\./, `Generated by Patch Win32 GUI backend ${PATCH_WIN32_GUI_BACKEND_V14_VERSION}.`);
  if (!adapted.sliders.length) return source;

  source = source.includes('common.dwICC = ICC_TAB_CLASSES | ICC_TREEVIEW_CLASSES')
    ? replaceRequired(source, 'common.dwICC = ICC_TAB_CLASSES | ICC_TREEVIEW_CLASSES', 'common.dwICC = ICC_TAB_CLASSES | ICC_TREEVIEW_CLASSES | ICC_BAR_CLASSES', 'Win32 Slider common-control initialization')
    : replaceRequired(source, 'common.dwICC = ICC_TAB_CLASSES', 'common.dwICC = ICC_TAB_CLASSES | ICC_BAR_CLASSES', 'Win32 Slider common-control initialization');

  for (const slider of adapted.sliders) {
    source = removeShadowState(source, slider);
    source = removeShadowRefresh(source, slider);
    source = replaceControlBlock(source, slider, sliderCreate(adapted, slider));
  }

  for (const patch of adapted.eventPatches) {
    source = patchSliderEventFunction(source, patch);
    const slider = adapted.sliders.find(item => item.id === patch.control);
    if (!slider) continue;
    source = replaceRequired(
      source,
      `  if (commandId == ${slider.commandId} && notification == EN_CHANGE) { Event_${patch.eventIndex}(WindowText(controlHwnd)); return; }\n`,
      '',
      `Win32 Slider '${slider.id}' legacy Input dispatch`
    );
  }

  source = replaceRequired(
    source,
    'static bool HandleTabNotify(NMHDR *header) {',
    `${emitSliderHelpers(adapted)}\n\nstatic bool HandleTabNotify(NMHDR *header) {`,
    'Win32 Slider helper insertion'
  );
  source = replaceRequired(
    source,
    '  switch (msg) {\n    case WM_COMMAND:',
    '  switch (msg) {\n    case WM_HSCROLL:\n      if (PatchHandleSliderScroll(reinterpret_cast<HWND>(lParam), LOWORD(wParam))) return 0;\n      break;\n    case WM_COMMAND:',
    'Win32 Slider WM_HSCROLL dispatch'
  );
  source = injectSliderRefresh(source, adapted);
  source = injectSliderSmoke(source, adapted);
  assertNoShadowState(source, adapted);
  return source;
}

function patchSliderEventFunction(source, patch) {
  const oldSignature = `static void Event_${patch.eventIndex}(const std::wstring& eventValue) {`;
  const newSignature = `static void Event_${patch.eventIndex}(double eventValue) {`;
  const start = source.indexOf(oldSignature);
  if (start < 0) throw new NativeGuiError(`Win32 Slider Event_${patch.eventIndex} signature marker is missing.`);
  const endMarker = '\n  RefreshUI();\n}';
  const end = source.indexOf(endMarker, start);
  if (end < 0) throw new NativeGuiError(`Win32 Slider Event_${patch.eventIndex} body marker is missing.`);
  let body = source.slice(start, end + endMarker.length).replace(oldSignature, newSignature);
  for (const sentinel of patch.sentinels) body = body.replaceAll(String(sentinel), 'eventValue');
  return source.slice(0, start) + body + source.slice(end + endMarker.length);
}

function emitSliderHelpers(adapted) {
  const valueFns = [];
  const branches = [];
  for (const slider of adapted.sliders) {
    const ticks = sliderTickCount(slider);
    valueFns.push(`static int PatchSliderPosition_${slider.nativeIndex}(double value) { double clamped=value<${number(slider.min)}?${number(slider.min)}:(value>${number(slider.max)}?${number(slider.max)}:value); long long position=(long long)std::llround((clamped-${number(slider.min)})/${number(slider.step)}); if(position<0)position=0; if(position>${ticks})position=${ticks}; return (int)position; }\nstatic double PatchSliderValue_${slider.nativeIndex}(HWND hwnd) { if(!hwnd)return ${number(slider.min)}; int position=(int)SendMessageW(hwnd,TBM_GETPOS,0,0); double value=${number(slider.min)}+((double)position*${number(slider.step)}); if(value<${number(slider.min)})value=${number(slider.min)}; if(value>${number(slider.max)})value=${number(slider.max)}; return value; }`);
    const event = adapted.events.find((item, index) => index === adapted.eventPatches.find(patch => patch.control === slider.id)?.eventIndex && item.control === slider.id && item.event === 'changed');
    const eventIndex = event ? adapted.events.indexOf(event) : -1;
    const call = eventIndex >= 0 ? ` Event_${eventIndex}(PatchSliderValue_${slider.nativeIndex}(controlHwnd));` : '';
    branches.push(`  if (controlHwnd == gControls[${slider.nativeIndex}]) { if(notification == TB_THUMBTRACK) return true;${call} return true; }`);
  }
  return `${valueFns.join('\n')}\nstatic bool PatchHandleSliderScroll(HWND controlHwnd, int notification) {\n  if (gRefreshing || !controlHwnd) return false;\n${branches.join('\n')}\n  return false;\n}`;
}

function sliderCreate(adapted, slider) {
  const control = adapted.controls[slider.nativeIndex];
  const pos = win32Position(control, adapted.controls);
  const width = positiveInt(control.layout?.width, 260), height = positiveInt(control.layout?.height, 44);
  const ticks = sliderTickCount(slider);
  const initialExpr = slider.binding ? stateName(slider.binding) : number(slider.min);
  return `  if (${control.formIndex} == index) {\n    gControls[${slider.nativeIndex}] = CreateWindowExW(0, TRACKBAR_CLASSW, L"", WS_CHILD | WS_VISIBLE | WS_TABSTOP | TBS_HORZ | TBS_AUTOTICKS, ${pos.x}, ${pos.y}, ${width}, ${height}, hwnd, reinterpret_cast<HMENU>((INT_PTR)${slider.commandId}), gInstance, nullptr);\n    if (!gControls[${slider.nativeIndex}]) return nullptr; if (gGuiFont) SendMessageW(gControls[${slider.nativeIndex}], WM_SETFONT, (WPARAM)gGuiFont, TRUE);\n    SendMessageW(gControls[${slider.nativeIndex}], TBM_SETRANGEMIN, FALSE, 0); SendMessageW(gControls[${slider.nativeIndex}], TBM_SETRANGEMAX, FALSE, ${ticks}); SendMessageW(gControls[${slider.nativeIndex}], TBM_SETPOS, TRUE, PatchSliderPosition_${slider.nativeIndex}(${initialExpr}));\n  }`;
}

function injectSliderRefresh(source, adapted) {
  const start = source.indexOf('static void RefreshUI() {');
  if (start < 0) throw new NativeGuiError('Generated Win32 source is missing RefreshUI for Slider state.');
  const marker = '  RefreshTabVisibility();';
  const at = source.indexOf(marker, start);
  if (at < 0) throw new NativeGuiError('Generated Win32 Slider refresh insertion point is missing.');
  const lines = adapted.sliders.filter(slider => slider.binding).map(slider =>
    `  if (gControls[${slider.nativeIndex}]) SendMessageW(gControls[${slider.nativeIndex}], TBM_SETPOS, TRUE, PatchSliderPosition_${slider.nativeIndex}(${stateName(slider.binding)}));`
  );
  return source.slice(0, at) + (lines.length ? lines.join('\n') + '\n' : '') + source.slice(at);
}

function injectSliderSmoke(source, adapted) {
  const start = source.indexOf('static int RunPatchSmoke() {');
  if (start < 0) throw new NativeGuiError('Generated Win32 source is missing Slider smoke function.');
  let insertion = source.indexOf('  ClearPatchAccessibleNames();', start);
  if (insertion < 0) insertion = source.indexOf('  DestroyWindow(', start);
  if (insertion < 0) throw new NativeGuiError('Generated Win32 Slider smoke cleanup marker is missing.');
  const checks = [];
  let code = 240;
  for (const slider of adapted.sliders) {
    checks.push(`  if (!gControls[${slider.nativeIndex}] || SendMessageW(gControls[${slider.nativeIndex}], TBM_GETRANGEMAX, 0, 0) != ${sliderTickCount(slider)}) return ${code++};`);
    const eventIndex = adapted.events.findIndex(event => event.control === slider.id && event.event === 'changed');
    if (eventIndex < 0) continue;
    const testPos = Math.max(0, sliderTickCount(slider));
    checks.push(`  SendMessageW(gControls[${slider.nativeIndex}], TBM_SETPOS, TRUE, ${testPos}); PatchHandleSliderScroll(gControls[${slider.nativeIndex}], TB_ENDTRACK);`);
    const target = sliderPersistentNumberTarget(adapted.events[eventIndex], adapted.states);
    if (target) checks.push(`  if (std::fabs(${stateName(target)} - PatchSliderValue_${slider.nativeIndex}(gControls[${slider.nativeIndex}])) > 1e-9) return ${code++};`);
  }
  return source.slice(0, insertion) + checks.join('\n') + '\n' + source.slice(insertion);
}

function replaceControlBlock(source, slider, replacement) {
  const anchor = `  if (${slider.formIndex} == index) {\n    gControls[${slider.nativeIndex}] = CreateWindowExW`;
  const start = source.indexOf(anchor);
  if (start < 0) throw new NativeGuiError(`Win32 Slider '${slider.id}' shadow control start is missing.`);
  const end = source.indexOf('\n  }', start);
  if (end < 0) throw new NativeGuiError(`Win32 Slider '${slider.id}' shadow control end is missing.`);
  return source.slice(0, start) + replacement + source.slice(end + 4);
}

function removeShadowState(source, slider) {
  return replaceRequired(source, `static std::wstring ${stateName(slider.shadowState)} = ${wideString(String(slider.initial))};\n`, '', `Win32 Slider '${slider.id}' shadow state`);
}
function removeShadowRefresh(source, slider) {
  return replaceRequired(source, `  if (gControls[${slider.nativeIndex}]) SetWindowTextIfDifferent(gControls[${slider.nativeIndex}], ${stateName(slider.shadowState)});\n`, '', `Win32 Slider '${slider.id}' shadow refresh`);
}
function assertNoShadowState(source, adapted) { for (const slider of adapted.sliders) if (source.includes(slider.shadowState)) throw new NativeGuiError(`Win32 Slider '${slider.id}' leaked backend shadow state.`); }
function sliderTickCount(slider) { const raw=(Number(slider.max)-Number(slider.min))/Number(slider.step); return Math.max(0, Math.min(2000000000, Math.floor(raw + 1e-10))); }
function win32Position(control, controls) { if ((control.parentTabIndex ?? -1) < 0) return { x:layoutInt(control.layout?.x,24), y:layoutInt(control.layout?.y,24) }; const tab=controls[control.parentTabIndex]; if(!tab||tab.type!=='tabs')throw new NativeGuiError(`Win32 Slider '${control.id}' has an invalid Tabs parent.`); return {x:layoutInt(tab.layout?.x,24)+10+layoutInt(control.layout?.x,12),y:layoutInt(tab.layout?.y,24)+30+layoutInt(control.layout?.y,12)}; }
function stateName(name){return `patch_state_${identifier(name)}`;} function identifier(value){return String(value).replace(/[^A-Za-z0-9_]/g,'_').replace(/^[0-9]/,'_$&');}
function wideString(value){return `L${JSON.stringify(String(value??'')).replace(/\\u([0-9a-fA-F]{4})/g,(_,hex)=>`\\x${hex}`)}`;}
function number(value){return String(Number(value));} function layoutInt(value,fallback){return Number.isFinite(Number(value))?Math.max(0,Math.round(Number(value))):fallback;} function positiveInt(value,fallback){return Number.isFinite(Number(value))?Math.max(1,Math.round(Number(value))):fallback;}
function replaceRequired(source,marker,replacement,label){if(!source.includes(marker))throw new NativeGuiError(`${label} marker is missing from generated Win32 source.`);return source.replace(marker,replacement);}
