import { NativeGuiError } from './native-gui-ir.js';
import { emitWin32GuiCpp as emitWin32GuiCppV08 } from './win32-gui-v08.js';
import {
  adaptNativeTablesForLegacyBackend,
  tableEventIndexById
} from './native-table-backend-adapter.js';

export const PATCH_WIN32_GUI_BACKEND_V09_VERSION = '0.9';

/** Emit Win32 backend v0.9 with real report-mode ListView Tables. */
export function emitWin32GuiCppV09(input) {
  const adapted = adaptNativeTablesForLegacyBackend(input);
  let source = emitWin32GuiCppV08(adapted.legacyIr)
    .replace(/Generated by Patch Win32 GUI backend 0\.8\./, `Generated by Patch Win32 GUI backend ${PATCH_WIN32_GUI_BACKEND_V09_VERSION}.`);
  if (!adapted.tables.length) return source;

  const eventIndexes = tableEventIndexById(adapted.ir);
  source = replaceRequired(
    source,
    'common.dwICC = ICC_TAB_CLASSES;',
    'common.dwICC = ICC_TAB_CLASSES | ICC_LISTVIEW_CLASSES;',
    'Win32 Table common-control initialization'
  );

  for (const table of adapted.tables) {
    source = removeShadowState(source, table);
    source = removeShadowRefresh(source, table);
    source = replaceRequired(source, legacyListBoxCreate(adapted, table), win32TableCreate(adapted, table), `Win32 Table '${table.id}' creation`);

    const eventIndex = eventIndexes.get(table.id);
    if (eventIndex !== undefined) {
      source = replaceRequired(
        source,
        `static void Event_${eventIndex}(const std::wstring& eventValue) {`,
        `static void Event_${eventIndex}(const std::vector<std::wstring>& eventValue) {`,
        `Win32 Table '${table.id}' event signature`
      );
      source = replaceRequired(
        source,
        `  if (commandId == ${1000 + table.nativeIndex} && notification == LBN_SELCHANGE) { Event_${eventIndex}(ListBoxText(controlHwnd)); return; }\n`,
        '',
        `Win32 Table '${table.id}' legacy ListBox dispatch`
      );
    }
  }

  source = replaceRequired(
    source,
    'static bool HandleTabNotify(NMHDR *header) {',
    `${win32TableHelpers(adapted, eventIndexes)}\nstatic bool HandleTabNotify(NMHDR *header) {`,
    'Win32 Table helper insertion'
  );
  source = replaceRequired(
    source,
    '    case WM_NOTIFY:\n      if (HandleTabNotify(reinterpret_cast<NMHDR*>(lParam))) return 0;',
    '    case WM_NOTIFY:\n      if (HandleTableNotify(reinterpret_cast<NMHDR*>(lParam))) return 0;\n      if (HandleTabNotify(reinterpret_cast<NMHDR*>(lParam))) return 0;',
    'Win32 Table WM_NOTIFY dispatch'
  );
  source = injectWin32TableSmoke(source, adapted);
  assertNoShadowState(source, adapted);
  return source;
}

function win32TableHelpers(adapted, eventIndexes) {
  const rowFunctions = adapted.tables.map(table => {
    const cases = table.rows.map((row, rowIndex) =>
      `    case ${rowIndex}: return {${row.map(value => `L${cppString(value)}`).join(', ')}};`
    ).join('\n');
    return `static std::vector<std::wstring> PatchTableRow_${table.nativeIndex}(int row) {\n  switch (row) {\n${cases}\n    default: return {};\n  }\n}`;
  }).join('\n');

  const notify = adapted.tables.map(table => {
    const eventIndex = eventIndexes.get(table.id);
    const eventCall = eventIndex === undefined ? '' : ` Event_${eventIndex}(PatchTableRow_${table.nativeIndex}(change->iItem));`;
    return `  if (gControls[${table.nativeIndex}] == header->hwndFrom && header->code == LVN_ITEMCHANGED) {\n    auto *change = reinterpret_cast<NMLISTVIEW*>(header);\n    if (change->iItem >= 0 && (change->uNewState & LVIS_SELECTED) && !(change->uOldState & LVIS_SELECTED)) { ++gPatchTableSelectionCount;${eventCall} }\n    return true;\n  }`;
  }).join('\n');

  return `${rowFunctions}\nstatic int gPatchTableSelectionCount = 0;\nstatic bool HandleTableNotify(NMHDR *header) {\n  if (!header) return false;\n${notify}\n  return false;\n}`;
}

function win32TableCreate(adapted, table) {
  const control = adapted.controls[table.nativeIndex];
  const position = win32Position(control, adapted.controls);
  const width = positiveInt(control.layout?.width, 400);
  const height = positiveInt(control.layout?.height, 180);
  const commandId = 1000 + table.nativeIndex;
  const columnWidth = Math.max(40, Math.floor(width / Math.max(1, table.columns.length)));
  const columns = table.columns.map((title, columnIndex) =>
    `    { LVCOLUMNW column{}; column.mask = LVCF_TEXT | LVCF_WIDTH | LVCF_SUBITEM; column.cx = ${columnIndex + 1 === table.columns.length ? Math.max(40, width - columnWidth * columnIndex) : columnWidth}; column.iSubItem = ${columnIndex}; column.pszText = const_cast<wchar_t*>(L${cppString(title)}); ListView_InsertColumn(gControls[${table.nativeIndex}], ${columnIndex}, &column); }`
  ).join('\n');
  const rows = table.rows.map((row, rowIndex) => {
    const rest = row.slice(1).map((value, columnOffset) =>
      `    ListView_SetItemText(gControls[${table.nativeIndex}], ${rowIndex}, ${columnOffset + 1}, const_cast<wchar_t*>(L${cppString(value)}));`
    ).join('\n');
    return `    { LVITEMW item{}; item.mask = LVIF_TEXT; item.iItem = ${rowIndex}; item.iSubItem = 0; item.pszText = const_cast<wchar_t*>(L${cppString(row[0] ?? '')}); ListView_InsertItem(gControls[${table.nativeIndex}], &item); }\n${rest}`;
  }).join('\n');
  return `  if (${control.formIndex} == index) {\n    gControls[${table.nativeIndex}] = CreateWindowExW(WS_EX_CLIENTEDGE, WC_LISTVIEWW, L"", WS_CHILD | WS_VISIBLE | WS_TABSTOP | LVS_REPORT | LVS_SINGLESEL | LVS_SHOWSELALWAYS, ${position.x}, ${position.y}, ${width}, ${height}, hwnd, reinterpret_cast<HMENU>((INT_PTR)${commandId}), gInstance, nullptr);\n    if (!gControls[${table.nativeIndex}]) return nullptr;\n    if (gGuiFont) SendMessageW(gControls[${table.nativeIndex}], WM_SETFONT, (WPARAM)gGuiFont, TRUE);\n    ListView_SetExtendedListViewStyle(gControls[${table.nativeIndex}], LVS_EX_FULLROWSELECT | LVS_EX_GRIDLINES | LVS_EX_DOUBLEBUFFER);\n${columns}\n${rows}\n  }`;
}

function legacyListBoxCreate(adapted, table) {
  const control = adapted.controls[table.nativeIndex];
  const position = win32Position(control, adapted.controls);
  const width = positiveInt(control.layout?.width, 400);
  const height = positiveInt(control.layout?.height, 180);
  const commandId = 1000 + table.nativeIndex;
  return `  if (${control.formIndex} == index) {\n    gControls[${table.nativeIndex}] = CreateWindowExW(0, L"LISTBOX", L"", WS_CHILD | WS_VISIBLE | WS_TABSTOP | WS_VSCROLL | WS_BORDER | LBS_NOTIFY, ${position.x}, ${position.y}, ${width}, ${height}, hwnd, reinterpret_cast<HMENU>((INT_PTR)${commandId}), gInstance, nullptr);\n    if (gControls[${table.nativeIndex}] && gGuiFont) SendMessageW(gControls[${table.nativeIndex}], WM_SETFONT, (WPARAM)gGuiFont, TRUE);\n    SendMessageW(gControls[${table.nativeIndex}], LB_ADDSTRING, 0, (LPARAM)L"__patch_table_row_0");\n    SendMessageW(gControls[${table.nativeIndex}], LB_ADDSTRING, 0, (LPARAM)L"__patch_table_row_1");\n  }`;
}

function removeShadowState(source, table) {
  return replaceRequired(
    source,
    `static std::wstring patch_state_${identifier(table.shadowState)} = L"__patch_table_row_0";\n`,
    '',
    `Win32 Table '${table.id}' private shadow state`
  );
}

function removeShadowRefresh(source, table) {
  return replaceRequired(
    source,
    `  if (gControls[${table.nativeIndex}]) SetListBoxSelection(gControls[${table.nativeIndex}], patch_state_${identifier(table.shadowState)});\n`,
    '',
    `Win32 Table '${table.id}' private shadow refresh`
  );
}

function injectWin32TableSmoke(source, adapted) {
  const checks = [];
  let code = 150;
  for (const table of adapted.tables) {
    const commandId = 1000 + table.nativeIndex;
    checks.push(`  if (!gControls[${table.nativeIndex}] || ListView_GetItemCount(gControls[${table.nativeIndex}]) != ${table.rows.length}) return ${code++};`);
    checks.push(`  if (!ListView_GetHeader(gControls[${table.nativeIndex}]) || Header_GetItemCount(ListView_GetHeader(gControls[${table.nativeIndex}])) != ${table.columns.length}) return ${code++};`);
    checks.push(`  { int before = gPatchTableSelectionCount; NMLISTVIEW change{}; change.hdr.hwndFrom = gControls[${table.nativeIndex}]; change.hdr.idFrom = ${commandId}; change.hdr.code = LVN_ITEMCHANGED; change.iItem = ${Math.max(0, table.rows.length - 1)}; change.uOldState = 0; change.uNewState = LVIS_SELECTED; SendMessageW(gForms[${table.formIndex}], WM_NOTIFY, ${commandId}, (LPARAM)&change); if (gPatchTableSelectionCount != before + 1) return ${code++}; }`);
  }
  const marker = '  DestroyWindow(gForms[';
  const index = source.indexOf(marker, source.indexOf('static int RunPatchSmoke() {'));
  if (index < 0) throw new NativeGuiError('Generated Win32 source is missing the native smoke destruction point for Table verification.');
  return source.slice(0, index) + checks.join('\n') + '\n' + source.slice(index);
}

function win32Position(control, controls) {
  if ((control.parentTabIndex ?? -1) < 0) {
    return { x: layoutInt(control.layout?.x, 24), y: layoutInt(control.layout?.y, 24) };
  }
  const tab = controls[control.parentTabIndex];
  if (!tab || tab.type !== 'tabs') throw new NativeGuiError(`Win32 Table '${control.id}' has an invalid Tabs parent.`);
  return {
    x: layoutInt(tab.layout?.x, 24) + 10 + layoutInt(control.layout?.x, 12),
    y: layoutInt(tab.layout?.y, 24) + 30 + layoutInt(control.layout?.y, 12)
  };
}

function assertNoShadowState(source, adapted) {
  for (const table of adapted.tables) {
    if (source.includes(table.shadowState) || source.includes(`patch_state_${identifier(table.shadowState)}`)) {
      throw new NativeGuiError(`Win32 Table '${table.id}' leaked its private backend shadow state.`);
    }
  }
}

function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated Win32 source.`);
  return source.replace(marker, replacement);
}
function identifier(value) { return String(value).replace(/[^A-Za-z0-9_]/g, '_').replace(/^[0-9]/, '_$&'); }
function layoutInt(value, fallback) { return Number.isFinite(Number(value)) ? Math.max(0, Math.round(Number(value))) : fallback; }
function positiveInt(value, fallback) { return Number.isFinite(Number(value)) ? Math.max(1, Math.round(Number(value))) : fallback; }
function cppString(value) { return JSON.stringify(String(value ?? '')).replace(/\\u([0-9a-fA-F]{4})/g, (_, hex) => `\\x${hex}`); }
