import { NativeGuiError } from './native-gui-ir.js';
import { emitWin32GuiCppV12 } from './win32-gui-v12.js';
import { adaptNativeTreesForV12Backend, treePersistentPathTarget } from './native-tree-backend-adapter.js';

export const PATCH_WIN32_GUI_BACKEND_V13_VERSION = '1.3';

/** Emit Win32 backend 1.3 with a real common-controls TreeView. */
export function emitWin32GuiCppV13(input) {
  const adapted = adaptNativeTreesForV12Backend(input);
  let source = emitWin32GuiCppV12(adapted.compatibleIr)
    .replace(/Generated by Patch Win32 GUI backend 1\.2\./, `Generated by Patch Win32 GUI backend ${PATCH_WIN32_GUI_BACKEND_V13_VERSION}.`);
  if (!adapted.trees.length) return source;

  source = replaceRequired(
    source,
    'static std::vector<std::vector<HWND>> gRadioItems(CONTROL_COUNT);',
    `static std::vector<std::vector<HWND>> gRadioItems(CONTROL_COUNT);\nstatic std::vector<HTREEITEM> gTreeItems[${Math.max(1, adapted.controls.length)}];\nstatic int gPatchTreeSelectionCount = 0;`,
    'Win32 TreeView storage'
  );
  source = replaceRequired(source, 'common.dwICC = ICC_TAB_CLASSES', 'common.dwICC = ICC_TAB_CLASSES | ICC_TREEVIEW_CLASSES', 'Win32 TreeView common-control initialization');

  for (const tree of adapted.trees) {
    source = removeShadowState(source, tree);
    source = removeShadowRefresh(source, tree);
    source = replaceControlBlock(source, tree, treeCreate(adapted, tree));
    const event = adapted.events.find(item => item.control === tree.id && item.event === 'changed');
    if (event) {
      source = replaceRequired(
        source,
        `  if (commandId == ${tree.commandId} && notification == LBN_SELCHANGE) { Event_${event.eventIndex}(ListBoxTexts(controlHwnd)); return; }\n`,
        '',
        `Win32 TreeView '${tree.id}' legacy ListBox dispatch`
      );
    }
  }

  const treeFunctions = adapted.trees.map(tree => emitTreeFunctions(tree, adapted.states)).join('\n\n');
  const treeNotify = emitTreeNotify(adapted);
  source = replaceRequired(source, 'static bool HandleTabNotify(NMHDR *header) {', `${treeFunctions}\n\n${treeNotify}\nstatic bool HandleTabNotify(NMHDR *header) {`, 'Win32 TreeView helper insertion');
  source = replaceRequired(
    source,
    '    case WM_NOTIFY:\n',
    '    case WM_NOTIFY:\n      if (HandleTreeNotify(reinterpret_cast<NMHDR*>(lParam))) return 0;\n',
    'Win32 TreeView WM_NOTIFY dispatch'
  );
  source = injectTreeRefresh(source, adapted);
  source = injectTreeSmoke(source, adapted);
  assertNoShadowState(source, adapted);
  return source;
}

function emitTreeFunctions(tree, states) {
  const textFunctions = tree.flatNodes.map(node =>
    `static std::wstring TreeNodeText_${tree.nativeIndex}_${node.flatIndex}() { return ${wideTemplateExpr(node.text, states)}; }`
  ).join('\n');
  const pathCases = tree.flatNodes.map(node => {
    const values = node.flatIndexPath.map(index => `TreeNodeText_${tree.nativeIndex}_${index}()`).join(', ');
    return `  if (item == gTreeItems[${tree.nativeIndex}][${node.flatIndex}]) return {${values}};`;
  }).join('\n');
  return `${textFunctions}\nstatic std::vector<std::wstring> PatchTreePath_${tree.nativeIndex}(HTREEITEM item) {\n  if (!item) return {};\n${pathCases}\n  return {};\n}`;
}

function emitTreeNotify(adapted) {
  const branches = adapted.trees.map(tree => {
    const event = adapted.events.find(item => item.control === tree.id && item.event === 'changed');
    const call = event ? ` Event_${event.eventIndex}(PatchTreePath_${tree.nativeIndex}(change->itemNew.hItem));` : '';
    return `  if (gControls[${tree.nativeIndex}] == header->hwndFrom && header->code == TVN_SELCHANGEDW) { auto *change = reinterpret_cast<NMTREEVIEWW*>(header); if (change->itemNew.hItem) { ++gPatchTreeSelectionCount;${call} } return true; }`;
  }).join('\n');
  return `static bool HandleTreeNotify(NMHDR *header) {\n  if (!header) return false;\n${branches}\n  return false;\n}`;
}

function treeCreate(adapted, tree) {
  const control = adapted.controls[tree.nativeIndex];
  const pos = win32Position(control, adapted.controls);
  const width = positiveInt(control.layout?.width, 220), height = positiveInt(control.layout?.height, 120);
  const inserts = [];
  const itemVars = new Map();
  for (const node of tree.flatNodes) {
    const parentFlat = node.flatIndexPath.length > 1 ? node.flatIndexPath[node.flatIndexPath.length - 2] : null;
    const parent = parentFlat === null ? 'TVI_ROOT' : itemVars.get(parentFlat);
    const variable = `treeItem_${tree.nativeIndex}_${node.flatIndex}`;
    itemVars.set(node.flatIndex, variable);
    inserts.push(`    { std::wstring label = TreeNodeText_${tree.nativeIndex}_${node.flatIndex}(); TVINSERTSTRUCTW insert{}; insert.hParent = ${parent}; insert.hInsertAfter = TVI_LAST; insert.item.mask = TVIF_TEXT; insert.item.pszText = label.data(); HTREEITEM ${variable} = TreeView_InsertItem(gControls[${tree.nativeIndex}], &insert); if (!${variable}) return nullptr; gTreeItems[${tree.nativeIndex}].push_back(${variable}); }`);
  }
  for (const node of tree.flatNodes.filter(node => node.children > 0)) inserts.push(`    TreeView_Expand(gControls[${tree.nativeIndex}], gTreeItems[${tree.nativeIndex}][${node.flatIndex}], TVE_EXPAND);`);
  return `  if (${control.formIndex} == index) {\n    gControls[${tree.nativeIndex}] = CreateWindowExW(WS_EX_CLIENTEDGE, WC_TREEVIEWW, L"", WS_CHILD | WS_VISIBLE | WS_TABSTOP | WS_BORDER | TVS_HASBUTTONS | TVS_HASLINES | TVS_LINESATROOT | TVS_SHOWSELALWAYS, ${pos.x}, ${pos.y}, ${width}, ${height}, hwnd, reinterpret_cast<HMENU>((INT_PTR)${tree.commandId}), gInstance, nullptr);\n    if (!gControls[${tree.nativeIndex}]) return nullptr; if (gGuiFont) SendMessageW(gControls[${tree.nativeIndex}], WM_SETFONT, (WPARAM)gGuiFont, TRUE);\n    gTreeItems[${tree.nativeIndex}].clear();\n${inserts.join('\n')}\n  }`;
}

function injectTreeRefresh(source, adapted) {
  const start = source.indexOf('static void RefreshUI() {');
  if (start < 0) throw new NativeGuiError('Generated Win32 source is missing RefreshUI for TreeView labels.');
  const marker = '  RefreshTabVisibility();';
  const at = source.indexOf(marker, start);
  if (at < 0) throw new NativeGuiError('Generated Win32 source is missing TreeView refresh insertion point.');
  const lines = [];
  for (const tree of adapted.trees) {
    for (const node of tree.flatNodes) {
      lines.push(`  if (gControls[${tree.nativeIndex}] && gTreeItems[${tree.nativeIndex}].size() > ${node.flatIndex}) { std::wstring label = TreeNodeText_${tree.nativeIndex}_${node.flatIndex}(); TVITEMW item{}; item.mask = TVIF_TEXT; item.hItem = gTreeItems[${tree.nativeIndex}][${node.flatIndex}]; item.pszText = label.data(); TreeView_SetItem(gControls[${tree.nativeIndex}], &item); }`);
    }
  }
  return source.slice(0, at) + lines.join('\n') + '\n' + source.slice(at);
}

function injectTreeSmoke(source, adapted) {
  const start = source.indexOf('static int RunPatchSmoke() {');
  if (start < 0) throw new NativeGuiError('Generated Win32 source is missing TreeView smoke function.');
  let insertion = source.indexOf('  ClearPatchAccessibleNames();', start);
  if (insertion < 0) insertion = source.indexOf('  DestroyWindow(', start);
  if (insertion < 0) throw new NativeGuiError('Generated Win32 TreeView smoke cleanup marker is missing.');
  const checks = [];
  let code = 210;
  for (const tree of adapted.trees) {
    checks.push(`  if (!gControls[${tree.nativeIndex}] || TreeView_GetCount(gControls[${tree.nativeIndex}]) != ${tree.flatNodes.length} || gTreeItems[${tree.nativeIndex}].size() != ${tree.flatNodes.length}) return ${code++};`);
    const event = adapted.events.find(item => item.control === tree.id && item.event === 'changed');
    if (!event || !tree.flatNodes.length) continue;
    const last = tree.flatNodes.at(-1).flatIndex;
    checks.push(`  { int before = gPatchTreeSelectionCount; NMTREEVIEWW change{}; change.hdr.hwndFrom = gControls[${tree.nativeIndex}]; change.hdr.idFrom = ${tree.commandId}; change.hdr.code = TVN_SELCHANGEDW; change.itemNew.hItem = gTreeItems[${tree.nativeIndex}][${last}]; SendMessageW(gForms[${tree.formIndex}], WM_NOTIFY, ${tree.commandId}, (LPARAM)&change); if (gPatchTreeSelectionCount != before + 1) return ${code++}; }`);
    const target = treePersistentPathTarget(event, adapted.states);
    if (target) checks.push(`  if (${stateName(target)} != PatchTreePath_${tree.nativeIndex}(gTreeItems[${tree.nativeIndex}][${last}])) return ${code++};`);
  }
  return source.slice(0, insertion) + checks.join('\n') + '\n' + source.slice(insertion);
}

function replaceControlBlock(source, tree, replacement) {
  const anchor = `  if (${tree.formIndex} == index) {\n    gControls[${tree.nativeIndex}] = CreateWindowExW`;
  const start = source.indexOf(anchor);
  if (start < 0) throw new NativeGuiError(`Win32 TreeView '${tree.id}' shadow control start is missing.`);
  const end = source.indexOf('\n  }', start);
  if (end < 0) throw new NativeGuiError(`Win32 TreeView '${tree.id}' shadow control end is missing.`);
  return source.slice(0, start) + replacement + source.slice(end + 4);
}
function removeShadowState(source, tree) { return replaceRequired(source, `static std::vector<std::wstring> ${stateName(tree.shadowState)} = {};\n`, '', `Win32 TreeView '${tree.id}' shadow state`); }
function removeShadowRefresh(source, tree) { return replaceRequired(source, `  if (gControls[${tree.nativeIndex}]) SetListBoxSelections(gControls[${tree.nativeIndex}], ${stateName(tree.shadowState)});\n`, '', `Win32 TreeView '${tree.id}' shadow refresh`); }
function assertNoShadowState(source, adapted) { for (const tree of adapted.trees) if (source.includes(tree.shadowState)) throw new NativeGuiError(`Win32 TreeView '${tree.id}' leaked backend shadow state.`); }

function wideTemplateExpr(text, states) {
  const parts = []; let cursor = 0; const re = /\{([A-Za-z_]\w*)\}/g; let match;
  while ((match = re.exec(text))) {
    if (match.index > cursor) parts.push(`std::wstring(${wideString(text.slice(cursor, match.index))})`);
    const state = states.get(match[1]);
    if (state.type === 'boolean') parts.push(`PatchBoolean(${stateName(state.name)})`);
    else if (state.type === 'number') parts.push(`PatchNumber(${stateName(state.name)})`);
    else parts.push(`${stateName(state.name)}`);
    cursor = match.index + match[0].length;
  }
  if (cursor < text.length) parts.push(`std::wstring(${wideString(text.slice(cursor))})`);
  return parts.length ? parts.join(' + ') : 'std::wstring()';
}
function win32Position(control, controls) { if ((control.parentTabIndex ?? -1) < 0) return { x:layoutInt(control.layout?.x,24), y:layoutInt(control.layout?.y,24) }; const tab=controls[control.parentTabIndex]; if(!tab||tab.type!=='tabs')throw new NativeGuiError(`Win32 TreeView '${control.id}' has an invalid Tabs parent.`); return {x:layoutInt(tab.layout?.x,24)+10+layoutInt(control.layout?.x,12),y:layoutInt(tab.layout?.y,24)+30+layoutInt(control.layout?.y,12)}; }
function stateName(name){return `patch_state_${identifier(name)}`;} function identifier(value){return String(value).replace(/[^A-Za-z0-9_]/g,'_').replace(/^[0-9]/,'_$&');}
function wideString(value){return `L${JSON.stringify(String(value??'')).replace(/\\u([0-9a-fA-F]{4})/g,(_,hex)=>`\\x${hex}`)}`;}
function layoutInt(value,fallback){return Number.isFinite(Number(value))?Math.max(0,Math.round(Number(value))):fallback;} function positiveInt(value,fallback){return Number.isFinite(Number(value))?Math.max(1,Math.round(Number(value))):fallback;}
function replaceRequired(source,marker,replacement,label){if(!source.includes(marker))throw new NativeGuiError(`${label} marker is missing from generated Win32 source.`);return source.replace(marker,replacement);}
