import { flattenNativeGuiControls, NativeGuiError } from './native-gui-ir.js';
import { emitWin32GuiCpp as emitWin32GuiCppV07 } from './win32-gui-v07.js';
import {
  nativeAccessibleName,
  nativeRadioItemAccessibleName,
  needsExplicitNativeAccessibleName
} from './native-accessibility.js';

export const PATCH_WIN32_GUI_BACKEND_VERSION = '0.8';

export function emitWin32GuiCpp(input) {
  const controls = flattenNativeGuiControls(input);
  let source = emitWin32GuiCppV07(input)
    .replace(/Generated by Patch Win32 GUI backend 0\.7\./, `Generated by Patch Win32 GUI backend ${PATCH_WIN32_GUI_BACKEND_VERSION}.`);

  source = replaceRequired(source, '#include <windows.h>\n', '#include <windows.h>\n#include <initguid.h>\n#include <oleacc.h>\n#include <objbase.h>\n', 'Win32 include block');
  source = replaceRequired(
    source,
    '#pragma comment(lib, "comctl32.lib")',
    '#pragma comment(lib, "comctl32.lib")\n#pragma comment(lib, "oleacc.lib")\n#pragma comment(lib, "ole32.lib")\n#pragma comment(lib, "oleaut32.lib")',
    'Win32 library block'
  );
  source = replaceRequired(source, 'static void RefreshTabVisibility() {', `${win32AccessibilityHelpers(controls)}\nstatic void RefreshTabVisibility() {`, 'Win32 accessibility helper insertion');
  source = replaceRequired(
    source,
    'int WINAPI wWinMain(HINSTANCE instance, HINSTANCE, PWSTR, int showCommand) {\n  gInstance = instance;',
    'int WINAPI wWinMain(HINSTANCE instance, HINSTANCE, PWSTR, int showCommand) {\n  PatchComScope patchCom;\n  gInstance = instance;',
    'Win32 COM initialization'
  );
  source = replaceRequired(
    source,
    'for (int i = 0; i < FORM_COUNT; ++i) if (!CreatePatchForm(i)) return 11 + i;\n  RefreshUI();',
    'for (int i = 0; i < FORM_COUNT; ++i) if (!CreatePatchForm(i)) return 11 + i;\n  ApplyPatchAccessibility();\n  RefreshUI();',
    'Win32 accessibility application'
  );
  source = replaceRequired(
    source,
    'if (form == 0) DestroyWindow(hwnd); else ShowWindow(hwnd, SW_HIDE);',
    'if (form == 0) { ClearPatchAccessibleNames(); DestroyWindow(hwnd); } else ShowWindow(hwnd, SW_HIDE);',
    'Win32 accessibility cleanup on close'
  );
  source = injectAccessibilitySmoke(source, controls);
  source = source.replace(/  DestroyWindow\(gForms\[(\d+)\]\);/g, '  ClearPatchAccessibleNames();\n  DestroyWindow(gForms[$1]);');
  return source;
}

function win32AccessibilityHelpers(controls) {
  const apply = [];
  const clear = [];
  for (const control of controls) {
    if (!needsExplicitNativeAccessibleName(control)) continue;
    if (control.type === 'radio') {
      for (let optionIndex = 0; optionIndex < control.options.length; optionIndex += 1) {
        const name = nativeRadioItemAccessibleName(control, control.options[optionIndex]);
        apply.push(`  if (gRadioItems[${control.nativeIndex}].size() > ${optionIndex}) SetPatchAccessibleName(gRadioItems[${control.nativeIndex}][${optionIndex}], L${cppString(name)});`);
        clear.push(`  if (gRadioItems[${control.nativeIndex}].size() > ${optionIndex}) ClearPatchAccessibleName(gRadioItems[${control.nativeIndex}][${optionIndex}]);`);
      }
      continue;
    }
    const name = nativeAccessibleName(control);
    if (!name) continue;
    apply.push(`  SetPatchAccessibleName(gControls[${control.nativeIndex}], L${cppString(name)});`);
    clear.push(`  ClearPatchAccessibleName(gControls[${control.nativeIndex}]);`);
  }

  return `struct PatchComScope {\n  HRESULT result;\n  PatchComScope() : result(CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED)) {}\n  ~PatchComScope() { if (SUCCEEDED(result)) CoUninitialize(); }\n};\nstatic void SetPatchAccessibleName(HWND hwnd, const wchar_t *name) {\n  if (!hwnd || !name || !*name) return;\n  IAccPropServices *service = nullptr;\n  const HRESULT created = CoCreateInstance(CLSID_AccPropServices, nullptr, CLSCTX_SERVER, IID_IAccPropServices, reinterpret_cast<void **>(&service));\n  if (SUCCEEDED(created) && service) {\n    service->SetHwndPropStr(hwnd, OBJID_CLIENT, CHILDID_SELF, PROPID_ACC_NAME, name);\n    service->Release();\n  }\n}\nstatic void ClearPatchAccessibleName(HWND hwnd) {\n  if (!hwnd) return;\n  IAccPropServices *service = nullptr;\n  const HRESULT created = CoCreateInstance(CLSID_AccPropServices, nullptr, CLSCTX_SERVER, IID_IAccPropServices, reinterpret_cast<void **>(&service));\n  if (SUCCEEDED(created) && service) {\n    MSAAPROPID property = PROPID_ACC_NAME;\n    service->ClearHwndProps(hwnd, OBJID_CLIENT, CHILDID_SELF, &property, 1);\n    service->Release();\n  }\n}\nstatic std::wstring PatchAccessibleName(HWND hwnd) {\n  if (!hwnd) return L\"\";\n  IAccessible *accessible = nullptr;\n  const HRESULT opened = AccessibleObjectFromWindow(hwnd, OBJID_CLIENT, IID_IAccessible, reinterpret_cast<void **>(&accessible));\n  if (FAILED(opened) || !accessible) return L\"\";\n  VARIANT child{}; child.vt = VT_I4; child.lVal = CHILDID_SELF;\n  BSTR value = nullptr;\n  const HRESULT read = accessible->get_accName(child, &value);\n  std::wstring result = SUCCEEDED(read) && value ? std::wstring(value) : std::wstring();\n  if (value) SysFreeString(value);\n  accessible->Release();\n  return result;\n}\nstatic void ApplyPatchAccessibility() {\n${apply.join('\n') || '  // Standard native control names need no Patch annotation.'}\n}\nstatic void ClearPatchAccessibleNames() {\n${clear.join('\n') || '  // No Patch accessibility annotations to clear.'}\n}\n`;
}

function injectAccessibilitySmoke(source, controls) {
  const checks = [];
  let code = 130;
  for (const control of controls) {
    if (!needsExplicitNativeAccessibleName(control)) continue;
    if (control.type === 'radio') {
      for (let optionIndex = 0; optionIndex < control.options.length; optionIndex += 1) {
        const expected = nativeRadioItemAccessibleName(control, control.options[optionIndex]);
        checks.push(`  if (gRadioItems[${control.nativeIndex}].size() <= ${optionIndex} || PatchAccessibleName(gRadioItems[${control.nativeIndex}][${optionIndex}]) != L${cppString(expected)}) return ${code++};`);
      }
      continue;
    }
    const expected = nativeAccessibleName(control);
    if (!expected) continue;
    checks.push(`  if (PatchAccessibleName(gControls[${control.nativeIndex}]) != L${cppString(expected)}) return ${code++};`);
  }
  if (!checks.length) return source;
  const start = source.indexOf('static int RunPatchSmoke() {');
  if (start < 0) throw new NativeGuiError('Generated Win32 source is missing RunPatchSmoke for accessibility verification.');
  const destroy = source.indexOf('  DestroyWindow(gForms[', start);
  if (destroy < 0) throw new NativeGuiError('Generated Win32 smoke has an unexpected shape for accessibility verification.');
  return source.slice(0, destroy) + checks.join('\n') + '\n' + source.slice(destroy);
}

function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated Win32 source.`);
  return source.replace(marker, replacement);
}

function cppString(value) {
  return JSON.stringify(String(value ?? '')).replace(/\\u([0-9a-fA-F]{4})/g, (_, hex) => `\\x${hex}`);
}
