import { NativeGuiError } from './native-gui-ir.js';
import { emitWin32GuiCppV11 } from './win32-gui-v11.js';
import { adaptNativeListsForV11Backend } from './native-list-backend-adapter.js';

export const PATCH_WIN32_GUI_BACKEND_V12_VERSION = '1.2';

/** Emit Win32 backend 1.2 with persistent list state and native multi-select ListBox. */
export function emitWin32GuiCppV12(input) {
  const adapted = adaptNativeListsForV11Backend(input);
  let source = emitWin32GuiCppV11(adapted.compatibleIr)
    .replace(/Generated by Patch Win32 GUI backend 1\.1\./, `Generated by Patch Win32 GUI backend ${PATCH_WIN32_GUI_BACKEND_V12_VERSION}.`);

  if (!adapted.listStates.size) return source;

  source = replaceRequired(source, '#include <cmath>', '#include <algorithm>\n#include <cmath>', 'Win32 list algorithm include');
  source = injectListHelpers(source);

  for (const state of adapted.listStates.values()) {
    const marker = `static std::wstring ${stateName(state.name)} = ${wideString(state.initial?.[0] ?? '')};`;
    const replacement = `static std::vector<std::wstring> ${stateName(state.name)} = ${wideVector(state.initial ?? [])};`;
    source = replaceRequired(source, marker, replacement, `Win32 list state '${state.name}' declaration`);
  }

  for (const control of adapted.multiControls) {
    const createMarker = `gControls[${control.nativeIndex}] = CreateWindowExW(0, L"LISTBOX", L"", WS_CHILD | WS_VISIBLE | WS_TABSTOP | WS_VSCROLL | WS_BORDER | LBS_NOTIFY,`;
    const createReplacement = `gControls[${control.nativeIndex}] = CreateWindowExW(0, L"LISTBOX", L"", WS_CHILD | WS_VISIBLE | WS_TABSTOP | WS_VSCROLL | WS_BORDER | LBS_NOTIFY | LBS_EXTENDEDSEL,`;
    source = replaceRequired(source, createMarker, createReplacement, `Win32 multi-select ListBox '${control.id}' creation`);
    source = replaceRequired(
      source,
      `SetListBoxSelection(gControls[${control.nativeIndex}], ${stateName(control.binding)});`,
      `SetListBoxSelections(gControls[${control.nativeIndex}], ${stateName(control.binding)});`,
      `Win32 multi-select ListBox '${control.id}' refresh`
    );
  }

  for (const event of adapted.events) {
    source = patchListEventFunction(source, event);
    const control = adapted.multiControls.find(item => item.id === event.control);
    if (!control) continue;
    source = replaceRequired(
      source,
      `Event_${event.eventIndex}(ListBoxText(controlHwnd));`,
      `Event_${event.eventIndex}(ListBoxTexts(controlHwnd));`,
      `Win32 multi-select ListBox '${event.control}' event dispatch`
    );
  }

  source = injectSmoke(source, adapted);
  return source;
}

function injectListHelpers(source) {
  const marker = `static void SetListBoxSelection(HWND hwnd, const std::wstring& value) {\n  if (!hwnd) return;\n  int count = (int)SendMessageW(hwnd, LB_GETCOUNT, 0, 0);\n  int selected = -1;\n  for (int i = 0; i < count; ++i) if (ListBoxTextAt(hwnd, i) == value) { selected = i; break; }\n  SendMessageW(hwnd, LB_SETCURSEL, selected, 0);\n}`;
  const addition = `${marker}\nstatic std::vector<std::wstring> ListBoxTexts(HWND hwnd) {\n  std::vector<std::wstring> out;\n  if (!hwnd) return out;\n  LRESULT selectedCount = SendMessageW(hwnd, LB_GETSELCOUNT, 0, 0);\n  if (selectedCount <= 0) return out;\n  std::vector<int> indices((size_t)selectedCount);\n  LRESULT copied = SendMessageW(hwnd, LB_GETSELITEMS, (WPARAM)indices.size(), (LPARAM)indices.data());\n  if (copied <= 0) return out;\n  for (int i = 0; i < (int)copied; ++i) out.push_back(ListBoxTextAt(hwnd, indices[(size_t)i]));\n  return out;\n}\nstatic void SetListBoxSelections(HWND hwnd, const std::vector<std::wstring>& values) {\n  if (!hwnd) return;\n  SendMessageW(hwnd, LB_SETSEL, FALSE, (LPARAM)-1);\n  for (const auto& value : values) {\n    int index = (int)SendMessageW(hwnd, LB_FINDSTRINGEXACT, (WPARAM)-1, (LPARAM)value.c_str());\n    if (index >= 0) SendMessageW(hwnd, LB_SETSEL, TRUE, (LPARAM)index);\n  }\n}`;
  return replaceRequired(source, marker, addition, 'Win32 multi-select ListBox helpers');
}

function patchListEventFunction(source, event) {
  const oldSignature = `static void Event_${event.eventIndex}(const std::wstring& eventValue) {`;
  const newSignature = `static void Event_${event.eventIndex}(const std::vector<std::wstring>& eventValue) {`;
  let start = source.indexOf(oldSignature);
  if (start < 0) throw new NativeGuiError(`Win32 list Event_${event.eventIndex} signature marker is missing.`);
  const endMarker = '\n  RefreshUI();\n}';
  const end = source.indexOf(endMarker, start);
  if (end < 0) throw new NativeGuiError(`Win32 list Event_${event.eventIndex} body marker is missing.`);
  let body = source.slice(start, end + endMarker.length).replace(oldSignature, newSignature);

  for (const action of event.actions ?? []) {
    if (action.kind !== 'change' || action.stateType !== 'list') continue;
    const target = stateName(action.target);
    for (const op of action.ops ?? []) {
      if (op.op === 'clear') continue;
      if (op.value?.kind === 'eventValue') continue;
      if (op.op === 'add') {
        body = replaceInBody(body, `  ${target} += std::wstring(${wideString('')});`, `  ${target}.push_back(std::wstring(${wideString(op.value.value)}));`, `Win32 list add '${action.target}'`);
      } else if (op.op === 'remove') {
        body = replaceInBody(body, `  ${target} = std::wstring(${wideString('')});`, `  ${target}.erase(std::remove(${target}.begin(), ${target}.end(), std::wstring(${wideString(op.value.value)})), ${target}.end());`, `Win32 list remove '${action.target}'`);
      } else if (op.op === 'set') {
        body = replaceInBody(body, `  ${target} = std::wstring(${wideString('')});`, `  ${target} = ${wideVector(op.value.value)};`, `Win32 list set '${action.target}'`);
      }
    }
  }
  return source.slice(0, start) + body + source.slice(end + endMarker.length);
}

function injectSmoke(source, adapted) {
  const candidate = adapted.multiControls.find(control => {
    const event = adapted.events.find(item => item.control === control.id && item.event === 'changed');
    return event && event.actions?.some(action => action.kind === 'change' && action.target === control.binding && action.ops?.some(op => op.op === 'set' && op.value?.kind === 'eventValue'));
  });
  if (!candidate || candidate.options.length < 2) return source;
  const first = candidate.options[0];
  const last = candidate.options[candidate.options.length - 1];
  const smoke = `  SendMessageW(gControls[${candidate.nativeIndex}], LB_SETSEL, FALSE, (LPARAM)-1);\n  SendMessageW(gControls[${candidate.nativeIndex}], LB_SETSEL, TRUE, 0);\n  SendMessageW(gControls[${candidate.nativeIndex}], LB_SETSEL, TRUE, ${candidate.options.length - 1});\n  OnCommand(${candidate.commandId}, LBN_SELCHANGE, gControls[${candidate.nativeIndex}]);\n  if (${stateName(candidate.binding)}.size() != 2 || ${stateName(candidate.binding)}[0] != ${wideString(first)} || ${stateName(candidate.binding)}[1] != ${wideString(last)}) return 91;\n`;
  const marker = '  DestroyWindow(gForms[mainIndex]);\n  return 0;';
  return replaceRequired(source, marker, smoke + marker, 'Win32 multi-select smoke insertion');
}

function replaceInBody(body, marker, replacement, label) {
  if (!body.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated Win32 event body.`);
  return body.replace(marker, replacement);
}
function stateName(name) { return `patch_state_${identifier(name)}`; }
function identifier(value) { return String(value).replace(/[^A-Za-z0-9_]/g, '_').replace(/^[0-9]/, '_$&'); }
function wideString(value) { return `L${JSON.stringify(String(value ?? '')).replace(/\\u([0-9a-fA-F]{4})/g, (_, hex) => `\\x${hex}`)}`; }
function wideVector(values) { return `{${(values ?? []).map(value => wideString(value)).join(', ')}}`; }
function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated Win32 source.`);
  return source.replace(marker, replacement);
}
