import { NativeGuiError } from './native-gui-ir.js';
import { emitWin32GuiCppV09 } from './win32-gui-v09.js';
import { adaptNativeMenusForLegacyBackend } from './native-menu-backend-adapter.js';
import { menuShortcutPlatformDisplay } from './menu-shortcut.js';

export const PATCH_WIN32_GUI_BACKEND_V10_VERSION = '1.0';

/** Emit Win32 backend 1.0 with native Menu separators and ACCEL shortcuts. */
export function emitWin32GuiCppV10(input) {
  const adapted = adaptNativeMenusForLegacyBackend(input);
  let source = emitWin32GuiCppV09(adapted.legacyIr)
    .replace(/Generated by Patch Win32 GUI backend 0\.9\./, `Generated by Patch Win32 GUI backend ${PATCH_WIN32_GUI_BACKEND_V10_VERSION}.`);

  for (const entry of adapted.separators) {
    source = replaceRequired(
      source,
      win32MenuLine(entry, entry.legacyText),
      `AppendMenuW(popup_${entry.formIndex}_${entry.menuIndex}, MF_SEPARATOR, 0, nullptr);`,
      `Win32 Menu separator ${entry.formIndex + 1}/${entry.menuIndex + 1}/${entry.itemIndex + 1}`
    );
  }

  for (const entry of adapted.shortcuts) {
    const label = `${entry.text}\t${menuShortcutPlatformDisplay(entry.shortcut, 'win32')}`;
    source = replaceRequired(
      source,
      win32MenuLine(entry, entry.legacyText),
      win32MenuLine(entry, label),
      `Win32 Menu shortcut '${entry.id}' label`
    );
  }

  if (adapted.shortcuts.length) source = injectAccelerators(source, adapted.shortcuts);
  return source;
}

function injectAccelerators(source, shortcuts) {
  const entries = shortcuts.map(entry =>
    `  {${win32Flags(entry.shortcut)}, ${win32Key(entry.shortcut.key)}, ${entry.commandId}}`
  ).join(',\n');
  const table = `static ACCEL PATCH_ACCELERATORS[] = {\n${entries}\n};\nstatic const int PATCH_ACCELERATOR_COUNT = ${shortcuts.length};`;

  source = replaceRequired(
    source,
    'static HINSTANCE gInstance = nullptr;',
    'static HINSTANCE gInstance = nullptr;\nstatic HACCEL gPatchAccelerators = nullptr;',
    'Win32 accelerator handle declaration'
  );
  source = replaceRequired(
    source,
    'int WINAPI wWinMain(HINSTANCE instance, HINSTANCE, PWSTR, int showCommand) {',
    `${table}\n\nint WINAPI wWinMain(HINSTANCE instance, HINSTANCE, PWSTR, int showCommand) {`,
    'Win32 accelerator table insertion'
  );
  source = replaceRequired(
    source,
    '  gSmokeMode = HasArg(L"--patch-smoke");',
    '  gSmokeMode = HasArg(L"--patch-smoke");\n  gPatchAccelerators = CreateAcceleratorTableW(PATCH_ACCELERATORS, PATCH_ACCELERATOR_COUNT);\n  if (!gPatchAccelerators) return 8;',
    'Win32 accelerator initialization'
  );
  source = replaceRequired(
    source,
    '  MSG msg{};\n  while (GetMessageW(&msg, nullptr, 0, 0) > 0) {\n    TranslateMessage(&msg);\n    DispatchMessageW(&msg);\n  }\n  return (int)msg.wParam;',
    '  MSG msg{};\n  while (GetMessageW(&msg, nullptr, 0, 0) > 0) {\n    HWND acceleratorTarget = msg.hwnd ? GetAncestor(msg.hwnd, GA_ROOT) : gForms[0];\n    if (!gPatchAccelerators || !TranslateAcceleratorW(acceleratorTarget ? acceleratorTarget : gForms[0], gPatchAccelerators, &msg)) {\n      TranslateMessage(&msg);\n      DispatchMessageW(&msg);\n    }\n  }\n  if (gPatchAccelerators) DestroyAcceleratorTable(gPatchAccelerators);\n  return (int)msg.wParam;',
    'Win32 accelerator message-loop dispatch'
  );
  return source;
}

function win32MenuLine(entry, label) {
  return `AppendMenuW(popup_${entry.formIndex}_${entry.menuIndex}, MF_STRING, ${entry.commandId}, L${cppString(label)});`;
}

function win32Flags(shortcut) {
  const flags = ['FVIRTKEY'];
  if (shortcut.primary) flags.push('FCONTROL');
  if (shortcut.shift) flags.push('FSHIFT');
  if (shortcut.alt) flags.push('FALT');
  return flags.join(' | ');
}

function win32Key(key) {
  if (/^[A-Z0-9]$/.test(key)) return `'${key}'`;
  if (/^F(?:[1-9]|1[0-2])$/.test(key)) return `VK_${key}`;
  throw new NativeGuiError(`Win32 shortcut key '${key}' is unsupported.`);
}

function replaceRequired(source, marker, replacement, label) {
  if (!source.includes(marker)) throw new NativeGuiError(`${label} marker is missing from generated Win32 source.`);
  return source.replace(marker, replacement);
}

function cppString(value) {
  return JSON.stringify(String(value ?? '')).replace(/\\u([0-9a-fA-F]{4})/g, (_, hex) => `\\x${hex}`);
}
