import { validateNativeGuiIR, NativeGuiError } from './native-gui-ir.js';

export const PATCH_WIN32_GUI_BACKEND_VERSION = '0.1';

export function emitWin32GuiCpp(input) {
  const ir = validateNativeGuiIR(input);
  const formIndex = new Map(ir.forms.map((form, index) => [form.id, index]));
  const controlRecords = [];
  let nextCommandId = 1000;
  for (let f = 0; f < ir.forms.length; f++) {
    for (const control of ir.forms[f].controls) {
      controlRecords.push({ ...control, formIndex: f, commandId: nextCommandId++, handleIndex: controlRecords.length });
    }
  }
  const controlById = new Map(controlRecords.filter(c => c.id).map(c => [c.id, c]));
  const stateByName = new Map(ir.states.map(state => [state.name, state]));

  for (const event of ir.events) {
    if (!controlById.has(event.control)) throw new NativeGuiError(`Win32 event control '${event.control}' is missing.`);
    for (const action of event.actions) {
      if ((action.kind === 'openForm' || action.kind === 'closeForm') && !formIndex.has(action.form)) {
        throw new NativeGuiError(`Win32 Form '${action.form}' is missing.`);
      }
    }
  }

  const stateDecls = ir.states.map(stateDeclaration).join('\n');
  const formDefs = ir.forms.map((form, index) =>
    `  {L${cppString(form.id)}, L${cppString(form.title)}, ${positiveInt(form.width, 640)}, ${positiveInt(form.height, 420)}, ${form.visible ? 'true' : 'false'}}${index + 1 === ir.forms.length ? '' : ','}`
  ).join('\n');
  const controlDefs = controlRecords.map((control, index) =>
    `  {${control.commandId}, ${control.formIndex}, ${controlKind(control.type)}, L${cppString(control.id ?? '')}, ${layoutInt(control.layout?.x, 24)}, ${layoutInt(control.layout?.y, 24)}, ${positiveInt(control.layout?.width, 120)}, ${positiveInt(control.layout?.height, 36)}}${index + 1 === controlRecords.length ? '' : ','}`
  ).join('\n');

  const textFunctions = controlRecords.map((control, index) => emitControlTextFunction(control, index, stateByName)).join('\n\n');
  const eventFunctions = ir.events.map((event, index) => emitEventFunction(event, index, formIndex, stateByName)).join('\n\n');
  const dispatchCases = ir.events.map((event, index) => emitDispatchCase(event, index, controlById)).join('\n');
  const refreshCases = controlRecords.map((control, index) => emitRefresh(control, index, stateByName)).join('\n');
  const createCases = controlRecords.map((control, index) => emitCreateControl(control, index)).join('\n');
  const smoke = emitSmoke(ir, formIndex, controlById, stateByName);

  return `// Generated by Patch Win32 GUI backend ${PATCH_WIN32_GUI_BACKEND_VERSION}.\n// Direct native Win32 controls: no Electron/Chromium runtime.\n#define UNICODE\n#define _UNICODE\n#include <windows.h>\n#include <string>\n#include <vector>\n#include <sstream>\n#include <cwchar>\n#include <cmath>\n\nstatic const wchar_t* PATCH_WINDOW_CLASS = L"PatchNativeWindowV1";\nstatic HINSTANCE gInstance = nullptr;\nstatic HFONT gGuiFont = nullptr;\nstatic bool gRefreshing = false;\n\nenum ControlKind { CK_TEXT=1, CK_BUTTON=2, CK_INPUT=3, CK_CHECKBOX=4 };\nstruct FormDef { const wchar_t* id; const wchar_t* title; int width; int height; bool visible; };\nstruct ControlDef { int commandId; int formIndex; ControlKind kind; const wchar_t* name; int x; int y; int width; int height; };\n\n${stateDecls}\n\nstatic const FormDef FORMS[] = {\n${formDefs}\n};\nstatic const int FORM_COUNT = ${ir.forms.length};\nstatic HWND gForms[${Math.max(1, ir.forms.length)}] = {};\n\nstatic const ControlDef CONTROLS[] = {\n${controlDefs || '  {0,0,CK_TEXT,L"",0,0,0,0}'}\n};\nstatic const int CONTROL_COUNT = ${controlRecords.length};\nstatic HWND gControls[${Math.max(1, controlRecords.length)}] = {};\n\nstatic std::wstring PatchNumber(double value) {\n  if (std::isfinite(value) && std::floor(value) == value) return std::to_wstring((long long)value);\n  std::wostringstream out; out << value; return out.str();\n}\nstatic std::wstring PatchBoolean(bool value) { return value ? L"true" : L"false"; }\nstatic std::wstring WindowText(HWND hwnd) {\n  const int len = GetWindowTextLengthW(hwnd);\n  if (len <= 0) return L"";\n  std::wstring value((size_t)len + 1, L'\\0');\n  const int copied = GetWindowTextW(hwnd, value.data(), len + 1);\n  value.resize(copied > 0 ? (size_t)copied : 0);\n  return value;\n}\nstatic void SetWindowTextIfDifferent(HWND hwnd, const std::wstring& value) {\n  if (WindowText(hwnd) != value) SetWindowTextW(hwnd, value.c_str());\n}\n\n${textFunctions}\n\nstatic void RefreshUI();\n\n${eventFunctions}\n\nstatic void DispatchControl(int commandId, int notification, HWND controlHwnd) {\n  if (gRefreshing) return;\n${dispatchCases || '  (void)commandId; (void)notification; (void)controlHwnd;'}\n}\n\nstatic void RefreshUI() {\n  gRefreshing = true;\n${refreshCases}\n  gRefreshing = false;\n}\n\nstatic LRESULT CALLBACK PatchWndProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam) {\n  int form = (int)(INT_PTR)GetWindowLongPtrW(hwnd, GWLP_USERDATA);\n  if (msg == WM_NCCREATE) {\n    auto* create = reinterpret_cast<CREATESTRUCTW*>(lParam);\n    form = (int)(INT_PTR)create->lpCreateParams;\n    SetWindowLongPtrW(hwnd, GWLP_USERDATA, (LONG_PTR)form);\n  }\n  switch (msg) {\n    case WM_COMMAND:\n      DispatchControl(LOWORD(wParam), HIWORD(wParam), reinterpret_cast<HWND>(lParam));\n      return 0;\n    case WM_CLOSE:\n      if (form == 0) DestroyWindow(hwnd); else ShowWindow(hwnd, SW_HIDE);\n      return 0;\n    case WM_DESTROY:\n      if (form == 0) PostQuitMessage(0);\n      return 0;\n  }\n  return DefWindowProcW(hwnd, msg, wParam, lParam);\n}\n\nstatic HWND CreatePatchForm(int index) {\n  RECT rect{0, 0, FORMS[index].width, FORMS[index].height};\n  AdjustWindowRect(&rect, WS_OVERLAPPEDWINDOW, FALSE);\n  HWND hwnd = CreateWindowExW(0, PATCH_WINDOW_CLASS, FORMS[index].title, WS_OVERLAPPEDWINDOW,\n    CW_USEDEFAULT, CW_USEDEFAULT, rect.right - rect.left, rect.bottom - rect.top,\n    nullptr, nullptr, gInstance, reinterpret_cast<void*>((INT_PTR)index));\n  if (!hwnd) return nullptr;\n  gForms[index] = hwnd;\n${createCases}\n  return hwnd;\n}\n\nstatic bool HasArg(const wchar_t* value) { return std::wcsstr(GetCommandLineW(), value) != nullptr; }\n\n${smoke}\n\nint WINAPI wWinMain(HINSTANCE instance, HINSTANCE, PWSTR, int showCommand) {\n  gInstance = instance;\n  gGuiFont = (HFONT)GetStockObject(DEFAULT_GUI_FONT);\n  WNDCLASSEXW wc{};\n  wc.cbSize = sizeof(wc);\n  wc.hInstance = instance;\n  wc.lpfnWndProc = PatchWndProc;\n  wc.lpszClassName = PATCH_WINDOW_CLASS;\n  wc.hCursor = LoadCursor(nullptr, IDC_ARROW);\n  wc.hIcon = LoadIcon(nullptr, IDI_APPLICATION);\n  wc.hbrBackground = (HBRUSH)(COLOR_WINDOW + 1);\n  if (!RegisterClassExW(&wc)) return 10;\n\n  for (int i = 0; i < FORM_COUNT; ++i) {\n    if (!CreatePatchForm(i)) return 11 + i;\n  }\n  RefreshUI();\n  for (int i = 0; i < FORM_COUNT; ++i) {\n    if (FORMS[i].visible) ShowWindow(gForms[i], showCommand == 0 ? SW_SHOWNORMAL : showCommand);\n  }\n  UpdateWindow(gForms[0]);\n\n  if (HasArg(L"--patch-smoke")) return RunPatchSmoke();\n\n  MSG msg{};\n  while (GetMessageW(&msg, nullptr, 0, 0) > 0) {\n    TranslateMessage(&msg);\n    DispatchMessageW(&msg);\n  }\n  return (int)msg.wParam;\n}\n`;
}

function stateDeclaration(state) {
  const name = stateName(state.name);
  if (state.type === 'boolean') return `static bool ${name} = ${state.initial ? 'true' : 'false'};`;
  if (state.type === 'number') return `static double ${name} = ${Number(state.initial)};`;
  if (state.type === 'text') return `static std::wstring ${name} = L${cppString(state.initial)};`;
  throw new NativeGuiError(`Win32 state type '${state.type}' is unsupported.`);
}

function emitControlTextFunction(control, index, states) {
  const text = String(control.text ?? '');
  const parts = [];
  let cursor = 0;
  const re = /\{([A-Za-z_]\w*)\}/g;
  let match;
  while ((match = re.exec(text))) {
    if (match.index > cursor) parts.push(`  out += L${cppString(text.slice(cursor, match.index))};`);
    const state = states.get(match[1]);
    if (!state) throw new NativeGuiError(`Win32 text '${text}' refers to unknown state '${match[1]}'.`);
    if (state.type === 'boolean') parts.push(`  out += PatchBoolean(${stateName(state.name)});`);
    else if (state.type === 'number') parts.push(`  out += PatchNumber(${stateName(state.name)});`);
    else if (state.type === 'text') parts.push(`  out += ${stateName(state.name)};`);
    cursor = match.index + match[0].length;
  }
  if (cursor < text.length) parts.push(`  out += L${cppString(text.slice(cursor))};`);
  if (!parts.length) parts.push(`  out += L${cppString(text)};`);
  return `static std::wstring ControlText_${index}() {\n  std::wstring out;\n${parts.join('\n')}\n  return out;\n}`;
}

function emitEventFunction(event, index, forms, states) {
  const param = event.valueType === 'boolean' ? 'bool eventValue' : event.valueType === 'text' ? 'const std::wstring& eventValue' : '';
  const actions = event.actions.map(action => emitAction(action, event, forms, states)).join('\n');
  return `static void Event_${index}(${param}) {\n${actions || '  // no-op'}\n  RefreshUI();\n}`;
}

function emitAction(action, event, forms, states) {
  if (action.kind === 'openForm') return `  ShowWindow(gForms[${forms.get(action.form)}], SW_SHOW); UpdateWindow(gForms[${forms.get(action.form)}]);`;
  if (action.kind === 'closeForm') return `  ShowWindow(gForms[${forms.get(action.form)}], SW_HIDE);`;
  if (action.kind !== 'change') throw new NativeGuiError(`Win32 action '${action.kind}' is unsupported.`);
  const state = states.get(action.target);
  if (!state) throw new NativeGuiError(`Win32 change target '${action.target}' is missing.`);
  return action.ops.map(op => emitOperation(state, op, event)).join('\n');
}

function emitOperation(state, op, event) {
  const target = stateName(state.name);
  if (op.op === 'clear') {
    if (state.type === 'boolean') return `  ${target} = false;`;
    if (state.type === 'number') return `  ${target} = 0.0;`;
    if (state.type === 'text') return `  ${target}.clear();`;
  }
  const value = emitNativeValue(state, op.value, event);
  if (op.op === 'set') return `  ${target} = ${value};`;
  if (op.op === 'add' && state.type === 'number') return `  ${target} += ${value};`;
  if (op.op === 'remove' && state.type === 'number') return `  ${target} -= ${value};`;
  if (op.op === 'add' && state.type === 'text') return `  ${target} += ${value};`;
  throw new NativeGuiError(`Win32 native GUI cannot apply '${op.op}' to ${state.type} state '${state.name}'.`);
}

function emitNativeValue(state, value, event) {
  if (value?.kind === 'eventValue') {
    if (state.type !== event.valueType) {
      throw new NativeGuiError(`Win32 event value type ${event.valueType ?? 'none'} cannot be assigned to ${state.type} state '${state.name}'.`);
    }
    return 'eventValue';
  }
  const literal = value?.value;
  if (state.type === 'boolean') return literal ? 'true' : 'false';
  if (state.type === 'number') return String(Number(literal));
  if (state.type === 'text') return `std::wstring(L${cppString(literal)})`;
  throw new NativeGuiError(`Win32 literal type '${state.type}' is unsupported.`);
}

function emitDispatchCase(event, index, controls) {
  const control = controls.get(event.control);
  const notify = control.type === 'button' ? 'BN_CLICKED' : control.type === 'checkbox' ? 'BN_CLICKED' : 'EN_CHANGE';
  let call;
  if (event.valueType === 'boolean') call = `Event_${index}(SendMessageW(controlHwnd, BM_GETCHECK, 0, 0) == BST_CHECKED);`;
  else if (event.valueType === 'text') call = `Event_${index}(WindowText(controlHwnd));`;
  else call = `Event_${index}();`;
  return `  if (commandId == ${control.commandId} && notification == ${notify}) { ${call} return; }`;
}

function emitRefresh(control, index, states) {
  if (control.type === 'text' || control.type === 'button') {
    return `  if (gControls[${index}]) SetWindowTextIfDifferent(gControls[${index}], ControlText_${index}());`;
  }
  if (control.type === 'checkbox') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) { SetWindowTextIfDifferent(gControls[${index}], ControlText_${index}()); SendMessageW(gControls[${index}], BM_SETCHECK, ${stateName(state.name)} ? BST_CHECKED : BST_UNCHECKED, 0); }`;
  }
  if (control.type === 'input') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) SetWindowTextIfDifferent(gControls[${index}], ${stateName(state.name)});`;
  }
  return '';
}

function emitCreateControl(control, index) {
  const style = control.type === 'text'
    ? 'WS_CHILD | WS_VISIBLE | SS_LEFT'
    : control.type === 'button'
      ? 'WS_CHILD | WS_VISIBLE | WS_TABSTOP | BS_PUSHBUTTON'
      : control.type === 'input'
        ? 'WS_CHILD | WS_VISIBLE | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL'
        : 'WS_CHILD | WS_VISIBLE | WS_TABSTOP | BS_AUTOCHECKBOX';
  const klass = control.type === 'text' ? 'L"STATIC"' : control.type === 'input' ? 'L"EDIT"' : 'L"BUTTON"';
  return `  if (${control.formIndex} == index) {\n    gControls[${index}] = CreateWindowExW(0, ${klass}, L"", ${style}, ${control.layout.x}, ${control.layout.y}, ${control.layout.width}, ${control.layout.height}, hwnd, reinterpret_cast<HMENU>((INT_PTR)${control.commandId}), gInstance, nullptr);\n    if (gControls[${index}] && gGuiFont) SendMessageW(gControls[${index}], WM_SETFONT, (WPARAM)gGuiFont, TRUE);\n  }`;
}

function emitSmoke(ir, forms, controls, states) {
  const mainIndex = forms.has('main') ? forms.get('main') : 0;
  const settingsIndex = forms.get('settings');
  const open = controls.get('open_settings');
  const close = controls.get('close_settings');
  const checkbox = controls.get('notifications');
  const notifications = states.get('notifications');
  const lines = [
    'static int RunPatchSmoke() {',
    `  if (!gForms[${mainIndex}] || !IsWindowVisible(gForms[${mainIndex}])) return 70;`
  ];
  if (settingsIndex !== undefined) lines.push(`  if (IsWindowVisible(gForms[${settingsIndex}])) return 71;`);
  if (open && settingsIndex !== undefined) {
    lines.push(`  SendMessageW(gForms[${open.formIndex}], WM_COMMAND, MAKEWPARAM(${open.commandId}, BN_CLICKED), (LPARAM)gControls[${open.handleIndex}]);`);
    lines.push(`  if (!IsWindowVisible(gForms[${settingsIndex}])) return 72;`);
  }
  if (checkbox && notifications?.type === 'boolean') {
    lines.push(`  SendMessageW(gControls[${checkbox.handleIndex}], BM_SETCHECK, BST_CHECKED, 0);`);
    lines.push(`  SendMessageW(gForms[${checkbox.formIndex}], WM_COMMAND, MAKEWPARAM(${checkbox.commandId}, BN_CLICKED), (LPARAM)gControls[${checkbox.handleIndex}]);`);
    lines.push(`  if (!${stateName(notifications.name)}) return 73;`);
  }
  if (close && settingsIndex !== undefined) {
    lines.push(`  SendMessageW(gForms[${close.formIndex}], WM_COMMAND, MAKEWPARAM(${close.commandId}, BN_CLICKED), (LPARAM)gControls[${close.handleIndex}]);`);
    lines.push(`  if (IsWindowVisible(gForms[${settingsIndex}])) return 74;`);
  }
  lines.push(`  DestroyWindow(gForms[${mainIndex}]);`);
  lines.push('  return 0;', '}');
  return lines.join('\n');
}

function controlKind(type) {
  return ({ text: 'CK_TEXT', button: 'CK_BUTTON', input: 'CK_INPUT', checkbox: 'CK_CHECKBOX' })[type] ?? 'CK_TEXT';
}

function stateName(name) { return `patch_state_${cppIdentifier(name)}`; }
function cppIdentifier(value) { return String(value).replace(/[^A-Za-z0-9_]/g, '_').replace(/^[0-9]/, '_$&'); }
function layoutInt(value, fallback) { return Number.isFinite(Number(value)) ? Math.max(0, Math.round(Number(value))) : fallback; }
function positiveInt(value, fallback) { return Number.isFinite(Number(value)) ? Math.max(1, Math.round(Number(value))) : fallback; }
function cppString(value) {
  return JSON.stringify(String(value ?? '')).replace(/\\u([0-9a-fA-F]{4})/g, (_, hex) => `\\x${hex}`);
}
