/**
 * HISTORICAL INCLUDE-CHAIN BASE — direct Win32 backend 0.6 for Native GUI IR 0.7.
 * This is not the Ready runtime. Direct native emit uses win32-gui-v13.js (frozen)
 * or win32-gui-v14.js (current).
 */
import { flattenNativeGuiControls, flattenNativeGuiMenuItems, validateNativeGuiIR, NativeGuiError } from './native-gui-ir.js';

export const PATCH_WIN32_GUI_BACKEND_VERSION = '0.6';

export function emitWin32GuiCpp(input) {
  const ir = validateNativeGuiIR(input);
  const forms = new Map(ir.forms.map((form, index) => [form.id, index]));
  const controls = flattenNativeGuiControls(ir).map(control => ({
    ...control,
    commandId: 1000 + control.nativeIndex,
    handleIndex: control.nativeIndex
  }));
  const menuItems = flattenNativeGuiMenuItems(ir).map(item => ({ ...item, commandId: 20000 + item.nativeIndex }));
  const controlsById = new Map(controls.filter(control => control.id).map(control => [control.id, control]));
  const menuById = new Map(menuItems.map(item => [item.id, item]));
  const sourcesById = new Map([...controlsById, ...menuById]);
  const states = new Map(ir.states.map(state => [state.name, state]));
  validateReferences(ir, forms, sourcesById);

  const stateDecls = ir.states.map(stateDeclaration).join('\n');
  const formDefs = ir.forms.map((form, index) =>
    `  {L${cppString(form.id)}, L${cppString(form.title)}, ${positiveInt(form.width, 640)}, ${positiveInt(form.height, 420)}, ${form.visible ? 'true' : 'false'}, ${form.menus.length ? 'true' : 'false'}}${index + 1 === ir.forms.length ? '' : ','}`
  ).join('\n');
  const controlDefs = controls.map((control, index) =>
    `  {${control.commandId}, ${control.formIndex}, ${controlKind(control.type)}, L${cppString(control.id ?? '')}, ${layoutInt(control.layout?.x, 24)}, ${layoutInt(control.layout?.y, 24)}, ${positiveInt(control.layout?.width, 120)}, ${positiveInt(control.layout?.height, 36)}, ${control.parentTabIndex ?? -1}, ${control.pageIndex ?? -1}}${index + 1 === controls.length ? '' : ','}`
  ).join('\n');
  const textFunctions = controls.map((control, index) => emitControlTextFunction(control, index, states)).join('\n\n');
  const eventFunctions = ir.events.map((event, index) => emitEventFunction(event, index, forms, states)).join('\n\n');
  const dispatch = ir.events.map((event, index) => emitDispatch(event, index, controlsById, menuById)).join('\n');
  const refresh = controls.map((control, index) => emitRefresh(control, index, states)).filter(Boolean).join('\n');
  const create = controls.map((control, index) => emitCreateControl(control, index, controls)).join('\n');
  const createMenus = ir.forms.map((form, index) => emitCreateMenus(form, index, menuById)).filter(Boolean).join('\n');
  const smoke = emitSmoke(forms, controlsById, menuById, states, controls);

  return `// Generated by Patch Win32 GUI backend ${PATCH_WIN32_GUI_BACKEND_VERSION}.
// Direct native Win32 controls: no Electron/Chromium runtime.
#define UNICODE
#define _UNICODE
#include <windows.h>
#include <commctrl.h>
#include <string>
#include <sstream>
#include <vector>
#include <cwchar>
#include <cmath>
#pragma comment(lib, "comctl32.lib")

static const wchar_t* PATCH_WINDOW_CLASS = L"PatchNativeWindowV1";
static HINSTANCE gInstance = nullptr;
static HFONT gGuiFont = nullptr;
static bool gRefreshing = false;
static bool gSmokeMode = false;
static std::wstring gLastDialogTitle;
static std::wstring gLastDialogMessage;

enum ControlKind { CK_TEXT=1, CK_BUTTON=2, CK_INPUT=3, CK_CHECKBOX=4, CK_COMBO=5, CK_LISTBOX=6, CK_TABS=7, CK_RADIO=8 };
struct FormDef { const wchar_t* id; const wchar_t* title; int width; int height; bool visible; bool hasMenu; };
struct ControlDef { int commandId; int formIndex; ControlKind kind; const wchar_t* name; int x; int y; int width; int height; int parentTabIndex; int pageIndex; };

${stateDecls}

static const FormDef FORMS[] = {
${formDefs}
};
static const int FORM_COUNT = ${ir.forms.length};
static HWND gForms[${Math.max(1, ir.forms.length)}] = {};

static const ControlDef CONTROLS[] = {
${controlDefs || '  {0,0,CK_TEXT,L"",0,0,0,0,-1,-1}'}
};
static const int CONTROL_COUNT = ${controls.length};
static HWND gControls[${Math.max(1, controls.length)}] = {};
static int gTabSelection[${Math.max(1, controls.length)}] = {};
static std::vector<std::vector<HWND>> gRadioItems(CONTROL_COUNT);

static std::wstring PatchNumber(double value) {
  if (std::isfinite(value) && std::floor(value) == value) return std::to_wstring((long long)value);
  std::wostringstream out; out << value; return out.str();
}
static std::wstring PatchBoolean(bool value) { return value ? L"true" : L"false"; }
static std::wstring WindowText(HWND hwnd) {
  const int len = GetWindowTextLengthW(hwnd);
  if (len <= 0) return L"";
  std::wstring value((size_t)len + 1, L'\\0');
  const int copied = GetWindowTextW(hwnd, value.data(), len + 1);
  value.resize(copied > 0 ? (size_t)copied : 0);
  return value;
}
static std::wstring ComboText(HWND hwnd) {
  const LRESULT selected = SendMessageW(hwnd, CB_GETCURSEL, 0, 0);
  if (selected == CB_ERR) return L"";
  const LRESULT len = SendMessageW(hwnd, CB_GETLBTEXTLEN, (WPARAM)selected, 0);
  if (len == CB_ERR || len < 0) return L"";
  std::wstring value((size_t)len + 1, L'\\0');
  const LRESULT copied = SendMessageW(hwnd, CB_GETLBTEXT, (WPARAM)selected, (LPARAM)value.data());
  value.resize(copied > 0 ? (size_t)copied : 0);
  return value;
}
static std::wstring ListBoxText(HWND hwnd) {
  const LRESULT selected = SendMessageW(hwnd, LB_GETCURSEL, 0, 0);
  if (selected == LB_ERR) return L"";
  const LRESULT len = SendMessageW(hwnd, LB_GETTEXTLEN, (WPARAM)selected, 0);
  if (len == LB_ERR || len < 0) return L"";
  std::wstring value((size_t)len + 1, L'\\0');
  const LRESULT copied = SendMessageW(hwnd, LB_GETTEXT, (WPARAM)selected, (LPARAM)value.data());
  value.resize(copied > 0 ? (size_t)copied : 0);
  return value;
}
static void SetWindowTextIfDifferent(HWND hwnd, const std::wstring& value) {
  if (WindowText(hwnd) != value) SetWindowTextW(hwnd, value.c_str());
}
static void SetComboSelection(HWND hwnd, const std::wstring& value) {
  if (ComboText(hwnd) == value) return;
  const LRESULT found = SendMessageW(hwnd, CB_FINDSTRINGEXACT, (WPARAM)-1, (LPARAM)value.c_str());
  SendMessageW(hwnd, CB_SETCURSEL, found == CB_ERR ? (WPARAM)-1 : (WPARAM)found, 0);
}
static void SetListBoxSelection(HWND hwnd, const std::wstring& value) {
  if (ListBoxText(hwnd) == value) return;
  const LRESULT found = SendMessageW(hwnd, LB_FINDSTRINGEXACT, (WPARAM)-1, (LPARAM)value.c_str());
  SendMessageW(hwnd, LB_SETCURSEL, found == LB_ERR ? (WPARAM)-1 : (WPARAM)found, 0);
}
static void SetRadioSelection(int index, const std::wstring& value) {
  if (index < 0 || index >= CONTROL_COUNT) return;
  for (HWND item : gRadioItems[(size_t)index]) {
    if (!item) continue;
    SendMessageW(item, BM_SETCHECK, WindowText(item) == value ? BST_CHECKED : BST_UNCHECKED, 0);
  }
}
static void ShowInfoDialog(int formIndex, const wchar_t* title, const wchar_t* message) {
  if (gSmokeMode) { gLastDialogTitle = title ? title : L""; gLastDialogMessage = message ? message : L""; return; }
  HWND owner = formIndex >= 0 && formIndex < FORM_COUNT ? gForms[formIndex] : nullptr;
  MessageBoxW(owner, message ? message : L"", title ? title : L"", MB_OK | MB_ICONINFORMATION);
}
static void RefreshTabVisibility() {
  for (int i = 0; i < CONTROL_COUNT; ++i) {
    const int parent = CONTROLS[i].parentTabIndex;
    if (parent < 0) continue;
    const bool visible = parent < CONTROL_COUNT && gTabSelection[parent] == CONTROLS[i].pageIndex;
    if (CONTROLS[i].kind == CK_RADIO) {
      for (HWND item : gRadioItems[(size_t)i]) if (item) ShowWindow(item, visible ? SW_SHOW : SW_HIDE);
    } else if (gControls[i]) {
      ShowWindow(gControls[i], visible ? SW_SHOW : SW_HIDE);
    }
  }
}
static bool HandleTabNotify(NMHDR *header) {
  if (!header || header->code != TCN_SELCHANGE) return false;
  for (int i = 0; i < CONTROL_COUNT; ++i) {
    if (CONTROLS[i].kind != CK_TABS || gControls[i] != header->hwndFrom) continue;
    int selected = (int)SendMessageW(gControls[i], TCM_GETCURSEL, 0, 0);
    gTabSelection[i] = selected >= 0 ? selected : 0;
    RefreshTabVisibility();
    return true;
  }
  return false;
}

${textFunctions}

static void RefreshUI();

${eventFunctions}

static void DispatchControl(int commandId, int notification, HWND controlHwnd) {
  if (gRefreshing) return;
${dispatch || '  (void)commandId; (void)notification; (void)controlHwnd;'}
}

static void RefreshUI() {
  gRefreshing = true;
${refresh}
  RefreshTabVisibility();
  gRefreshing = false;
}

static LRESULT CALLBACK PatchWndProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam) {
  int form = (int)(INT_PTR)GetWindowLongPtrW(hwnd, GWLP_USERDATA);
  if (msg == WM_NCCREATE) {
    auto* create = reinterpret_cast<CREATESTRUCTW*>(lParam);
    form = (int)(INT_PTR)create->lpCreateParams;
    SetWindowLongPtrW(hwnd, GWLP_USERDATA, (LONG_PTR)form);
  }
  switch (msg) {
    case WM_COMMAND:
      DispatchControl(LOWORD(wParam), HIWORD(wParam), reinterpret_cast<HWND>(lParam));
      return 0;
    case WM_NOTIFY:
      if (HandleTabNotify(reinterpret_cast<NMHDR*>(lParam))) return 0;
      break;
    case WM_CLOSE:
      if (form == 0) DestroyWindow(hwnd); else ShowWindow(hwnd, SW_HIDE);
      return 0;
    case WM_DESTROY:
      if (form == 0) PostQuitMessage(0);
      return 0;
  }
  return DefWindowProcW(hwnd, msg, wParam, lParam);
}

static HWND CreatePatchForm(int index) {
  RECT rect{0, 0, FORMS[index].width, FORMS[index].height};
  AdjustWindowRect(&rect, WS_OVERLAPPEDWINDOW, FORMS[index].hasMenu ? TRUE : FALSE);
  HWND hwnd = CreateWindowExW(0, PATCH_WINDOW_CLASS, FORMS[index].title, WS_OVERLAPPEDWINDOW,
    CW_USEDEFAULT, CW_USEDEFAULT, rect.right - rect.left, rect.bottom - rect.top,
    nullptr, nullptr, gInstance, reinterpret_cast<void*>((INT_PTR)index));
  if (!hwnd) return nullptr;
  gForms[index] = hwnd;
${createMenus}
${create}
  RefreshTabVisibility();
  return hwnd;
}

static bool HasArg(const wchar_t* value) { return std::wcsstr(GetCommandLineW(), value) != nullptr; }

${smoke}

int WINAPI wWinMain(HINSTANCE instance, HINSTANCE, PWSTR, int showCommand) {
  gInstance = instance;
  gGuiFont = (HFONT)GetStockObject(DEFAULT_GUI_FONT);
  gSmokeMode = HasArg(L"--patch-smoke");
  INITCOMMONCONTROLSEX common{};
  common.dwSize = sizeof(common);
  common.dwICC = ICC_TAB_CLASSES;
  if (!InitCommonControlsEx(&common)) return 9;
  WNDCLASSEXW wc{};
  wc.cbSize = sizeof(wc);
  wc.hInstance = instance;
  wc.lpfnWndProc = PatchWndProc;
  wc.lpszClassName = PATCH_WINDOW_CLASS;
  wc.hCursor = LoadCursor(nullptr, IDC_ARROW);
  wc.hIcon = LoadIcon(nullptr, IDI_APPLICATION);
  wc.hbrBackground = (HBRUSH)(COLOR_WINDOW + 1);
  if (!RegisterClassExW(&wc)) return 10;

  for (int i = 0; i < FORM_COUNT; ++i) if (!CreatePatchForm(i)) return 11 + i;
  RefreshUI();
  for (int i = 0; i < FORM_COUNT; ++i) if (FORMS[i].visible) ShowWindow(gForms[i], showCommand == 0 ? SW_SHOWNORMAL : showCommand);
  UpdateWindow(gForms[0]);

  if (gSmokeMode) return RunPatchSmoke();

  MSG msg{};
  while (GetMessageW(&msg, nullptr, 0, 0) > 0) {
    TranslateMessage(&msg);
    DispatchMessageW(&msg);
  }
  return (int)msg.wParam;
}
`;
}

function validateReferences(ir, forms, sources) {
  for (const event of ir.events) {
    if (!sources.has(event.control)) throw new NativeGuiError(`Win32 event source '${event.control}' is missing.`);
    for (const action of event.actions ?? []) {
      if ((action.kind === 'openForm' || action.kind === 'closeForm' || action.kind === 'dialog') && !forms.has(action.form)) {
        throw new NativeGuiError(`Win32 Form '${action.form}' is missing.`);
      }
    }
  }
}

function stateDeclaration(state) {
  const name = stateName(state.name);
  if (state.type === 'boolean') return `static bool ${name} = ${state.initial ? 'true' : 'false'};`;
  if (state.type === 'number') return `static double ${name} = ${Number(state.initial)};`;
  if (state.type === 'text') return `static std::wstring ${name} = L${cppString(state.initial)};`;
  throw new NativeGuiError(`Win32 state type '${state.type}' is unsupported.`);
}

function emitControlTextFunction(control, index, states) {
  const text = String(control.text ?? '');
  const lines = ['  std::wstring out;'];
  let cursor = 0;
  const re = /\{([A-Za-z_]\w*)\}/g;
  let match;
  while ((match = re.exec(text))) {
    if (match.index > cursor) lines.push(`  out += L${cppString(text.slice(cursor, match.index))};`);
    const state = states.get(match[1]);
    if (!state) throw new NativeGuiError(`Win32 text '${text}' refers to unknown state '${match[1]}'.`);
    if (state.type === 'boolean') lines.push(`  out += PatchBoolean(${stateName(state.name)});`);
    else if (state.type === 'number') lines.push(`  out += PatchNumber(${stateName(state.name)});`);
    else lines.push(`  out += ${stateName(state.name)};`);
    cursor = match.index + match[0].length;
  }
  if (cursor < text.length) lines.push(`  out += L${cppString(text.slice(cursor))};`);
  lines.push('  return out;');
  return `static std::wstring ControlText_${index}() {\n${lines.join('\n')}\n}`;
}

function emitEventFunction(event, index, forms, states) {
  const param = event.valueType === 'boolean' ? 'bool eventValue' : event.valueType === 'text' ? 'const std::wstring& eventValue' : '';
  const actions = (event.actions ?? []).map(action => emitAction(action, event, forms, states)).join('\n');
  return `static void Event_${index}(${param}) {\n${actions || '  // no-op'}\n  RefreshUI();\n}`;
}

function emitAction(action, event, forms, states) {
  if (action.kind === 'openForm') return `  ShowWindow(gForms[${forms.get(action.form)}], SW_SHOW); UpdateWindow(gForms[${forms.get(action.form)}]);`;
  if (action.kind === 'closeForm') return `  ShowWindow(gForms[${forms.get(action.form)}], SW_HIDE);`;
  if (action.kind === 'dialog') return `  ShowInfoDialog(${forms.get(action.form)}, L${cppString(action.title)}, L${cppString(action.message)});`;
  if (action.kind !== 'change') throw new NativeGuiError(`Win32 action '${action.kind}' is unsupported.`);
  const state = states.get(action.target);
  if (!state) throw new NativeGuiError(`Win32 change target '${action.target}' is missing.`);
  return (action.ops ?? []).map(op => emitOperation(state, op, event)).join('\n');
}

function emitOperation(state, op, event) {
  const target = stateName(state.name);
  if (op.op === 'clear') {
    if (state.type === 'boolean') return `  ${target} = false;`;
    if (state.type === 'number') return `  ${target} = 0.0;`;
    return `  ${target}.clear();`;
  }
  const value = emitNativeValue(state, op.value, event);
  if (op.op === 'set') return `  ${target} = ${value};`;
  if (op.op === 'add' && state.type === 'number') return `  ${target} += ${value};`;
  if (op.op === 'remove' && state.type === 'number') return `  ${target} -= ${value};`;
  if (op.op === 'add' && state.type === 'text') return `  ${target} += ${value};`;
  throw new NativeGuiError(`Win32 native GUI cannot apply '${op.op}' to ${state.type} state '${state.name}'.`);
}

function emitNativeValue(state, value, event) {
  if (value?.kind === 'eventValue') {
    if (state.type !== event.valueType) throw new NativeGuiError(`Win32 event value type ${event.valueType ?? 'none'} cannot be assigned to ${state.type} state '${state.name}'.`);
    return 'eventValue';
  }
  if (state.type === 'boolean') return value?.value ? 'true' : 'false';
  if (state.type === 'number') return String(Number(value?.value));
  if (state.type === 'text') return `std::wstring(L${cppString(value?.value)})`;
  throw new NativeGuiError(`Win32 literal type '${state.type}' is unsupported.`);
}

function emitDispatch(event, index, controls, menus) {
  const menu = menus.get(event.control);
  if (menu) return `  if (commandId == ${menu.commandId} && notification == 0 && controlHwnd == nullptr) { Event_${index}(); return; }`;
  const control = controls.get(event.control);
  if (!control) return '';
  const notification = control.type === 'button' || control.type === 'checkbox' || control.type === 'radio'
    ? 'BN_CLICKED'
    : control.type === 'combo'
      ? 'CBN_SELCHANGE'
      : control.type === 'listbox'
        ? 'LBN_SELCHANGE'
        : 'EN_CHANGE';
  let call = `Event_${index}();`;
  if (event.valueType === 'boolean') call = `Event_${index}(SendMessageW(controlHwnd, BM_GETCHECK, 0, 0) == BST_CHECKED);`;
  if (event.valueType === 'text') {
    if (control.type === 'combo') call = `Event_${index}(ComboText(controlHwnd));`;
    else if (control.type === 'listbox') call = `Event_${index}(ListBoxText(controlHwnd));`;
    else call = `Event_${index}(WindowText(controlHwnd));`;
  }
  return `  if (commandId == ${control.commandId} && notification == ${notification}) { ${call} return; }`;
}

function emitRefresh(control, index, states) {
  if (control.type === 'tabs') return '';
  if (control.type === 'text' || control.type === 'button') return `  if (gControls[${index}]) SetWindowTextIfDifferent(gControls[${index}], ControlText_${index}());`;
  if (control.type === 'checkbox') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) { SetWindowTextIfDifferent(gControls[${index}], ControlText_${index}()); SendMessageW(gControls[${index}], BM_SETCHECK, ${stateName(state.name)} ? BST_CHECKED : BST_UNCHECKED, 0); }`;
  }
  if (control.type === 'input') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) SetWindowTextIfDifferent(gControls[${index}], ${stateName(state.name)});`;
  }
  if (control.type === 'combo') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) SetComboSelection(gControls[${index}], ${stateName(state.name)});`;
  }
  if (control.type === 'listbox') {
    const state = states.get(control.binding);
    return `  if (gControls[${index}]) SetListBoxSelection(gControls[${index}], ${stateName(state.name)});`;
  }
  if (control.type === 'radio') {
    const state = states.get(control.binding);
    return `  SetRadioSelection(${index}, ${stateName(state.name)});`;
  }
  return '';
}

function emitCreateMenus(form, formIndex, menuById) {
  if (!form.menus.length) return '';
  const menus = form.menus.map((menu, menuIndex) => {
    const items = menu.items.map(item => {
      const native = menuById.get(item.id);
      return `      AppendMenuW(popup_${formIndex}_${menuIndex}, MF_STRING, ${native.commandId}, L${cppString(item.text)});`;
    }).join('\n');
    return `    HMENU popup_${formIndex}_${menuIndex} = CreatePopupMenu();\n    if (!popup_${formIndex}_${menuIndex}) return nullptr;\n${items}\n    AppendMenuW(menuBar, MF_POPUP, (UINT_PTR)popup_${formIndex}_${menuIndex}, L${cppString(menu.title)});`;
  }).join('\n');
  return `  if (${formIndex} == index) {\n    HMENU menuBar = CreateMenu();\n    if (!menuBar) return nullptr;\n${menus}\n    if (!SetMenu(hwnd, menuBar)) return nullptr;\n  }`;
}

function emitCreateControl(control, index, controls) {
  const position = win32Position(control, controls);
  const width = positiveInt(control.layout?.width, 120);
  const sourceHeight = positiveInt(control.layout?.height, 36);
  const height = control.type === 'combo' ? Math.max(sourceHeight + 120, 160) : sourceHeight;
  if (control.type === 'tabs') {
    const pages = control.pageTitles.map((title, pageIndex) =>
      `    { TCITEMW item{}; item.mask = TCIF_TEXT; item.pszText = const_cast<wchar_t*>(L${cppString(title)}); SendMessageW(gControls[${index}], TCM_INSERTITEMW, ${pageIndex}, (LPARAM)&item); }`
    ).join('\n');
    return `  if (${control.formIndex} == index) {\n    gControls[${index}] = CreateWindowExW(0, WC_TABCONTROLW, L"", WS_CHILD | WS_VISIBLE | WS_TABSTOP | WS_CLIPSIBLINGS, ${position.x}, ${position.y}, ${width}, ${height}, hwnd, reinterpret_cast<HMENU>((INT_PTR)${control.commandId}), gInstance, nullptr);\n    if (gControls[${index}] && gGuiFont) SendMessageW(gControls[${index}], WM_SETFONT, (WPARAM)gGuiFont, TRUE);\n${pages}\n    SendMessageW(gControls[${index}], TCM_SETCURSEL, 0, 0);\n    gTabSelection[${index}] = 0;\n  }`;
  }
  if (control.type === 'radio') {
    const count = Math.max(1, control.options.length);
    const itemHeight = Math.max(22, Math.min(30, Math.floor(sourceHeight / count) || 26));
    const items = control.options.map((option, optionIndex) => {
      const group = optionIndex === 0 ? ' | WS_GROUP' : '';
      const y = position.y + optionIndex * itemHeight;
      return `    { HWND item = CreateWindowExW(0, L"BUTTON", L${cppString(option)}, WS_CHILD | WS_VISIBLE | WS_TABSTOP | BS_AUTORADIOBUTTON${group}, ${position.x}, ${y}, ${width}, ${itemHeight}, hwnd, reinterpret_cast<HMENU>((INT_PTR)${control.commandId}), gInstance, nullptr); if (!item) return nullptr; if (gGuiFont) SendMessageW(item, WM_SETFONT, (WPARAM)gGuiFont, TRUE); gRadioItems[${index}].push_back(item); if (!gControls[${index}]) gControls[${index}] = item; }`;
    }).join('\n');
    return `  if (${control.formIndex} == index) {\n${items}\n  }`;
  }
  const style = control.type === 'text'
    ? 'WS_CHILD | WS_VISIBLE | SS_LEFT'
    : control.type === 'button'
      ? 'WS_CHILD | WS_VISIBLE | WS_TABSTOP | BS_PUSHBUTTON'
      : control.type === 'input'
        ? 'WS_CHILD | WS_VISIBLE | WS_TABSTOP | WS_BORDER | ES_AUTOHSCROLL'
        : control.type === 'combo'
          ? 'WS_CHILD | WS_VISIBLE | WS_TABSTOP | WS_VSCROLL | CBS_DROPDOWNLIST'
          : control.type === 'listbox'
            ? 'WS_CHILD | WS_VISIBLE | WS_TABSTOP | WS_VSCROLL | WS_BORDER | LBS_NOTIFY'
            : 'WS_CHILD | WS_VISIBLE | WS_TABSTOP | BS_AUTOCHECKBOX';
  const klass = control.type === 'text'
    ? 'L"STATIC"'
    : control.type === 'input'
      ? 'L"EDIT"'
      : control.type === 'combo'
        ? 'L"COMBOBOX"'
        : control.type === 'listbox'
          ? 'L"LISTBOX"'
          : 'L"BUTTON"';
  const options = control.type === 'combo'
    ? control.options.map(option => `    SendMessageW(gControls[${index}], CB_ADDSTRING, 0, (LPARAM)L${cppString(option)});`).join('\n')
    : control.type === 'listbox'
      ? control.options.map(option => `    SendMessageW(gControls[${index}], LB_ADDSTRING, 0, (LPARAM)L${cppString(option)});`).join('\n')
      : '';
  return `  if (${control.formIndex} == index) {\n    gControls[${index}] = CreateWindowExW(0, ${klass}, L"", ${style}, ${position.x}, ${position.y}, ${width}, ${height}, hwnd, reinterpret_cast<HMENU>((INT_PTR)${control.commandId}), gInstance, nullptr);\n    if (gControls[${index}] && gGuiFont) SendMessageW(gControls[${index}], WM_SETFONT, (WPARAM)gGuiFont, TRUE);\n${options}\n  }`;
}

function win32Position(control, controls) {
  if ((control.parentTabIndex ?? -1) < 0) {
    return { x: layoutInt(control.layout?.x, 24), y: layoutInt(control.layout?.y, 24) };
  }
  const tab = controls[control.parentTabIndex];
  if (!tab || tab.type !== 'tabs') throw new NativeGuiError(`Win32 child control '${control.id}' has an invalid Tabs parent.`);
  return {
    x: layoutInt(tab.layout?.x, 24) + 10 + layoutInt(control.layout?.x, 12),
    y: layoutInt(tab.layout?.y, 24) + 30 + layoutInt(control.layout?.y, 12)
  };
}

function emitSmoke(forms, controls, menus, states, allControls) {
  const mainIndex = forms.has('main') ? forms.get('main') : 0;
  const settingsIndex = forms.get('settings');
  const open = controls.get('open_settings');
  const close = controls.get('close_settings');
  const checkbox = controls.get('notifications');
  const checkboxState = states.get('notifications');
  const combo = controls.get('size');
  const comboState = states.get('size');
  const listbox = controls.get('fruit');
  const listboxState = states.get('fruit');
  const radio = controls.get('mode');
  const radioState = states.get('mode');
  const tabs = controls.get('settings');
  const about = menus.get('about_item');
  const lines = ['static int RunPatchSmoke() {', `  if (!gForms[${mainIndex}] || !IsWindowVisible(gForms[${mainIndex}])) return 70;`];
  if (settingsIndex !== undefined) lines.push(`  if (IsWindowVisible(gForms[${settingsIndex}])) return 71;`);
  if (open && settingsIndex !== undefined) {
    lines.push(`  SendMessageW(gForms[${open.formIndex}], WM_COMMAND, MAKEWPARAM(${open.commandId}, BN_CLICKED), (LPARAM)gControls[${open.handleIndex}]);`);
    lines.push(`  if (!IsWindowVisible(gForms[${settingsIndex}])) return 72;`);
  }
  if (checkbox && checkboxState?.type === 'boolean') {
    lines.push(`  SendMessageW(gControls[${checkbox.handleIndex}], BM_SETCHECK, BST_CHECKED, 0);`);
    lines.push(`  SendMessageW(gForms[${checkbox.formIndex}], WM_COMMAND, MAKEWPARAM(${checkbox.commandId}, BN_CLICKED), (LPARAM)gControls[${checkbox.handleIndex}]);`);
    lines.push(`  if (!${stateName(checkboxState.name)}) return 73;`);
  }
  if (combo && comboState?.type === 'text' && combo.options.length) {
    const last = combo.options.length - 1;
    lines.push(`  SendMessageW(gControls[${combo.handleIndex}], CB_SETCURSEL, ${last}, 0);`);
    lines.push(`  SendMessageW(gForms[${combo.formIndex}], WM_COMMAND, MAKEWPARAM(${combo.commandId}, CBN_SELCHANGE), (LPARAM)gControls[${combo.handleIndex}]);`);
    lines.push(`  if (${stateName(comboState.name)} != L${cppString(combo.options[last])}) return 75;`);
  }
  if (listbox && listboxState?.type === 'text' && listbox.options.length) {
    const last = listbox.options.length - 1;
    lines.push(`  SendMessageW(gControls[${listbox.handleIndex}], LB_SETCURSEL, ${last}, 0);`);
    lines.push(`  SendMessageW(gForms[${listbox.formIndex}], WM_COMMAND, MAKEWPARAM(${listbox.commandId}, LBN_SELCHANGE), (LPARAM)gControls[${listbox.handleIndex}]);`);
    lines.push(`  if (${stateName(listboxState.name)} != L${cppString(listbox.options[last])}) return 76;`);
  }
  if (radio && radioState?.type === 'text' && radio.options.length) {
    const last = radio.options.length - 1;
    lines.push(`  if (gRadioItems[${radio.handleIndex}].size() != ${radio.options.length}) return 81;`);
    lines.push(`  SendMessageW(gRadioItems[${radio.handleIndex}][${last}], BM_CLICK, 0, 0);`);
    lines.push(`  if (${stateName(radioState.name)} != L${cppString(radio.options[last])}) return 82;`);
  }
  if (tabs?.type === 'tabs' && tabs.pageTitles.length > 1) {
    const first = allControls.find(control => control.parentTabIndex === tabs.handleIndex && control.pageIndex === 0);
    const second = allControls.find(control => control.parentTabIndex === tabs.handleIndex && control.pageIndex === 1);
    lines.push(`  if ((int)SendMessageW(gControls[${tabs.handleIndex}], TCM_GETITEMCOUNT, 0, 0) != ${tabs.pageTitles.length}) return 77;`);
    lines.push(`  SendMessageW(gControls[${tabs.handleIndex}], TCM_SETCURSEL, 1, 0);`);
    lines.push(`  { NMHDR header{}; header.hwndFrom = gControls[${tabs.handleIndex}]; header.idFrom = ${tabs.commandId}; header.code = TCN_SELCHANGE; SendMessageW(gForms[${tabs.formIndex}], WM_NOTIFY, header.idFrom, (LPARAM)&header); }`);
    lines.push(`  if (gTabSelection[${tabs.handleIndex}] != 1) return 78;`);
    if (first) lines.push(`  if (IsWindowVisible(gControls[${first.handleIndex}])) return 79;`);
    if (second) lines.push(`  if (!IsWindowVisible(gControls[${second.handleIndex}])) return 80;`);
  }
  if (about) {
    lines.push(`  SendMessageW(gForms[${about.formIndex}], WM_COMMAND, MAKEWPARAM(${about.commandId}, 0), 0);`);
    lines.push(`  if (gLastDialogTitle != L"About Patch" || gLastDialogMessage != L"Native menus and informational dialogs") return 83;`);
  }
  if (close && settingsIndex !== undefined) {
    lines.push(`  SendMessageW(gForms[${close.formIndex}], WM_COMMAND, MAKEWPARAM(${close.commandId}, BN_CLICKED), (LPARAM)gControls[${close.handleIndex}]);`);
    lines.push(`  if (IsWindowVisible(gForms[${settingsIndex}])) return 74;`);
  }
  lines.push(`  DestroyWindow(gForms[${mainIndex}]);`, '  return 0;', '}');
  return lines.join('\n');
}

function controlKind(type) {
  return ({ text: 'CK_TEXT', button: 'CK_BUTTON', input: 'CK_INPUT', checkbox: 'CK_CHECKBOX', combo: 'CK_COMBO', listbox: 'CK_LISTBOX', tabs: 'CK_TABS', radio: 'CK_RADIO' })[type] ?? 'CK_TEXT';
}
function stateName(name) { return `patch_state_${cppIdentifier(name)}`; }
function cppIdentifier(value) { return String(value).replace(/[^A-Za-z0-9_]/g, '_').replace(/^[0-9]/, '_$&'); }
function layoutInt(value, fallback) { return Number.isFinite(Number(value)) ? Math.max(0, Math.round(Number(value))) : fallback; }
function positiveInt(value, fallback) { return Number.isFinite(Number(value)) ? Math.max(1, Math.round(Number(value))) : fallback; }
function cppString(value) { return JSON.stringify(String(value ?? '')).replace(/\\u([0-9a-fA-F]{4})/g, (_, hex) => `\\x${hex}`); }
