import { flattenNativeGuiControls, flattenNativeGuiMenuItems, NativeGuiError } from './native-gui-ir.js';
import { emitWin32GuiCpp as emitWin32GuiCppV06 } from './win32-gui.js';
import {
  planNativeResultDialogs,
  buildAuxiliaryResultIr,
  resultHandlerName,
  resultHandler,
  injectIntoEvent,
  extractEventZero,
  insertAfter,
  insertBefore,
  identifier
} from './native-result-dialog-overlay.js';

export const PATCH_WIN32_GUI_BACKEND_VERSION = '0.7';

export function emitWin32GuiCpp(input) {
  const plan = planNativeResultDialogs(input);
  let source = emitWin32GuiCppV06(plan.baseIr)
    .replace(/Generated by Patch Win32 GUI backend 0\.6\./, `Generated by Patch Win32 GUI backend ${PATCH_WIN32_GUI_BACKEND_VERSION}.`)
    .replace('#include <commctrl.h>\n', '#include <commctrl.h>\n#include <commdlg.h>\n')
    .replace('#pragma comment(lib, "comctl32.lib")', '#pragma comment(lib, "comctl32.lib")\n#pragma comment(lib, "comdlg32.lib")');

  if (!plan.triggers.length) return source;

  const resultFunctions = plan.resultEvents.map(event => {
    const aux = buildAuxiliaryResultIr(plan.ir, event);
    return extractEventZero(emitWin32GuiCppV06(aux), resultHandlerName(event.control, event.event));
  }).join('\n\n');

  source = insertAfter(source, 'static void RefreshUI();', `\n\n${resultFunctions}\n`);
  source = insertBefore(source, 'static void RefreshTabVisibility() {', `${win32Helpers()}\n`);

  for (const trigger of plan.triggers) {
    source = injectIntoEvent(source, trigger.baseIndex, win32ResultAction(plan, trigger.action));
  }

  source = injectSmoke(source, plan);
  return source;
}

function win32Helpers() {
  return `static std::wstring gLastResultSource;\nstatic std::wstring gLastResultValue;\nstatic int gLastResultEvent = 0;\nstatic bool PatchConfirmDialog(int formIndex, const wchar_t* title, const wchar_t* message) {\n  if (gSmokeMode) return true;\n  HWND owner = formIndex >= 0 && formIndex < FORM_COUNT ? gForms[formIndex] : nullptr;\n  return MessageBoxW(owner, message ? message : L\"\", title ? title : L\"\", MB_YESNO | MB_ICONQUESTION) == IDYES;\n}\nstatic bool PatchFileDialog(int formIndex, const wchar_t* title, bool save, std::wstring& result) {\n  if (gSmokeMode) { result = save ? L\"C:\\\\Patch\\\\saved.patch\" : L\"C:\\\\Patch\\\\opened.patch\"; return true; }\n  wchar_t path[32768] = {};\n  OPENFILENAMEW ofn{};\n  ofn.lStructSize = sizeof(ofn);\n  ofn.hwndOwner = formIndex >= 0 && formIndex < FORM_COUNT ? gForms[formIndex] : nullptr;\n  ofn.lpstrFile = path;\n  ofn.nMaxFile = (DWORD)(sizeof(path) / sizeof(path[0]));\n  ofn.lpstrTitle = title;\n  ofn.Flags = OFN_EXPLORER | OFN_PATHMUSTEXIST | (save ? OFN_OVERWRITEPROMPT : OFN_FILEMUSTEXIST);\n  const BOOL ok = save ? GetSaveFileNameW(&ofn) : GetOpenFileNameW(&ofn);\n  if (!ok) return false;\n  result.assign(path);\n  return true;\n}\n`;
}

function win32ResultAction(plan, action) {
  const formIndex = plan.ir.forms.findIndex(form => form.id === action.form);
  if (formIndex < 0) throw new NativeGuiError(`Win32 result dialog Form '${action.form}' is missing.`);
  const confirmed = resultHandler(plan, action.id, 'confirmed');
  const chosen = resultHandler(plan, action.id, 'chosen');
  const cancelled = resultHandler(plan, action.id, 'cancelled');
  const onConfirmed = confirmed ? `${resultHandlerName(action.id, 'confirmed')}();` : '';
  const onChosen = chosen ? `${resultHandlerName(action.id, 'chosen')}(patchResultValue);` : '';
  const onCancelled = cancelled ? `${resultHandlerName(action.id, 'cancelled')}();` : '';

  if (action.kind === 'confirmDialog') {
    return `  {\n    const bool patchAccepted = PatchConfirmDialog(${formIndex}, L${cppString(action.title)}, L${cppString(action.message)});\n    gLastResultSource = L${cppString(action.id)}; gLastResultValue.clear(); gLastResultEvent = patchAccepted ? 3 : 5;\n    if (patchAccepted) { ${onConfirmed} } else { ${onCancelled} }\n  }`;
  }
  const save = action.kind === 'saveFileDialog';
  return `  {\n    std::wstring patchResultValue;\n    const bool patchChosen = PatchFileDialog(${formIndex}, L${cppString(action.title)}, ${save ? 'true' : 'false'}, patchResultValue);\n    gLastResultSource = L${cppString(action.id)}; gLastResultValue = patchChosen ? patchResultValue : L\"\"; gLastResultEvent = patchChosen ? 4 : 5;\n    if (patchChosen) { ${onChosen} } else { ${onCancelled} }\n  }`;
}

function injectSmoke(source, plan) {
  const controls = new Map(flattenNativeGuiControls(plan.baseIr).filter(control => control.id).map(control => [control.id, control]));
  const menus = new Map(flattenNativeGuiMenuItems(plan.baseIr).map(item => [item.id, item]));
  const checks = [];
  let code = 90;
  for (const trigger of plan.triggers) {
    const control = controls.get(trigger.event.control);
    const menu = menus.get(trigger.event.control);
    if (control?.type === 'button') {
      const commandId = 1000 + control.nativeIndex;
      checks.push(`  SendMessageW(gForms[${control.formIndex}], WM_COMMAND, MAKEWPARAM(${commandId}, BN_CLICKED), (LPARAM)gControls[${control.nativeIndex}]);`);
    } else if (menu) {
      checks.push(`  SendMessageW(gForms[${menu.formIndex}], WM_COMMAND, MAKEWPARAM(${20000 + menu.nativeIndex}, 0), 0);`);
    } else {
      continue;
    }
    const expectedEvent = trigger.action.kind === 'confirmDialog' ? 3 : 4;
    const expectedValue = trigger.action.kind === 'openFileDialog' ? 'C:\\Patch\\opened.patch' : trigger.action.kind === 'saveFileDialog' ? 'C:\\Patch\\saved.patch' : '';
    checks.push(`  if (gLastResultSource != L${cppString(trigger.action.id)} || gLastResultEvent != ${expectedEvent}) return ${code++};`);
    if (expectedValue) checks.push(`  if (gLastResultValue != L${cppString(expectedValue)}) return ${code++};`);
    const handler = trigger.action.kind === 'confirmDialog'
      ? resultHandler(plan, trigger.action.id, 'confirmed')
      : resultHandler(plan, trigger.action.id, 'chosen');
    const eventValueChange = handler?.actions?.find(action => action.kind === 'change' && action.stateType === 'text' && action.ops?.some(op => op.value?.kind === 'eventValue'));
    if (expectedValue && eventValueChange) {
      checks.push(`  if (patch_state_${identifier(eventValueChange.target)} != L${cppString(expectedValue)}) return ${code++};`);
    }
  }
  if (!checks.length) return source;
  const start = source.indexOf('static int RunPatchSmoke() {');
  if (start < 0) throw new NativeGuiError('Generated Win32 source is missing RunPatchSmoke.');
  const destroy = source.indexOf('  DestroyWindow(gForms[', start);
  if (destroy < 0) throw new NativeGuiError('Generated Win32 smoke has an unexpected shape.');
  return source.slice(0, destroy) + checks.join('\n') + '\n' + source.slice(destroy);
}

function cppString(value) {
  return JSON.stringify(String(value ?? '')).replace(/\\u([0-9a-fA-F]{4})/g, (_, hex) => `\\x${hex}`);
}
